import type { KbArticleMeta } from './types.js'

/**
 * Every article's metadata, in the same reading order as the content — GENERATED from the articles
 * and asserted identical to them by the package's own tests. Edit an article, run the tests, and a
 * stale entry here fails rather than silently mislabelling a help link.
 *
 * It exists so the ROOT entry point can answer "may this reader open that article, and what is it
 * called" without loading a single article body. Titles only, deliberately: summaries are four
 * times the bytes and every surface that wants one is already reading the article.
 */
export const KB_META: readonly KbArticleMeta[] = [
  {
    slug: 'how-tracking-works',
    category: 'start',
    surfaces: { site: true, app: true },
    title: { en: 'How GPS tracking actually works', lt: 'Kaip iš tikrųjų veikia GPS sekimas', pl: 'Jak naprawdę działa lokalizacja GPS', de: 'Wie GPS-Ortung wirklich funktioniert' },
  },
  {
    slug: 'first-steps',
    category: 'start',
    surfaces: { site: true, app: true },
    screen: '/app',
    title: { en: 'Your first hour', lt: 'Pirmoji jūsų valanda', pl: 'Twoja pierwsza godzina', de: 'Ihre erste Stunde' },
  },
  {
    slug: 'logins-and-roles',
    category: 'start',
    surfaces: { site: true, app: true },
    screen: '/app/settings',
    title: { en: 'Logins, roles and accounts', lt: 'Prisijungimai, rolės ir paskyros', pl: 'Loginy, role i konta', de: 'Zugänge, Rollen und Konten' },
  },
  {
    slug: 'glossary',
    category: 'start',
    surfaces: { site: true, app: true },
    title: { en: 'Glossary — every term in one place', lt: 'Žodynėlis — visos sąvokos vienoje vietoje', pl: 'Słowniczek — wszystkie pojęcia w jednym miejscu', de: 'Glossar — alle Begriffe an einem Ort' },
  },
  {
    slug: 'choose-a-tracker',
    category: 'devices',
    surfaces: { site: true, app: true },
    title: { en: 'Choosing a tracker', lt: 'Kaip pasirinkti seklį', pl: 'Wybór lokalizatora', de: 'Den passenden Tracker wählen' },
  },
  {
    slug: 'imei',
    category: 'devices',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'What an IMEI is, and why it matters here', lt: 'Kas yra IMEI ir kodėl jis čia svarbus', pl: 'Czym jest IMEI i dlaczego jest tu ważny', de: 'Was eine IMEI ist — und warum sie hier zählt' },
  },
  {
    slug: 'sim-and-apn',
    category: 'devices',
    surfaces: { site: true, app: true },
    title: { en: 'SIM cards, APN and mobile data', lt: 'SIM kortelės, APN ir mobilieji duomenys', pl: 'Karty SIM, APN i transmisja danych', de: 'SIM-Karten, APN und Mobilfunkdaten' },
  },
  {
    slug: 'connect-a-tracker',
    category: 'devices',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'Connecting a tracker for the first time', lt: 'Seklio prijungimas pirmą kartą', pl: 'Pierwsze podłączenie lokalizatora', de: 'Einen Tracker zum ersten Mal anschließen' },
  },
  {
    slug: 'config-sms',
    category: 'devices',
    surfaces: { site: true, app: true },
    title: { en: 'The configuration SMS explained', lt: 'Konfigūracijos SMS paaiškinta', pl: 'SMS konfiguracyjny wyjaśniony', de: 'Die Konfigurations-SMS erklärt' },
  },
  {
    slug: 'reporting-intervals',
    category: 'devices',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'Reporting intervals — how often the tracker speaks', lt: 'Siuntimo intervalai — kaip dažnai seklys prabyla', pl: 'Częstotliwość raportowania — jak często lokalizator się odzywa', de: 'Sendeintervalle — wie oft der Tracker spricht' },
  },
  {
    slug: 'commands',
    category: 'devices',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'Sending commands to a tracker', lt: 'Komandų siuntimas sekliui', pl: 'Wysyłanie komend do lokalizatora', de: 'Befehle an einen Tracker senden' },
  },
  {
    slug: 'can-and-obd',
    category: 'devices',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'CAN and OBD data — fuel, mileage and the engine', lt: 'CAN ir OBD duomenys — kuras, rida ir variklis', pl: 'Dane CAN i OBD — paliwo, przebieg i silnik', de: 'CAN- und OBD-Daten — Kraftstoff, Kilometer und Motor' },
  },
  {
    slug: 'device-lifecycle',
    category: 'devices',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'Retiring, moving and erasing a device', lt: 'Įrenginio nurašymas, perkėlimas ir duomenų ištrynimas', pl: 'Wycofywanie, przenoszenie i kasowanie urządzenia', de: 'Gerät stilllegen, umsetzen und löschen' },
  },
  {
    slug: 'map-basics',
    category: 'map',
    surfaces: { site: true, app: true },
    screen: '/app',
    title: { en: 'Reading the live map', lt: 'Kaip skaityti gyvą žemėlapį', pl: 'Jak czytać mapę na żywo', de: 'Die Live-Karte lesen' },
  },
  {
    slug: 'position-accuracy',
    category: 'map',
    surfaces: { site: true, app: true },
    title: { en: 'Position accuracy, drift and positions we throw away', lt: 'Pozicijos tikslumas, dreifas ir pozicijos, kurias išmetame', pl: 'Dokładność pozycji, dryf i pozycje, które odrzucamy', de: 'Positionsgenauigkeit, Drift und verworfene Positionen' },
  },
  {
    slug: 'device-status',
    category: 'map',
    surfaces: { site: true, app: true },
    title: { en: 'Device status — the two things "inactive" could mean', lt: 'Įrenginio būsena — du dalykai, kuriuos galėtų reikšti „neaktyvus"', pl: 'Status urządzenia — dwie rzeczy, które mogłoby znaczyć „nieaktywne"', de: 'Gerätestatus — die zwei Dinge, die „inaktiv" heißen könnte' },
  },
  {
    slug: 'share-a-live-link',
    category: 'map',
    surfaces: { site: true, app: true },
    screen: '/app',
    title: { en: 'Sharing a vehicle with someone who has no login', lt: 'Kaip parodyti automobilį tam, kas neturi prisijungimo', pl: 'Udostępnianie pojazdu komuś bez loginu', de: 'Ein Fahrzeug mit jemandem ohne Zugang teilen' },
  },
  {
    slug: 'how-trips-are-detected',
    category: 'trips',
    surfaces: { site: true, app: true },
    screen: '/app/trips',
    title: { en: 'How a trip is decided', lt: 'Kaip nusprendžiama, kad tai kelionė', pl: 'Jak rozstrzyga się, że to trasa', de: 'Wie eine Fahrt entschieden wird' },
  },
  {
    slug: 'distance-and-odometer',
    category: 'trips',
    surfaces: { site: true, app: true },
    screen: '/app/trips',
    title: { en: 'Distance and the odometer', lt: 'Atstumas ir odometras', pl: 'Dystans a licznik', de: 'Strecke und Kilometerstand' },
  },
  {
    slug: 'playback',
    category: 'trips',
    surfaces: { site: true, app: true },
    screen: '/app/playback',
    title: { en: 'Replaying a day', lt: 'Dienos peržaidimas', pl: 'Odtwarzanie dnia', de: 'Einen Tag noch einmal abspielen' },
  },
  {
    slug: 'geofences',
    category: 'alerts',
    surfaces: { site: true, app: true },
    screen: '/app/geofences',
    title: { en: 'Geofences — drawing places that matter', lt: 'Geozonos — kaip apibrėžti svarbias vietas', pl: 'Geostrefy — rysowanie miejsc, które mają znaczenie', de: 'Geozonen — Orte zeichnen, auf die es ankommt' },
  },
  {
    slug: 'rules-and-alerts',
    category: 'alerts',
    surfaces: { site: true, app: true },
    screen: '/app/rules',
    title: { en: 'Rules — being told instead of looking', lt: 'Taisyklės — kai pranešama jums, o ne jūs tikrinate', pl: 'Reguły — być informowanym zamiast sprawdzać', de: 'Regeln — informiert werden statt nachsehen' },
  },
  {
    slug: 'event-types',
    category: 'alerts',
    surfaces: { site: true, app: true },
    screen: '/app/events',
    title: { en: 'Every event type, in plain words', lt: 'Visi įvykių tipai paprastais žodžiais', pl: 'Wszystkie rodzaje zdarzeń, prostymi słowami', de: 'Alle Ereignistypen, in Klartext' },
  },
  {
    slug: 'notification-channels',
    category: 'alerts',
    surfaces: { site: true, app: true },
    screen: '/app/rules',
    title: { en: 'Where alerts are delivered', lt: 'Kur pristatomi pranešimai', pl: 'Dokąd trafiają alerty', de: 'Wohin Alarme zugestellt werden' },
  },
  {
    slug: 'report-types',
    category: 'reports',
    surfaces: { site: true, app: true },
    screen: '/app/reports',
    title: { en: 'Which report answers which question', lt: 'Kuri ataskaita atsako į kurį klausimą', pl: 'Który raport odpowiada na które pytanie', de: 'Welcher Bericht welche Frage beantwortet' },
  },
  {
    slug: 'scheduled-reports',
    category: 'reports',
    surfaces: { site: true, app: true },
    screen: '/app/reports',
    title: { en: 'Reports that arrive on their own', lt: 'Ataskaitos, kurios atkeliauja pačios', pl: 'Raporty, które przychodzą same', de: 'Berichte, die von selbst kommen' },
  },
  {
    slug: 'time-zones-and-units',
    category: 'reports',
    surfaces: { site: true, app: true },
    screen: '/app/settings',
    title: { en: 'Time zones, language and units — two settings, not one', lt: 'Laiko juostos, kalba ir vienetai — du nustatymai, ne vienas', pl: 'Strefy czasowe, język i jednostki — dwa ustawienia, nie jedno', de: 'Zeitzonen, Sprache und Einheiten — zwei Einstellungen, nicht eine' },
  },
  {
    slug: 'drivers',
    category: 'fleet',
    surfaces: { site: true, app: true },
    screen: '/app/drivers',
    title: { en: 'Drivers and who was behind the wheel', lt: 'Vairuotojai ir kas sėdėjo prie vairo', pl: 'Kierowcy i kto siedział za kierownicą', de: 'Fahrer — und wer am Steuer saß' },
  },
  {
    slug: 'vehicle-card',
    category: 'fleet',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'The vehicle card: profile, documents and service history', lt: 'Automobilio kortelė: profilis, dokumentai ir serviso istorija', pl: 'Karta pojazdu: profil, dokumenty i historia serwisowa', de: 'Die Fahrzeugkarte: Profil, Dokumente und Servicehistorie' },
  },
  {
    slug: 'maintenance',
    category: 'fleet',
    surfaces: { site: true, app: true },
    screen: '/app/maintenance',
    title: { en: 'Maintenance reminders', lt: 'Priežiūros priminimai', pl: 'Przypomnienia serwisowe', de: 'Wartungserinnerungen' },
  },
  {
    slug: 'plans-and-limits',
    category: 'account',
    surfaces: { site: true, app: true },
    audience: { platformOnly: true },
    screen: '/app/settings',
    title: { en: 'What your plan includes', lt: 'Kas įeina į jūsų planą', pl: 'Co obejmuje Twój plan', de: 'Was Ihr Tarif enthält' },
  },
  {
    slug: 'billing-and-invoices',
    category: 'account',
    surfaces: { site: true, app: true },
    audience: { platformOnly: true, adminOnly: true },
    screen: '/app/settings',
    title: { en: 'Billing, invoices and usage', lt: 'Mokėjimai, sąskaitos ir naudojimas', pl: 'Płatności, faktury i zużycie', de: 'Abrechnung, Rechnungen und Verbrauch' },
  },
  {
    slug: 'unpaid-what-happens',
    category: 'account',
    surfaces: { site: true, app: true },
    audience: { platformOnly: true },
    title: { en: 'What happens if an invoice goes unpaid', lt: 'Kas nutinka neapmokėjus sąskaitos', pl: 'Co się dzieje przy braku płatności', de: 'Was bei einer unbezahlten Rechnung passiert' },
  },
  {
    slug: 'white-label-explained',
    category: 'tsp',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true },
    title: { en: 'What white-label actually means here', lt: 'Ką čia iš tikrųjų reiškia white-label', pl: 'Co tak naprawdę znaczy tu white-label', de: 'Was White-Label hier wirklich bedeutet' },
  },
  {
    slug: 'customer-accounts',
    category: 'tsp',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true, entitlement: 'subAccounts' },
    screen: '/app/accounts',
    title: { en: 'Customer accounts — one per customer', lt: 'Klientų paskyros — po vieną kiekvienam klientui', pl: 'Konta klientów — po jednym na klienta', de: 'Kundenkonten — eines je Kunde' },
  },
  {
    slug: 'branding',
    category: 'tsp',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true, entitlement: 'whiteLabel' },
    screen: '/app/branding',
    title: { en: 'Branding your dashboard', lt: 'Skydelio ženklinimas', pl: 'Marka Twojego panelu', de: 'Ihr Dashboard branden' },
  },
  {
    slug: 'custom-domain',
    category: 'tsp',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true, entitlement: 'customDomains' },
    screen: '/app/branding',
    title: { en: 'Your own domain', lt: 'Nuosavas domenas', pl: 'Własna domena', de: 'Eigene Domain' },
  },
  {
    slug: 'emails-to-your-customers',
    category: 'tsp',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true, entitlement: 'whiteLabel' },
    screen: '/app/branding',
    title: { en: 'E-mail your customers receive', lt: 'Laiškai, kuriuos gauna jūsų klientai', pl: 'E-maile, które dostają Twoi klienci', de: 'E-Mails, die Ihre Kunden erhalten' },
  },
  {
    slug: 'api-quickstart',
    category: 'integrations',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true, entitlement: 'apiAccess' },
    screen: '/app/api-keys',
    title: { en: 'API quick start', lt: 'API pradžia', pl: 'Szybki start API', de: 'API-Schnellstart' },
  },
  {
    slug: 'webhooks',
    category: 'integrations',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true, entitlement: 'webhooks' },
    screen: '/app/webhooks',
    title: { en: 'Webhooks — events pushed to your system', lt: 'Webhook\'ai — įvykiai, siunčiami į jūsų sistemą', pl: 'Webhooki — zdarzenia wypychane do Twojego systemu', de: 'Webhooks — Ereignisse in Ihr System geschoben' },
  },
  {
    slug: 'where-your-data-lives',
    category: 'trust',
    surfaces: { site: true, app: true },
    title: { en: 'Where your data lives and how long it stays', lt: 'Kur laikomi jūsų duomenys ir kiek laiko', pl: 'Gdzie są Twoje dane i jak długo tam zostają', de: 'Wo Ihre Daten liegen und wie lange sie bleiben' },
  },
  {
    slug: 'tracking-employees-lawfully',
    category: 'trust',
    surfaces: { site: true, app: true },
    title: { en: 'Tracking employees lawfully', lt: 'Teisėtas darbuotojų sekimas', pl: 'Legalne monitorowanie pracowników', de: 'Mitarbeiter rechtmäßig orten' },
  },
  {
    slug: 'export-and-erase-data',
    category: 'trust',
    surfaces: { site: true, app: true },
    audience: { adminOnly: true },
    screen: '/app/settings',
    title: { en: 'Exporting and erasing your data', lt: 'Duomenų eksportas ir ištrynimas', pl: 'Eksport i usuwanie danych', de: 'Daten exportieren und löschen' },
  },
  {
    slug: 'device-not-reporting',
    category: 'troubleshooting',
    surfaces: { site: true, app: true },
    screen: '/app/devices',
    title: { en: 'A device is not reporting', lt: 'Įrenginys nesiunčia duomenų', pl: 'Urządzenie nie raportuje', de: 'Ein Gerät meldet sich nicht' },
  },
  {
    slug: 'map-wont-load',
    category: 'troubleshooting',
    surfaces: { site: true, app: true },
    screen: '/app',
    title: { en: 'The map is blank, black or will not load', lt: 'Žemėlapis tuščias, juodas arba neįsikelia', pl: 'Mapa jest pusta, czarna albo się nie ładuje', de: 'Die Karte ist leer, schwarz oder lädt nicht' },
  },
  {
    slug: 'not-getting-emails',
    category: 'troubleshooting',
    surfaces: { site: true, app: true },
    title: { en: 'Not receiving e-mails', lt: 'Negaunu laiškų', pl: 'Nie dostaję e-maili', de: 'Keine E-Mails erhalten' },
  },
]
