import type { LocalizedDoc } from "./types";

/**
 * Impressum / provider information (§5 DDG). Mostly factual provider data — company name, address,
 * register — kept identical across languages; only the surrounding prose is translated.
 */
export const impressum: LocalizedDoc = {
  en: {
    title: "Impressum",
    label: "LEGAL (§5 DDG)",
    updated: "August 2026",
    blocks: [
      { p: "Provider information under §5 DDG (formerly §5 TMG) and Art. 5 of the EU e-Commerce Directive." },
      { h2: "1. Provider" },
      { ul: [
        "**Legal name / Anbieter:** MB Dokigo",
        "**Legal form:** mažoji bendrija (small partnership) under Lithuanian law",
        "**Registered address:** Krivių g. 5, LT-01204 Vilnius, Lithuania",
        "**Company code / Register-Nr.:** 307575857",
        "**Register:** Register of Legal Entities of the Republic of Lithuania (Juridinių asmenų registras), maintained by the State Enterprise Centre of Registers",
        "**Represented by / Vertretungsberechtigt:** Ernestas Dubovskich, Director",
        "**Contact:** [hello@orbetra.com](mailto:hello@orbetra.com)",
        "**Responsible for content (§18 (2) MStV):** Ernestas Dubovskich, address as above",
      ] },
      { p: "**Orbetra** is a product and brand of MB Dokigo." },
      { h2: "2. VAT" },
      { p: "Prices published on this site exclude VAT. Where MB Dokigo is registered for VAT, the VAT identification number is shown on the invoice; EU business customers who supply a valid VAT number are invoiced under the reverse-charge mechanism where it applies." },
      { h2: "3. Data protection" },
      { p: "How we handle personal data is described in the [Privacy Policy](/privacy), the [Cookie Policy](/cookies) and, for customer data, the [Data Processing Addendum](/dpa). We have not appointed a data protection officer; privacy requests go to [hello@orbetra.com](mailto:hello@orbetra.com). The competent supervisory authority is the Lithuanian State Data Protection Inspectorate (Valstybinė duomenų apsaugos inspekcija, VDAI), Vilnius." },
      { h2: "4. Dispute resolution" },
      { p: "Orbetra is sold to businesses and other organisations, not to consumers. We are not obliged and not willing to participate in dispute resolution proceedings before a consumer arbitration board. Contractual disputes are governed by the [Terms of Service](/terms): Lithuanian law, courts of Vilnius. Please write to [hello@orbetra.com](mailto:hello@orbetra.com) first — most things are faster to fix directly." },
      { h2: "5. Liability for content and links" },
      { p: "We prepare the content of this site with care, but we give no warranty that it is complete or current, and product descriptions are not binding offers. Our site contains links to external websites over whose content we have no control. Responsibility for the content of linked pages always lies with their respective operator; if we become aware of an infringement we remove the link." },
    ],
  },
  lt: {
    title: "Rekvizitai",
    label: "TEISINĖ INFORMACIJA (§5 DDG)",
    updated: "2026 m. rugpjūtis",
    blocks: [
      { p: "Paslaugų teikėjo informacija pagal Vokietijos §5 DDG (anksčiau §5 TMG) ir ES Elektroninės komercijos direktyvos 5 straipsnį." },
      { h2: "1. Paslaugų teikėjas" },
      { ul: [
        "**Juridinis pavadinimas:** MB Dokigo",
        "**Teisinė forma:** mažoji bendrija pagal Lietuvos teisę",
        "**Registracijos adresas:** Krivių g. 5, LT-01204 Vilnius, Lietuva",
        "**Įmonės kodas:** 307575857",
        "**Registras:** Lietuvos Respublikos juridinių asmenų registras, tvarkomas VĮ Registrų centro",
        "**Atstovaujantis asmuo:** Ernestas Dubovskich, direktorius",
        "**Kontaktai:** [hello@orbetra.com](mailto:hello@orbetra.com)",
        "**Atsakingas už turinį (§18 (2) MStV):** Ernestas Dubovskich, adresas nurodytas aukščiau",
      ] },
      { p: "**Orbetra** yra MB Dokigo produktas ir prekės ženklas." },
      { h2: "2. PVM" },
      { p: "Šioje svetainėje skelbiamos kainos yra be PVM. Kai MB Dokigo yra registruota PVM mokėtoja, PVM mokėtojo kodas nurodomas sąskaitoje faktūroje; ES verslo klientams, pateikusiems galiojantį PVM kodą, sąskaitos išrašomos taikant atvirkštinio apmokestinimo mechanizmą, kai jis taikytinas." },
      { h2: "3. Duomenų apsauga" },
      { p: "Kaip tvarkome asmens duomenis, aprašyta [Privatumo politikoje](/privacy), [Slapukų politikoje](/cookies) ir, kalbant apie klientų duomenis, [Duomenų tvarkymo priede](/dpa). Duomenų apsaugos pareigūno nepaskyrėme; su privatumu susiję prašymai siunčiami adresu [hello@orbetra.com](mailto:hello@orbetra.com). Kompetentinga priežiūros institucija — Valstybinė duomenų apsaugos inspekcija (VDAI), Vilnius." },
      { h2: "4. Ginčų sprendimas" },
      { p: "Orbetra parduodama verslui ir kitoms organizacijoms, o ne vartotojams. Neprivalome ir nesutinkame dalyvauti ginčų sprendimo procedūrose vartotojų arbitražo komisijoje. Sutartiniams ginčams taikoma [Paslaugų teikimo sąlygose](/terms) nustatyta tvarka: Lietuvos teisė, Vilniaus teismai. Pirmiausia parašykite adresu [hello@orbetra.com](mailto:hello@orbetra.com) — daugelį dalykų greičiau išspręsti tiesiogiai." },
      { h2: "5. Atsakomybė už turinį ir nuorodas" },
      { p: "Šios svetainės turinį rengiame kruopščiai, tačiau negarantuojame, kad jis yra išsamus ar aktualus, o produktų aprašymai nėra įpareigojantys pasiūlymai. Svetainėje yra nuorodų į išorines svetaines, kurių turinio nekontroliuojame. Atsakomybė už susietų puslapių turinį visada tenka atitinkamam jų valdytojui; sužinoję apie pažeidimą, nuorodą pašaliname." },
    ],
  },
  pl: {
    title: "Impressum",
    label: "INFORMACJE PRAWNE (§5 DDG)",
    updated: "sierpień 2026",
    blocks: [
      { p: "Informacje o usługodawcy zgodnie z niemieckim §5 DDG (dawniej §5 TMG) oraz art. 5 dyrektywy UE o handlu elektronicznym." },
      { h2: "1. Usługodawca" },
      { ul: [
        "**Nazwa prawna:** MB Dokigo",
        "**Forma prawna:** mažoji bendrija (mała spółka) według prawa litewskiego",
        "**Adres siedziby:** Krivių g. 5, LT-01204 Wilno, Litwa",
        "**Numer firmy:** 307575857",
        "**Rejestr:** Rejestr Osób Prawnych Republiki Litewskiej (Juridinių asmenų registras), prowadzony przez Centrum Rejestrów",
        "**Reprezentowana przez:** Ernestas Dubovskich, dyrektor",
        "**Kontakt:** [hello@orbetra.com](mailto:hello@orbetra.com)",
        "**Odpowiedzialny za treść (§18 (2) MStV):** Ernestas Dubovskich, adres jak wyżej",
      ] },
      { p: "**Orbetra** jest produktem i marką MB Dokigo." },
      { h2: "2. VAT" },
      { p: "Ceny publikowane na tej stronie nie zawierają VAT. Jeśli MB Dokigo jest zarejestrowana jako podatnik VAT, numer identyfikacyjny VAT jest podany na fakturze; klienci biznesowi z UE, którzy podadzą ważny numer VAT, są rozliczani w ramach mechanizmu odwrotnego obciążenia tam, gdzie ma on zastosowanie." },
      { h2: "3. Ochrona danych" },
      { p: "Sposób przetwarzania danych osobowych opisano w [Polityce prywatności](/privacy), [Polityce plików cookie](/cookies) oraz — w odniesieniu do danych klientów — w [Załączniku o powierzeniu przetwarzania danych](/dpa). Nie wyznaczyliśmy inspektora ochrony danych; wnioski dotyczące prywatności należy kierować na adres [hello@orbetra.com](mailto:hello@orbetra.com). Właściwym organem nadzorczym jest litewski Państwowy Inspektorat Ochrony Danych (Valstybinė duomenų apsaugos inspekcija, VDAI), Wilno." },
      { h2: "4. Rozwiązywanie sporów" },
      { p: "Orbetra jest sprzedawana przedsiębiorstwom i innym organizacjom, a nie konsumentom. Nie jesteśmy zobowiązani ani skłonni uczestniczyć w postępowaniach polubownych przed konsumenckim organem arbitrażowym. Spory umowne reguluje [Regulamin usługi](/terms): prawo litewskie, sądy w Wilnie. Prosimy najpierw napisać na adres [hello@orbetra.com](mailto:hello@orbetra.com) — większość spraw szybciej rozwiązać bezpośrednio." },
      { h2: "5. Odpowiedzialność za treść i odnośniki" },
      { p: "Treści na tej stronie przygotowujemy starannie, nie gwarantujemy jednak ich kompletności ani aktualności, a opisy produktów nie stanowią wiążących ofert. Nasza strona zawiera odnośniki do witryn zewnętrznych, nad których treścią nie mamy kontroli. Odpowiedzialność za treść stron, do których prowadzą odnośniki, ponosi zawsze ich operator; po powzięciu wiadomości o naruszeniu usuwamy odnośnik." },
    ],
  },
  de: {
    title: "Impressum",
    label: "RECHTLICHES (§5 DDG)",
    updated: "August 2026",
    blocks: [
      { p: "Anbieterkennzeichnung gemäß §5 DDG (vormals §5 TMG) und Art. 5 der EU-E-Commerce-Richtlinie." },
      { h2: "1. Anbieter" },
      { ul: [
        "**Anbieter:** MB Dokigo",
        "**Rechtsform:** mažoji bendrija (Kleinpartnerschaft) nach litauischem Recht",
        "**Anschrift:** Krivių g. 5, LT-01204 Vilnius, Litauen",
        "**Registernummer:** 307575857",
        "**Register:** Register der juristischen Personen der Republik Litauen (Juridinių asmenų registras), geführt vom staatlichen Registerzentrum",
        "**Vertretungsberechtigt:** Ernestas Dubovskich, Direktor",
        "**Kontakt:** [hello@orbetra.com](mailto:hello@orbetra.com)",
        "**Verantwortlich für den Inhalt (§18 Abs. 2 MStV):** Ernestas Dubovskich, Anschrift wie oben",
      ] },
      { p: "**Orbetra** ist ein Produkt und eine Marke der MB Dokigo." },
      { h2: "2. Umsatzsteuer" },
      { p: "Die auf dieser Website veröffentlichten Preise verstehen sich ohne Umsatzsteuer. Sofern MB Dokigo umsatzsteuerlich registriert ist, wird die Umsatzsteuer-Identifikationsnummer auf der Rechnung ausgewiesen; EU-Geschäftskunden, die eine gültige USt-IdNr. angeben, wird nach dem Reverse-Charge-Verfahren in Rechnung gestellt, soweit dieses anwendbar ist." },
      { h2: "3. Datenschutz" },
      { p: "Wie wir mit personenbezogenen Daten umgehen, ist in der [Datenschutzerklärung](/privacy), der [Cookie-Richtlinie](/cookies) und — für Kundendaten — im [Auftragsverarbeitungs-Nachtrag](/dpa) beschrieben. Wir haben keinen Datenschutzbeauftragten bestellt; Datenschutzanfragen richten Sie bitte an [hello@orbetra.com](mailto:hello@orbetra.com). Zuständige Aufsichtsbehörde ist die litauische Staatliche Datenschutzinspektion (Valstybinė duomenų apsaugos inspekcija, VDAI), Vilnius." },
      { h2: "4. Streitbeilegung" },
      { p: "Orbetra wird an Unternehmen und andere Organisationen verkauft, nicht an Verbraucher. Wir sind nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen. Vertragliche Streitigkeiten richten sich nach den [Nutzungsbedingungen](/terms): litauisches Recht, Gerichte in Vilnius. Bitte schreiben Sie zuerst an [hello@orbetra.com](mailto:hello@orbetra.com) — die meisten Dinge lassen sich direkt schneller klären." },
      { h2: "5. Haftung für Inhalte und Links" },
      { p: "Die Inhalte dieser Website erstellen wir mit Sorgfalt, übernehmen jedoch keine Gewähr für deren Vollständigkeit oder Aktualität, und Produktbeschreibungen sind keine verbindlichen Angebote. Unsere Website enthält Links zu externen Websites, auf deren Inhalte wir keinen Einfluss haben. Für die Inhalte verlinkter Seiten ist stets deren jeweiliger Betreiber verantwortlich; bei Bekanntwerden einer Rechtsverletzung entfernen wir den Link." },
    ],
  },
};
