import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import pg from 'pg'
import { GenericContainer, Wait, type StartedTestContainer } from 'testcontainers'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import { migrate } from '../sql/migrate.js'

/**
 * R8-2 verification gate (PROJECT_PLAN §6.3 comment + E01-3 AC):
 * buffered floods from devices offline > compress_after insert into COMPRESSED chunks.
 * Prove, on the pinned TimescaleDB version, that (a) a NEW row inserts into a compressed
 * chunk and (b) a DUPLICATE PK with ON CONFLICT DO NOTHING dedupes there too (I3).
 * The measured outcome is written to docs/audit/ts-compressed-insert.md.
 */
const IMAGE = 'timescale/timescaledb-ha:pg16'
const AUDIT_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../docs/audit/ts-compressed-insert.md',
)

let container: StartedTestContainer
let client: pg.Client

beforeAll(async () => {
  container = await new GenericContainer(IMAGE)
    .withEnvironment({ POSTGRES_PASSWORD: 'test', POSTGRES_DB: 'r8two' })
    .withExposedPorts(5432)
    .withWaitStrategy(Wait.forLogMessage(/database system is ready to accept connections/, 2))
    .start()
  const url = `postgresql://postgres:test@${container.getHost()}:${container.getMappedPort(5432)}/r8two`
  await migrate(url)
  client = new pg.Client({ connectionString: url })
  await client.connect()
}, 240_000)

afterAll(async () => {
  await client?.end()
  await container?.stop()
})

const INSERT = `INSERT INTO positions (device_id, fix_time, lat, lon, fix_valid, rec_hash)
  VALUES ($1, $2, 54.7, 25.3, true, $3) ON CONFLICT (device_id, fix_time, rec_hash) DO NOTHING`

describe('R8-2: inserts into compressed chunks (pinned image)', () => {
  it('new row + ON CONFLICT dedupe both work inside a compressed chunk', async () => {
    const oldTs = new Date(Date.now() - 30 * 24 * 3600 * 1000)
    await client.query(INSERT, [1, oldTs, 1001n])

    const chunks = await client.query<{ compress_chunk: string }>(
      `SELECT compress_chunk(c) FROM show_chunks('positions') c ORDER BY c::text LIMIT 1`,
    )
    expect(chunks.rows.length).toBe(1)

    const compressedBefore = await client.query<{ number_compressed_chunks: number }>(
      `SELECT number_compressed_chunks FROM hypertable_compression_stats('positions')`,
    )
    expect(Number(compressedBefore.rows[0]!.number_compressed_chunks)).toBe(1)

    // (a) NEW row, same chunk window, different rec_hash
    let newRowOutcome: string
    try {
      await client.query(INSERT, [1, new Date(oldTs.getTime() + 60_000), 1002n])
      newRowOutcome = 'WORKS'
    } catch (err) {
      newRowOutcome = `FAILS: ${(err as Error).message}`
    }

    // (b) DUPLICATE PK into the compressed chunk — the I3 dedupe path
    let dupOutcome: string
    try {
      const res = await client.query(INSERT, [1, oldTs, 1001n])
      dupOutcome = res.rowCount === 0 ? 'DEDUPES (rowCount 0)' : `UNEXPECTED rowCount ${res.rowCount}`
    } catch (err) {
      dupOutcome = `FAILS: ${(err as Error).message}`
    }

    const version = await client.query<{ extversion: string }>(
      `SELECT extversion FROM pg_extension WHERE extname='timescaledb'`,
    )
    const tsVersion = version.rows[0]!.extversion

    const count = await client.query<{ n: string }>(`SELECT count(*) n FROM positions`)

    // Regenerate the tracked audit doc only when explicitly asked (WRITE_AUDIT=1) —
    // otherwise every test run would dirty the working tree with a new date stamp.
    if (process.env['WRITE_AUDIT'] === '1')
      writeFileSync(
        AUDIT_PATH,
      `# TimescaleDB compressed-chunk insert verification (R8-2 / E01-3 AC)

**Generated by** \`packages/db/__tests__/compressed-insert.spec.ts\` — do not hand-edit; re-run the test to refresh.
**Image:** ${IMAGE} · **TimescaleDB:** ${tsVersion} · **Date:** ${new Date().toISOString().slice(0, 10)}

| Scenario | Outcome |
|---|---|
| INSERT new row into compressed chunk (late buffered record) | ${newRowOutcome} |
| INSERT duplicate PK with ON CONFLICT DO NOTHING into compressed chunk (I3 dedupe) | ${dupOutcome} |
| Rows in table after both | ${count.rows[0]!.n} |

**Consequence for E04-2 recompute:** ${
        newRowOutcome === 'WORKS' && dupOutcome.startsWith('DEDUPES')
          ? 'no decompress_chunk() fallback needed on this version — direct inserts into compressed chunks preserve both insert and dedupe semantics.'
          : 'decompress_chunk() fallback REQUIRED before replaying into compressed windows (set the recompute config flag per E04-2).'
      }
`,
    )

    // the invariant we actually require: both paths must behave
    expect(newRowOutcome).toBe('WORKS')
    expect(dupOutcome).toBe('DEDUPES (rowCount 0)')
    expect(Number(count.rows[0]!.n)).toBe(2)
  }, 120_000)
})
