/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TspRouteImport } from './routes/tsp'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubprocessorsRouteImport } from './routes/subprocessors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as IndexRouteImport } from './routes/index'

const TspRoute = TspRouteImport.update({
  id: '/tsp',
  path: '/tsp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubprocessorsRoute = SubprocessorsRouteImport.update({
  id: '/subprocessors',
  path: '/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dpa': typeof DpaRoute
  '/impressum': typeof ImpressumRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/tsp': typeof TspRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dpa': typeof DpaRoute
  '/impressum': typeof ImpressumRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/tsp': typeof TspRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dpa': typeof DpaRoute
  '/impressum': typeof ImpressumRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/tsp': typeof TspRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dpa'
    | '/impressum'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/subprocessors'
    | '/terms'
    | '/tsp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dpa'
    | '/impressum'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/subprocessors'
    | '/terms'
    | '/tsp'
  id:
    | '__root__'
    | '/'
    | '/dpa'
    | '/impressum'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/subprocessors'
    | '/terms'
    | '/tsp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DpaRoute: typeof DpaRoute
  ImpressumRoute: typeof ImpressumRoute
  PilotRoute: typeof PilotRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SubprocessorsRoute: typeof SubprocessorsRoute
  TermsRoute: typeof TermsRoute
  TspRoute: typeof TspRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tsp': {
      id: '/tsp'
      path: '/tsp'
      fullPath: '/tsp'
      preLoaderRoute: typeof TspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subprocessors': {
      id: '/subprocessors'
      path: '/subprocessors'
      fullPath: '/subprocessors'
      preLoaderRoute: typeof SubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DpaRoute: DpaRoute,
  ImpressumRoute: ImpressumRoute,
  PilotRoute: PilotRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SubprocessorsRoute: SubprocessorsRoute,
  TermsRoute: TermsRoute,
  TspRoute: TspRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
