import type { KbArticle } from '../types.js'

export const apiQuickstart: KbArticle = {
  slug: 'api-quickstart',
  category: 'integrations',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true, entitlement: 'apiAccess' },
  screen: '/app/api-keys',
  doc: {
    en: {
      title: 'API quick start',
      summary: 'Create a key, make your first call, and understand what a key can and cannot do.',
      keywords: ['api', 'rest', 'key', 'integration', 'curl', 'authentication', 'token', 'read-only', 'rate limit'],
      blocks: [
        { p: 'Everything the dashboard shows is available over a REST API, on the same domain your dashboard runs on. There is no separate API host — a white-label deployment answers on its own address, which is what keeps an integration inside one brand.' },
        { h2: 'Create a key', id: 'create' },
        { ol: [
          'Go to **Settings → API keys** and create one. Name it after the system that will use it, not after a person.',
          'Choose the scope: one account, or the whole organisation.',
          'Copy the key immediately. It is shown once and cannot be retrieved afterwards — if it is lost, revoke it and make another.',
        ] },
        { h2: 'Your first call', id: 'first-call' },
        { code: 'curl https://your-dashboard-domain/v1/devices \\\n  -H "X-Api-Key: orb_live_<your-api-key>"' },
        { p: 'Send the key in the `X-Api-Key` header, over HTTPS. `Authorization: Bearer` is the dashboard\'s own session token and is not an API key — a key sent that way is rejected.' },
        { h2: 'What a key can do', id: 'scope' },
        { ul: [
          '**Read only.** Devices, positions, trips, events and reports. There is no write access through a key by design: an integration that can only read cannot damage a fleet.',
          '**Within its scope only.** A key scoped to one account cannot see another, whatever it asks for.',
          '**Rate limited.** Exceeding the limit returns `429` with a `Retry-After` header. Respect it rather than retrying immediately.',
        ] },
        { h2: 'The endpoints you will use first', id: 'endpoints' },
        { table: { head: ['Call', 'Gives you'], rows: [
          ['`GET /v1/devices`', 'Your devices, with names, plates and status.'],
          ['`GET /v1/devices/last`', 'The last known position of every device — the live snapshot in one request.'],
          ['`GET /v1/devices/{id}/positions`', 'Positions for one device over a time range.'],
          ['`GET /v1/trips`', 'Trips, grouped by device and day.'],
          ['`GET /v1/events`', 'Alerts: geofence, overspeed, ignition, power cut and the rest.'],
        ] } },
        { h2: 'Polling versus webhooks', id: 'webhooks' },
        { callout: 'tip', p: 'If you are polling `/v1/events` in a loop to find out when something happened, use a webhook instead — you get the event as it happens, without the loop. See [Webhooks](kb:webhooks).' },
        { h2: 'Looking after keys', id: 'hygiene' },
        { ul: [
          'One key per integration. When something has to be revoked, you want to break one thing, not everything.',
          'Never put a key in a browser, a mobile app or anything a customer can open. A key in a front end is a key everyone has.',
          'Revoke immediately when a key is no longer needed or may have leaked. Revocation is instant and cannot be undone.',
          'The keys list shows when each was last used — the fastest way to find the ones nobody needs any more.',
        ] },
      ],
    },
    lt: {
      title: 'API pradžia',
      summary: 'Sukurkite raktą, atlikite pirmą užklausą ir supraskite, ką raktas gali ir ko negali.',
      keywords: ['api', 'rest', 'raktas', 'integracija', 'curl', 'autentifikavimas', 'tik skaitymas', 'limitas'],
      blocks: [
        { p: 'Viskas, ką rodo skydelis, prieinama per REST API tuo pačiu domenu, kuriuo veikia jūsų skydelis. Atskiro API serverio nėra – prekės ženklu pažymėtas diegimas atsako savo adresu, ir kaip tik tai išlaiko integraciją viename prekės ženkle.' },
        { h2: 'Sukurkite raktą', id: 'create' },
        { ol: [
          'Eikite į **Nustatymai → API raktai** ir sukurkite. Pavadinkite pagal sistemą, kuri jį naudos, o ne pagal žmogų.',
          'Parinkite apimtį: viena paskyra ar visa organizacija.',
          'Iškart nukopijuokite raktą. Jis parodomas vieną kartą ir vėliau neatgaunamas – pametus reikia jį atšaukti ir sukurti kitą.',
        ] },
        { h2: 'Pirmoji užklausa', id: 'first-call' },
        { code: 'curl https://your-dashboard-domain/v1/devices \\\n  -H "X-Api-Key: orb_live_<your-api-key>"' },
        { p: 'Raktą siųskite `X-Api-Key` antraštėje per HTTPS. `Authorization: Bearer` yra paties skydelio sesijos raktas, o ne API raktas – taip atsiųstas raktas atmetamas.' },
        { h2: 'Ką raktas gali', id: 'scope' },
        { ul: [
          '**Tik skaityti.** Įrenginius, pozicijas, keliones, įvykius ir ataskaitas. Rašymo per raktą sąmoningai nėra: integracija, kuri gali tik skaityti, parko sugadinti negali.',
          '**Tik savo apimtyje.** Vienai paskyrai priskirtas raktas kitos nemato, kad ir ko prašytų.',
          '**Ribojamas dažnis.** Viršijus limitą grąžinamas `429` su `Retry-After` antrašte. Jos laikykitės, o ne kartokite iškart.',
        ] },
        { h2: 'Galiniai taškai, kuriuos naudosite pirmiausia', id: 'endpoints' },
        { table: { head: ['Užklausa', 'Ką duoda'], rows: [
          ['`GET /v1/devices`', 'Jūsų įrenginius su pavadinimais, numeriais ir būsena.'],
          ['`GET /v1/devices/last`', 'Paskutinę žinomą kiekvieno įrenginio poziciją – gyvą momentinę nuotrauką viena užklausa.'],
          ['`GET /v1/devices/{id}/positions`', 'Vieno įrenginio pozicijas per laiko intervalą.'],
          ['`GET /v1/trips`', 'Keliones, sugrupuotas pagal įrenginį ir dieną.'],
          ['`GET /v1/events`', 'Pranešimus: geozonos, greičio viršijimo, degimo, maitinimo dingimo ir kitus.'],
        ] } },
        { h2: 'Apklausa ar webhook\'ai', id: 'webhooks' },
        { callout: 'tip', p: 'Jei ciklu apklausinėjate `/v1/events`, kad sužinotumėte, kada kas nutiko, geriau naudokite webhook\'ą – įvykį gausite tą pačią akimirką ir be ciklo. Žr. [Webhook\'ai](kb:webhooks).' },
        { h2: 'Kaip prižiūrėti raktus', id: 'hygiene' },
        { ul: [
          'Po vieną raktą kiekvienai integracijai. Kai ką nors reikia atšaukti, norite sugadinti vieną dalyką, o ne viską.',
          'Niekada nedėkite rakto į naršyklę, mobiliąją programėlę ar bet ką, ką klientas gali atverti. Raktas priekinėje dalyje – raktas, kurį turi visi.',
          'Atšaukite iškart, kai raktas nebereikalingas arba galėjo nutekėti. Atšaukimas įsigalioja iškart ir yra negrįžtamas.',
          'Raktų sąrašas rodo, kada kiekvienas paskutinį kartą naudotas – greičiausias būdas rasti tuos, kurių niekam nebereikia.',
        ] },
      ],
    },
    pl: {
      title: 'Szybki start API',
      summary: 'Utwórz klucz, wykonaj pierwsze wywołanie i zrozum, co klucz może, a czego nie.',
      keywords: ['api', 'rest', 'klucz', 'integracja', 'curl', 'uwierzytelnianie', 'tylko odczyt', 'limit'],
      blocks: [
        { p: 'Wszystko, co pokazuje panel, jest dostępne przez REST API pod tą samą domeną, na której działa Twój panel. Nie ma osobnego hosta API — instalacja z własną marką odpowiada pod własnym adresem, i to właśnie trzyma integrację wewnątrz jednej marki.' },
        { h2: 'Utwórz klucz', id: 'create' },
        { ol: [
          'Wejdź w **Ustawieniach → Klucze API** i utwórz klucz. Nazwij go po systemie, który go użyje, a nie po osobie.',
          'Wybierz zakres: jedno konto albo cała organizacja.',
          'Skopiuj klucz od razu. Pokazuje się raz i później nie da się go odzyskać — jeśli zginie, unieważnij go i zrób nowy.',
        ] },
        { h2: 'Pierwsze wywołanie', id: 'first-call' },
        { code: 'curl https://your-dashboard-domain/v1/devices \\\n  -H "X-Api-Key: orb_live_<your-api-key>"' },
        { p: 'Klucz wysyłaj w nagłówku `X-Api-Key`, po HTTPS. `Authorization: Bearer` to własny token sesji panelu, a nie klucz API — klucz wysłany w ten sposób zostanie odrzucony.' },
        { h2: 'Co klucz może', id: 'scope' },
        { ul: [
          '**Tylko odczyt.** Urządzenia, pozycje, trasy, zdarzenia i raporty. Zapisu przez klucz celowo nie ma: integracja, która potrafi tylko czytać, nie zepsuje floty.',
          '**Tylko w swoim zakresie.** Klucz przypisany do jednego konta nie zobaczy innego, o cokolwiek zapyta.',
          '**Limit żądań.** Przekroczenie zwraca `429` z nagłówkiem `Retry-After`. Uszanuj go, zamiast ponawiać natychmiast.',
        ] },
        { h2: 'Punkty końcowe, których użyjesz najpierw', id: 'endpoints' },
        { table: { head: ['Wywołanie', 'Co daje'], rows: [
          ['`GET /v1/devices`', 'Twoje urządzenia z nazwami, tablicami i statusem.'],
          ['`GET /v1/devices/last`', 'Ostatnią znaną pozycję każdego urządzenia — migawkę na żywo w jednym żądaniu.'],
          ['`GET /v1/devices/{id}/positions`', 'Pozycje jednego urządzenia w zakresie czasu.'],
          ['`GET /v1/trips`', 'Trasy pogrupowane po urządzeniu i dniu.'],
          ['`GET /v1/events`', 'Alerty: geostrefa, przekroczenie prędkości, zapłon, utrata zasilania i pozostałe.'],
        ] } },
        { h2: 'Odpytywanie czy webhooki', id: 'webhooks' },
        { callout: 'tip', p: 'Jeśli odpytujesz `/v1/events` w pętli, żeby dowiedzieć się, kiedy coś się stało, użyj raczej webhooka — dostaniesz zdarzenie w chwili jego wystąpienia, bez pętli. Zobacz [Webhooki](kb:webhooks).' },
        { h2: 'Higiena kluczy', id: 'hygiene' },
        { ul: [
          'Jeden klucz na integrację. Gdy trzeba coś unieważnić, chcesz zepsuć jedną rzecz, a nie wszystko.',
          'Nigdy nie umieszczaj klucza w przeglądarce, aplikacji mobilnej ani niczym, co klient może otworzyć. Klucz we frontendzie to klucz, który ma każdy.',
          'Unieważniaj natychmiast, gdy klucz przestaje być potrzebny albo mógł wyciec. Unieważnienie działa od razu i jest nieodwracalne.',
          'Lista kluczy pokazuje, kiedy każdy był ostatnio użyty — najszybszy sposób na znalezienie tych, których już nikt nie potrzebuje.',
        ] },
      ],
    },
    de: {
      title: 'API-Schnellstart',
      summary: 'Einen Schlüssel anlegen, den ersten Aufruf machen und verstehen, was ein Schlüssel darf und was nicht.',
      keywords: ['api', 'rest', 'schlüssel', 'integration', 'curl', 'authentifizierung', 'nur lesen', 'ratenlimit'],
      blocks: [
        { p: 'Alles, was das Dashboard zeigt, ist über eine REST-API verfügbar — auf derselben Domain, auf der Ihr Dashboard läuft. Es gibt keinen separaten API-Host: Eine gebrandete Installation antwortet unter ihrer eigenen Adresse, und genau das hält eine Integration innerhalb einer Marke.' },
        { h2: 'Einen Schlüssel anlegen', id: 'create' },
        { ol: [
          'Unter **Einstellungen → API-Schlüssel** einen anlegen. Benennen Sie ihn nach dem System, das ihn nutzt, nicht nach einer Person.',
          'Den Geltungsbereich wählen: ein Konto oder die ganze Organisation.',
          'Den Schlüssel sofort kopieren. Er wird einmal angezeigt und ist danach nicht mehr abrufbar — geht er verloren, widerrufen Sie ihn und legen einen neuen an.',
        ] },
        { h2: 'Ihr erster Aufruf', id: 'first-call' },
        { code: 'curl https://your-dashboard-domain/v1/devices \\\n  -H "X-Api-Key: orb_live_<your-api-key>"' },
        { p: 'Senden Sie den Schlüssel im Header `X-Api-Key`, über HTTPS. `Authorization: Bearer` ist das Sitzungstoken des Dashboards und kein API-Schlüssel — so gesendet wird er abgelehnt.' },
        { h2: 'Was ein Schlüssel darf', id: 'scope' },
        { ul: [
          '**Nur lesen.** Geräte, Positionen, Fahrten, Ereignisse und Berichte. Schreibzugriff über einen Schlüssel gibt es bewusst nicht: Eine Integration, die nur lesen kann, richtet an einer Flotte keinen Schaden an.',
          '**Nur im eigenen Bereich.** Ein auf ein Konto begrenzter Schlüssel sieht kein anderes, was immer er anfragt.',
          '**Ratenbegrenzt.** Ein Überschreiten liefert `429` mit einem `Retry-After`-Header. Halten Sie sich daran, statt sofort erneut zu versuchen.',
        ] },
        { h2: 'Die Endpunkte für den Anfang', id: 'endpoints' },
        { table: { head: ['Aufruf', 'Liefert'], rows: [
          ['`GET /v1/devices`', 'Ihre Geräte mit Namen, Kennzeichen und Status.'],
          ['`GET /v1/devices/last`', 'Die letzte bekannte Position jedes Geräts — die Momentaufnahme in einer Anfrage.'],
          ['`GET /v1/devices/{id}/positions`', 'Positionen eines Geräts über einen Zeitraum.'],
          ['`GET /v1/trips`', 'Fahrten, gruppiert nach Gerät und Tag.'],
          ['`GET /v1/events`', 'Alarme: Geozone, Tempoüberschreitung, Zündung, Stromausfall und die übrigen.'],
        ] } },
        { h2: 'Polling oder Webhooks', id: 'webhooks' },
        { callout: 'tip', p: 'Wenn Sie `/v1/events` in einer Schleife abfragen, um zu erfahren, wann etwas passiert ist, nehmen Sie lieber einen Webhook — Sie bekommen das Ereignis im Moment seines Auftretens, ohne Schleife. Siehe [Webhooks](kb:webhooks).' },
        { h2: 'Schlüsselpflege', id: 'hygiene' },
        { ul: [
          'Ein Schlüssel je Integration. Wenn etwas widerrufen werden muss, wollen Sie eine Sache kaputtmachen, nicht alles.',
          'Nie einen Schlüssel in einen Browser, eine App oder irgendetwas legen, das ein Kunde öffnen kann. Ein Schlüssel im Frontend ist ein Schlüssel, den alle haben.',
          'Sofort widerrufen, wenn ein Schlüssel nicht mehr gebraucht wird oder abgeflossen sein könnte. Der Widerruf wirkt sofort und ist endgültig.',
          'Die Schlüsselliste zeigt die letzte Verwendung — der schnellste Weg zu denen, die niemand mehr braucht.',
        ] },
      ],
    },
  },
}
