import type { KbArticle } from '../types.js'

export const auditLog: KbArticle = {
  slug: 'audit-log',
  category: 'trust',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true },
  screen: '/app/audit',
  doc: {
    en: {
      title: 'The audit log — who changed what',
      summary: 'Every change anyone made, with the values before and after. What it records, what it deliberately does not, and the questions it settles.',
      keywords: ['audit', 'log', 'history', 'who', 'changed', 'trail', 'accountability', 'compliance'],
      blocks: [
        { p: 'Every change to a device, rule, zone, driver, login, key or setting is recorded: who made it, when, and what the value was before and after. Nobody has to remember, and nobody has to be believed.' },
        { h2: 'What an entry contains', id: 'entry' },
        { table: { head: ['Column', 'Meaning'], rows: [
          ['**When**', 'The moment of the change, in your display time zone.'],
          ['**User**', 'The person who made it — or **System**, for something the platform did on a schedule.'],
          ['**Action**', 'Created, Updated or Deleted.'],
          ['**Entity**', 'What was touched: a device, a rule, a zone, a login, a key, a domain, a document…'],
          ['**Details**', 'The fields that changed, each with its value before and after.'],
        ] } },
        { p: 'Filter by entity and by action to cut a long trail down to the question you are asking.' },
        { h2: 'The questions it settles', id: 'uses' },
        { ul: [
          '“Why did this vehicle stop reporting on Tuesday?” — someone changed a setting, and the entry says who and to what.',
          '“Who deleted the depot zone?” — the entry survives the zone.',
          '“Did anybody touch this rule before the alerts stopped?” — filter to rules, read the diff.',
          '“Who added this login?” — every account and login change is recorded, which is what makes handing out access safe.',
        ] },
        { h2: 'What it does not record', id: 'not' },
        { ul: [
          '**Reading.** Who opened which screen is not tracked. The log is about changes, not surveillance of your own staff.',
          '**Positions.** A vehicle moving is not a change somebody made — that history is in trips and playback.',
          '**Secrets.** A password or a key is shown as hidden rather than in the clear. That an API key was created is on the record; the key itself never is.',
        ] },
        { callout: 'note', p: 'Entries cannot be edited or removed from the interface — not by an admin, not by anyone. A log that could be tidied afterwards would not be worth reading.' },
        { h2: 'When someone leaves', id: 'leavers' },
        { p: 'Removing a login stops that person signing in immediately, and leaves everything they did in the log. That is deliberate, and it is the reason to remove a login rather than reuse it for the next person: an entry attributed to an address two people shared answers nothing.' },
      ],
    },
    lt: {
      title: 'Audito žurnalas — kas ką pakeitė',
      summary: 'Kiekvienas kieno nors atliktas pakeitimas su reikšmėmis prieš ir po. Ką jis įrašo, ko sąmoningai neįrašo ir kokius klausimus išsprendžia.',
      keywords: ['auditas', 'žurnalas', 'istorija', 'kas', 'pakeitė', 'atsakomybė', 'atitiktis'],
      blocks: [
        { p: 'Kiekvienas įrenginio, taisyklės, zonos, vairuotojo, prisijungimo, rakto ar nustatymo pakeitimas įrašomas: kas jį atliko, kada ir kokia reikšmė buvo prieš ir po. Niekam nereikia prisiminti ir niekuo nereikia tikėti.' },
        { h2: 'Ką turi įrašas', id: 'entry' },
        { table: { head: ['Stulpelis', 'Reikšmė'], rows: [
          ['**Kada**', 'Pakeitimo momentas jūsų rodymo laiko juosta.'],
          ['**Vartotojas**', 'Jį atlikęs žmogus – arba **Sistema**, jei tai pagal grafiką padarė pati platforma.'],
          ['**Veiksmas**', 'Sukurta, Atnaujinta arba Ištrinta.'],
          ['**Objektas**', 'Kas paliesta: įrenginys, taisyklė, zona, prisijungimas, raktas, domenas, dokumentas…'],
          ['**Detalės**', 'Pasikeitę laukai, kiekvienas su reikšme prieš ir po.'],
        ] } },
        { p: 'Filtruokite pagal objektą ir veiksmą, kad ilgą pėdsaką sumažintumėte iki to klausimo, kurio klausiate.' },
        { h2: 'Kokius klausimus jis išsprendžia', id: 'uses' },
        { ul: [
          '„Kodėl šis automobilis antradienį nustojo siųsti duomenis?“ – kažkas pakeitė nustatymą, ir įrašas sako kas ir į ką.',
          '„Kas ištrynė bazės zoną?“ – įrašas pergyvena pačią zoną.',
          '„Ar kas nors lietė šią taisyklę prieš nutylant pranešimams?“ – filtruokite taisykles ir perskaitykite skirtumą.',
          '„Kas pridėjo šį prisijungimą?“ – kiekvienas paskyros ir prisijungimo pakeitimas įrašomas, ir kaip tik dėl to prieigą dalyti saugu.',
        ] },
        { h2: 'Ko jis neįrašo', id: 'not' },
        { ul: [
          '**Skaitymo.** Kas kurį ekraną atvėrė, nesekama. Žurnalas yra apie pakeitimus, o ne apie savo darbuotojų stebėjimą.',
          '**Pozicijų.** Judantis automobilis nėra kieno nors atliktas pakeitimas – ta istorija yra kelionėse ir peržaidime.',
          '**Paslapčių.** Slaptažodis ar raktas rodomas kaip paslėptas, o ne atviru tekstu. Tai, kad API raktas buvo sukurtas, lieka įraše; pats raktas – niekada.',
        ] },
        { callout: 'note', p: 'Įrašų iš sąsajos redaguoti ar pašalinti negalima – nei administratoriui, nei niekam. Žurnalas, kurį vėliau būtų galima „sutvarkyti“, nebūtų vertas skaitymo.' },
        { h2: 'Kai žmogus išeina', id: 'leavers' },
        { p: 'Pašalinus prisijungimą, tas žmogus iškart nebegali prisijungti, o viskas, ką jis darė, lieka žurnale. Tai sąmoninga, ir kaip tik todėl prisijungimą reikia pašalinti, o ne perduoti kitam: įrašas, priskirtas adresui, kurį dalijosi du žmonės, neatsako į nieką.' },
      ],
    },
    pl: {
      title: 'Dziennik audytu — kto co zmienił',
      summary: 'Każda zmiana wprowadzona przez kogokolwiek, z wartościami przed i po. Co zapisuje, czego celowo nie zapisuje i jakie pytania rozstrzyga.',
      keywords: ['audyt', 'dziennik', 'historia', 'kto', 'zmienił', 'odpowiedzialność', 'zgodność'],
      blocks: [
        { p: 'Każda zmiana urządzenia, reguły, strefy, kierowcy, loginu, klucza czy ustawienia jest zapisywana: kto ją wprowadził, kiedy i jaka wartość była przed i po. Nikt nie musi pamiętać i nikomu nie trzeba wierzyć na słowo.' },
        { h2: 'Co zawiera wpis', id: 'entry' },
        { table: { head: ['Kolumna', 'Znaczenie'], rows: [
          ['**Kiedy**', 'Moment zmiany, w Twojej strefie wyświetlania.'],
          ['**Użytkownik**', 'Osoba, która ją wprowadziła — albo **System**, gdy zrobiła to platforma według harmonogramu.'],
          ['**Akcja**', 'Utworzono, Zaktualizowano albo Usunięto.'],
          ['**Obiekt**', 'Czego dotyczyła: urządzenia, reguły, strefy, loginu, klucza, domeny, dokumentu…'],
          ['**Szczegóły**', 'Pola, które się zmieniły, każde z wartością przed i po.'],
        ] } },
        { p: 'Filtruj po obiekcie i akcji, żeby zawęzić długi ślad do pytania, które faktycznie zadajesz.' },
        { h2: 'Jakie pytania rozstrzyga', id: 'uses' },
        { ul: [
          '„Dlaczego ten pojazd przestał raportować we wtorek?” — ktoś zmienił ustawienie, a wpis mówi kto i na co.',
          '„Kto usunął strefę bazy?” — wpis przeżywa samą strefę.',
          '„Czy ktoś ruszał tę regułę, zanim ustały alerty?” — odfiltruj reguły i przeczytaj różnicę.',
          '„Kto dodał ten login?” — każda zmiana konta i loginu jest zapisana, i to właśnie czyni rozdawanie dostępu bezpiecznym.',
        ] },
        { h2: 'Czego nie zapisuje', id: 'not' },
        { ul: [
          '**Odczytów.** Kto otworzył który ekran, nie jest śledzone. Dziennik dotyczy zmian, a nie inwigilacji własnych pracowników.',
          '**Pozycji.** Jadący pojazd nie jest zmianą wprowadzoną przez człowieka — ta historia jest w trasach i odtwarzaniu.',
          '**Sekretów.** Hasło albo klucz pokazywane są jako ukryte, nie jawnie. To, że klucz API powstał, zostaje w zapisie; sam klucz nigdy.',
        ] },
        { callout: 'note', p: 'Wpisów nie da się edytować ani usunąć z interfejsu — ani administratorowi, ani nikomu. Dziennik, który dałoby się później „uporządkować”, nie byłby wart czytania.' },
        { h2: 'Gdy ktoś odchodzi', id: 'leavers' },
        { p: 'Usunięcie loginu natychmiast odcina tej osobie logowanie, a wszystko, co zrobiła, zostaje w dzienniku. To celowe i właśnie dlatego login należy usunąć, a nie przekazać następnej osobie: wpis przypisany do adresu dzielonego przez dwie osoby nie odpowiada na nic.' },
      ],
    },
    de: {
      title: 'Das Audit-Log — wer was geändert hat',
      summary: 'Jede Änderung, die jemand gemacht hat, mit den Werten davor und danach. Was es festhält, was bewusst nicht, und welche Fragen es klärt.',
      keywords: ['audit', 'protokoll', 'historie', 'wer', 'geändert', 'nachvollziehbarkeit', 'compliance'],
      blocks: [
        { p: 'Jede Änderung an einem Gerät, einer Regel, einer Zone, einem Fahrer, einem Zugang, einem Schlüssel oder einer Einstellung wird festgehalten: wer sie gemacht hat, wann, und welchen Wert es davor und danach hatte. Niemand muss sich erinnern, und niemandem muss geglaubt werden.' },
        { h2: 'Was ein Eintrag enthält', id: 'entry' },
        { table: { head: ['Spalte', 'Bedeutung'], rows: [
          ['**Wann**', 'Der Zeitpunkt der Änderung, in Ihrer Anzeigezeitzone.'],
          ['**Benutzer**', 'Die Person, die sie gemacht hat — oder **System**, wenn die Plattform es planmäßig tat.'],
          ['**Aktion**', 'Erstellt, Aktualisiert oder Gelöscht.'],
          ['**Objekt**', 'Was betroffen war: Gerät, Regel, Zone, Zugang, Schlüssel, Domain, Dokument…'],
          ['**Details**', 'Die geänderten Felder, jeweils mit Wert davor und danach.'],
        ] } },
        { p: 'Filtern Sie nach Objekt und Aktion, um eine lange Spur auf die Frage einzudampfen, die Sie wirklich stellen.' },
        { h2: 'Welche Fragen es klärt', id: 'uses' },
        { ul: [
          '„Warum hat dieses Fahrzeug am Dienstag aufgehört zu melden?“ — jemand hat eine Einstellung geändert, und der Eintrag nennt wer und worauf.',
          '„Wer hat die Hof-Zone gelöscht?“ — der Eintrag überlebt die Zone.',
          '„Hat jemand diese Regel angefasst, bevor die Alarme ausblieben?“ — auf Regeln filtern, die Differenz lesen.',
          '„Wer hat diesen Zugang angelegt?“ — jede Konto- und Zugangsänderung steht darin, und genau das macht das Verteilen von Zugriff sicher.',
        ] },
        { h2: 'Was es nicht festhält', id: 'not' },
        { ul: [
          '**Lesen.** Wer welchen Bildschirm geöffnet hat, wird nicht erfasst. Das Log handelt von Änderungen, nicht von der Überwachung der eigenen Leute.',
          '**Positionen.** Ein fahrendes Fahrzeug ist keine Änderung, die jemand gemacht hat — dieser Verlauf steht in Fahrten und Wiedergabe.',
          '**Geheimnisse.** Ein Passwort oder Schlüssel erscheint als verborgen, nicht im Klartext. Dass ein API-Schlüssel angelegt wurde, steht im Protokoll; der Schlüssel selbst nie.',
        ] },
        { callout: 'note', p: 'Einträge lassen sich über die Oberfläche weder bearbeiten noch entfernen — von keinem Admin und von niemandem. Ein Protokoll, das man nachträglich aufräumen könnte, wäre das Lesen nicht wert.' },
        { h2: 'Wenn jemand geht', id: 'leavers' },
        { p: 'Das Löschen eines Zugangs beendet die Anmeldung dieser Person sofort und lässt alles, was sie getan hat, im Protokoll stehen. Das ist Absicht — und der Grund, einen Zugang zu löschen statt ihn an die nächste Person weiterzugeben: Ein Eintrag unter einer Adresse, die sich zwei geteilt haben, beantwortet nichts.' },
      ],
    },
  },
}
