import type { KbArticle } from '../types.js'

export const billingAndInvoices: KbArticle = {
  slug: 'billing-and-invoices',
  category: 'account',
  surfaces: { site: true, app: true },
  audience: { platformOnly: true, adminOnly: true },
  screen: '/app/settings',
  doc: {
    en: {
      title: 'Billing, invoices and usage',
      summary: 'Where the invoices are, how a mid-month plan change is charged, and how device-days and overage are counted.',
      keywords: ['billing', 'invoice', 'payment', 'card', 'stripe', 'proration', 'overage', 'device-days', 'vat', 'subscription'],
      blocks: [
        { p: 'Payments are handled by Stripe. Card details are never stored here and are never visible to anyone in this dashboard — the billing screen takes you to Stripe\'s own portal for anything involving a card.' },
        { h2: 'What is on the billing screen', id: 'screen' },
        { ul: [
          'The current plan and the date it renews.',
          'The payment method on file, by its last digits and expiry.',
          'Usage so far this period.',
          'The upcoming invoice, including anything accrued.',
          'A link into the Stripe portal for invoices, receipts, VAT details and changing the card.',
        ] },
        { h2: 'How usage is counted', id: 'usage' },
        { table: { head: ['Term', 'Meaning'], rows: [
          ['**Active devices**', 'Devices registered and not retired right now.'],
          ['**Peak per day**', 'The highest count reached on any single day of the period. A device added and retired on the same day still counted that day.'],
          ['**Device-days**', 'The sum across the period: one device for thirty days and thirty devices for one day are the same number.'],
          ['**Overage device-days**', 'The part of that sum above the allowance included in the plan. Billed at the metered rate on the next invoice.'],
        ] } },
        { callout: 'note', p: 'Counting in device-days is what makes a fleet that grows mid-month fair in both directions: you are not charged a full month for a device added on the 28th, and you are not free to add fifty for a week without it showing.' },
        { h2: 'Changing plan mid-period', id: 'proration' },
        { p: 'A change takes effect immediately, and the money is settled on the **next** invoice rather than in the moment. An upgrade adds the prorated difference for the remainder of the period; a downgrade credits the unused portion. Nothing is charged to the card at the moment you switch, and the confirmation dialog states the exact amount before you agree to it.' },
        { h2: 'Failed payments', id: 'failed' },
        { p: 'A card that fails is retried on Stripe\'s schedule, and the subscription sits in a grace state while that happens. Service continues during the retries — this is a temporary card problem, not a decision about your account. If the retries all fail, see [What happens if an invoice goes unpaid](kb:unpaid-what-happens).' },
        { h2: 'Invoices, VAT and receipts', id: 'invoices' },
        { p: 'Every invoice, receipt and VAT document lives in the Stripe portal, reachable from the billing screen, and stays available after a subscription ends. Company name, address and VAT number are edited there too, and take effect from the next invoice — an invoice already issued cannot be reissued with different details.' },
      ],
    },
    lt: {
      title: 'Mokėjimai, sąskaitos ir naudojimas',
      summary: 'Kur yra sąskaitos, kaip apmokestinamas plano keitimas mėnesio viduryje ir kaip skaičiuojamos įrenginių dienos bei viršijimas.',
      keywords: ['mokėjimai', 'sąskaita', 'kortelė', 'stripe', 'proporcinis', 'viršijimas', 'įrenginių dienos', 'pvm', 'prenumerata'],
      blocks: [
        { p: 'Mokėjimus tvarko Stripe. Kortelės duomenys čia niekada nesaugomi ir šiame skydelyje niekam nematomi – viskam, kas susiję su kortele, mokėjimų ekranas nuveda į patį Stripe portalą.' },
        { h2: 'Kas yra mokėjimų ekrane', id: 'screen' },
        { ul: [
          'Dabartinis planas ir atnaujinimo data.',
          'Įrašytas mokėjimo būdas – paskutiniai skaitmenys ir galiojimas.',
          'Šio laikotarpio naudojimas iki šiol.',
          'Artėjanti sąskaita kartu su viskuo, kas susikaupė.',
          'Nuoroda į Stripe portalą sąskaitoms, kvitams, PVM duomenims ir kortelės keitimui.',
        ] },
        { h2: 'Kaip skaičiuojamas naudojimas', id: 'usage' },
        { table: { head: ['Sąvoka', 'Reikšmė'], rows: [
          ['**Aktyvūs įrenginiai**', 'Šiuo metu užregistruoti ir dar neišregistruoti įrenginiai.'],
          ['**Dienos pikas**', 'Didžiausias skaičius, pasiektas bet kurią laikotarpio dieną. Tą pačią dieną pridėtas ir išregistruotas įrenginys tą dieną vis tiek skaičiuojasi.'],
          ['**Įrenginių dienos**', 'Suma per laikotarpį: vienas įrenginys trisdešimt dienų ir trisdešimt įrenginių vieną dieną yra tas pats skaičius.'],
          ['**Viršijimo įrenginių dienos**', 'Tos sumos dalis virš į planą įskaičiuoto kiekio. Apmokestinama pagal matuojamą įkainį kitoje sąskaitoje.'],
        ] } },
        { callout: 'note', p: 'Skaičiavimas įrenginių dienomis padaro mėnesio viduryje augantį parką sąžiningą į abi puses: už 28 dieną pridėtą įrenginį neapmokestinama visam mėnesiui, o penkiasdešimt savaitei pridėtų neliks nepastebėti.' },
        { h2: 'Plano keitimas laikotarpio viduryje', id: 'proration' },
        { p: 'Pakeitimas įsigalioja iškart, o pinigai suvedami **kitoje** sąskaitoje, o ne tą pačią akimirką. Aukštesnis planas prideda proporcingą skirtumą už likusį laikotarpį; žemesnis įskaito nepanaudotą dalį. Persijungimo akimirką nuo kortelės nenuskaitoma nieko, o patvirtinimo langas prieš sutinkant nurodo tikslią sumą.' },
        { h2: 'Nepavykę mokėjimai', id: 'failed' },
        { p: 'Nepavykusi kortelė kartojama pagal Stripe grafiką, o prenumerata tuo metu būna atidėjimo būsenoje. Kartojimų metu paslauga tęsiasi – tai laikina kortelės problema, o ne sprendimas dėl jūsų paskyros. Jei nepavyksta visi bandymai, žr. [Kas nutinka neapmokėjus sąskaitos](kb:unpaid-what-happens).' },
        { h2: 'Sąskaitos, PVM ir kvitai', id: 'invoices' },
        { p: 'Kiekviena sąskaita, kvitas ir PVM dokumentas gyvena Stripe portale, pasiekiamame iš mokėjimų ekrano, ir lieka prieinami pasibaigus prenumeratai. Įmonės pavadinimas, adresas ir PVM kodas redaguojami irgi ten ir įsigalioja nuo kitos sąskaitos – jau išrašytos sąskaitos kitais duomenimis perrašyti negalima.' },
      ],
    },
    pl: {
      title: 'Płatności, faktury i zużycie',
      summary: 'Gdzie są faktury, jak rozliczana jest zmiana planu w połowie miesiąca i jak liczy się dni urządzeń oraz nadwyżkę.',
      keywords: ['płatności', 'faktura', 'karta', 'stripe', 'proporcjonalnie', 'nadwyżka', 'dni urządzeń', 'vat', 'subskrypcja'],
      blocks: [
        { p: 'Płatnościami zajmuje się Stripe. Dane karty nigdy nie są tu przechowywane i nikt w tym panelu ich nie widzi — we wszystkim, co dotyczy karty, ekran płatności przenosi do portalu Stripe.' },
        { h2: 'Co jest na ekranie płatności', id: 'screen' },
        { ul: [
          'Bieżący plan i data odnowienia.',
          'Zapisana metoda płatności — ostatnie cyfry i data ważności.',
          'Zużycie w tym okresie do tej pory.',
          'Nadchodząca faktura wraz z tym, co się naliczyło.',
          'Link do portalu Stripe po faktury, potwierdzenia, dane do VAT i zmianę karty.',
        ] },
        { h2: 'Jak liczone jest zużycie', id: 'usage' },
        { table: { head: ['Pojęcie', 'Znaczenie'], rows: [
          ['**Aktywne urządzenia**', 'Urządzenia obecnie zarejestrowane i niewycofane.'],
          ['**Szczyt dzienny**', 'Najwyższa liczba osiągnięta któregoś dnia okresu. Urządzenie dodane i wycofane tego samego dnia i tak liczyło się tego dnia.'],
          ['**Dni urządzeń**', 'Suma za okres: jedno urządzenie przez trzydzieści dni i trzydzieści urządzeń przez jeden dzień to ta sama liczba.'],
          ['**Dni urządzeń ponad limit**', 'Ta część sumy, która przekracza pulę zawartą w planie. Rozliczana według stawki licznikowej na następnej fakturze.'],
        ] } },
        { callout: 'note', p: 'Liczenie w dniach urządzeń czyni flotę rosnącą w połowie miesiąca sprawiedliwą w obie strony: nie płacisz pełnego miesiąca za urządzenie dodane 28-go, a dodanie pięćdziesięciu na tydzień nie przejdzie niezauważone.' },
        { h2: 'Zmiana planu w trakcie okresu', id: 'proration' },
        { p: 'Zmiana działa natychmiast, a pieniądze rozlicza **następna** faktura, nie ta chwila. Wyższy plan dodaje proporcjonalną różnicę za resztę okresu; niższy zalicza niewykorzystaną część. W momencie przełączenia karta nie jest obciążana, a okno potwierdzenia podaje dokładną kwotę, zanim się zgodzisz.' },
        { h2: 'Nieudane płatności', id: 'failed' },
        { p: 'Nieudana karta jest ponawiana według harmonogramu Stripe, a subskrypcja czeka w stanie karencji. Podczas ponowień usługa działa dalej — to chwilowy problem z kartą, a nie decyzja o Twoim koncie. Jeśli wszystkie próby zawiodą, zobacz [Co się dzieje przy braku płatności](kb:unpaid-what-happens).' },
        { h2: 'Faktury, VAT i potwierdzenia', id: 'invoices' },
        { p: 'Każda faktura, potwierdzenie i dokument VAT mieszka w portalu Stripe, dostępnym z ekranu płatności, i pozostaje dostępny po zakończeniu subskrypcji. Nazwę firmy, adres i NIP edytuje się również tam, a zmiany działają od następnej faktury — już wystawionej faktury nie da się wystawić ponownie z innymi danymi.' },
      ],
    },
    de: {
      title: 'Abrechnung, Rechnungen und Verbrauch',
      summary: 'Wo die Rechnungen liegen, wie ein Tarifwechsel mitten im Monat berechnet wird und wie Gerätetage und Mehrverbrauch gezählt werden.',
      keywords: ['abrechnung', 'rechnung', 'karte', 'stripe', 'anteilig', 'mehrverbrauch', 'gerätetage', 'umsatzsteuer', 'abo'],
      blocks: [
        { p: 'Zahlungen laufen über Stripe. Kartendaten werden hier nie gespeichert und sind in diesem Dashboard für niemanden sichtbar — für alles rund um die Karte führt von der Abrechnungsseite ins Stripe-Portal.' },
        { h2: 'Was auf der Abrechnungsseite steht', id: 'screen' },
        { ul: [
          'Der aktuelle Tarif und sein Verlängerungsdatum.',
          'Die hinterlegte Zahlungsart mit letzten Ziffern und Ablauf.',
          'Der bisherige Verbrauch dieser Periode.',
          'Die kommende Rechnung samt allem Aufgelaufenen.',
          'Ein Link ins Stripe-Portal für Rechnungen, Belege, Steuerdaten und Kartenwechsel.',
        ] },
        { h2: 'Wie der Verbrauch gezählt wird', id: 'usage' },
        { table: { head: ['Begriff', 'Bedeutung'], rows: [
          ['**Aktive Geräte**', 'Aktuell registrierte und nicht stillgelegte Geräte.'],
          ['**Tagesspitze**', 'Der höchste Stand an irgendeinem Tag der Periode. Ein am selben Tag angelegtes und stillgelegtes Gerät zählte an diesem Tag trotzdem.'],
          ['**Gerätetage**', 'Die Summe über die Periode: Ein Gerät dreißig Tage und dreißig Geräte einen Tag sind dieselbe Zahl.'],
          ['**Gerätetage über Kontingent**', 'Der Teil dieser Summe oberhalb des im Tarif enthaltenen Kontingents. Wird auf der nächsten Rechnung nach Messtarif berechnet.'],
        ] } },
        { callout: 'note', p: 'Die Zählung in Gerätetagen macht eine mitten im Monat wachsende Flotte in beide Richtungen fair: für ein am 28. angelegtes Gerät zahlen Sie keinen ganzen Monat, und fünfzig Geräte für eine Woche fallen nicht durchs Raster.' },
        { h2: 'Tarifwechsel mitten in der Periode', id: 'proration' },
        { p: 'Ein Wechsel wirkt sofort, und das Geld wird auf der **nächsten** Rechnung verrechnet, nicht im Moment. Ein Upgrade addiert die anteilige Differenz für den Rest der Periode; ein Downgrade schreibt den ungenutzten Teil gut. Beim Umschalten wird die Karte nicht belastet, und der Bestätigungsdialog nennt den genauen Betrag, bevor Sie zustimmen.' },
        { h2: 'Fehlgeschlagene Zahlungen', id: 'failed' },
        { p: 'Eine fehlgeschlagene Karte wird nach Stripes Zeitplan erneut versucht, und das Abonnement steht währenddessen in einer Nachfrist. Während der Wiederholungen läuft der Dienst weiter — das ist ein vorübergehendes Kartenproblem, keine Entscheidung über Ihr Konto. Schlagen alle Versuche fehl, siehe [Was bei einer unbezahlten Rechnung passiert](kb:unpaid-what-happens).' },
        { h2: 'Rechnungen, Steuer und Belege', id: 'invoices' },
        { p: 'Jede Rechnung, jeder Beleg und jedes Steuerdokument liegt im Stripe-Portal, erreichbar von der Abrechnungsseite, und bleibt auch nach Abonnement-Ende verfügbar. Firmenname, Adresse und Umsatzsteuer-ID werden ebenfalls dort gepflegt und gelten ab der nächsten Rechnung — eine bereits ausgestellte Rechnung lässt sich nicht mit anderen Angaben neu ausstellen.' },
      ],
    },
  },
}
