import type { KbArticle } from '../types.js'

export const branding: KbArticle = {
  slug: 'branding',
  category: 'tsp',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true, entitlement: 'whiteLabel' },
  screen: '/app/branding',
  doc: {
    en: {
      title: 'Branding your dashboard',
      summary: 'Product name, colours, logo, favicon and support address — the five fields your customers actually notice.',
      keywords: ['branding', 'logo', 'colours', 'favicon', 'product name', 'support email', 'theme', 'appearance'],
      blocks: [
        { p: 'Five fields, ten minutes, and the product stops looking like software somebody else made.' },
        { h2: 'Product name', id: 'name' },
        { p: 'Appears in the browser tab, in the sidebar and as the sender name on every message the platform sends on your behalf. Use the name your customers already call you — this is not the place for a legal entity.' },
        { callout: 'warning', p: 'Leave it blank on your own domain and there is no name anywhere: the tab shows the bare address and the sidebar shows nothing. Blank does not fall back to ours — it stays blank.' },
        { h2: 'Colours', id: 'colours' },
        { p: 'A primary and an accent colour, given as hex values. They are applied to buttons, highlights, the active navigation item and the charts. If a colour would be unreadable against the current background, it is adjusted just enough to be legible — a brand colour nobody can read is not a brand colour on that screen.' },
        { p: 'Both light and dark themes are supported, and your colours are re-checked for each. Look at the preview in both before saving.' },
        { h2: 'Logo', id: 'logo' },
        { ul: [
          'Shown on the sign-in page, in the sidebar and in e-mails.',
          'A wide mark of roughly 200×50 works best. PNG or SVG, under half a megabyte.',
          'Either upload a file or give a URL you host yourself. An uploaded file is served from here, which is one less thing to keep alive.',
        ] },
        { h2: 'Favicon', id: 'favicon' },
        { p: 'The browser-tab and home-screen icon. A **square** mark reads best; 192×192 or larger covers a phone home screen too. If you set only a logo, the logo is used — which is why a wide wordmark often looks like a smudge at 16 pixels. Setting a square icon here is the fix.' },
        { h2: 'Support address', id: 'support' },
        { p: 'Becomes the reply address on notifications and reports. A customer replying to an alert reaches **you**, which is exactly right: they are your customer.' },
        { h2: 'What the messages look like', id: 'mail' },
        { p: 'Messages sent on your behalf carry your product name as the sender name, your logo, your colours and your support address for replies. See [E-mail your customers receive](kb:emails-to-your-customers) for what is and is not branded today.' },
        { h2: 'Then the domain', id: 'domain' },
        { p: 'Branding is half the job; the address bar is the other half. See [Your own domain](kb:custom-domain).' },
      ],
    },
    lt: {
      title: 'Skydelio ženklinimas',
      summary: 'Produkto pavadinimas, spalvos, logotipas, piktograma ir pagalbos adresas – penki laukai, kuriuos klientai iš tikrųjų pastebi.',
      keywords: ['prekės ženklas', 'logotipas', 'spalvos', 'piktograma', 'produkto pavadinimas', 'pagalbos paštas', 'tema', 'išvaizda'],
      blocks: [
        { p: 'Penki laukai, dešimt minučių – ir produktas nustoja atrodyti kaip kažkieno kito padaryta programa.' },
        { h2: 'Produkto pavadinimas', id: 'name' },
        { p: 'Rodomas naršyklės kortelėje, šoninėje juostoje ir kaip siuntėjo vardas kiekvienoje jūsų vardu siunčiamoje žinutėje. Naudokite pavadinimą, kuriuo klientai jus jau vadina – čia ne vieta juridiniam asmeniui.' },
        { callout: 'warning', p: 'Palikus tuščią savame domene, pavadinimo niekur nebus: kortelėje matysis plikas adresas, o šoninėje juostoje – nieko. Tuščia vieta neužpildoma mūsų – ji lieka tuščia.' },
        { h2: 'Spalvos', id: 'colours' },
        { p: 'Pagrindinė ir akcentinė spalva, nurodomos šešioliktainėmis reikšmėmis. Jos taikomos mygtukams, paryškinimams, aktyviam meniu punktui ir grafikams. Jei spalva būtų neįskaitoma ant esamo fono, ji pakoreguojama tiek, kad taptų įskaitoma – prekės ženklo spalva, kurios niekas neperskaito, tame ekrane nėra prekės ženklo spalva.' },
        { p: 'Palaikomos ir šviesi, ir tamsi temos, o jūsų spalvos kiekvienai patikrinamos iš naujo. Prieš išsaugodami pažiūrėkite peržiūrą abiejose.' },
        { h2: 'Logotipas', id: 'logo' },
        { ul: [
          'Rodomas prisijungimo puslapyje, šoninėje juostoje ir laiškuose.',
          'Geriausiai tinka platus ženklas, maždaug 200×50. PNG arba SVG, mažiau nei pusė megabaito.',
          'Arba įkelkite failą, arba nurodykite savo talpinamą URL. Įkeltas failas pateikiamas iš čia – vienu dalyku mažiau, kurį reikia prižiūrėti.',
        ] },
        { h2: 'Piktograma (favicon)', id: 'favicon' },
        { p: 'Naršyklės kortelės ir pagrindinio ekrano piktograma. Geriausiai skaitosi **kvadratinis** ženklas; 192×192 ar didesnis padengia ir telefono pagrindinį ekraną. Nustačius tik logotipą, naudojamas logotipas – todėl platus užrašas prie 16 taškų dažnai atrodo kaip dėmė. Kvadratinė piktograma čia tai ir ištaiso.' },
        { h2: 'Pagalbos adresas', id: 'support' },
        { p: 'Tampa atsakymo adresu pranešimuose ir ataskaitose. Klientas, atsakantis į pranešimą, pasiekia **jus**, ir tai visiškai teisinga: jis jūsų klientas.' },
        { h2: 'Kaip atrodo žinutės', id: 'mail' },
        { p: 'Jūsų vardu siunčiamos žinutės nešioja jūsų produkto pavadinimą kaip siuntėjo vardą, jūsų logotipą, spalvas ir jūsų pagalbos adresą atsakymams. Kas šiandien paženklinta, o kas ne, žr. [Laiškai, kuriuos gauna jūsų klientai](kb:emails-to-your-customers).' },
        { h2: 'Toliau — domenas', id: 'domain' },
        { p: 'Ženklinimas – pusė darbo; kita pusė yra adreso juosta. Žr. [Nuosavas domenas](kb:custom-domain).' },
      ],
    },
    pl: {
      title: 'Marka Twojego panelu',
      summary: 'Nazwa produktu, kolory, logo, favikona i adres wsparcia — pięć pól, które klienci naprawdę zauważają.',
      keywords: ['marka', 'logo', 'kolory', 'favikona', 'nazwa produktu', 'e-mail wsparcia', 'motyw', 'wygląd'],
      blocks: [
        { p: 'Pięć pól, dziesięć minut — i produkt przestaje wyglądać jak oprogramowanie zrobione przez kogoś innego.' },
        { h2: 'Nazwa produktu', id: 'name' },
        { p: 'Pojawia się w karcie przeglądarki, w pasku bocznym i jako nazwa nadawcy w każdej wiadomości wysyłanej w Twoim imieniu. Użyj nazwy, którą klienci już się posługują — to nie miejsce na podmiot prawny.' },
        { callout: 'warning', p: 'Zostaw puste we własnej domenie, a nazwy nie będzie nigdzie: karta pokaże goły adres, a pasek boczny nic. Pustka nie cofa się do naszej — zostaje pustką.' },
        { h2: 'Kolory', id: 'colours' },
        { p: 'Kolor główny i akcent, podawane szesnastkowo. Stosowane są do przycisków, wyróżnień, aktywnej pozycji nawigacji i wykresów. Jeśli kolor byłby nieczytelny na obecnym tle, zostaje skorygowany dokładnie tyle, by dało się go odczytać — kolor marki, którego nikt nie przeczyta, nie jest na tym ekranie kolorem marki.' },
        { p: 'Obsługiwane są motywy jasny i ciemny, a Twoje kolory są sprawdzane dla każdego z osobna. Przed zapisaniem obejrzyj podgląd w obu.' },
        { h2: 'Logo', id: 'logo' },
        { ul: [
          'Pokazywane na stronie logowania, w pasku bocznym i w e-mailach.',
          'Najlepiej sprawdza się szeroki znak, mniej więcej 200×50. PNG albo SVG, poniżej pół megabajta.',
          'Albo wgraj plik, albo podaj URL hostowany przez Ciebie. Wgrany plik serwujemy stąd, więc jedną rzecz mniej trzeba utrzymywać.',
        ] },
        { h2: 'Favikona', id: 'favicon' },
        { p: 'Ikona karty przeglądarki i ekranu głównego. Najlepiej czyta się znak **kwadratowy**; 192×192 lub większy obsłuży też ekran główny telefonu. Jeśli ustawisz tylko logo, użyte zostanie logo — dlatego szeroki napis przy 16 pikselach często wygląda jak plama. Kwadratowa ikona tutaj to naprawia.' },
        { h2: 'Adres wsparcia', id: 'support' },
        { p: 'Staje się adresem odpowiedzi w powiadomieniach i raportach. Klient odpowiadający na alert trafia do **Ciebie**, i tak właśnie ma być: to Twój klient.' },
        { h2: 'Jak wyglądają wiadomości', id: 'mail' },
        { p: 'Wiadomości wysyłane w Twoim imieniu niosą nazwę Twojego produktu jako nadawcę, Twoje logo, kolory i Twój adres wsparcia do odpowiedzi. Co dziś jest, a co nie jest brandowane, zobacz w [E-maile, które dostają Twoi klienci](kb:emails-to-your-customers).' },
        { h2: 'Potem domena', id: 'domain' },
        { p: 'Marka to połowa pracy; drugą połową jest pasek adresu. Zobacz [Własna domena](kb:custom-domain).' },
      ],
    },
    de: {
      title: 'Ihr Dashboard branden',
      summary: 'Produktname, Farben, Logo, Favicon und Support-Adresse — die fünf Felder, die Ihre Kunden wirklich bemerken.',
      keywords: ['branding', 'logo', 'farben', 'favicon', 'produktname', 'support-mail', 'theme', 'erscheinungsbild'],
      blocks: [
        { p: 'Fünf Felder, zehn Minuten — und das Produkt sieht nicht mehr nach Software von jemand anderem aus.' },
        { h2: 'Produktname', id: 'name' },
        { p: 'Erscheint im Browser-Tab, in der Seitenleiste und als Absendername in jeder Nachricht, die die Plattform in Ihrem Namen versendet. Nehmen Sie den Namen, den Ihre Kunden ohnehin benutzen — hier gehört keine Firmierung hin.' },
        { callout: 'warning', p: 'Bleibt er auf Ihrer Domain leer, steht nirgends ein Name: der Tab zeigt die nackte Adresse, die Seitenleiste nichts. Leer fällt nicht auf unseren zurück — leer bleibt leer.' },
        { h2: 'Farben', id: 'colours' },
        { p: 'Eine Primär- und eine Akzentfarbe als Hex-Werte. Sie gelten für Schaltflächen, Hervorhebungen, den aktiven Navigationspunkt und die Diagramme. Wäre eine Farbe auf dem aktuellen Hintergrund unlesbar, wird sie gerade so weit angepasst, dass sie lesbar ist — eine Markenfarbe, die niemand lesen kann, ist auf diesem Bildschirm keine Markenfarbe.' },
        { p: 'Helles und dunkles Theme werden unterstützt, und Ihre Farben werden für jedes neu geprüft. Sehen Sie sich die Vorschau vor dem Speichern in beiden an.' },
        { h2: 'Logo', id: 'logo' },
        { ul: [
          'Erscheint auf der Anmeldeseite, in der Seitenleiste und in E-Mails.',
          'Am besten ein breites Zeichen von etwa 200×50. PNG oder SVG, unter einem halben Megabyte.',
          'Entweder eine Datei hochladen oder eine selbst gehostete URL angeben. Eine hochgeladene Datei liefern wir aus — eine Sache weniger, die am Leben bleiben muss.',
        ] },
        { h2: 'Favicon', id: 'favicon' },
        { p: 'Das Icon für Browser-Tab und Startbildschirm. Ein **quadratisches** Zeichen liest sich am besten; 192×192 oder größer deckt auch den Handy-Startbildschirm ab. Setzen Sie nur ein Logo, wird das Logo genommen — deshalb wirkt eine breite Wortmarke bei 16 Pixeln oft wie ein Fleck. Ein quadratisches Icon hier behebt das.' },
        { h2: 'Support-Adresse', id: 'support' },
        { p: 'Wird zur Antwortadresse in Benachrichtigungen und Berichten. Ein Kunde, der auf einen Alarm antwortet, erreicht **Sie** — und genau so gehört es sich: es ist Ihr Kunde.' },
        { h2: 'Wie die Nachrichten aussehen', id: 'mail' },
        { p: 'In Ihrem Namen versendete Nachrichten tragen Ihren Produktnamen als Absendernamen, Ihr Logo, Ihre Farben und Ihre Support-Adresse für Antworten. Was heute gebrandet ist und was nicht, steht in [E-Mails, die Ihre Kunden erhalten](kb:emails-to-your-customers).' },
        { h2: 'Dann die Domain', id: 'domain' },
        { p: 'Branding ist die halbe Arbeit; die andere Hälfte ist die Adresszeile. Siehe [Eigene Domain](kb:custom-domain).' },
      ],
    },
  },
}
