import type { KbArticle } from '../types.js'

export const canAndObd: KbArticle = {
  slug: 'can-and-obd',
  category: 'devices',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'CAN and OBD data — fuel, mileage and the engine',
      summary: 'Where fuel level and factory mileage actually come from, why a working CAN bus still shows nothing, and how to switch the parameters on.',
      keywords: ['can', 'obd', 'fuel', 'mileage', 'rpm', 'engine hours', 'adblue', 'bus', 'adapter', 'lv-can'],
      blocks: [
        { p: 'GPS knows where a vehicle is and how fast it moves. It knows nothing about fuel, engine hours, factory odometer, coolant temperature or fault codes. All of that comes from the vehicle\'s own data bus — CAN — and getting it requires three separate things to line up.' },
        { h2: 'The three conditions', id: 'conditions' },
        { ol: [
          '**The tracker must have a CAN interface** — either built in, or added with a separate CAN adapter wired alongside it.',
          '**The vehicle must be supported.** Manufacturers do not publish their bus, so support is per make, per model, per year and often per equipment level. Check the specific vehicle in the supported-vehicles list before promising anything.',
          '**The installation must reach the right wires.** Which lines, and where, depends on the vehicle. This is installer work.',
        ] },
        { h2: 'The step everybody misses', id: 'off-by-default' },
        { callout: 'warning', p: 'A Teltonika tracker leaves the factory with **every CAN parameter switched off**. A perfectly installed adapter on a fully supported vehicle therefore reports almost nothing until somebody turns the parameters on. This is the single most common reason for “the CAN doesn\'t work”.' },
        { p: 'The **CAN parameters** panel on a device lists everything that model can send, marks the handful most vehicles actually report, and lets you switch them on in one action. The change is queued and delivered the next time the tracker connects.' },
        { h2: 'What you get once it works', id: 'values' },
        { ul: [
          '**Fuel level**, as a percentage or in litres — the basis of fuel-theft detection and of the fuel chart in history playback.',
          '**Total mileage** from the vehicle itself, which is the number a service book and a lease contract care about — see [Distance and odometer](kb:distance-and-odometer).',
          '**Engine hours** — how machinery and standing-work vehicles are serviced, instead of by distance driven.',
          '**Engine RPM, load, throttle, coolant temperature** — live engine state.',
          '**Door and security state**, on vehicles that publish it.',
          'On trucks: **AdBlue**, axle loads and tachograph values including driver cards.',
        ] },
        { h2: 'Switch on what you need, not everything', id: 'restraint' },
        { p: 'Every enabled parameter travels with every record, so turning on fifty of them multiplies the data a vehicle sends. Start with the handful marked as commonly reported, confirm they arrive, and add more deliberately.' },
        { h2: 'When values are missing or wrong', id: 'missing' },
        { table: { head: ['What you see', 'Usually means'], rows: [
          ['Nothing at all from CAN', 'Parameters never switched on, or the adapter is not connected'],
          ['Some values, not others', 'The vehicle does not publish those — normal and not fixable from here'],
          ['Fuel jumps around while driving', 'Float-sensor behaviour in the tank; read it when the vehicle is standing still, not while it is cornering'],
          ['Mileage far from the vehicle\'s own dashboard', 'The vehicle\'s counter starts from a different number; use the change between readings, not the total'],
        ] } },
      ],
    },
    lt: {
      title: 'CAN ir OBD duomenys — kuras, rida ir variklis',
      summary: 'Iš kur iš tikrųjų ateina kuro lygis ir gamyklinė rida, kodėl veikianti CAN magistralė vis tiek nieko nerodo ir kaip įjungti parametrus.',
      keywords: ['can', 'obd', 'kuras', 'rida', 'apsukos', 'variklio valandos', 'adblue', 'magistralė', 'adapteris'],
      blocks: [
        { p: 'GPS žino, kur automobilis yra ir kaip greitai važiuoja. Jis nieko nežino apie kurą, variklio valandas, gamyklinę ridą, aušinimo skysčio temperatūrą ar klaidų kodus. Visa tai ateina iš paties automobilio duomenų magistralės – CAN – ir tam turi sutapti trys atskiri dalykai.' },
        { h2: 'Trys sąlygos', id: 'conditions' },
        { ol: [
          '**Sekiklis turi turėti CAN sąsają** – arba integruotą, arba per atskirą, šalia prijungtą CAN adapterį.',
          '**Automobilis turi būti palaikomas.** Gamintojai savo magistralės neskelbia, todėl palaikymas yra pagal markę, modelį, metus ir dažnai pagal komplektaciją. Prieš ką nors žadėdami, pasitikrinkite konkretų automobilį palaikomų automobilių sąraše.',
          '**Montuojant reikia prisijungti prie reikiamų laidų.** Kurios linijos ir kur – priklauso nuo automobilio. Tai montuotojo darbas.',
        ] },
        { h2: 'Žingsnis, kurį visi praleidžia', id: 'off-by-default' },
        { callout: 'warning', p: 'Teltonika sekiklis iš gamyklos išeina su **išjungtais visais CAN parametrais**. Todėl nepriekaištingai sumontuotas adapteris visiškai palaikomame automobilyje beveik nieko nesiunčia, kol kas nors neįjungia parametrų. Tai dažniausia priežastis, kodėl „CAN neveikia“.' },
        { p: 'Įrenginio **CAN parametrų** skydelis išvardija viską, ką tas modelis gali siųsti, pažymi tuos kelis, kuriuos dauguma automobilių iš tiesų praneša, ir leidžia juos įjungti vienu veiksmu. Pakeitimas patenka į eilę ir pristatomas kitą kartą sekikliui prisijungus.' },
        { h2: 'Ką gaunate, kai veikia', id: 'values' },
        { ul: [
          '**Kuro lygis** procentais arba litrais – tuo remiasi kuro vagysčių aptikimas ir kuro grafikas istorijos atkūrime.',
          '**Bendra rida** iš paties automobilio – būtent šio skaičiaus reikia serviso knygelei ir lizingo sutarčiai; žr. [Atstumas ir odometras](kb:distance-and-odometer).',
          '**Variklio valandos** – pagal jas prižiūrima technika ir stovint dirbantys automobiliai, o ne pagal kilometrus.',
          '**Variklio apsukos, apkrova, droselis, aušinimo skysčio temperatūra** – gyva variklio būsena.',
          '**Durų ir apsaugos būsena** automobiliuose, kurie ją skelbia.',
          'Sunkvežimiuose: **AdBlue**, ašių apkrovos ir tachografo reikšmės kartu su vairuotojų kortelėmis.',
        ] },
        { h2: 'Įjunkite tai, ko reikia, o ne viską', id: 'restraint' },
        { p: 'Kiekvienas įjungtas parametras keliauja su kiekvienu įrašu, tad įjungus penkiasdešimt, automobilio siunčiamų duomenų kiekis išauga kelis kartus. Pradėkite nuo kelių, pažymėtų kaip dažniausiai pranešamų, įsitikinkite, kad jie atkeliauja, ir tik tada sąmoningai pridėkite daugiau.' },
        { h2: 'Kai reikšmių trūksta arba jos klaidingos', id: 'missing' },
        { table: { head: ['Ką matote', 'Dažniausiai reiškia'], rows: [
          ['Iš CAN – visiškai nieko', 'Parametrai niekada neįjungti arba adapteris neprijungtas'],
          ['Vienos reikšmės yra, kitų nėra', 'Automobilis jų neskelbia – normalu ir iš čia nepataisoma'],
          ['Kuras važiuojant šokinėja', 'Plūdinio daviklio elgsena bake; skaitykite stovint, o ne posūkio viduryje'],
          ['Rida labai skiriasi nuo prietaisų skydelio', 'Automobilis praneša kitokio atskaitos taško skaitiklį; naudokite skirtumams, ne absoliučioms reikšmėms'],
        ] } },
      ],
    },
    pl: {
      title: 'Dane CAN i OBD — paliwo, przebieg i silnik',
      summary: 'Skąd naprawdę bierze się poziom paliwa i fabryczny przebieg, dlaczego działająca magistrala CAN i tak nic nie pokazuje i jak włączyć parametry.',
      keywords: ['can', 'obd', 'paliwo', 'przebieg', 'obroty', 'motogodziny', 'adblue', 'magistrala', 'adapter'],
      blocks: [
        { p: 'GPS wie, gdzie jest pojazd i jak szybko jedzie. Nie wie nic o paliwie, motogodzinach, fabrycznym przebiegu, temperaturze płynu chłodzącego ani kodach błędów. To wszystko pochodzi z własnej magistrali pojazdu — CAN — i wymaga zbiegu trzech osobnych warunków.' },
        { h2: 'Trzy warunki', id: 'conditions' },
        { ol: [
          '**Lokalizator musi mieć interfejs CAN** — wbudowany albo przez osobny adapter CAN podłączony obok.',
          '**Pojazd musi być obsługiwany.** Producenci nie publikują swojej magistrali, więc obsługa jest ustalana osobno dla każdej marki, modelu i rocznika, a często poziom wyposażenia. Zanim cokolwiek obiecasz, sprawdź konkretny pojazd na liście obsługiwanych.',
          '**Montaż musi trafić we właściwe przewody.** Które linie i gdzie — zależy od pojazdu. To praca montera.',
        ] },
        { h2: 'Krok, który wszyscy pomijają', id: 'off-by-default' },
        { callout: 'warning', p: 'Lokalizator Teltonika wychodzi z fabryki z **wyłączonymi wszystkimi parametrami CAN**. Idealnie zamontowany adapter w pojeździe w pełni obsługiwanym nie raportuje więc prawie niczego, dopóki ktoś nie włączy parametrów. To najczęstsza przyczyna „CAN nie działa”.' },
        { p: 'Panel **Parametry CAN** urządzenia wymienia wszystko, co dany model może wysyłać, oznacza tę garstkę, którą większość pojazdów faktycznie raportuje, i pozwala włączyć je jedną akcją. Zmiana trafia do kolejki i zostaje dostarczona przy następnym połączeniu lokalizatora.' },
        { h2: 'Co dostajesz, gdy działa', id: 'values' },
        { ul: [
          '**Poziom paliwa** w procentach albo litrach — podstawa wykrywania kradzieży paliwa i wykresu paliwa w odtwarzaniu historii.',
          '**Całkowity przebieg** z samego pojazdu — to liczba, która liczy się w książce serwisowej i w umowie leasingowej; zobacz [Dystans a licznik](kb:distance-and-odometer).',
          '**Motogodziny** — maszyny i pojazdy pracujące na postoju serwisuje się według nich, nie według kilometrów.',
          '**Obroty, obciążenie, przepustnica, temperatura płynu chłodzącego** — bieżący stan silnika.',
          '**Stan drzwi i zabezpieczeń** w pojazdach, które to publikują.',
          'W ciężarówkach: **AdBlue**, naciski na osie i wartości tachografu wraz z kartami kierowców.',
        ] },
        { h2: 'Włącz to, czego potrzebujesz, nie wszystko', id: 'restraint' },
        { p: 'Każdy włączony parametr jest wysyłany w każdym rekordzie, więc włączenie pięćdziesięciu zwielokrotnia ilość wysyłanych danych. Zacznij od tych kilku oznaczonych jako powszechnie raportowane, sprawdź, czy docierają, i dopiero potem świadomie dokładaj kolejne.' },
        { h2: 'Gdy wartości brakuje albo jest błędna', id: 'missing' },
        { table: { head: ['Co widzisz', 'Zwykle znaczy'], rows: [
          ['Z CAN zupełnie nic', 'Parametry nigdy nie włączone albo adapter nie jest podłączony'],
          ['Część wartości jest, części nie', 'Pojazd ich nie publikuje — normalne i nie do naprawienia z tego poziomu'],
          ['Paliwo skacze w czasie jazdy', 'Zachowanie pływaka w baku; odczytuj na postoju, a nie na zakręcie'],
          ['Przebieg daleki od wskazań licznika na desce rozdzielczej', 'Pojazd podaje licznik o innym punkcie odniesienia; używaj do różnic, nie do wartości bezwzględnych'],
        ] } },
      ],
    },
    de: {
      title: 'CAN- und OBD-Daten — Kraftstoff, Kilometer und Motor',
      summary: 'Woher Tankfüllstand und Werkskilometer wirklich kommen, warum ein funktionierender CAN-Bus trotzdem nichts zeigt und wie man die Parameter einschaltet.',
      keywords: ['can', 'obd', 'kraftstoff', 'kilometerstand', 'drehzahl', 'motorstunden', 'adblue', 'bus', 'adapter'],
      blocks: [
        { p: 'GPS weiß, wo ein Fahrzeug ist und wie schnell es fährt. Über Kraftstoff, Motorstunden, Werks-Kilometerstand, Kühlmitteltemperatur oder Fehlercodes weiß es nichts. All das kommt vom fahrzeugeigenen Datenbus — CAN — und dafür müssen drei Dinge zusammenkommen.' },
        { h2: 'Die drei Bedingungen', id: 'conditions' },
        { ol: [
          '**Der Tracker braucht eine CAN-Schnittstelle** — entweder eingebaut oder über einen separaten, daneben verdrahteten CAN-Adapter.',
          '**Das Fahrzeug muss unterstützt sein.** Hersteller veröffentlichen ihren Bus nicht, also gilt Unterstützung je Marke, Modell, Baujahr und oft Ausstattungslinie. Prüfen Sie das konkrete Fahrzeug in der Liste, bevor Sie etwas zusagen.',
          '**Der Einbau muss die richtigen Leitungen treffen.** Welche das sind und wo sie liegen, hängt vom Fahrzeug ab. Das ist Sache des Monteurs.',
        ] },
        { h2: 'Der Schritt, den alle übersehen', id: 'off-by-default' },
        { callout: 'warning', p: 'Ein Teltonika-Tracker verlässt das Werk mit **deaktivierten CAN-Parametern**. Ein perfekt eingebauter Adapter an einem voll unterstützten Fahrzeug meldet deshalb fast nichts, bis jemand die Parameter einschaltet. Das ist der mit Abstand häufigste Grund für „das CAN geht nicht“.' },
        { p: 'Die Ansicht **CAN-Parameter** eines Geräts listet alles auf, was dieses Modell senden kann, markiert die Handvoll, die die meisten Fahrzeuge tatsächlich melden, und lässt Sie sie in einem Schritt einschalten. Die Änderung wird eingereiht und beim nächsten Verbinden zugestellt.' },
        { h2: 'Was Sie bekommen, wenn es läuft', id: 'values' },
        { ul: [
          '**Tankfüllstand** in Prozent oder Litern — Grundlage der Kraftstoff-Diebstahlerkennung und des Kraftstoffdiagramms im Verlauf-Wiedergabe.',
          '**Gesamtkilometer** aus dem Fahrzeug selbst — die Zahl, auf die Serviceheft und Leasingvertrag schauen; siehe [Strecke und Kilometerstand](kb:distance-and-odometer).',
          '**Motorstunden** — danach werden Maschinen und im Stand arbeitende Fahrzeuge gewartet, nicht nach Kilometern.',
          '**Drehzahl, Last, Drosselklappe, Kühlmitteltemperatur** — der aktuelle Motorzustand.',
          '**Tür- und Sicherungszustand** bei Fahrzeugen, die ihn veröffentlichen.',
          'Bei Lkw: **AdBlue**, Achslasten und Tachographenwerte samt Fahrerkarten.',
        ] },
        { h2: 'Schalten Sie ein, was Sie brauchen — nicht alles', id: 'restraint' },
        { p: 'Jeder aktivierte Parameter wird in jedem Datensatz mit übertragen; fünfzig davon vervielfachen die gesendete Datenmenge. Beginnen Sie mit den wenigen als üblich markierten, prüfen Sie, ob sie ankommen, und ergänzen Sie bewusst.' },
        { h2: 'Wenn Werte fehlen oder falsch sind', id: 'missing' },
        { table: { head: ['Was Sie sehen', 'Bedeutet meist'], rows: [
          ['Vom CAN gar nichts', 'Parameter nie eingeschaltet, oder der Adapter ist nicht angeschlossen'],
          ['Manche Werte, andere nicht', 'Das Fahrzeug veröffentlicht sie nicht — normal und von hier nicht behebbar'],
          ['Kraftstoff springt während der Fahrt', 'Verhalten des Schwimmers im Tank; im Stand ablesen, nicht in der Kurve'],
          ['Kilometerstand weit weg vom Tacho', 'Das Fahrzeug meldet einen Zähler mit anderem Ursprung; für Differenzen nutzen, nicht absolut'],
        ] } },
      ],
    },
  },
}
