import type { KbArticle } from '../types.js'

export const chooseATracker: KbArticle = {
  slug: 'choose-a-tracker',
  category: 'devices',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'Choosing a tracker',
      summary: 'Wired, OBD or battery — what each type can and cannot tell you, and which questions decide the choice.',
      keywords: ['hardware', 'teltonika', 'fmb', 'fmc', 'obd', 'asset tracker', 'model', 'which device'],
      blocks: [
        { p: '{product} speaks the Teltonika protocol natively, and about a hundred of their models are catalogued with their own parameter tables. Within that range the choice is not really about the model number — it is about three questions.' },
        { h2: 'Question 1 — how is it powered?', id: 'power' },
        { table: { head: ['Type', 'Fits', 'Trade-off'], rows: [
          ['**Wired** (FMB/FMC/FMM series)', 'Vans, trucks, cars you own and can open up', 'Needs 20 minutes with an installer. In exchange it is hidden, always powered, and can read the ignition wire and the vehicle bus.'],
          ['**OBD plug-in**', 'Leased cars, short-term fleets, anything you must not modify', 'Plugs into the diagnostic socket in seconds — and can be unplugged just as fast. Visible.'],
          ['**Battery / asset** (TAT series)', 'Trailers, containers, machinery, anything with no power at all', 'Reports a few times a day, not every few seconds. Battery life is measured in years only because it stays asleep.'],
        ] } },
        { h2: 'Question 2 — do you need the ignition?', id: 'ignition' },
        { p: 'A tracker that is wired to a circuit which is live only with the engine running knows exactly when a trip starts and ends. Everything downstream gets sharper: trip boundaries, engine hours, idling time, "left the engine running at the depot" alerts.' },
        { p: 'Without that wire, {product} falls back to movement — it can still see that the vehicle drove, but a trip may start a minute late and idling cannot be distinguished from parking. It is the single cheapest upgrade to data quality on the whole list.' },
        { h2: 'Question 3 — do you need the vehicle\'s own data?', id: 'can' },
        { p: 'Fuel level, factory odometer, engine RPM, coolant temperature and fault codes come from the vehicle bus, not from GPS. That needs a model with a CAN interface and a vehicle whose make, model, year and equipment are supported. See [CAN and OBD data](kb:can-and-obd) before you buy on this basis.' },
        { callout: 'warning', p: 'Never assume fuel data. It depends on the exact vehicle, not on the tracker alone — check the supported-vehicle list for the specific make, model and year first.' },
        { h2: 'What does not depend on the model', id: 'same' },
        { p: 'Live map, trips, history, geofences, alerts, reports, driver identification and the API work identically on every supported tracker. Paying more buys inputs and interfaces, not features in {product}.' },
      ],
    },
    lt: {
      title: 'Kaip pasirinkti seklį',
      summary: 'Laidinis, OBD ar baterinis – ką kiekvienas tipas gali ir ko negali pasakyti, ir kurie klausimai nulemia pasirinkimą.',
      keywords: ['įranga', 'teltonika', 'fmb', 'fmc', 'obd', 'turto seklys', 'modelis', 'kurį įrenginį'],
      blocks: [
        { p: '{product} natūraliai kalba Teltonika protokolu, o apie šimtas jų modelių yra sukataloguoti su savo parametrų lentelėmis. Šiame diapazone pasirinkimas iš tikrųjų ne apie modelio numerį – jis apie tris klausimus.' },
        { h2: '1 klausimas — iš kur maitinimas?', id: 'power' },
        { table: { head: ['Tipas', 'Kam tinka', 'Kompromisas'], rows: [
          ['**Laidinis** (FMB/FMC/FMM serijos)', 'Furgonams, sunkvežimiams, savo automobiliams, kuriuos galima ardyti', 'Reikia 20 minučių su montuotoju. Užtat paslėptas, visada maitinamas ir gali skaityti degimo laidą bei automobilio magistralę.'],
          ['**OBD kištukinis**', 'Lizinguotiems automobiliams, trumpalaikiams parkams, visam, ko negalima modifikuoti', 'Įkišamas į diagnostikos lizdą per sekundes – ir taip pat greitai ištraukiamas. Matomas.'],
          ['**Baterinis / turto** (TAT serija)', 'Priekaboms, konteineriams, technikai, visam, kas neturi maitinimo', 'Praneša kelis kartus per parą, o ne kas kelias sekundes. Baterija tarnauja metus tik todėl, kad seklys daugiausia miega.'],
        ] } },
        { h2: '2 klausimas — ar reikia degimo?', id: 'ignition' },
        { p: 'Seklys, prijungtas prie grandinės, kuri įtampą turi tik varikliui veikiant, tiksliai žino, kada kelionė prasideda ir baigiasi. Nuo to paaštrėja viskas toliau: kelionių ribos, variklio valandos, tuščiosios eigos laikas, pranešimas „paliko veikiantį variklį bazėje".' },
        { p: 'Be to laido {product} remiasi judėjimu – vis tiek mato, kad automobilis važiavo, bet kelionė gali prasidėti minute vėliau, o tuščiosios eigos nuo stovėjimo atskirti nepavyks. Tai pigiausias duomenų kokybės patobulinimas visame sąraše.' },
        { h2: '3 klausimas — ar reikia paties automobilio duomenų?', id: 'can' },
        { p: 'Kuro lygis, gamyklinė rida, variklio apsukos, aušinimo skysčio temperatūra ir klaidų kodai ateina iš automobilio magistralės, o ne iš GPS. Tam reikia modelio su CAN sąsaja ir automobilio, kurio markė, modelis, metai ir komplektacija yra palaikomi. Prieš pirkdami dėl to, perskaitykite [CAN ir OBD duomenys](kb:can-and-obd).' },
        { callout: 'warning', p: 'Niekada nelaikykite kuro duomenų savaime suprantamais. Jie priklauso nuo konkretaus automobilio, o ne vien nuo seklio – pirma pasitikrinkite palaikomų automobilių sąraše konkrečią markę, modelį ir metus.' },
        { h2: 'Kas nepriklauso nuo modelio', id: 'same' },
        { p: 'Gyvas žemėlapis, kelionės, istorija, geozonos, pranešimai, ataskaitos, vairuotojų atpažinimas ir API vienodai veikia su kiekvienu palaikomu sekliu. Mokėdami daugiau perkate įėjimus ir sąsajas, o ne funkcijas {product} sistemoje.' },
      ],
    },
    pl: {
      title: 'Wybór lokalizatora',
      summary: 'Przewodowy, OBD czy bateryjny — co każdy typ może i czego nie powie, i które pytania rozstrzygają wybór.',
      keywords: ['sprzęt', 'teltonika', 'fmb', 'fmc', 'obd', 'lokalizator zasobów', 'model', 'jakie urządzenie'],
      blocks: [
        { p: '{product} mówi protokołem Teltonika natywnie, a około stu ich modeli jest skatalogowanych z własnymi tabelami parametrów. W tym zakresie wybór nie dotyczy naprawdę numeru modelu — dotyczy trzech pytań.' },
        { h2: 'Pytanie 1 — skąd zasilanie?', id: 'power' },
        { table: { head: ['Typ', 'Pasuje do', 'Kompromis'], rows: [
          ['**Przewodowy** (serie FMB/FMC/FMM)', 'Busy, ciężarówki, własne auta, które można rozebrać', 'Wymaga 20 minut z monterem. W zamian jest ukryty, zawsze zasilany i potrafi czytać przewód zapłonu oraz magistralę pojazdu.'],
          ['**OBD wtykowy**', 'Auta w leasingu, floty krótkoterminowe, wszystko, czego nie wolno modyfikować', 'Wpina się w gniazdo diagnostyczne w kilka sekund — i równie szybko można go wypiąć. Widoczny.'],
          ['**Bateryjny / zasobowy** (seria TAT)', 'Naczepy, kontenery, maszyny, wszystko bez zasilania', 'Raportuje kilka razy dziennie, nie co kilka sekund. Bateria starcza na lata tylko dlatego, że urządzenie śpi.'],
        ] } },
        { h2: 'Pytanie 2 — czy potrzebny zapłon?', id: 'ignition' },
        { p: 'Lokalizator wpięty w obwód, który ma napięcie tylko przy pracującym silniku, wie dokładnie, kiedy trasa się zaczyna i kończy. Ostrzejsze staje się wszystko dalej: granice tras, godziny pracy silnika, czas pracy na postoju, alert „zostawił silnik na chodzie w bazie".' },
        { p: 'Bez tego przewodu {product} opiera się na ruchu — nadal widzi, że pojazd jechał, ale trasa może zacząć się minutę później, a pracy na postoju nie da się odróżnić od parkowania. To najtańsze ulepszenie jakości danych na całej liście.' },
        { h2: 'Pytanie 3 — czy potrzebne dane samego pojazdu?', id: 'can' },
        { p: 'Poziom paliwa, fabryczny przebieg, obroty silnika, temperatura płynu i kody błędów pochodzą z magistrali pojazdu, nie z GPS. Wymaga to modelu z interfejsem CAN i pojazdu, którego marka, model, rok i wyposażenie są obsługiwane. Przeczytaj [Dane CAN i OBD](kb:can-and-obd), zanim kupisz z tego powodu.' },
        { callout: 'warning', p: 'Nigdy nie zakładaj danych o paliwie. Zależą od konkretnego pojazdu, nie od samego lokalizatora — najpierw sprawdź listę obsługiwanych pojazdów dla danej marki, modelu i rocznika.' },
        { h2: 'Co nie zależy od modelu', id: 'same' },
        { p: 'Mapa na żywo, trasy, historia, geostrefy, alerty, raporty, identyfikacja kierowcy i API działają identycznie na każdym obsługiwanym lokalizatorze. Płacąc więcej, kupujesz wejścia i interfejsy, a nie funkcje w {product}.' },
      ],
    },
    de: {
      title: 'Den passenden Tracker wählen',
      summary: 'Verkabelt, OBD oder batteriebetrieben — was jeder Typ leisten kann und was nicht, und welche Fragen die Wahl entscheiden.',
      keywords: ['hardware', 'teltonika', 'fmb', 'fmc', 'obd', 'asset-tracker', 'modell', 'welches gerät'],
      blocks: [
        { p: '{product} spricht das Teltonika-Protokoll nativ; rund hundert ihrer Modelle sind mit eigenen Parametertabellen katalogisiert. Innerhalb dieser Bandbreite geht es nicht wirklich um die Modellnummer — es geht um drei Fragen.' },
        { h2: 'Frage 1 — woher kommt der Strom?', id: 'power' },
        { table: { head: ['Typ', 'Passt zu', 'Kompromiss'], rows: [
          ['**Verkabelt** (FMB/FMC/FMM-Serien)', 'Transporter, Lkw, eigene Fahrzeuge, die man öffnen darf', 'Braucht 20 Minuten mit einem Einbauer. Dafür verborgen, dauerhaft versorgt und in der Lage, Zündungsleitung und Fahrzeugbus zu lesen.'],
          ['**OBD-Stecker**', 'Leasingfahrzeuge, kurzfristige Flotten, alles, was nicht verändert werden darf', 'Steckt in Sekunden in der Diagnosebuchse — und ist ebenso schnell abgezogen. Sichtbar.'],
          ['**Batterie / Asset** (TAT-Serie)', 'Anhänger, Container, Maschinen, alles ohne Stromversorgung', 'Meldet ein paar Mal am Tag, nicht alle paar Sekunden. Die Batterie hält nur deshalb Jahre, weil das Gerät schläft.'],
        ] } },
        { h2: 'Frage 2 — brauchen Sie die Zündung?', id: 'ignition' },
        { p: 'Ein Tracker an einem Stromkreis, der nur bei laufendem Motor Spannung führt, weiß genau, wann eine Fahrt beginnt und endet. Alles Nachgelagerte wird schärfer: Fahrtgrenzen, Motorstunden, Leerlaufzeit, der Alarm „Motor am Hof laufen gelassen".' },
        { p: 'Ohne diese Leitung greift {product} auf Bewegung zurück — es sieht weiterhin, dass gefahren wurde, aber eine Fahrt kann eine Minute zu spät beginnen, und Leerlauf lässt sich nicht vom Parken unterscheiden. Es ist das billigste Upgrade der Datenqualität überhaupt.' },
        { h2: 'Frage 3 — brauchen Sie die Fahrzeugdaten selbst?', id: 'can' },
        { p: 'Tankfüllstand, Werks-Kilometerstand, Drehzahl, Kühlmitteltemperatur und Fehlercodes kommen vom Fahrzeugbus, nicht vom GPS. Dafür braucht es ein Modell mit CAN-Schnittstelle und ein Fahrzeug, dessen Marke, Modell, Baujahr und Ausstattung unterstützt sind. Lesen Sie [CAN- und OBD-Daten](kb:can-and-obd), bevor Sie deswegen kaufen.' },
        { callout: 'warning', p: 'Setzen Sie Kraftstoffdaten nie voraus. Sie hängen vom konkreten Fahrzeug ab, nicht am Tracker allein — prüfen Sie zuerst die Fahrzeugliste für genau diese Marke, dieses Modell und dieses Baujahr.' },
        { h2: 'Was nicht vom Modell abhängt', id: 'same' },
        { p: 'Live-Karte, Fahrten, Historie, Geozonen, Alarme, Berichte, Fahrererkennung und API funktionieren auf jedem unterstützten Tracker gleich. Mehr Geld kauft Eingänge und Schnittstellen, nicht Funktionen in {product}.' },
      ],
    },
  },
}
