import type { KbArticle } from '../types.js'

export const commands: KbArticle = {
  slug: 'commands',
  category: 'devices',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'Sending commands to a tracker',
      summary: 'The command console: what you can ask a device, what the statuses mean, and why a queued command still runs an hour later.',
      keywords: ['command', 'console', 'getinfo', 'reboot', 'output', 'queue', 'acknowledged', 'terminal'],
      blocks: [
        { p: 'Once a tracker is connected, you can talk to it directly from the **Commands** panel — no SMS, no cost, and every exchange is recorded.' },
        { h2: 'The everyday commands', id: 'presets' },
        { table: { head: ['Preset', 'Asks the device'], rows: [
          ['**Info**', 'General status: network, signal, mode.'],
          ['**Version**', 'Which firmware it is running.'],
          ['**GPS fix**', 'Its current position and satellite count, right now.'],
          ['**IO status**', 'The state of its inputs and outputs.'],
          ['**Reboot**', 'Restart. The usual first move when a device is behaving oddly.'],
          ['**Output on / off**', 'Switches a relay output, where one is wired.'],
        ] } },
        { p: 'You can also type any command the model supports. Only plain printable characters are accepted — the protocol carries no accents or emoji, and a rejected character is better than a mangled command.' },
        { h2: 'What the statuses mean', id: 'status' },
        { table: { head: ['Status', 'Meaning'], rows: [
          ['**Queued**', 'We have it; the device has not connected since. Perfectly normal for a parked vehicle.'],
          ['**Sent**', 'Handed to the device over its live connection.'],
          ['**Acknowledged**', 'The device answered. The reply is shown next to the command.'],
          ['**Failed**', 'The device rejected it, or the connection dropped mid-exchange.'],
          ['**Expired**', 'It sat in the queue too long and was given up on.'],
        ] } },
        { callout: 'warning', p: 'A queued command is a promise, not a draft. If a vehicle is parked for three days and you queue a reboot, that reboot happens the moment the vehicle wakes up — three days later, possibly while someone is driving it. If a command is no longer wanted, deal with it before the device reconnects.' },
        { h2: 'Destructive commands', id: 'destructive' },
        { p: 'A few commands are not undoable — deleting the records held in the tracker\'s memory is the obvious one, since those records have not been uploaded yet by definition. Those require a second, explicit confirmation. That prompt is the only safeguard there is; nothing can bring the data back afterwards.' },
        { h2: 'Prefer the settings panel where one exists', id: 'prefer-settings' },
        { p: 'Reporting frequency, distance and angle triggers all have proper sliders under [Reporting intervals](kb:reporting-intervals), with the valid range for that exact model and a data-cost estimate. Setting the same values by raw command works, but nothing checks the range for you, and a number outside it is simply refused by the device.' },
        { h2: 'Every command is on the record', id: 'audit' },
        { p: 'Who sent what, when, and what the device replied is kept in the command history and in the audit log. On a shared fleet that record is usually the fastest answer to “why did this vehicle reboot yesterday”.' },
      ],
    },
    lt: {
      title: 'Komandų siuntimas sekikliui',
      summary: 'Komandų konsolė: ko galima paklausti įrenginio, ką reiškia būsenos ir kodėl eilėje laukusi komanda įvykdoma net po valandos.',
      keywords: ['komanda', 'konsolė', 'getinfo', 'perkrovimas', 'išėjimas', 'eilė', 'patvirtinta', 'terminalas'],
      blocks: [
        { p: 'Kai sekiklis prisijungęs, su juo galima kalbėtis tiesiogiai iš **Komandų** skydelio – be SMS, nemokamai, ir kiekvienas pokalbis įrašomas.' },
        { h2: 'Kasdienės komandos', id: 'presets' },
        { table: { head: ['Ruošinys', 'Ko klausia įrenginio'], rows: [
          ['**Informacija**', 'Bendra būsena: tinklas, signalas, režimas.'],
          ['**Versija**', 'Kokia programinė įranga veikia.'],
          ['**GPS fiksacija**', 'Dabartinė pozicija ir palydovų skaičius šią akimirką.'],
          ['**IO būsena**', 'Įėjimų ir išėjimų būsena.'],
          ['**Perkrauti**', 'Paleisti iš naujo. Įprastas pirmas žingsnis, kai įrenginys elgiasi keistai.'],
          ['**Išėjimas įjungti / išjungti**', 'Perjungia relės išėjimą, jei toks prijungtas.'],
        ] } },
        { p: 'Taip pat galima įvesti bet kurią modelio palaikomą komandą. Priimami tik paprasti spausdinami simboliai – protokolas neperneša nei lietuviškų raidžių, nei jaustukų, o atmestas simbolis geriau nei sudarkyta komanda.' },
        { h2: 'Ką reiškia būsenos', id: 'status' },
        { table: { head: ['Būsena', 'Reikšmė'], rows: [
          ['**Eilėje**', 'Mes ją turime; įrenginys nuo tada neprisijungė. Stovinčiam automobiliui visiškai normalu.'],
          ['**Išsiųsta**', 'Perduota įrenginiui per jo gyvą ryšį.'],
          ['**Patvirtinta**', 'Įrenginys atsakė. Atsakymas rodomas šalia komandos.'],
          ['**Nepavyko**', 'Įrenginys atmetė arba ryšys nutrūko pusiaukelėje.'],
          ['**Nebegalioja**', 'Per ilgai išgulėjo eilėje ir jos buvo atsisakyta.'],
        ] } },
        { callout: 'warning', p: 'Eilėje laukianti komanda – ne juodraštis, o pažadas. Jei automobilis stovi tris dienas, o jūs įtraukiate į eilę perkrovimą, tas perkrovimas įvyks tą akimirką, kai automobilis pabus – po trijų dienų, galbūt kam nors važiuojant. Jei komandos nebereikia, sutvarkykite tai anksčiau, nei įrenginys vėl prisijungs.' },
        { h2: 'Negrįžtamos komandos', id: 'destructive' },
        { p: 'Kelių komandų atšaukti neįmanoma – akivaizdžiausia yra sekiklio atmintyje laikomų įrašų ištrynimas, nes tie įrašai pagal apibrėžimą dar neišsiųsti. Toms reikia antro, aiškaus patvirtinimo. Tas klausimas – vienintelė apsauga; vėliau duomenų nebeatgaus niekas.' },
        { h2: 'Kur yra nustatymų skydelis, rinkitės jį', id: 'prefer-settings' },
        { p: 'Siuntimo dažnis, atstumo ir kampo trigeriai turi normalius slankiklius skiltyje [Siuntimo intervalai](kb:reporting-intervals), su būtent to modelio galiojančiu diapazonu ir duomenų kainos įverčiu. Tas pačias reikšmes nustatyti žalia komanda galima, bet diapazono niekas už jus nepatikrins, o už jo ribų esantį skaičių įrenginys tiesiog atmes.' },
        { h2: 'Kiekviena komanda lieka įraše', id: 'audit' },
        { p: 'Kas ką siuntė, kada ir ką įrenginys atsakė, saugoma komandų istorijoje ir audito žurnale. Bendrame autoparke šis įrašas paprastai greičiausiai atsako į klausimą „kodėl vakar šis automobilis persikrovė“.' },
      ],
    },
    pl: {
      title: 'Wysyłanie poleceń do lokalizatora',
      summary: 'Konsola poleceń: o co można zapytać urządzenie, co znaczą statusy i dlaczego polecenie z kolejki wykonuje się także godzinę później.',
      keywords: ['polecenie', 'konsola', 'getinfo', 'restart', 'wyjście', 'kolejka', 'potwierdzone', 'terminal'],
      blocks: [
        { p: 'Gdy lokalizator jest połączony, można z nim rozmawiać bezpośrednio z panelu **Polecenia** — bez SMS-a, bez kosztów, a każda wymiana jest zapisywana.' },
        { h2: 'Polecenia na co dzień', id: 'presets' },
        { table: { head: ['Szablon', 'Pyta urządzenie o'], rows: [
          ['**Informacje**', 'Ogólny stan: sieć, sygnał, tryb.'],
          ['**Wersja**', 'Jakie oprogramowanie ma wgrane.'],
          ['**Pozycja GPS**', 'Bieżącą pozycję i liczbę satelitów, teraz.'],
          ['**Stan IO**', 'Stan wejść i wyjść.'],
          ['**Restart**', 'Ponowne uruchomienie. Typowy pierwszy ruch, gdy urządzenie zachowuje się dziwnie.'],
          ['**Wyjście wł. / wył.**', 'Przełącza wyjście przekaźnikowe, jeśli jest podłączone.'],
        ] } },
        { p: 'Można też wpisać dowolne polecenie obsługiwane przez model. Przyjmowane są wyłącznie zwykłe znaki drukowalne — protokół nie przenosi polskich znaków ani emoji, a odrzucony znak jest lepszy niż zniekształcone polecenie.' },
        { h2: 'Co znaczą statusy', id: 'status' },
        { table: { head: ['Status', 'Znaczenie'], rows: [
          ['**W kolejce**', 'Mamy ją; urządzenie od tego czasu się nie połączyło. Przy zaparkowanym pojeździe całkiem normalne.'],
          ['**Wysłano**', 'Przekazano urządzeniu przez jego aktywne połączenie.'],
          ['**Potwierdzono**', 'Urządzenie odpowiedziało. Odpowiedź widnieje obok polecenia.'],
          ['**Niepowodzenie**', 'Urządzenie odrzuciło polecenie albo połączenie zerwało się w trakcie.'],
          ['**Wygasło**', 'Zbyt długo czekało w kolejce i zostało porzucone.'],
        ] } },
        { callout: 'warning', p: 'Polecenie w kolejce to obietnica, nie szkic. Jeśli pojazd stoi trzy dni, a Ty zakolejkujesz restart, ten restart nastąpi w chwili, gdy pojazd się obudzi — trzy dni później, być może gdy ktoś nim jedzie. Jeśli polecenie przestała być potrzebna, zajmij się tym, zanim urządzenie znów się połączy.' },
        { h2: 'Polecenia nieodwracalne', id: 'destructive' },
        { p: 'Kilku poleceń nie da się cofnąć — najoczywistszym przykładem jest skasowanie zapisów w pamięci lokalizatora, bo te zapisy z definicji nie zostały jeszcze wysłane. Takie polecenia wymagają drugiego, wyraźnego potwierdzenia. To pytanie jest jedynym zabezpieczeniem; później nikt tych danych nie przywróci.' },
        { h2: 'Gdy jest panel ustawień, wybieraj jego', id: 'prefer-settings' },
        { p: 'Częstotliwość wysyłki oraz wyzwalacze dystansu i kąta mają porządne suwaki w [Częstotliwość raportowania](kb:reporting-intervals), z zakresem właściwym dla danego modelu i szacunkiem kosztu danych. Te same wartości można ustawić surowym poleceniem, ale nikt nie sprawdzi za Ciebie zakresu, a liczbę spoza niego urządzenie po prostu odrzuci.' },
        { h2: 'Każde polecenie zostaje w zapisie', id: 'audit' },
        { p: 'Kto co wysłał, kiedy i co odpowiedziało urządzenie, zostaje w historii poleceń i w dzienniku audytu. We wspólnej flocie ten zapis to zwykle najszybsza odpowiedź na pytanie „dlaczego ten pojazd wczoraj się zrestartował”.' },
      ],
    },
    de: {
      title: 'Befehle an einen Tracker senden',
      summary: 'Die Befehlskonsole: was Sie ein Gerät fragen können, was die Status bedeuten und warum ein eingereihter Befehl auch eine Stunde später noch läuft.',
      keywords: ['befehl', 'konsole', 'getinfo', 'neustart', 'ausgang', 'warteschlange', 'bestätigt', 'terminal'],
      blocks: [
        { p: 'Sobald ein Tracker verbunden ist, können Sie direkt aus dem Panel **Befehle** mit ihm sprechen — ohne SMS, ohne Kosten, und jeder Austausch wird protokolliert.' },
        { h2: 'Die alltäglichen Befehle', id: 'presets' },
        { table: { head: ['Vorlage', 'Fragt das Gerät nach'], rows: [
          ['**Info**', 'Allgemeiner Status: Netz, Signal, Modus.'],
          ['**Version**', 'Welche Firmware läuft.'],
          ['**GPS-Fix**', 'Aktuelle Position und Satellitenzahl, jetzt.'],
          ['**IO-Status**', 'Zustand der Ein- und Ausgänge.'],
          ['**Neustart**', 'Neu starten. Der übliche erste Griff, wenn ein Gerät sich seltsam verhält.'],
          ['**Ausgang ein / aus**', 'Schaltet einen Relaisausgang, sofern einer verdrahtet ist.'],
        ] } },
        { p: 'Sie können auch jeden vom Modell unterstützten Befehl tippen. Angenommen werden nur einfache druckbare Zeichen — das Protokoll transportiert weder Umlaute noch Emoji, und ein abgelehntes Zeichen ist besser als ein verstümmelter Befehl.' },
        { h2: 'Was die Status bedeuten', id: 'status' },
        { table: { head: ['Status', 'Bedeutung'], rows: [
          ['**Eingereiht**', 'Wir haben ihn; das Gerät hat sich seither nicht verbunden. Bei einem geparkten Fahrzeug völlig normal.'],
          ['**Gesendet**', 'Über die aktive Verbindung an das Gerät übergeben.'],
          ['**Bestätigt**', 'Das Gerät hat geantwortet. Die Antwort steht neben dem Befehl.'],
          ['**Fehlgeschlagen**', 'Das Gerät hat abgelehnt, oder die Verbindung brach mittendrin ab.'],
          ['**Verfallen**', 'Zu lange in der Warteschlange, daher aufgegeben.'],
        ] } },
        { callout: 'warning', p: 'Ein eingereihter Befehl ist ein Versprechen, kein Entwurf. Steht ein Fahrzeug drei Tage und Sie reihen einen Neustart ein, passiert dieser Neustart in dem Moment, in dem das Fahrzeug aufwacht — drei Tage später, womöglich während jemand fährt. Ist ein Befehl nicht mehr gewollt, klären Sie das, bevor das Gerät sich wieder verbindet.' },
        { h2: 'Zerstörende Befehle', id: 'destructive' },
        { p: 'Einige Befehle lassen sich nicht rückgängig machen — das Löschen der im Trackerspeicher liegenden Datensätze ist der offensichtliche Fall, denn diese Datensätze sind per Definition noch nicht hochgeladen. Sie verlangen eine zweite, ausdrückliche Bestätigung. Diese Rückfrage ist die einzige Sicherung; danach holt niemand die Daten zurück.' },
        { h2: 'Wo es ein Einstellungspanel gibt, nutzen Sie es', id: 'prefer-settings' },
        { p: 'Sendefrequenz sowie Distanz- und Winkelauslöser haben eigene Regler unter [Meldeintervalle](kb:reporting-intervals) — mit dem gültigen Bereich für genau dieses Modell und einer Datenkostenschätzung. Dieselben Werte per Rohbefehl zu setzen funktioniert, aber niemand prüft den Bereich für Sie, und eine Zahl außerhalb wird vom Gerät schlicht abgelehnt.' },
        { h2: 'Jeder Befehl bleibt aktenkundig', id: 'audit' },
        { p: 'Wer was wann gesendet hat und was das Gerät geantwortet hat, steht in der Befehlsverlauf und im Audit-Log. In einer geteilten Flotte ist dieser Eintrag meist die schnellste Antwort auf „warum hat dieses Fahrzeug gestern neu gestartet“.' },
      ],
    },
  },
}
