import type { KbArticle } from '../types.js'

export const configSms: KbArticle = {
  slug: 'config-sms',
  category: 'devices',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'The configuration SMS explained',
      summary: 'What that odd-looking text message actually says to the tracker, why the leading spaces matter, and why it sometimes changes nothing.',
      keywords: ['sms', 'setparam', 'command', 'text message', 'spaces', 'password', 'configuration'],
      blocks: [
        { p: 'Before a tracker has a data connection, the only way to reach it is a text message to its SIM. That message is not a sentence — it is a command, and trackers are unforgiving about its exact shape.' },
        { h2: 'What the message is made of', id: 'anatomy' },
        { p: 'A configuration message has two parts: a password, and a command. Straight from the factory the password is not set, so its place is filled by **whitespace**. What follows is `setparam` and a list of numbered settings.' },
        { code: '  setparam 2001:internet;2004:tracking.example.com;2005:5027;2006:0' },
        { ul: [
          '`2001` — the APN, so the SIM can reach the internet',
          '`2004` — the server address to send to',
          '`2005` — the port on that server',
          '`2006` — the protocol; `0` means TCP',
        ] },
        { h2: 'The leading spaces are the whole message', id: 'spaces' },
        { p: 'This is the detail that costs people an afternoon. Some device families expect `password space command` — one space when the password is unset. Others expect `login space password space command` — **two** spaces. Send one where two were expected and the tracker receives a perfectly deliverable message, parses nothing at all, replies nothing, and simply never connects.' },
        { callout: 'warning', p: 'From the server\'s side, a wrongly-spaced message is indistinguishable from a dead SIM, a wrong APN, or a tracker that was never powered on. There is no error to see anywhere — that is exactly what makes it expensive.' },
        { p: 'The onboarding panel already knows which spacing your device family needs and builds the message accordingly. This is why the copy button exists and why retyping the command is a bad idea.' },
        { h2: 'Messaging apps quietly break commands', id: 'apps' },
        { p: 'Some phones, and many bulk-SMS services, “clean up” outgoing text: they trim leading spaces, swap ordinary spaces for typographic ones, or normalise punctuation. All of these produce a message that looks identical on screen and is nonsense to the tracker. If you must send by hand, send from a plain phone messaging app and paste rather than type.' },
        { h2: 'Some models hide their own position', id: 'masking' },
        { p: 'A few tracker models ship with position masking switched on: they connect, they report, and every position they send is zero — including the satellite count and the date. It looks exactly like a tracker that cannot see the sky, and no amount of waiting on a windowsill fixes it.' },
        { p: 'The configuration message generated for those models includes the setting that turns masking off, so a device onboarded through the panel does not have this problem. If you configured a tracker by hand and it reports zeros with a healthy signal, this is the first thing to check.' },
        { h2: 'After the first connection, stop using SMS', id: 'after' },
        { p: 'Once the tracker has a data connection, every further change goes over that connection instead — instantly, with a confirmation, and at no per-message cost. See [Sending commands](kb:commands) and [Reporting intervals](kb:reporting-intervals).' },
      ],
    },
    lt: {
      title: 'Konfigūracijos SMS paaiškinta',
      summary: 'Ką iš tikrųjų ta keista žinutė sako sekikliui, kodėl svarbūs tarpai pradžioje ir kodėl kartais ji nieko nepakeičia.',
      keywords: ['sms', 'setparam', 'komanda', 'žinutė', 'tarpai', 'slaptažodis', 'konfigūracija'],
      blocks: [
        { p: 'Kol sekiklis neturi duomenų ryšio, vienintelis būdas jį pasiekti – SMS į jo SIM. Ta žinutė nėra sakinys – tai komanda, o sekikliai itin priekabūs jos formai.' },
        { h2: 'Iš ko sudaryta žinutė', id: 'anatomy' },
        { p: 'Konfigūracijos žinutę sudaro dvi dalys: slaptažodis ir komanda. Ką tik iš gamyklos slaptažodis nenustatytas, todėl jo vietą užima **tarpai**. Toliau eina `setparam` ir sunumeruotų nustatymų sąrašas.' },
        { code: '  setparam 2001:internet;2004:tracking.example.com;2005:5027;2006:0' },
        { ul: [
          '`2001` – APN, kad SIM pasiektų internetą',
          '`2004` – serverio adresas, kuriuo siųsti',
          '`2005` – prievadas tame serveryje',
          '`2006` – protokolas; `0` reiškia TCP',
        ] },
        { h2: 'Tarpai pradžioje ir yra visa žinutė', id: 'spaces' },
        { p: 'Būtent ši smulkmena atima žmonėms popietę. Vienos įrenginių šeimos tikisi `slaptažodis tarpas komanda` – vieno tarpo, kai slaptažodis nenustatytas. Kitos tikisi `prisijungimas tarpas slaptažodis tarpas komanda` – **dviejų** tarpų. Nusiuntus vieną ten, kur laukiami du, sekiklis gauna puikiai pristatytą žinutę, nieko iš jos neperskaito, nieko neatsako ir tiesiog niekada neprisijungia.' },
        { callout: 'warning', p: 'Iš serverio pusės netinkamai įtraukta žinutė neatskiriama nuo negyvos SIM, neteisingo APN ar niekada neįjungto sekiklio. Niekur nematyti jokios klaidos – kaip tik dėl to tai ir brangu.' },
        { p: 'Prijungimo skydelis jau žino, kokio tarpo reikia jūsų įrenginių šeimai, ir žinutę sudaro atitinkamai. Todėl ir yra kopijavimo mygtukas, o komandos perrašinėjimas ranka – bloga mintis.' },
        { h2: 'Žinučių programos tyliai gadina komandas', id: 'apps' },
        { p: 'Kai kurie telefonai ir daugelis masinio SMS siuntimo paslaugų „sutvarko“ išsiunčiamą tekstą: nukerpa tarpus pradžioje, paprastus tarpus keičia tipografiniais arba normalizuoja skyrybą. Visa tai duoda žinutę, kuri ekrane atrodo lygiai tokia pat, o sekikliui yra nesąmonė. Jei siunčiate ranka – siųskite iš paprastos telefono žinučių programos ir įklijuokite, o ne rašykite.' },
        { h2: 'Kai kurie modeliai slepia savo poziciją', id: 'masking' },
        { p: 'Keli sekiklių modeliai iš gamyklos ateina su įjungtu pozicijos slėpimu: jie prisijungia, siunčia duomenis, o kiekviena jų siunčiama pozicija yra nuliai – įskaitant palydovų skaičių ir datą. Tai atrodo lygiai kaip sekiklis, nematantis dangaus, ir jokie laukimai ant palangės to neišsprendžia.' },
        { p: 'Tiems modeliams sugeneruotoje konfigūracijos žinutėje jau yra nustatymas, išjungiantis slėpimą, todėl per skydelį prijungtas įrenginys šios bėdos neturi. Jei sekiklį konfigūravote ranka ir jis siunčia nulius esant geram signalui – tai pirmas dalykas, kurį reikia patikrinti.' },
        { h2: 'Po pirmo prisijungimo SMS nebereikia', id: 'after' },
        { p: 'Kai sekiklis turi duomenų ryšį, kiekvienas tolesnis pakeitimas keliauja tuo ryšiu – akimirksniu, su patvirtinimu ir be mokesčio už žinutę. Žr. [Komandų siuntimas](kb:commands) ir [Siuntimo intervalai](kb:reporting-intervals).' },
      ],
    },
    pl: {
      title: 'SMS konfiguracyjny wyjaśniony',
      summary: 'Co ta dziwnie wyglądająca wiadomość naprawdę mówi lokalizatorowi, dlaczego liczą się wiodące spacje i dlaczego czasem nic nie zmienia.',
      keywords: ['sms', 'setparam', 'polecenie', 'wiadomość', 'spacje', 'hasło', 'konfiguracja'],
      blocks: [
        { p: 'Zanim lokalizator ma połączenie danych, jedynym sposobem dotarcia do niego jest SMS na jego kartę SIM. Ta wiadomość nie jest zdaniem — jest poleceniem, a lokalizatory są bezlitosne wobec jej dokładnego kształtu.' },
        { h2: 'Z czego składa się wiadomość', id: 'anatomy' },
        { p: 'Wiadomość konfiguracyjna ma dwie części: hasło i polecenie. Prosto z fabryki hasło nie jest ustawione, więc jego miejsce wypełniają **spacje**. Dalej idzie `setparam` i lista ponumerowanych ustawień.' },
        { code: '  setparam 2001:internet;2004:tracking.example.com;2005:5027;2006:0' },
        { ul: [
          '`2001` — APN, żeby karta SIM dotarła do internetu',
          '`2004` — adres serwera, na który wysyłać',
          '`2005` — port na tym serwerze',
          '`2006` — protokół; `0` oznacza TCP',
        ] },
        { h2: 'Wiodące spacje to cała wiadomość', id: 'spaces' },
        { p: 'To ten szczegół, który kosztuje ludzi popołudnie. Niektóre rodziny urządzeń oczekują `hasło spacja polecenie` — jednej spacji, gdy hasła nie ustawiono. Inne oczekują `login spacja hasło spacja polecenie` — **dwóch** spacji. Wyślij jedną tam, gdzie oczekiwano dwóch, a lokalizator odbierze doskonale doręczoną wiadomość, nie odczyta z niej nic, nie odpowie nic i po prostu nigdy się nie połączy.' },
        { callout: 'warning', p: 'Od strony serwera źle wcięta wiadomość jest nie do odróżnienia od martwej karty SIM, złego APN albo lokalizatora, którego nigdy nie włączono. Nigdzie nie widać żadnego błędu — i właśnie to czyni ją tak kosztowną.' },
        { p: 'Panel podłączania wie już, jakiego wcięcia potrzebuje Twoja rodzina urządzeń, i buduje wiadomość odpowiednio. Dlatego istnieje przycisk kopiowania, a przepisywanie polecenia ręcznie to zły pomysł.' },
        { h2: 'Aplikacje do wiadomości po cichu psują polecenia', id: 'apps' },
        { p: 'Niektóre telefony i wiele usług masowego SMS „porządkują” wysyłany tekst: obcinają wiodące spacje, zamieniają zwykłe spacje na typograficzne albo normalizują interpunkcję. Wszystko to daje wiadomość wyglądającą na ekranie identycznie, a dla lokalizatora będącą bełkotem. Jeśli musisz wysłać ręcznie, wyślij ze zwykłej aplikacji SMS w telefonie i wklej zamiast pisać.' },
        { h2: 'Niektóre modele ukrywają własną pozycję', id: 'masking' },
        { p: 'Kilka modeli wychodzi z fabryki z włączonym maskowaniem pozycji: łączą się, raportują, a każda wysyłana pozycja to zera — łącznie z liczbą satelitów i datą. Wygląda to dokładnie jak lokalizator, który nie widzi nieba, i żadne czekanie na parapecie tego nie naprawi.' },
        { p: 'Wiadomość konfiguracyjna generowana dla tych modeli zawiera ustawienie wyłączające maskowanie, więc urządzenie podłączone przez panel tego problemu nie ma. Jeśli konfigurowałeś lokalizator ręcznie, a raportuje zera przy dobrym sygnale — sprawdź to w pierwszej kolejności.' },
        { h2: 'Po pierwszym połączeniu przestań używać SMS', id: 'after' },
        { p: 'Gdy lokalizator ma połączenie danych, każda kolejna zmiana idzie tym połączeniem — natychmiast, z potwierdzeniem i bez kosztu za wiadomość. Zobacz [Wysyłanie poleceń](kb:commands) i [Częstotliwość raportowania](kb:reporting-intervals).' },
      ],
    },
    de: {
      title: 'Die Konfigurations-SMS erklärt',
      summary: 'Was diese seltsam aussehende Nachricht dem Tracker wirklich sagt, warum die führenden Leerzeichen zählen und warum sie manchmal nichts bewirkt.',
      keywords: ['sms', 'setparam', 'befehl', 'nachricht', 'leerzeichen', 'passwort', 'konfiguration'],
      blocks: [
        { p: 'Bevor ein Tracker eine Datenverbindung hat, ist eine SMS an seine SIM der einzige Weg zu ihm. Diese Nachricht ist kein Satz — sie ist ein Befehl, und Tracker sind mit ihrer genauen Form gnadenlos.' },
        { h2: 'Woraus die Nachricht besteht', id: 'anatomy' },
        { p: 'Eine Konfigurationsnachricht hat zwei Teile: ein Passwort und einen Befehl. Ab Werk ist das Passwort nicht gesetzt, seine Stelle füllen also **Leerzeichen**. Danach folgen `setparam` und eine Liste nummerierter Einstellungen.' },
        { code: '  setparam 2001:internet;2004:tracking.example.com;2005:5027;2006:0' },
        { ul: [
          '`2001` — der APN, damit die SIM ins Internet kommt',
          '`2004` — die Serveradresse, an die gesendet wird',
          '`2005` — der Port auf diesem Server',
          '`2006` — das Protokoll; `0` bedeutet TCP',
        ] },
        { h2: 'Die führenden Leerzeichen sind die ganze Nachricht', id: 'spaces' },
        { p: 'Das ist das Detail, das Leute einen Nachmittag kostet. Manche Gerätefamilien erwarten `Passwort Leerzeichen Befehl` — bei nicht gesetztem Passwort also ein Leerzeichen. Andere erwarten `Login Leerzeichen Passwort Leerzeichen Befehl` — **zwei**. Senden Sie eines, wo zwei erwartet werden, empfängt der Tracker eine tadellos zugestellte Nachricht, liest daraus gar nichts, antwortet nichts und verbindet sich schlicht nie.' },
        { callout: 'warning', p: 'Vom Server aus ist eine falsch eingerückte Nachricht nicht von einer toten SIM, einem falschen APN oder einem nie eingeschalteten Tracker zu unterscheiden. Nirgends ist ein Fehler zu sehen — genau das macht sie teuer.' },
        { p: 'Das Einrichtungspanel weiß bereits, welche Einrückung Ihre Gerätefamilie braucht, und baut die Nachricht entsprechend. Dafür gibt es die Kopierschaltfläche, und deshalb ist Abtippen eine schlechte Idee.' },
        { h2: 'Messaging-Apps zerstören Befehle unbemerkt', id: 'apps' },
        { p: 'Manche Telefone und viele Massen-SMS-Dienste „räumen“ ausgehenden Text auf: Manche schneiden führende Leerzeichen weg, ersetzen normale durch typografische Leerzeichen oder normalisieren Satzzeichen. All das ergibt eine Nachricht, die auf dem Bildschirm identisch aussieht und für den Tracker Unsinn ist. Wenn Sie von Hand senden müssen, senden Sie aus einer schlichten SMS-App und fügen Sie ein, statt zu tippen.' },
        { h2: 'Manche Modelle verbergen ihre eigene Position', id: 'masking' },
        { p: 'Einige Trackermodelle kommen mit aktivierter Positionsmaskierung: Solche Geräte verbinden sich, sie melden, und jede gesendete Position ist null — inklusive Satellitenzahl und Datum. Das sieht exakt aus wie ein Tracker ohne Himmelssicht, und kein Warten auf der Fensterbank behebt es.' },
        { p: 'Die für diese Modelle erzeugte Konfigurationsnachricht enthält die Einstellung, die die Maskierung abschaltet — ein über das Panel eingerichtetes Gerät hat dieses Problem also nicht. Haben Sie einen Tracker von Hand konfiguriert und er meldet bei gutem Signal Nullen, prüfen Sie das zuerst.' },
        { h2: 'Nach der ersten Verbindung keine SMS mehr', id: 'after' },
        { p: 'Sobald der Tracker eine Datenverbindung hat, läuft jede weitere Änderung darüber — sofort, mit Bestätigung und ohne Kosten je Nachricht. Siehe [Befehle senden](kb:commands) und [Meldeintervalle](kb:reporting-intervals).' },
      ],
    },
  },
}
