import type { KbArticle } from '../types.js'

export const connectATracker: KbArticle = {
  slug: 'connect-a-tracker',
  category: 'devices',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'Connecting a tracker for the first time',
      summary: 'The three things a tracker needs to know, the two ways to tell it, and how to confirm it worked.',
      keywords: ['onboarding', 'setup', 'server', 'port', 'configure', 'install', 'first connection'],
      blocks: [
        { p: 'A tracker straight from the factory knows how to find satellites and how to use a mobile network. It does not know where to send anything. Telling it is a one-time job with three values.' },
        { h2: 'The three values', id: 'values' },
        { table: { head: ['Value', 'What it is'], rows: [
          ['**APN**', 'How the SIM reaches the internet. Comes from your SIM provider — see [SIM cards and APN](kb:sim-and-apn).'],
          ['**Server**', 'The address the tracker sends to. Shown on the device\'s onboarding panel; it belongs to this deployment, so never copy it from a forum post.'],
          ['**Port**', 'The numeric door on that server. Shown next to it.'],
        ] } },
        { callout: 'warning', p: 'Use the server and port from your own onboarding panel, not from a manual or another platform\'s guide. Pointing hardware at the wrong host is the single most common reason an otherwise perfect installation stays silent.' },
        { h2: 'Way 1 — let us send the configuration message', id: 'auto' },
        { p: 'This is the short path and it needs no tools at all.' },
        { ol: [
          'Add the device with its IMEI, and save the SIM\'s phone number on the device.',
          'Open the device and press **Onboard**.',
          'Press **Send config SMS**. The APN and the server settings go to the tracker as one text message.',
          'Within about a minute the tracker connects and appears on your map.',
        ] },
        { p: 'From then on the tracker is managed over its data connection — no further text messages, and no cost per change. See [Sending commands](kb:commands).' },
        { h2: 'Way 2 — send the message yourself', id: 'manual' },
        { p: 'If the platform cannot send text messages for you, or the SIM cannot receive them, the same panel shows the exact commands to send by hand, or to type into the manufacturer\'s configurator over USB.' },
        { ol: [
          'Send the APN command to the tracker\'s phone number. Wait about 30 seconds.',
          'Send the server command.',
          'Wait a minute and check the map.',
        ] },
        { callout: 'warning', p: 'Copy the command **exactly**, including the spaces at the beginning. Those leading spaces stand in for the tracker\'s unset password, and different device families need a different number of them. A message that looks right but has the wrong leading spacing is delivered successfully, parsed as nothing, and answered with silence — indistinguishable from a dead SIM. Use the copy button rather than retyping. See [The configuration SMS explained](kb:config-sms).' },
        { h2: 'Confirming it worked', id: 'confirm' },
        { p: 'A device that has never sent a position is listed as **Never reported**. Once the first position arrives that label is replaced by a live status and the vehicle appears on the map. Give it a couple of minutes outdoors — a tracker indoors may connect fine and still have no position to send.' },
        { p: 'Still nothing after fifteen minutes? Work through [Device not reporting](kb:device-not-reporting) — it is ordered by how often each cause turns out to be the real one.' },
      ],
    },
    lt: {
      title: 'Seklio prijungimas pirmą kartą',
      summary: 'Trys dalykai, kuriuos seklys turi sužinoti, du būdai jam tai pasakyti ir kaip įsitikinti, kad pavyko.',
      keywords: ['prijungimas', 'nustatymas', 'serveris', 'prievadas', 'konfigūracija', 'montavimas'],
      blocks: [
        { p: 'Ką tik iš gamyklos atkeliavęs seklys moka rasti palydovus ir naudotis mobiliuoju tinklu. Jis nežino, kur ką siųsti. Tai pasakoma vieną kartą, trimis reikšmėmis.' },
        { h2: 'Trys reikšmės', id: 'values' },
        { table: { head: ['Reikšmė', 'Kas tai'], rows: [
          ['**APN**', 'Kaip SIM pasiekia internetą. Gaunama iš SIM tiekėjo – žr. [SIM kortelės ir APN](kb:sim-and-apn).'],
          ['**Serveris**', 'Adresas, kuriuo seklys siunčia. Rodomas įrenginio prijungimo skydelyje; jis priklauso šiam diegimui, todėl niekada nekopijuokite jo iš forumo.'],
          ['**Prievadas**', 'Skaitinės durys tame serveryje. Rodomos šalia.'],
        ] } },
        { callout: 'warning', p: 'Naudokite serverį ir prievadą iš savo prijungimo skydelio, o ne iš instrukcijos ar kitos platformos vadovo. Nukreipta į netinkamą serverį įranga – dažniausia priežastis, kodėl nepriekaištingai sumontuotas seklys tyli.' },
        { h2: '1 būdas — leiskite mums išsiųsti konfigūracijos žinutę', id: 'auto' },
        { p: 'Tai trumpasis kelias ir jam nereikia jokių įrankių.' },
        { ol: [
          'Pridėkite įrenginį su jo IMEI ir įrašykite SIM kortelės telefono numerį įrenginio kortelėje.',
          'Atverkite įrenginį ir spauskite **Prijungti**.',
          'Spauskite **Siųsti konfigūracijos SMS**. APN ir serverio nustatymai iškeliauja sekliui viena žinute.',
          'Maždaug per minutę seklys prisijungia ir pasirodo žemėlapyje.',
        ] },
        { p: 'Nuo tada seklys valdomas per duomenų ryšį – jokių daugiau SMS ir jokių mokesčių už pakeitimą. Žr. [Komandų siuntimas](kb:commands).' },
        { h2: '2 būdas — išsiųskite žinutę patys', id: 'manual' },
        { p: 'Jei platforma negali siųsti SMS už jus arba SIM jų nepriima, tas pats skydelis parodo tikslias komandas – nusiųsti ranka arba suvesti gamintojo konfigūravimo programoje per USB.' },
        { ol: [
          'Nusiųskite APN komandą į seklio telefono numerį. Palaukite apie 30 sekundžių.',
          'Nusiųskite serverio komandą.',
          'Palaukite minutę ir pažiūrėkite žemėlapį.',
        ] },
        { callout: 'warning', p: 'Komandą nukopijuokite **tiksliai**, kartu su tarpais pradžioje. Tie tarpai pradžioje atstoja nenustatytą seklio slaptažodį, o skirtingoms įrenginių šeimoms jų reikia skirtingo skaičiaus. Iš pažiūros teisinga žinutė su netinkamu tarpu pradžioje pristatoma sėkmingai, neperskaitoma kaip niekas ir atsakoma tyla – neatskiriama nuo negyvos SIM. Naudokite kopijavimo mygtuką, o ne perrašinėkite. Žr. [Konfigūracijos SMS paaiškinta](kb:config-sms).' },
        { h2: 'Kaip įsitikinti, kad pavyko', id: 'confirm' },
        { p: 'Įrenginys, niekada nesiuntęs pozicijos, rodomas kaip **Niekada nesiuntė**. Atkeliavus pirmajai pozicijai šis užrašas keičiamas gyva būsena, o automobilis atsiranda žemėlapyje. Duokite jam kelias minutes lauke – patalpoje esantis seklys gali puikiai prisijungti ir vis tiek neturėti ką siųsti.' },
        { p: 'Vis dar nieko po penkiolikos minučių? Eikite per [Įrenginys nesiunčia duomenų](kb:device-not-reporting) – jis surikiuotas pagal tai, kaip dažnai kiekviena priežastis pasirodo esanti tikroji.' },
      ],
    },
    pl: {
      title: 'Pierwsze podłączenie lokalizatora',
      summary: 'Trzy rzeczy, które lokalizator musi wiedzieć, dwa sposoby, żeby mu je przekazać, i jak potwierdzić, że zadziałało.',
      keywords: ['podłączenie', 'konfiguracja', 'serwer', 'port', 'montaż', 'pierwsze połączenie'],
      blocks: [
        { p: 'Lokalizator prosto z fabryki umie znaleźć satelity i korzystać z sieci komórkowej. Nie wie, dokąd cokolwiek wysyłać. Mówi się mu to raz, trzema wartościami.' },
        { h2: 'Trzy wartości', id: 'values' },
        { table: { head: ['Wartość', 'Co to jest'], rows: [
          ['**APN**', 'Jak karta SIM wychodzi do internetu. Podaje go dostawca SIM — zobacz [Karty SIM i APN](kb:sim-and-apn).'],
          ['**Serwer**', 'Adres, na który lokalizator wysyła. Widoczny w panelu podłączania urządzenia; należy do tej instalacji, więc nigdy nie kopiuj go z forum.'],
          ['**Port**', 'Numeryczne drzwi na tym serwerze. Pokazany obok.'],
        ] } },
        { callout: 'warning', p: 'Użyj serwera i portu z własnego panelu podłączania, nie z instrukcji ani poradnika innej platformy. Skierowanie sprzętu na zły host to najczęstszy powód, dla którego bezbłędnie zamontowany lokalizator milczy.' },
        { h2: 'Sposób 1 — pozwól nam wysłać wiadomość konfiguracyjną', id: 'auto' },
        { p: 'To krótka droga i nie wymaga żadnych narzędzi.' },
        { ol: [
          'Dodaj urządzenie z jego IMEI i zapisz numer telefonu karty SIM na urządzeniu.',
          'Otwórz urządzenie i naciśnij **Podłącz**.',
          'Naciśnij **Wyślij SMS konfiguracyjny**. APN i ustawienia serwera trafiają do lokalizatora jedną wiadomością.',
          'W około minutę lokalizator łączy się i pojawia na mapie.',
        ] },
        { p: 'Od tej chwili lokalizatorem zarządza się przez połączenie danych — żadnych kolejnych SMS-ów ani kosztu za zmianę. Zobacz [Wysyłanie komend](kb:commands).' },
        { h2: 'Sposób 2 — wyślij wiadomość samodzielnie', id: 'manual' },
        { p: 'Jeśli platforma nie może wysyłać SMS-ów za Ciebie albo karta ich nie odbiera, ten sam panel pokazuje dokładne komendy — do wysłania ręcznie albo do wpisania w konfiguratorze producenta przez USB.' },
        { ol: [
          'Wyślij komendę APN na numer telefonu lokalizatora. Odczekaj około 30 sekund.',
          'Wyślij komendę serwera.',
          'Poczekaj minutę i sprawdź mapę.',
        ] },
        { callout: 'warning', p: 'Skopiuj komendę **dokładnie**, razem ze spacjami na początku. Te wiodące spacje zastępują nieustawione hasło lokalizatora, a różne rodziny urządzeń potrzebują ich innej liczby. Wiadomość wyglądająca poprawnie, ale z błędną liczbą spacji, zostaje doręczona, nie zostaje odczytana i nie dostaje odpowiedzi — nie do odróżnienia od martwej karty SIM. Używaj przycisku kopiowania zamiast przepisywać. Zobacz [SMS konfiguracyjny wyjaśniony](kb:config-sms).' },
        { h2: 'Potwierdzenie, że zadziałało', id: 'confirm' },
        { p: 'Urządzenie, które nigdy nie wysłało pozycji, widnieje jako **Nigdy nie raportowało**. Po pierwszej pozycji ta etykieta ustępuje miejsca statusowi na żywo, a pojazd pojawia się na mapie. Daj mu kilka minut na zewnątrz — lokalizator w budynku może się świetnie połączyć i nadal nie mieć pozycji do wysłania.' },
        { p: 'Wciąż nic po piętnastu minutach? Przejdź przez [Urządzenie nie raportuje](kb:device-not-reporting) — jest uporządkowane według tego, jak często dana przyczyna okazuje się prawdziwa.' },
      ],
    },
    de: {
      title: 'Einen Tracker zum ersten Mal anschließen',
      summary: 'Die drei Angaben, die ein Tracker braucht, die zwei Wege sie ihm zu geben, und wie Sie den Erfolg prüfen.',
      keywords: ['inbetriebnahme', 'einrichtung', 'server', 'port', 'konfigurieren', 'einbau', 'erste verbindung'],
      blocks: [
        { p: 'Ein Tracker direkt aus dem Werk weiß, wie er Satelliten findet und ein Mobilfunknetz nutzt. Er weiß nicht, wohin er irgendetwas senden soll. Das sagt man ihm einmal, mit drei Werten.' },
        { h2: 'Die drei Werte', id: 'values' },
        { table: { head: ['Wert', 'Was es ist'], rows: [
          ['**APN**', 'Wie die SIM ins Internet kommt. Kommt von Ihrem SIM-Anbieter — siehe [SIM-Karten und APN](kb:sim-and-apn).'],
          ['**Server**', 'Die Adresse, an die der Tracker sendet. Steht im Einrichtungspanel des Geräts; sie gehört zu dieser Installation — kopieren Sie sie nie aus einem Forenbeitrag.'],
          ['**Port**', 'Die numerische Tür auf diesem Server. Steht daneben.'],
        ] } },
        { callout: 'warning', p: 'Nehmen Sie Server und Port aus Ihrem eigenen Einrichtungspanel, nicht aus einem Handbuch oder der Anleitung einer anderen Plattform. Hardware auf den falschen Host zu richten ist der häufigste Grund, warum ein sonst perfekter Einbau stumm bleibt.' },
        { h2: 'Weg 1 — wir senden die Konfigurationsnachricht', id: 'auto' },
        { p: 'Das ist der kurze Weg, und er braucht überhaupt kein Werkzeug.' },
        { ol: [
          'Gerät mit seiner IMEI anlegen und die Rufnummer der SIM am Gerät speichern.',
          'Gerät öffnen und **Einrichten** drücken.',
          '**Konfigurations-SMS senden** drücken. APN und Servereinstellungen gehen als eine Nachricht an den Tracker.',
          'Nach etwa einer Minute verbindet sich der Tracker und erscheint auf Ihrer Karte.',
        ] },
        { p: 'Ab da wird der Tracker über seine Datenverbindung verwaltet — keine weiteren SMS, keine Kosten je Änderung. Siehe [Befehle senden](kb:commands).' },
        { h2: 'Weg 2 — Sie senden die Nachricht selbst', id: 'manual' },
        { p: 'Kann die Plattform keine SMS für Sie senden oder empfängt die SIM keine, zeigt dasselbe Panel die exakten Befehle — zum Senden von Hand oder zum Eintippen im Konfigurator des Herstellers über USB.' },
        { ol: [
          'APN-Befehl an die Rufnummer des Trackers senden. Etwa 30 Sekunden warten.',
          'Server-Befehl senden.',
          'Eine Minute warten und die Karte prüfen.',
        ] },
        { callout: 'warning', p: 'Kopieren Sie den Befehl **exakt**, einschließlich der Leerzeichen am Anfang. Diese führenden Leerzeichen stehen für das nicht gesetzte Passwort des Trackers, und verschiedene Gerätefamilien brauchen unterschiedlich viele. Eine Nachricht, die richtig aussieht, aber falsch eingerückt ist, wird zugestellt, als nichts gelesen und mit Schweigen beantwortet — nicht von einer toten SIM zu unterscheiden. Nutzen Sie die Kopierschaltfläche statt abzutippen. Siehe [Die Konfigurations-SMS erklärt](kb:config-sms).' },
        { h2: 'Erfolg prüfen', id: 'confirm' },
        { p: 'Ein Gerät, das nie eine Position gesendet hat, steht als **Nie gemeldet**. Mit der ersten Position weicht diese Bezeichnung einem Live-Status, und das Fahrzeug erscheint auf der Karte. Geben Sie ihm ein paar Minuten im Freien — ein Tracker im Gebäude kann sich einwandfrei verbinden und trotzdem keine Position zu senden haben.' },
        { p: 'Nach fünfzehn Minuten noch nichts? Arbeiten Sie [Gerät meldet sich nicht](kb:device-not-reporting) durch — es ist danach sortiert, wie oft sich die jeweilige Ursache als die echte erweist.' },
      ],
    },
  },
}
