import type { KbArticle } from '../types.js'

export const customerAccounts: KbArticle = {
  slug: 'customer-accounts',
  category: 'tsp',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true, entitlement: 'subAccounts' },
  screen: '/app/accounts',
  doc: {
    en: {
      title: 'Customer accounts — one per customer',
      summary: 'Creating accounts and logins, switching between "all customers" and acting for one, and the boundary that keeps them apart.',
      keywords: ['account', 'customer', 'sub-account', 'tenant', 'login', 'switch', 'act for', 'overview'],
      blocks: [
        { p: 'An account is one customer. Everything belongs to exactly one: vehicles, zones, rules, drivers, reports and logins. That boundary is not a filter you can widen — it is enforced everywhere, so no query, report or API key can reach across it.' },
        { h2: 'Creating one', id: 'create' },
        { ol: [
          'Create the account with the customer\'s name and their time zone. The time zone decides how their reports cut days — see [Time zones and units](kb:time-zones-and-units).',
          'Add a login: their e-mail address and a starting password. Choose the role — a customer who should look but not change is a **Viewer**; one who runs their own fleet is an **Account manager**. See [Logins and roles](kb:logins-and-roles).',
          'Add their devices to that account.',
          'Hand over the address of your dashboard and the password. They change it themselves.',
        ] },
        { h2: 'The two ways you look at a customer', id: 'context' },
        { table: { head: ['Mode', 'What it is'], rows: [
          ['**All accounts**', 'The read-only overview. Every page shows everything across your whole book of customers, and operational changes are withheld. This is the mode for answering "how is everyone doing".'],
          ['**Acting for one customer**', 'Every page narrows to that account, and editing works exactly as it does for them. This is the mode for doing work on their behalf.'],
        ] } },
        { p: 'You switch between them from the customer selector in the top bar. The distinction is deliberate: the mode where you can see everybody is the mode where you cannot change anything, so a click on the wrong row cannot alter the wrong customer\'s fleet.' },
        { h2: 'What your customer sees', id: 'their-view' },
        { p: 'Their own account and nothing else. They cannot see that other accounts exist, cannot see your organisation, and cannot see the platform behind your brand. Their sign-in page is yours — see [What white-label means](kb:white-label-explained).' },
        { h2: 'Deleting an account', id: 'delete' },
        { callout: 'warning', p: 'Deleting an account removes its logins and its assignments. Move or retire its devices first — an account that still holds devices will refuse to be deleted, and that refusal is a safeguard rather than an obstacle.' },
        { h2: 'A naming habit worth having', id: 'naming' },
        { p: 'Name accounts the way your invoices name them, and name vehicles the way your customer names them. Six months in, an alert that says "Sprinter 402 left Depot" is actionable and "Device 7 left Zone 3" is a research task.' },
      ],
    },
    lt: {
      title: 'Klientų paskyros — po vieną kiekvienam klientui',
      summary: 'Paskyrų ir prisijungimų kūrimas, perjungimas tarp „visų klientų" ir darbo vieno vardu, ir riba, kuri juos laiko atskirai.',
      keywords: ['paskyra', 'klientas', 'subpaskyra', 'prisijungimas', 'perjungimas', 'veikti už', 'apžvalga'],
      blocks: [
        { p: 'Paskyra – tai vienas klientas. Viskas priklauso lygiai vienai: automobiliai, zonos, taisyklės, vairuotojai, ataskaitos ir prisijungimai. Ši riba nėra filtras, kurį galima praplėsti – ji užtikrinama visur, tad nė viena užklausa, ataskaita ar API raktas jos neperžengia.' },
        { h2: 'Kaip sukurti', id: 'create' },
        { ol: [
          'Sukurkite paskyrą su kliento pavadinimu ir jo laiko juosta. Laiko juosta lemia, kaip jo ataskaitos kerpa dienas – žr. [Laiko juostos ir vienetai](kb:time-zones-and-units).',
          'Pridėkite prisijungimą: jo el. pašto adresą ir pradinį slaptažodį. Parinkite rolę – klientui, kuris turi žiūrėti, bet nekeisti, tinka **Stebėtojas**; tvarkančiam savo parką – **Paskyros valdytojas**. Žr. [Prisijungimai ir rolės](kb:logins-and-roles).',
          'Pridėkite jo įrenginius į tą paskyrą.',
          'Perduokite savo skydelio adresą ir slaptažodį. Jį jis pasikeis pats.',
        ] },
        { h2: 'Du būdai žiūrėti į klientą', id: 'context' },
        { table: { head: ['Režimas', 'Kas tai'], rows: [
          ['**Visos paskyros**', 'Tik skaitymo apžvalga. Kiekvienas puslapis rodo viską per visą jūsų klientų portfelį, o operatyviniai pakeitimai sulaikomi. Tai režimas atsakyti į klausimą „kaip visiems sekasi".'],
          ['**Veikiant vieno kliento vardu**', 'Kiekvienas puslapis susiaurėja iki tos paskyros, o redagavimas veikia lygiai taip, kaip veikia jam. Tai režimas dirbti jo vardu.'],
        ] } },
        { p: 'Perjungiama klientų parinkikliu viršutinėje juostoje. Skirtumas sąmoningas: režimas, kuriame matote visus, yra režimas, kuriame nieko negalite pakeisti, tad spustelėjimas ne toje eilutėje negali pakeisti ne to kliento parko.' },
        { h2: 'Ką mato jūsų klientas', id: 'their-view' },
        { p: 'Savo paskyrą ir daugiau nieko. Jis nemato, kad egzistuoja kitos paskyros, nemato jūsų organizacijos ir nemato platformos už jūsų prekės ženklo. Jo prisijungimo puslapis – jūsų; žr. [Ką reiškia white-label](kb:white-label-explained).' },
        { h2: 'Paskyros ištrynimas', id: 'delete' },
        { callout: 'warning', p: 'Ištrynus paskyrą pašalinami jos prisijungimai ir priskyrimai. Pirmiausia perkelkite arba nurašykite jos įrenginius – paskyra, kuri dar turi įrenginių, ištrinti neleis, ir tas atsisakymas yra apsauga, o ne kliūtis.' },
        { h2: 'Vertas įprotis vardijant', id: 'naming' },
        { p: 'Paskyras vadinkite taip, kaip jas vadina jūsų sąskaitos, o automobilius – taip, kaip juos vadina jūsų klientas. Po pusmečio pranešimas „Sprinter 402 išvažiavo iš Bazės" yra veiksmas, o „Įrenginys 7 išvažiavo iš 3 zonos" – tyrimo užduotis.' },
      ],
    },
    pl: {
      title: 'Konta klientów — po jednym na klienta',
      summary: 'Tworzenie kont i loginów, przełączanie między „wszystkimi klientami" a działaniem w imieniu jednego, i granica, która ich rozdziela.',
      keywords: ['konto', 'klient', 'subkonto', 'login', 'przełączanie', 'działaj za', 'przegląd'],
      blocks: [
        { p: 'Konto to jeden klient. Wszystko należy do dokładnie jednego: pojazdy, strefy, reguły, kierowcy, raporty i loginy. Ta granica nie jest filtrem, który da się poszerzyć — jest egzekwowana wszędzie, więc żadne zapytanie, raport ani klucz API jej nie przekroczy.' },
        { h2: 'Tworzenie', id: 'create' },
        { ol: [
          'Utwórz konto z nazwą klienta i jego strefą czasową. Strefa decyduje, jak jego raporty tną dni — zobacz [Strefy czasowe i jednostki](kb:time-zones-and-units).',
          'Dodaj login: jego adres e-mail i hasło startowe. Wybierz rolę — klient, który ma patrzeć, a nie zmieniać, to **Podgląd**; ten, który prowadzi własną flotę, to **Menedżer konta**. Zobacz [Loginy i role](kb:logins-and-roles).',
          'Dodaj jego urządzenia do tego konta.',
          'Przekaż adres swojego panelu i hasło. Zmieni je sam.',
        ] },
        { h2: 'Dwa sposoby patrzenia na klienta', id: 'context' },
        { table: { head: ['Tryb', 'Czym jest'], rows: [
          ['**Wszystkie konta**', 'Przegląd tylko do odczytu. Każda strona pokazuje wszystko w całym Twoim portfelu klientów, a zmiany operacyjne są wstrzymane. To tryb na pytanie „jak wszystkim idzie".'],
          ['**Działanie za jednego klienta**', 'Każda strona zawęża się do tego konta, a edycja działa dokładnie tak, jak działa u niego. To tryb pracy w jego imieniu.'],
        ] } },
        { p: 'Przełączasz się selektorem klienta na górnym pasku. Rozróżnienie jest celowe: tryb, w którym widzisz wszystkich, to tryb, w którym niczego nie zmienisz, więc kliknięcie w złym wierszu nie zmieni floty niewłaściwego klienta.' },
        { h2: 'Co widzi Twój klient', id: 'their-view' },
        { p: 'Swoje konto i nic więcej. Nie widzi, że istnieją inne konta, nie widzi Twojej organizacji i nie widzi platformy za Twoją marką. Jego strona logowania jest Twoja — zobacz [Co znaczy white-label](kb:white-label-explained).' },
        { h2: 'Usuwanie konta', id: 'delete' },
        { callout: 'warning', p: 'Usunięcie konta kasuje jego loginy i przypisania. Najpierw przenieś albo wycofaj jego urządzenia — konto, które wciąż je ma, odmówi usunięcia, a ta odmowa to zabezpieczenie, nie przeszkoda.' },
        { h2: 'Nawyk w nazewnictwie wart wyrobienia', id: 'naming' },
        { p: 'Konta nazywaj tak, jak nazywają je Twoje faktury, a pojazdy tak, jak nazywa je Twój klient. Po pół roku alert „Sprinter 402 opuścił Bazę" jest działaniem, a „Urządzenie 7 opuściło Strefę 3" zadaniem badawczym.' },
      ],
    },
    de: {
      title: 'Kundenkonten — eines je Kunde',
      summary: 'Konten und Zugänge anlegen, zwischen „alle Kunden" und dem Handeln für einen wechseln, und die Grenze, die sie trennt.',
      keywords: ['konto', 'kunde', 'unterkonto', 'zugang', 'umschalten', 'handeln für', 'übersicht'],
      blocks: [
        { p: 'Ein Konto ist ein Kunde. Alles gehört zu genau einem: Fahrzeuge, Zonen, Regeln, Fahrer, Berichte und Zugänge. Diese Grenze ist kein Filter, den man weiten kann — sie wird überall durchgesetzt, sodass keine Abfrage, kein Bericht und kein API-Schlüssel über sie hinausreicht.' },
        { h2: 'Eines anlegen', id: 'create' },
        { ol: [
          'Konto mit dem Namen des Kunden und seiner Zeitzone anlegen. Die Zeitzone bestimmt, wie seine Berichte Tage schneiden — siehe [Zeitzonen und Einheiten](kb:time-zones-and-units).',
          'Zugang anlegen: E-Mail-Adresse und Startpasswort. Rolle wählen — ein Kunde, der schauen und nicht ändern soll, ist **Betrachter**; wer die eigene Flotte führt, ist **Kontomanager**. Siehe [Zugänge und Rollen](kb:logins-and-roles).',
          'Die Geräte diesem Konto zuordnen.',
          'Die Adresse Ihres Dashboards und das Passwort übergeben. Der Kunde ändert es selbst.',
        ] },
        { h2: 'Zwei Arten, auf einen Kunden zu blicken', id: 'context' },
        { table: { head: ['Modus', 'Was er ist'], rows: [
          ['**Alle Konten**', 'Die Nur-Lese-Übersicht. Jede Seite zeigt alles über Ihren gesamten Kundenbestand, operative Änderungen bleiben gesperrt. Der Modus für die Frage „wie läuft es bei allen".'],
          ['**Für einen Kunden handeln**', 'Jede Seite verengt sich auf dieses Konto, und Bearbeiten funktioniert genau wie bei ihm. Der Modus, um in seinem Namen zu arbeiten.'],
        ] } },
        { p: 'Umgeschaltet wird über die Kundenauswahl in der Kopfzeile. Die Trennung ist Absicht: der Modus, in dem Sie alle sehen, ist der Modus, in dem Sie nichts ändern können — ein Klick in der falschen Zeile kann so nicht die Flotte des falschen Kunden verändern.' },
        { h2: 'Was Ihr Kunde sieht', id: 'their-view' },
        { p: 'Sein eigenes Konto und sonst nichts. Er sieht nicht, dass es andere Konten gibt, sieht Ihre Organisation nicht und sieht die Plattform hinter Ihrer Marke nicht. Seine Anmeldeseite ist Ihre — siehe [Was White-Label bedeutet](kb:white-label-explained).' },
        { h2: 'Ein Konto löschen', id: 'delete' },
        { callout: 'warning', p: 'Das Löschen eines Kontos entfernt seine Zugänge und Zuordnungen. Verschieben oder legen Sie seine Geräte vorher still — ein Konto, das noch Geräte hält, verweigert die Löschung, und diese Weigerung ist eine Sicherung, kein Hindernis.' },
        { h2: 'Eine Benennungsgewohnheit, die sich lohnt', id: 'naming' },
        { p: 'Benennen Sie Konten so, wie Ihre Rechnungen sie nennen, und Fahrzeuge so, wie Ihr Kunde sie nennt. Ein halbes Jahr später ist „Sprinter 402 hat Betriebshof verlassen" eine Handlung und „Gerät 7 hat Zone 3 verlassen" eine Rechercheaufgabe.' },
      ],
    },
  },
}
