import type { KbArticle } from '../types.js'

export const customDomain: KbArticle = {
  slug: 'custom-domain',
  category: 'tsp',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true, entitlement: 'customDomains' },
  screen: '/app/branding',
  doc: {
    en: {
      title: 'Your own domain',
      summary: 'Two DNS records, what each one does, the trailing dot that quietly breaks setups, and what the statuses mean.',
      keywords: ['domain', 'dns', 'cname', 'a record', 'txt', 'verification', 'https', 'certificate', 'subdomain'],
      blocks: [
        { p: 'Your customers should sign in at your address, not somebody else\'s. There are two ways to get there, and one of them needs no DNS work at all.' },
        { h2: 'The quick way — a subdomain on the platform domain', id: 'sub' },
        { p: 'Claim a name and your dashboard is live on it in seconds, with a certificate, and no DNS records to publish. It is the right choice for getting started, for a pilot, or for a customer who has to be live this afternoon.' },
        { h2: 'The proper way — a domain you own', id: 'dns' },
        { p: 'Use your own address — `fleet.yourcompany.com`, or `yourcompany.com` itself. Two DNS records make it work: one proves the domain is yours; the other sends visitors to us. You add them once, in the control panel of whoever manages your domain.' },
        { h2: 'What the two records do', id: 'dns-what' },
        { p: 'The **TXT** record is proof of ownership. It sits on a name of its own — a verification prefix in front of your address — and its value is a token generated for you. It sends nobody anywhere; it only confirms that you control the domain. You can leave it in place afterwards.' },
        { p: 'The **routing** record is what actually brings visitors to us. It is either a CNAME or an A record, and which one depends on your address.' },
        { h2: 'CNAME or A record', id: 'dns-cname-a' },
        { p: 'If your address has a word in front of your domain — `fleet.yourcompany.com` — use a **CNAME**. It points at a name rather than a number, so if our address ever changes, you do not have to do anything.' },
        { p: 'If your address is the domain itself — `yourcompany.com`, with nothing in front — a CNAME cannot be used. That is not a limit of this product: a bare domain always carries the records that make it a domain, and a CNAME is not allowed to sit beside any of them. Almost no provider will let you create one there. Use the **A** record instead, or, if your provider offers **ALIAS** or **ANAME**, use that — it behaves like an A record but still follows us if our address changes.' },
        { p: 'Your dashboard shows the one record that applies to the address you entered. You do not have to choose.' },
        { h2: 'The dot at the end of a name', id: 'dns-dot' },
        { p: 'Names are written in full and with a dot at the end — `fleet.yourcompany.com.` — because that dot means “this name is already complete”.' },
        { callout: 'warning', p: 'Many control panels follow the older convention where a name **without** a dot is treated as unfinished, and your domain is appended to it a second time. Paste `fleet.yourcompany.com` without the dot and the record can quietly end up at `fleet.yourcompany.com.yourcompany.com`. In the panel the record looks perfectly correct, and the address answers nothing.' },
        { p: 'So: keep the dot, or enter only the part before your domain (`fleet`). Both are right. The full name without a dot is the one to avoid — and if the dashboard detects that this has happened, it says so.' },
        { h2: 'What the statuses mean', id: 'dns-status' },
        { table: { head: ['Status', 'Meaning'], rows: [
          ['**Pending**', 'The records have not yet been seen in public DNS. The dashboard keeps checking on its own — there is no button to press.'],
          ['**Found**', 'That record is published and correct.'],
          ['**Not found**', 'The record is not visible yet. Changes take a few minutes to spread; if it has been longer, check the name and value against the table.'],
          ['**Verified**', 'Both records are in place. The HTTPS certificate is issued automatically on the first secure request.'],
        ] } },
        { h2: 'Two things this does not touch', id: 'not' },
        { ul: [
          '**Your e-mail.** Mail is delivered by MX records, which are separate and are never altered by this setup.',
          '**Your website.** If your main site lives at `yourcompany.com`, put the dashboard on a subdomain — pointing the bare domain here would take the website down.',
        ] },
      ],
    },
    lt: {
      title: 'Nuosavas domenas',
      summary: 'Du DNS įrašai, ką kiekvienas daro, taškas gale, kuris tyliai sugadina visą sąranką, ir ką reiškia būsenos.',
      keywords: ['domenas', 'dns', 'cname', 'a įrašas', 'txt', 'patvirtinimas', 'https', 'sertifikatas', 'subdomenas'],
      blocks: [
        { p: 'Jūsų klientai turėtų prisijungti jūsų adresu, o ne kažkieno kito. Ten veda du keliai, ir vienam iš jų DNS darbų visai nereikia.' },
        { h2: 'Greitasis būdas — subdomenas platformos domene', id: 'sub' },
        { p: 'Pasirinkite vardą, ir jūsų skydelis jame veikia per kelias sekundes, su sertifikatu, ir jums nieko nereikia skelbti. Tai teisingas pasirinkimas pradžiai, bandomajam projektui ar klientui, kuriam viskas turi veikti jau šią popietę.' },
        { h2: 'Tikrasis būdas — jums priklausantis domenas', id: 'dns' },
        { p: 'Naudokite savo adresą – `fleet.jusuimone.lt` arba patį `jusuimone.lt`. Kad veiktų, reikia dviejų DNS įrašų: vienas įrodo, kad domenas jūsų, kitas atveda lankytojus pas mus. Juos pridedate vieną kartą, jūsų domeną tvarkančios įmonės valdymo skydelyje.' },
        { h2: 'Ką daro tie du įrašai', id: 'dns-what' },
        { p: '**TXT** įrašas – nuosavybės įrodymas. Jis rašomas atskiru vardu – prieš jūsų adresą einančiu patvirtinimo priešdėliu – o jo reikšmė yra jums sugeneruotas raktas. Jis niekur nieko nenukreipia; jis tik patvirtina, kad domeną valdote jūs. Vėliau jį galima palikti vietoje.' },
        { p: '**Nukreipimo** įrašas ir yra tas, kuris atveda lankytojus. Jis yra arba CNAME, arba A įrašas, ir kuris – priklauso nuo jūsų adreso.' },
        { h2: 'CNAME ar A įrašas', id: 'dns-cname-a' },
        { p: 'Jei jūsų adresas turi žodį prieš domeną – `fleet.jusuimone.lt` – naudokite **CNAME**. Jis rodo į vardą, o ne į skaičių, tad jei mūsų adresas kada nors pasikeis, jums nereikės daryti nieko.' },
        { p: 'Jei jūsų adresas yra pats domenas – `jusuimone.lt`, be nieko priekyje – CNAME naudoti negalima. Tai ne šio produkto apribojimas: plikas domenas visada turi įrašus, kurie jį daro domenu, o CNAME negali būti šalia nė vieno iš jų. Beveik nė vienas tiekėjas ten jo sukurti neleis. Vietoj to naudokite **A** įrašą arba, jei tiekėjas siūlo **ALIAS** ar **ANAME**, naudokite jį – jis elgiasi kaip A įrašas, bet vis tiek seka paskui mus, jei mūsų adresas pasikeis.' },
        { p: 'Jūsų skydelis parodo tą vieną įrašą, kuris tinka jūsų įvestam adresui. Rinktis nereikia.' },
        { h2: 'Taškas vardo gale', id: 'dns-dot' },
        { p: 'Vardai rašomi pilni ir su tašku gale – `fleet.jusuimone.lt.` – nes tas taškas reiškia „šis vardas jau pilnas“.' },
        { callout: 'warning', p: 'Daugelis valdymo skydelių laikosi senesnės tvarkos, pagal kurią vardas **be** taško laikomas nebaigtu, ir jūsų domenas prie jo pridedamas antrą kartą. Įklijavus `fleet.jusuimone.lt` be taško, įrašas gali tyliai atsidurti ties `fleet.jusuimone.lt.jusuimone.lt`. Skydelyje jis atrodo nepriekaištingai teisingas, o adresas nieko neatsako.' },
        { p: 'Taigi: palikite tašką arba įveskite tik dalį prieš savo domeną (`fleet`). Abu variantai teisingi. Vengti reikia pilno vardo be taško – o jei skydelis pastebi, kad taip nutiko, jis tai pasako.' },
        { h2: 'Ką reiškia būsenos', id: 'dns-status' },
        { table: { head: ['Būsena', 'Reikšmė'], rows: [
          ['**Laukiama**', 'Abiejų įrašų viešame DNS dar nematyti. Skydelis tikrina pats – spausti nieko nereikia.'],
          ['**Rastas**', 'Tas įrašas paskelbtas ir teisingas.'],
          ['**Nerastas**', 'Kol kas jo nematome. Pakeitimai pasklinda per kelias minutes; jei praėjo daugiau, palyginkite vardą ir reikšmę su lentele.'],
          ['**Patvirtinta**', 'Abu įrašai vietoje. HTTPS išduodamas automatiškai per pirmą saugų kreipimąsi.'],
        ] } },
        { h2: 'Du dalykai, kurių tai neliečia', id: 'not' },
        { ul: [
          '**Jūsų el. paštas.** Paštą pristato MX įrašai, kurie yra atskiri ir per šią sąranką niekada nekeičiami.',
          '**Jūsų svetainė.** Jei pagrindinė svetainė yra ties `jusuimone.lt`, skydelį kelkite į subdomeną – nukreipus plikąjį domeną čia, svetainė nustotų veikti.',
        ] },
      ],
    },
    pl: {
      title: 'Własna domena',
      summary: 'Dwa rekordy DNS, co robi każdy z nich, kropka na końcu, która po cichu psuje konfiguracje, i co znaczą statusy.',
      keywords: ['domena', 'dns', 'cname', 'rekord a', 'txt', 'weryfikacja', 'https', 'certyfikat', 'subdomena'],
      blocks: [
        { p: 'Twoi klienci powinni logować się pod Twoim adresem, nie czyimś innym. Prowadzą tam dwie drogi, a jedna z nich nie wymaga żadnej pracy w DNS.' },
        { h2: 'Droga szybka — subdomena w domenie platformy', id: 'sub' },
        { p: 'Zajmij nazwę, a Twój panel działa pod nią w kilka sekund, z certyfikatem i bez niczego do opublikowania. To właściwy wybór na start, na pilotaż albo dla klienta, który musi działać jeszcze dziś po południu.' },
        { h2: 'Droga właściwa — domena, którą posiadasz', id: 'dns' },
        { p: 'Użyj własnego adresu — `fleet.twojafirma.pl` albo samego `twojafirma.pl`. Do działania potrzebne są dwa rekordy DNS: jeden dowodzi, że domena jest Twoja, drugi kieruje odwiedzających do nas. Dodajesz je raz, w panelu tego, kto zarządza Twoją domeną.' },
        { h2: 'Co robią te dwa rekordy', id: 'dns-what' },
        { p: 'Rekord **TXT** to dowód własności. Znajduje się pod własną nazwą — prefiksie weryfikacyjnym przed Twoim adresem — a jego wartością jest wygenerowany dla Ciebie token. Nikogo nigdzie nie kieruje; jedynie potwierdza, że kontrolujesz domenę. Po weryfikacji można go zostawić.' },
        { p: 'Rekord **routingu** to ten, który faktycznie sprowadza odwiedzających. Jest to CNAME albo rekord A, a który — zależy od Twojego adresu.' },
        { h2: 'CNAME czy rekord A', id: 'dns-cname-a' },
        { p: 'Jeśli Twój adres ma słowo przed domeną — `fleet.twojafirma.pl` — użyj **CNAME**. Wskazuje on na nazwę, a nie na liczbę, więc gdyby nasz adres kiedyś się zmienił, nic nie musisz robić.' },
        { p: 'Jeśli Twój adres to sama domena — `twojafirma.pl`, bez niczego z przodu — CNAME nie może być użyty. To nie ograniczenie tego produktu: goła domena zawsze ma rekordy, które czynią ją domeną, a CNAME nie może stać obok żadnego z nich. Prawie żaden dostawca nie pozwoli go tam utworzyć. Użyj rekordu **A**, albo — jeśli dostawca oferuje **ALIAS** lub **ANAME** — użyj ich: działają jak rekord A, a mimo to podążają za nami, gdy nasz adres się zmieni.' },
        { p: 'Panel pokazuje ten jeden rekord, który pasuje do wpisanego adresu. Nie musisz wybierać.' },
        { h2: 'Kropka na końcu nazwy', id: 'dns-dot' },
        { p: 'Nazwy są zapisane w pełnej postaci i z kropką na końcu — `fleet.twojafirma.pl.` — bo ta kropka znaczy „ta nazwa jest już pełna”.' },
        { callout: 'warning', p: 'Wiele paneli trzyma się starszej konwencji, w której nazwa **bez** kropki jest traktowana jako niedokończona, a Twoja domena zostaje do niej dopisana drugi raz. Wklej `fleet.twojafirma.pl` bez kropki, a rekord może po cichu wylądować pod `fleet.twojafirma.pl.twojafirma.pl`. Panel pokaże go jako całkiem poprawny, a adres nie odpowie na nic.' },
        { p: 'Czyli: zostaw kropkę albo wpisz tylko część przed swoją domeną (`fleet`). Oba warianty są dobre. Unikać należy pełnej nazwy bez kropki — a jeśli panel wykryje, że tak się stało, powie o tym.' },
        { h2: 'Co znaczą statusy', id: 'dns-status' },
        { table: { head: ['Status', 'Znaczenie'], rows: [
          ['**Oczekuje**', 'Obu rekordów nie widać jeszcze w publicznym DNS. Panel sprawdza sam — nie ma przycisku do naciśnięcia.'],
          ['**Znaleziono**', 'Ten rekord jest opublikowany i poprawny.'],
          ['**Nie znaleziono**', 'Jeszcze go nie widzimy. Zmiany rozchodzą się kilka minut; jeśli minęło więcej, porównaj nazwę i wartość z tabelą.'],
          ['**Zweryfikowano**', 'Oba rekordy są na miejscu. HTTPS jest wystawiany automatycznie przy pierwszym bezpiecznym żądaniu.'],
        ] } },
        { h2: 'Dwie rzeczy, których to nie dotyka', id: 'not' },
        { ul: [
          '**Twoja poczta.** Pocztę doręczają rekordy MX, osobne — ta konfiguracja nigdy ich nie zmienia.',
          '**Twoja strona.** Jeśli główna witryna stoi pod `twojafirma.pl`, umieść panel na subdomenie — skierowanie gołej domeny tutaj wyłączyłoby stronę.',
        ] },
      ],
    },
    de: {
      title: 'Eigene Domain',
      summary: 'Zwei DNS-Einträge, was jeder tut, der Punkt am Ende, der Konfigurationen unbemerkt scheitern lässt, und was die Status bedeuten.',
      keywords: ['domain', 'dns', 'cname', 'a-record', 'txt', 'verifizierung', 'https', 'zertifikat', 'subdomain'],
      blocks: [
        { p: 'Ihre Kunden sollen sich unter Ihrer Adresse anmelden, nicht unter der von jemand anderem. Dorthin führen zwei Wege, und einer davon braucht überhaupt keine DNS-Arbeit.' },
        { h2: 'Der schnelle Weg — eine Subdomain auf der Plattformdomain', id: 'sub' },
        { p: 'Sichern Sie sich einen Namen, und Ihr Dashboard läuft darunter in Sekunden, mit Zertifikat und ohne etwas zu veröffentlichen. Die richtige Wahl für den Start, für ein Pilotprojekt oder für einen Kunden, der heute Nachmittag live sein muss.' },
        { h2: 'Der richtige Weg — eine Domain, die Ihnen gehört', id: 'dns' },
        { p: 'Nutzen Sie Ihre eigene Adresse — `fleet.ihrefirma.de` oder `ihrefirma.de` selbst. Zwei DNS-Einträge machen es möglich: Einer beweist, dass die Domain Ihnen gehört, der andere schickt Besucher zu uns. Sie tragen sie einmal ein, im Panel dessen, der Ihre Domain verwaltet.' },
        { h2: 'Was die beiden Einträge tun', id: 'dns-what' },
        { p: 'Der **TXT**-Eintrag ist der Eigentumsnachweis. Er sitzt auf einem eigenen Namen — einem Verifizierungspräfix vor Ihrer Adresse — und sein Wert ist ein für Sie erzeugtes Token. Er schickt niemanden irgendwohin; er bestätigt nur, dass Sie die Domain kontrollieren. Er darf danach stehen bleiben.' },
        { p: 'Der **Routing**-Eintrag ist der, der Besucher tatsächlich zu uns bringt. Er ist entweder ein CNAME oder ein A-Record, und welcher es ist, hängt von Ihrer Adresse ab.' },
        { h2: 'CNAME oder A-Record', id: 'dns-cname-a' },
        { p: 'Hat Ihre Adresse ein Wort vor der Domain — `fleet.ihrefirma.de` — nehmen Sie einen **CNAME**. Er zeigt auf einen Namen statt auf eine Zahl; ändert sich unsere Adresse je, müssen Sie nichts tun.' },
        { p: 'Ist Ihre Adresse die Domain selbst — `ihrefirma.de`, ohne etwas davor — geht kein CNAME. Das ist keine Einschränkung dieses Produkts: Eine nackte Domain trägt immer die Einträge, die sie zur Domain machen, und ein CNAME darf neben keinem davon stehen. Fast kein Anbieter lässt Sie dort einen anlegen. Nehmen Sie stattdessen den **A**-Record, oder — wenn Ihr Anbieter **ALIAS** oder **ANAME** bietet — diese: Solche Einträge verhalten sich wie ein A-Record und folgen uns trotzdem, wenn sich unsere Adresse ändert.' },
        { p: 'Ihr Dashboard zeigt genau den Eintrag, der zu Ihrer eingegebenen Adresse passt. Sie müssen nicht wählen.' },
        { h2: 'Der Punkt am Ende eines Namens', id: 'dns-dot' },
        { p: 'Namen werden vollständig und mit einem Punkt am Ende geschrieben — `fleet.ihrefirma.de.` — denn dieser Punkt heißt „dieser Name ist bereits vollständig“.' },
        { callout: 'warning', p: 'Viele Panels folgen der älteren Konvention, nach der ein Name **ohne** Punkt als unfertig gilt und Ihre Domain ein zweites Mal angehängt wird. Fügen Sie `fleet.ihrefirma.de` ohne Punkt ein, kann der Eintrag still bei `fleet.ihrefirma.de.ihrefirma.de` landen. Im Panel sieht der Eintrag völlig korrekt aus, und die Adresse antwortet auf nichts.' },
        { p: 'Also: den Punkt behalten oder nur den Teil vor Ihrer Domain eintragen (`fleet`). Beides ist richtig. Zu vermeiden ist der vollständige Name ohne Punkt — und erkennt das Dashboard, dass das passiert ist, sagt es das.' },
        { h2: 'Was die Status bedeuten', id: 'dns-status' },
        { table: { head: ['Status', 'Bedeutung'], rows: [
          ['**Ausstehend**', 'Beide Einträge sind im öffentlichen DNS noch nicht zu sehen. Das Dashboard prüft von selbst weiter — es gibt keinen Knopf zu drücken.'],
          ['**Gefunden**', 'Dieser Eintrag ist veröffentlicht und korrekt.'],
          ['**Nicht gefunden**', 'Wir sehen ihn noch nicht. Änderungen brauchen ein paar Minuten; dauert es länger, vergleichen Sie Name und Wert mit der Tabelle.'],
          ['**Verifiziert**', 'Beide Einträge stehen. HTTPS wird bei der ersten sicheren Anfrage automatisch ausgestellt.'],
        ] } },
        { h2: 'Zwei Dinge, die das nicht anfasst', id: 'not' },
        { ul: [
          '**Ihre E-Mail.** E-Mails werden über MX-Einträge zugestellt; die sind getrennt und werden von dieser Einrichtung nie verändert.',
          '**Ihre Website.** Liegt Ihre Hauptseite auf `ihrefirma.de`, setzen Sie das Dashboard auf eine Subdomain — die nackte Domain hierher zu zeigen würde die Website abschalten.',
        ] },
      ],
    },
  },
}
