import type { KbArticle } from '../types.js'

export const deviceNotReporting: KbArticle = {
  slug: 'device-not-reporting',
  category: 'troubleshooting',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'A device is not reporting',
      summary: 'A decision tree ordered by how often each cause turns out to be the real one — start at the top and stop when it works.',
      keywords: ['not reporting', 'offline', 'never reported', 'silent', 'no data', 'troubleshoot', 'no contact', 'dead'],
      blocks: [
        { p: 'Work down the list. It is ordered by how often each cause turns out to be the answer, and each step is cheap enough to just do rather than reason about.' },
        { h2: 'First, which of the two problems is it?', id: 'which' },
        { table: { head: ['State', 'Meaning', 'Go to'], rows: [
          ['**Never reported**', 'It has never sent anything. The installation is not finished.', 'Section A'],
          ['**No contact** (was working)', 'It worked and then stopped.', 'Section B'],
        ] } },
        { h2: 'A — it has never reported', id: 'never' },
        { ol: [
          '**Check the IMEI, digit by digit.** A single wrong character is the most common cause in existence. The [quarantine list](kb:imei) holds the IMEIs of devices that connected but are not registered — if yours is in there, the real number is sitting in front of you.',
          '**Is it powered and outdoors?** A tracker in a workshop may connect fine and have no position to send. Give it a few minutes with a view of the sky.',
          '**Is the SIM activated, and does it have data?** Put it in a phone. If the phone cannot browse, the tracker will not either — see [SIM cards and APN](kb:sim-and-apn).',
          '**Is the APN set?** Signal is not data. This is the second most common cause and it looks exactly like a dead device.',
          '**Was the configuration message actually understood?** Delivered is not the same as parsed. The leading spaces matter and messaging apps damage them — see [The configuration SMS explained](kb:config-sms).',
          '**Is it pointed at the right server?** Check the server and port against your own onboarding panel, not against a manual — see [Connecting a tracker](kb:connect-a-tracker).',
        ] },
        { h2: 'B — it worked, then stopped', id: 'stopped' },
        { ol: [
          '**When exactly did it stop?** The last-contact time is the most informative field on the screen. Match it against something: a service visit, a border crossing, a settings change, the end of a billing month.',
          '**Did it stop at a border?** Most trackers carry a separate roaming profile that ships configured not to transmit — see [Reporting intervals](kb:reporting-intervals).',
          '**Did several vehicles stop on the same day?** That is not hardware. It is a data allowance, a SIM provider suspension, or a subscription — see [What happens if an invoice goes unpaid](kb:unpaid-what-happens).',
          '**Was a settings change applied just before?** A send period of zero means do not transmit. It is a one-field mistake with a total effect.',
          '**Has the vehicle been in a workshop?** Disconnecting the battery, replacing a fuse or removing a panel is a very common way for a tracker to end up unplugged.',
          '**Is it parked underground?** No signal is not a fault. The records are being kept and will arrive when the vehicle comes out.',
        ] },
        { h2: 'What to check on the device itself', id: 'device' },
        { p: 'If the device is still reachable at all, ask it directly: the **Info** command returns its network state and the **GPS fix** command returns its current position and satellite count. A device that answers commands but sends no positions has a GPS problem; one that answers nothing has a power or network problem. See [Sending commands](kb:commands).' },
        { h2: 'Stop this being a surprise', id: 'prevent' },
        { callout: 'tip', p: 'Create one **Device offline** rule covering the whole account. It is the only way to learn about a dead tracker without noticing an absence — and noticing an absence is something people are reliably bad at. See [Every event type](kb:event-types).' },
      ],
    },
    lt: {
      title: 'Įrenginys nesiunčia duomenų',
      summary: 'Sprendimų medis, surikiuotas pagal tai, kaip dažnai kiekviena priežastis pasirodo esanti tikroji – pradėkite nuo viršaus ir sustokite, kai suveiks.',
      keywords: ['nesiunčia', 'neprisijungęs', 'niekada nesiuntė', 'tyli', 'nėra duomenų', 'gedimas', 'nėra ryšio'],
      blocks: [
        { p: 'Eikite sąrašu žemyn. Jis surikiuotas pagal tai, kaip dažnai kiekviena priežastis pasirodo esanti atsakymas, o kiekvienas žingsnis pakankamai pigus, kad jį būtų paprasčiau tiesiog atlikti nei apsvarstyti.' },
        { h2: 'Pirma: kuri iš dviejų problemų?', id: 'which' },
        { table: { head: ['Būsena', 'Reikšmė', 'Eikite į'], rows: [
          ['**Niekada nesiuntė**', 'Jis nieko nėra siuntęs. Montavimas nebaigtas.', 'A skyrių'],
          ['**Nėra ryšio** (veikė anksčiau)', 'Veikė ir nustojo.', 'B skyrių'],
        ] } },
        { h2: 'A — niekada nesiuntė', id: 'never' },
        { ol: [
          '**Patikrinkite IMEI skaitmuo po skaitmens.** Vienas neteisingas simbolis yra dažniausia priežastis apskritai. [Karantino sąraše](kb:imei) yra prisijungusių, bet neužregistruotų įrenginių IMEI – jei jūsiškis ten, tikrasis numeris guli prieš akis.',
          '**Ar jis įjungtas ir lauke?** Dirbtuvėse esantis seklys gali puikiai prisijungti ir neturėti ką siųsti. Duokite jam kelias minutes po atviru dangumi.',
          '**Ar SIM aktyvuota ir turi duomenų?** Įdėkite į telefoną. Jei telefonas nenaršo, seklys irgi nenaršys – žr. [SIM kortelės ir APN](kb:sim-and-apn).',
          '**Ar nustatytas APN?** Signalas nėra duomenys. Tai antra pagal dažnumą priežastis, ir ji atrodo lygiai kaip negyvas įrenginys.',
          '**Ar konfigūracijos žinutė tikrai buvo suprasta?** Pristatyta ir perskaityta – ne tas pat. Tarpai pradžioje svarbūs, o žinučių programos juos gadina – žr. [Konfigūracijos SMS paaiškinta](kb:config-sms).',
          '**Ar jis nukreiptas į teisingą serverį?** Palyginkite serverį ir prievadą su savo prijungimo skydeliu, o ne su instrukcija – žr. [Seklio prijungimas](kb:connect-a-tracker).',
        ] },
        { h2: 'B — veikė, paskui nustojo', id: 'stopped' },
        { ol: [
          '**Kada tiksliai nustojo?** Paskutinio ryšio laikas – informatyviausias laukas ekrane. Susiekite jį su kuo nors: serviso vizitu, sienos kirtimu, nustatymų pakeitimu, atsiskaitymo mėnesio pabaiga.',
          '**Ar nustojo prie sienos?** Dauguma seklių turi atskirą tarptinklinio ryšio profilį, iš gamyklos sukonfigūruotą nesiųsti – žr. [Siuntimo intervalai](kb:reporting-intervals).',
          '**Ar tą pačią dieną nutilo keli automobiliai?** Tai ne įranga. Tai duomenų limitas, operatoriaus blokada arba prenumerata – žr. [Kas nutinka neapmokėjus sąskaitos](kb:unpaid-what-happens).',
          '**Ar prieš tai buvo pritaikytas nustatymų pakeitimas?** Nulinis siuntimo periodas reiškia „nesiųsk". Vieno lauko klaida, kurios poveikis visiškas.',
          '**Ar automobilis buvo dirbtuvėse?** Atjungtas akumuliatorius, pakeistas saugiklis ar nuimta apdaila – labai dažnas būdas sekliui likti be maitinimo.',
          '**Ar jis stovi po žeme?** Nėra signalo – ne gedimas. Įrašai kaupiami ir atkeliaus, kai automobilis išvažiuos.',
        ] },
        { h2: 'Ką patikrinti pačiame įrenginyje', id: 'device' },
        { p: 'Jei įrenginį apskritai dar galima pasiekti, paklauskite jo tiesiogiai: komanda **Informacija** grąžina tinklo būseną, o **GPS fiksacija** – dabartinę poziciją ir palydovų skaičių. Įrenginys, kuris atsako į komandas, bet nesiunčia pozicijų, turi GPS problemą; tas, kuris neatsako į nieką, – maitinimo arba tinklo. Žr. [Komandų siuntimas](kb:commands).' },
        { h2: 'Kad tai nustotų būti staigmena', id: 'prevent' },
        { callout: 'tip', p: 'Sukurkite vieną **Nėra ryšio** taisyklę visai paskyrai. Tai vienintelis būdas sužinoti apie mirusį seklį nepastebint nebuvimo – o nebuvimą pastebėti žmonėms sekasi patikimai prastai. Žr. [Visi įvykių tipai](kb:event-types).' },
      ],
    },
    pl: {
      title: 'Urządzenie nie raportuje',
      summary: 'Drzewo decyzyjne uporządkowane według tego, jak często dana przyczyna okazuje się prawdziwa — zacznij od góry i przestań, gdy zadziała.',
      keywords: ['nie raportuje', 'offline', 'nigdy nie raportowało', 'milczy', 'brak danych', 'usterka', 'brak kontaktu'],
      blocks: [
        { p: 'Idź listą w dół. Jest uporządkowana według tego, jak często dana przyczyna okazuje się odpowiedzią, a każdy krok jest na tyle tani, że łatwiej go po prostu wykonać niż rozważać.' },
        { h2: 'Najpierw: który z dwóch problemów?', id: 'which' },
        { table: { head: ['Stan', 'Znaczenie', 'Idź do'], rows: [
          ['**Nigdy nie raportowało**', 'Nigdy nic nie wysłało. Montaż nie jest dokończony.', 'Sekcji A'],
          ['**Brak kontaktu** (działało wcześniej)', 'Działało i przestało.', 'Sekcji B'],
        ] } },
        { h2: 'A — nigdy nie raportowało', id: 'never' },
        { ol: [
          '**Sprawdź IMEI, cyfra po cyfrze.** Jeden zły znak to najczęstsza przyczyna w ogóle. [Lista kwarantanny](kb:imei) zawiera IMEI urządzeń, które się połączyły, ale nie są zarejestrowane — jeśli Twoje tam jest, prawdziwy numer leży przed Tobą.',
          '**Czy jest zasilone i na zewnątrz?** Lokalizator w warsztacie może świetnie się połączyć i nie mieć pozycji do wysłania. Daj mu kilka minut z widokiem na niebo.',
          '**Czy karta SIM jest aktywna i ma dane?** Włóż ją do telefonu. Jeśli telefon nie przegląda, lokalizator też nie — zobacz [Karty SIM i APN](kb:sim-and-apn).',
          '**Czy ustawiony jest APN?** Zasięg to nie dane. To druga co do częstości przyczyna i wygląda dokładnie jak martwe urządzenie.',
          '**Czy wiadomość konfiguracyjna została naprawdę zrozumiana?** Doręczona to nie to samo co odczytana. Wiodące spacje mają znaczenie, a aplikacje SMS je psują — zobacz [SMS konfiguracyjny wyjaśniony](kb:config-sms).',
          '**Czy celuje we właściwy serwer?** Porównaj serwer i port z własnym panelem podłączania, a nie z instrukcją — zobacz [Podłączanie lokalizatora](kb:connect-a-tracker).',
        ] },
        { h2: 'B — działało, potem przestało', id: 'stopped' },
        { ol: [
          '**Kiedy dokładnie przestało?** Czas ostatniego kontaktu to najbardziej informatywne pole na ekranie. Zestaw go z czymś: wizytą serwisową, przekroczeniem granicy, zmianą ustawień, końcem okresu rozliczeniowego.',
          '**Czy przestało na granicy?** Większość lokalizatorów ma osobny profil roamingowy fabrycznie ustawiony tak, by nie nadawać — zobacz [Częstotliwość raportowania](kb:reporting-intervals).',
          '**Czy tego samego dnia zamilkło kilka pojazdów?** To nie sprzęt. To pakiet danych, blokada operatora albo subskrypcja — zobacz [Co się dzieje przy braku płatności](kb:unpaid-what-happens).',
          '**Czy tuż przed tym zastosowano zmianę ustawień?** Okres wysyłki zero znaczy „nie nadawaj". Błąd w jednym polu o całkowitym skutku.',
          '**Czy pojazd był w warsztacie?** Odłączenie akumulatora, wymiana bezpiecznika albo zdjęcie osłony to bardzo częsty sposób, w jaki lokalizator zostaje bez zasilania.',
          '**Czy stoi pod ziemią?** Brak zasięgu to nie usterka. Zapisy są gromadzone i dotrą, gdy pojazd wyjedzie.',
        ] },
        { h2: 'Co sprawdzić w samym urządzeniu', id: 'device' },
        { p: 'Jeśli urządzenie w ogóle jest jeszcze osiągalne, zapytaj je wprost: komenda **Informacje** zwraca stan sieci, a **Fix GPS** bieżącą pozycję i liczbę satelitów. Urządzenie, które odpowiada na komendy, ale nie wysyła pozycji, ma problem z GPS; to, które nie odpowiada na nic — z zasilaniem albo siecią. Zobacz [Wysyłanie komend](kb:commands).' },
        { h2: 'Żeby to przestało być niespodzianką', id: 'prevent' },
        { callout: 'tip', p: 'Utwórz jedną regułę **Brak kontaktu** dla całego konta. To jedyny sposób dowiedzieć się o martwym lokalizatorze bez zauważania nieobecności — a w zauważaniu nieobecności ludzie są niezawodnie słabi. Zobacz [Wszystkie rodzaje zdarzeń](kb:event-types).' },
      ],
    },
    de: {
      title: 'Ein Gerät meldet sich nicht',
      summary: 'Ein Entscheidungsbaum, geordnet danach, wie oft sich die jeweilige Ursache als die echte erweist — oben anfangen und aufhören, wenn es läuft.',
      keywords: ['meldet nicht', 'offline', 'nie gemeldet', 'stumm', 'keine daten', 'fehlersuche', 'kein kontakt'],
      blocks: [
        { p: 'Arbeiten Sie die Liste ab. Sie ist danach sortiert, wie oft die jeweilige Ursache die Antwort ist, und jeder Schritt ist billig genug, ihn einfach zu tun statt darüber nachzudenken.' },
        { h2: 'Zuerst: welches der zwei Probleme?', id: 'which' },
        { table: { head: ['Zustand', 'Bedeutung', 'Weiter zu'], rows: [
          ['**Nie gemeldet**', 'Es hat nie etwas gesendet. Der Einbau ist nicht fertig.', 'Abschnitt A'],
          ['**Kein Kontakt** (lief vorher)', 'Es lief und hat aufgehört.', 'Abschnitt B'],
        ] } },
        { h2: 'A — es hat nie gemeldet', id: 'never' },
        { ol: [
          '**IMEI Ziffer für Ziffer prüfen.** Ein einziges falsches Zeichen ist die häufigste Ursache überhaupt. Die [Quarantäneliste](kb:imei) enthält die IMEIs von Geräten, die sich verbunden haben und nicht registriert sind — steht Ihre darin, liegt die echte Nummer vor Ihnen.',
          '**Hat es Strom und ist es draußen?** Ein Tracker in der Werkstatt kann sich einwandfrei verbinden und keine Position zu senden haben. Geben Sie ihm ein paar Minuten mit Himmelssicht.',
          '**Ist die SIM aktiviert und hat sie Daten?** Stecken Sie sie in ein Telefon. Surft das Telefon nicht, tut es der Tracker auch nicht — siehe [SIM-Karten und APN](kb:sim-and-apn).',
          '**Ist der APN gesetzt?** Empfang ist keine Datenverbindung. Das ist die zweithäufigste Ursache und sieht genau wie ein totes Gerät aus.',
          '**Wurde die Konfigurationsnachricht wirklich verstanden?** Zugestellt ist nicht gelesen. Die führenden Leerzeichen zählen, und Messaging-Apps beschädigen sie — siehe [Die Konfigurations-SMS erklärt](kb:config-sms).',
          '**Zeigt es auf den richtigen Server?** Vergleichen Sie Server und Port mit Ihrem eigenen Einrichtungspanel, nicht mit einem Handbuch — siehe [Tracker anschließen](kb:connect-a-tracker).',
        ] },
        { h2: 'B — es lief und hörte auf', id: 'stopped' },
        { ol: [
          '**Wann genau hörte es auf?** Die Zeit des letzten Kontakts ist das aussagekräftigste Feld auf dem Bildschirm. Gleichen Sie sie mit etwas ab: einem Werkstattbesuch, einem Grenzübertritt, einer Einstellungsänderung, dem Ende eines Abrechnungsmonats.',
          '**Hörte es an einer Grenze auf?** Die meisten Tracker führen ein eigenes Roaming-Profil, das ab Werk auf „nicht senden" steht — siehe [Sendeintervalle](kb:reporting-intervals).',
          '**Sind am selben Tag mehrere Fahrzeuge verstummt?** Das ist keine Hardware. Das ist ein Datenvolumen, eine Sperre des SIM-Anbieters oder ein Abo — siehe [Was bei einer unbezahlten Rechnung passiert](kb:unpaid-what-happens).',
          '**Wurde kurz davor eine Einstellungsänderung angewandt?** Ein Sendeintervall von null heißt: nicht senden. Ein Ein-Feld-Fehler mit vollständiger Wirkung.',
          '**War das Fahrzeug in der Werkstatt?** Batterie abklemmen, Sicherung tauschen oder eine Verkleidung abnehmen ist ein sehr häufiger Weg, wie ein Tracker stromlos endet.',
          '**Steht es unter der Erde?** Kein Signal ist kein Defekt. Die Datensätze werden gesammelt und kommen an, wenn das Fahrzeug herauskommt.',
        ] },
        { h2: 'Was am Gerät selbst zu prüfen ist', id: 'device' },
        { p: 'Ist das Gerät überhaupt noch erreichbar, fragen Sie es direkt: der Befehl **Info** liefert seinen Netzzustand, der Befehl **GPS-Fix** die aktuelle Position und die Satellitenzahl. Ein Gerät, das auf Befehle antwortet, aber keine Positionen sendet, hat ein GPS-Problem; eines, das auf nichts antwortet, ein Strom- oder Netzproblem. Siehe [Befehle senden](kb:commands).' },
        { h2: 'Damit das keine Überraschung mehr ist', id: 'prevent' },
        { callout: 'tip', p: 'Legen Sie eine Regel **Kein Kontakt** für das ganze Konto an. Nur so erfahren Sie von einem toten Tracker, ohne eine Abwesenheit zu bemerken — und Abwesenheiten zu bemerken können Menschen verlässlich schlecht. Siehe [Alle Ereignistypen](kb:event-types).' },
      ],
    },
  },
}
