import type { KbArticle } from '../types.js'

export const deviceLifecycle: KbArticle = {
  slug: 'device-lifecycle',
  category: 'devices',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'Retiring, moving and erasing a device',
      summary: 'What to do when a tracker changes vehicle, leaves the fleet, or has to be wiped — and what each action is irreversible about.',
      keywords: ['retire', 'remove', 'delete', 'transfer', 'replace', 'erase', 'gdpr', 'sold vehicle', 'decommission'],
      blocks: [
        { p: 'Trackers move between vehicles, vehicles get sold, and customers leave. Three different actions cover it, and they are not interchangeable.' },
        { h2: 'Moving a tracker to another vehicle', id: 'move' },
        { p: 'The tracker keeps its identity, so you do not create anything new — you edit the existing device: rename it, change the plate, update the vehicle card. Its history stays attached to the device, which is correct, because that history is where the tracker was, not where the vehicle was.' },
        { callout: 'note', p: 'If the two vehicles must have separate histories, retire the old device and add a new one instead. You cannot have both: one physical tracker is one device record.' },
        { h2: 'Retiring a device', id: 'retire' },
        { p: 'Retiring is the normal way to take a tracker out of service. From that moment ingest refuses that IMEI — a tracker still sitting in a sold vehicle stops being able to report to you, which is exactly what you want on the day the vehicle leaves.' },
        { ul: [
          'The history stays and remains readable in trips, reports and playback.',
          'The device stops counting toward your plan\'s device limit.',
          'The IMEI stays claimed by your organisation, so it cannot be added elsewhere while retired.',
        ] },
        { h2: 'Erasing a device\'s data', id: 'erase' },
        { p: 'Erasing is the permanent removal of everything the device ever produced: positions, trips, events and command history. It exists because a data-protection request may demand it, and because a customer who leaves is entitled to have their data gone.' },
        { callout: 'warning', p: 'An erase cannot be undone and nothing is kept back for support purposes. A device has to be retired for a while before it can be erased — that delay is deliberate, and it is the only chance to change your mind.' },
        { h2: 'Handing a tracker to someone else', id: 'transfer' },
        { p: 'An IMEI can only be registered in one account at a time, anywhere on the platform. Before the new owner can add it, it has to be released from yours — retiring is usually not enough, because a retired device still holds its claim. If a buyer reports "that IMEI is already registered", this is why.' },
        { h2: 'What happens to a device you simply stop using', id: 'idle' },
        { p: 'Nothing automatic. It keeps its slot in your plan and shows as having had no contact for a growing length of time. Retire it — a fleet list full of vehicles that left two years ago is how a real problem gets missed among the noise.' },
      ],
    },
    lt: {
      title: 'Įrenginio nurašymas, perkėlimas ir duomenų ištrynimas',
      summary: 'Ką daryti, kai seklys keičia automobilį, palieka parką arba turi būti išvalytas – ir kas kiekviename veiksme yra negrįžtama.',
      keywords: ['nurašyti', 'pašalinti', 'ištrinti', 'perkelti', 'pakeisti', 'gdpr', 'parduotas automobilis'],
      blocks: [
        { p: 'Sekliai keliauja tarp automobilių, automobiliai parduodami, klientai išeina. Tam yra trys skirtingi veiksmai, ir jie nėra tarpusavyje pakeičiami.' },
        { h2: 'Seklio perkėlimas į kitą automobilį', id: 'move' },
        { p: 'Seklys išlaiko savo tapatybę, tad nieko naujo nekuriate – redaguojate esamą įrenginį: pervadinate, pakeičiate valstybinį numerį, atnaujinate automobilio kortelę. Istorija lieka prie įrenginio, ir tai teisinga, nes ta istorija rodo, kur buvo seklys, o ne kur buvo automobilis.' },
        { callout: 'note', p: 'Jei dviejų automobilių istorijos turi būti atskiros, senąjį įrenginį nurašykite ir vietoj jo pridėkite naują. Abiejų iš karto turėti negalima: vienas fizinis seklys – vienas įrenginio įrašas.' },
        { h2: 'Įrenginio nurašymas', id: 'retire' },
        { p: 'Nurašymas – įprastas būdas išimti seklį iš eksploatacijos. Nuo tos akimirkos duomenų priėmimas to IMEI nebepriima – parduotame automobilyje likęs seklys nebegali jums siųsti duomenų, o būtent to ir norite tą dieną, kai automobilis išvažiuoja.' },
        { ul: [
          'Istorija lieka ir toliau skaitoma kelionėse, ataskaitose ir peržaidime.',
          'Įrenginys nustoja skaičiuotis į jūsų plano įrenginių limitą.',
          'IMEI lieka rezervuotas jūsų organizacijai, tad nurašytas jis negali būti pridėtas kitur.',
        ] },
        { h2: 'Įrenginio duomenų ištrynimas', id: 'erase' },
        { p: 'Ištrynimas – negrįžtamas viso, ką įrenginys kada nors sukūrė, pašalinimas: pozicijų, kelionių, įvykių ir komandų istorijos. Jis egzistuoja todėl, kad to gali pareikalauti duomenų apsaugos prašymas ir kad išeinantis klientas turi teisę, jog jo duomenų nebeliktų.' },
        { callout: 'warning', p: 'Ištrynimo atšaukti neįmanoma ir nieko nepasiliekama „palaikymo tikslais". Prieš ištrinant įrenginys kurį laiką turi būti nurašytas – ta pauzė yra sąmoninga ir tai vienintelė proga apsigalvoti.' },
        { h2: 'Seklio perdavimas kitam', id: 'transfer' },
        { p: 'Vienu metu IMEI gali būti užregistruotas tik vienoje paskyroje – bet kur platformoje. Kad naujasis savininkas galėtų jį pridėti, jis turi būti atlaisvintas iš jūsų; nurašymo dažniausiai neužtenka, nes nurašytas įrenginys rezervaciją tebeturi. Jei pirkėjas praneša „toks IMEI jau užregistruotas" – priežastis būtent ši.' },
        { h2: 'Kas nutinka įrenginiui, kurio tiesiog nustojote naudoti', id: 'idle' },
        { p: 'Automatiškai – nieko. Jis toliau užima vietą jūsų plane ir rodomas kaip vis ilgiau neturintis ryšio. Nurašykite jį – autoparko sąrašas, pilnas prieš dvejus metus išvažiavusių automobilių, yra kaip tik tai, kas leidžia tikrai problemai pasislėpti triukšme.' },
      ],
    },
    pl: {
      title: 'Wycofywanie, przenoszenie i kasowanie urządzenia',
      summary: 'Co zrobić, gdy lokalizator zmienia pojazd, opuszcza flotę albo musi zostać wyczyszczony — i co w każdej akcji jest nieodwracalne.',
      keywords: ['wycofanie', 'usunięcie', 'kasowanie', 'przeniesienie', 'wymiana', 'rodo', 'sprzedany pojazd'],
      blocks: [
        { p: 'Lokalizatory wędrują między pojazdami, pojazdy się sprzedaje, klienci odchodzą. Obsługują to trzy różne akcje i nie są wymienne.' },
        { h2: 'Przeniesienie lokalizatora do innego pojazdu', id: 'move' },
        { p: 'Lokalizator zachowuje tożsamość, więc nie tworzysz nic nowego — edytujesz istniejące urządzenie: zmieniasz nazwę, tablicę, kartę pojazdu. Historia zostaje przy urządzeniu, i słusznie, bo ta historia mówi, gdzie był lokalizator, a nie gdzie był pojazd.' },
        { callout: 'note', p: 'Jeśli oba pojazdy muszą mieć osobne historie, wycofaj stare urządzenie i dodaj nowe. Nie da się mieć obu naraz: jeden fizyczny lokalizator to jeden wpis urządzenia.' },
        { h2: 'Wycofanie urządzenia', id: 'retire' },
        { p: 'Wycofanie to normalny sposób wyjęcia lokalizatora z eksploatacji. Od tej chwili przyjmowanie danych odrzuca ten IMEI — lokalizator wciąż siedzący w sprzedanym pojeździe przestaje móc do Ciebie raportować, a właśnie tego chcesz w dniu, w którym pojazd odjeżdża.' },
        { ul: [
          'Historia zostaje i nadal jest czytelna w trasach, raportach i odtwarzaniu.',
          'Urządzenie przestaje liczyć się do limitu urządzeń w planie.',
          'IMEI pozostaje zajęty przez Twoją organizację, więc wycofany nie może zostać dodany gdzie indziej.',
        ] },
        { h2: 'Kasowanie danych urządzenia', id: 'erase' },
        { p: 'Kasowanie to trwałe usunięcie wszystkiego, co urządzenie kiedykolwiek wytworzyło: pozycji, tras, zdarzeń i historii komend. Istnieje, bo może tego zażądać wniosek z zakresu ochrony danych i bo odchodzący klient ma prawo, by jego danych już nie było.' },
        { callout: 'warning', p: 'Kasowania nie da się cofnąć i nic nie zostaje zachowane „na potrzeby wsparcia". Przed skasowaniem urządzenie musi przez pewien czas być wycofane — ta zwłoka jest celowa i to jedyna szansa, by zmienić zdanie.' },
        { h2: 'Przekazanie lokalizatora komuś innemu', id: 'transfer' },
        { p: 'IMEI może być zarejestrowany tylko w jednym koncie naraz, gdziekolwiek na platformie. Zanim nowy właściciel go doda, musi zostać zwolniony u Ciebie — samo wycofanie zwykle nie wystarczy, bo wycofane urządzenie wciąż trzyma rezerwację. Jeśli kupujący zgłasza „ten IMEI jest już zarejestrowany", to właśnie dlatego.' },
        { h2: 'Co dzieje się z urządzeniem, którego po prostu przestałeś używać', id: 'idle' },
        { p: 'Automatycznie nic. Nadal zajmuje miejsce w planie i pokazuje coraz dłuższy brak kontaktu. Wycofaj je — lista floty pełna pojazdów, które odeszły dwa lata temu, to dokładnie to, przez co prawdziwy problem ginie w szumie.' },
      ],
    },
    de: {
      title: 'Gerät stilllegen, umsetzen und löschen',
      summary: 'Was zu tun ist, wenn ein Tracker das Fahrzeug wechselt, die Flotte verlässt oder gelöscht werden muss — und was an jeder Aktion unumkehrbar ist.',
      keywords: ['stilllegen', 'entfernen', 'löschen', 'übertragen', 'ersetzen', 'dsgvo', 'verkauftes fahrzeug'],
      blocks: [
        { p: 'Tracker wandern zwischen Fahrzeugen, Fahrzeuge werden verkauft, Kunden gehen. Drei verschiedene Aktionen decken das ab, und sie sind nicht austauschbar.' },
        { h2: 'Einen Tracker in ein anderes Fahrzeug umsetzen', id: 'move' },
        { p: 'Der Tracker behält seine Identität, Sie legen also nichts Neues an — Sie bearbeiten das bestehende Gerät: umbenennen, Kennzeichen ändern, Fahrzeugkarte aktualisieren. Die Historie bleibt am Gerät, und das ist richtig: diese Historie sagt, wo der Tracker war, nicht wo das Fahrzeug war.' },
        { callout: 'note', p: 'Sollen die beiden Fahrzeuge getrennte Historien haben, legen Sie stattdessen das alte Gerät still und fügen ein neues hinzu. Beides gleichzeitig geht nicht: ein physischer Tracker ist ein Gerätedatensatz.' },
        { h2: 'Ein Gerät stilllegen', id: 'retire' },
        { p: 'Stilllegen ist der normale Weg, einen Tracker außer Dienst zu nehmen. Ab diesem Moment weist die Datenannahme diese IMEI ab — ein Tracker, der noch im verkauften Fahrzeug steckt, kann Ihnen nicht mehr melden, und genau das wollen Sie an dem Tag, an dem das Fahrzeug geht.' },
        { ul: [
          'Die Historie bleibt und ist in Fahrten, Berichten und Replay weiter lesbar.',
          'Das Gerät zählt nicht mehr gegen das Gerätelimit Ihres Tarifs.',
          'Die IMEI bleibt Ihrer Organisation zugeordnet und kann im stillgelegten Zustand nirgends sonst hinzugefügt werden.',
        ] },
        { h2: 'Die Daten eines Geräts löschen', id: 'erase' },
        { p: 'Löschen ist die endgültige Entfernung von allem, was das Gerät je erzeugt hat: Positionen, Fahrten, Ereignisse und Befehlshistorie. Es existiert, weil eine Datenschutzanfrage es verlangen kann und weil ein scheidender Kunde ein Recht darauf hat, dass seine Daten weg sind.' },
        { callout: 'warning', p: 'Ein Löschvorgang ist nicht rückgängig zu machen, und es wird nichts „für den Support" zurückbehalten. Ein Gerät muss eine Weile stillgelegt sein, bevor es gelöscht werden kann — diese Verzögerung ist Absicht und die einzige Gelegenheit, es sich anders zu überlegen.' },
        { h2: 'Einen Tracker an jemand anderen weitergeben', id: 'transfer' },
        { p: 'Eine IMEI kann zu einem Zeitpunkt nur in einem Konto registriert sein, irgendwo auf der Plattform. Bevor der neue Besitzer sie hinzufügen kann, muss sie bei Ihnen freigegeben werden — Stilllegen genügt meist nicht, denn ein stillgelegtes Gerät hält seinen Anspruch weiter. Meldet ein Käufer „diese IMEI ist bereits registriert", ist das der Grund.' },
        { h2: 'Was mit einem Gerät passiert, das Sie einfach nicht mehr nutzen', id: 'idle' },
        { p: 'Automatisch nichts. Es belegt weiter seinen Platz im Tarif und zeigt einen immer länger werdenden Kontaktausfall. Legen Sie es still — eine Flottenliste voller Fahrzeuge, die vor zwei Jahren gegangen sind, ist genau der Lärm, in dem ein echtes Problem untergeht.' },
      ],
    },
  },
}
