import type { KbArticle } from '../types.js'

export const distanceAndOdometer: KbArticle = {
  slug: 'distance-and-odometer',
  category: 'trips',
  surfaces: { site: true, app: true },
  screen: '/app/trips',
  doc: {
    en: {
      title: 'Distance and the odometer',
      summary: 'Three different numbers can all be called “kilometres driven”. Which one you are looking at, and which one to bill from.',
      keywords: ['distance', 'odometer', 'mileage', 'kilometres', 'gps distance', 'discrepancy', 'billing'],
      blocks: [
        { p: 'Nothing generates more “your system is wrong” conversations than distance, and it is almost always because two people are comparing two different measurements.' },
        { h2: 'The three sources', id: 'sources' },
        { table: { head: ['Source', 'What it is', 'Behaviour'], rows: [
          ['**GPS distance**', 'The length of the line through the recorded positions.', 'Always available. Slightly under-reads on winding roads, because a curve is drawn as a series of straight segments.'],
          ['**Device odometer**', 'A running total the tracker keeps itself.', 'Steadier over long distances. Goes back to zero when the tracker is reset or replaced.'],
          ['**Vehicle odometer (CAN)**', 'The manufacturer\'s counter, read from the vehicle bus.', 'The number a service book and a lease contract care about. Needs CAN — see [CAN and OBD data](kb:can-and-obd).'],
        ] } },
        { h2: 'Which one a trip uses', id: 'choice' },
        { p: 'Each trip records not only its distance but where that distance came from, and the trip list shows it. On the automatic setting, the device\'s own odometer is preferred where it is present and plausible, with GPS distance as the fallback. You can pin a device to one source when you know its behaviour and want consistency above all.' },
        { callout: 'note', p: 'An odometer reading that moves backwards, or jumps by an implausible amount, is rejected rather than believed. A tracker replaced mid-month would otherwise wipe out or invent a month of mileage in one record.' },
        { h2: 'Why it will never match the vehicle\'s own dashboard exactly', id: 'discrepancy' },
        { ul: [
          'A vehicle\'s own odometer is calibrated from wheel rotations, and tyre wear, tyre size and pressure all change the result. By law it is allowed to over-read but not to under-read.',
          'GPS distance measures the ground path between sampled points; a tighter recording interval gets closer to the truth and never quite reaches it.',
          'Positions we refuse to trust are excluded from distance entirely — see [Position accuracy](kb:position-accuracy).',
          'Movement below the noise threshold is not counted, so a day of shuffling around the yard adds nothing.',
        ] },
        { p: 'A difference of a couple of percent between GPS distance and the vehicle\'s own dashboard is normal and expected. A difference in the tens of percent is worth investigating — usually poor coverage on a route, or a very long recording interval.' },
        { h2: 'Which to use for billing or reimbursement', id: 'billing' },
        { p: 'Pick one source and keep it. Consistency matters more than which number is “right”: a customer invoiced from GPS distance every month has a comparable series, while a customer invoiced from whichever source happened to be available has an argument every month. Where a contract refers to the vehicle\'s own odometer, use CAN mileage — and whichever source you pick, name it in the contract.' },
      ],
    },
    lt: {
      title: 'Atstumas ir odometras',
      summary: 'Trys skirtingi skaičiai gali būti vadinami „nuvažiuotais kilometrais“. Į kurį žiūrite ir pagal kurį išrašyti sąskaitą.',
      keywords: ['atstumas', 'odometras', 'rida', 'kilometrai', 'gps atstumas', 'neatitikimas', 'sąskaita'],
      blocks: [
        { p: 'Niekas nesukelia tiek pokalbių apie tai, kad „jūsų sistema klysta“, kiek atstumas, ir beveik visada todėl, kad du žmonės lygina du skirtingus matavimus.' },
        { h2: 'Trys šaltiniai', id: 'sources' },
        { table: { head: ['Šaltinis', 'Kas tai', 'Elgsena'], rows: [
          ['**GPS atstumas**', 'Linijos, einančios per įrašytas pozicijas, ilgis.', 'Visada prieinamas. Vingiuotuose keliuose šiek tiek per mažas, nes kreivė braižoma kaip tiesių atkarpų virtinė.'],
          ['**Įrenginio odometras**', 'Bendra suma, kurią sekiklis skaičiuoja pats.', 'Stabilesnis ilgais atstumais. Perkrovus ar pakeitus sekiklį, pradedamas skaičiuoti iš naujo.'],
          ['**Automobilio odometras (CAN)**', 'Gamintojo skaitiklis, nuskaitytas iš automobilio magistralės.', 'Būtent tas skaičius rūpi serviso knygelei ir lizingo sutarčiai. Reikia CAN – žr. [CAN ir OBD duomenys](kb:can-and-obd).'],
        ] } },
        { h2: 'Kurį šaltinį naudoja kelionė', id: 'choice' },
        { p: 'Kiekviena kelionė įrašo ne tik atstumą, bet ir tai, iš kur tas atstumas gautas, o kelionių sąrašas tai parodo. Palikus automatinį režimą, pirmenybė teikiama paties įrenginio odometrui, jei jis yra ir atrodo įtikinamas, o atsarginis variantas – GPS atstumas. Įrenginį galima priskirti vienam šaltiniui, kai žinote jo elgseną ir labiausiai norite nuoseklumo.' },
        { callout: 'note', p: 'Odometro rodmuo, kuris sumažėja arba šokteli neįtikėtinai, atmetamas, o ne priimamas. Kitaip viduryje mėnesio pakeistas sekiklis vienu įrašu ištrintų arba prasimanytų mėnesio ridą.' },
        { h2: 'Kodėl skaičius niekada tiksliai nesutaps su prietaisų skydeliu', id: 'discrepancy' },
        { ul: [
          'Automobilio odometras kalibruojamas pagal rato apsisukimus, o padangų nusidėvėjimas, dydis ir slėgis keičia rezultatą. Teisiškai jam leidžiama rodyti daugiau ir neleidžiama mažiau.',
          'GPS atstumas matuoja kelią tarp užfiksuotų taškų; trumpesnis įrašymo intervalas priartėja prie tiesos, bet jos taip ir nepasiekia.',
          'Pozicijos, kuriomis atsisakome tikėti, į atstumą visai neįskaitomos – žr. [Pozicijos tikslumas](kb:position-accuracy).',
          'Judėjimas žemiau triukšmo ribos neskaičiuojamas, tad diena, praleista manevruojant kieme, nieko neprideda.',
        ] },
        { p: 'Poros procentų skirtumas tarp GPS atstumo ir prietaisų skydelio yra normalus ir laukiamas. Dešimčių procentų skirtumas – signalas, kurį verta tirti; dažniausiai tai prasta aprėptis maršrute arba labai ilgas įrašymo intervalas.' },
        { h2: 'Kurį naudoti sąskaitoms ar kompensacijoms', id: 'billing' },
        { p: 'Pasirinkite vieną šaltinį ir jo laikykitės. Nuoseklumas svarbiau nei tai, kuris skaičius „teisingas“: klientas, kuriam kas mėnesį sąskaita rašoma pagal GPS atstumą, turi palyginamą duomenų seką, o klientas, kuriam sąskaita rašoma pagal tai, kas tuo metu buvo prieinama, kas mėnesį ginčijasi. Jei sutartyje nurodytas paties automobilio odometras, naudokite CAN ridą ir tai joje parašykite.' },
      ],
    },
    pl: {
      title: 'Dystans a licznik',
      summary: 'Trzy różne liczby mogą nazywać się „przejechane kilometry”. Na którą patrzysz i z której fakturować.',
      keywords: ['dystans', 'licznik', 'przebieg', 'kilometry', 'dystans gps', 'rozbieżność', 'fakturowanie'],
      blocks: [
        { p: 'Nic nie generuje tylu rozmów „wasz system się myli” co dystans, i prawie zawsze dlatego, że dwie osoby porównują dwa różne pomiary.' },
        { h2: 'Trzy źródła', id: 'sources' },
        { table: { head: ['Źródło', 'Co to jest', 'Zachowanie'], rows: [
          ['**Dystans GPS**', 'Długość linii przechodzącej przez zapisane pozycje.', 'Zawsze dostępny. Na krętych drogach lekko zaniża, bo łuk rysowany jest jako ciąg prostych odcinków.'],
          ['**Licznik urządzenia**', 'Suma bieżąca prowadzona przez sam lokalizator.', 'Stabilniejszy na długich dystansach. Zeruje się przy resecie lub wymianie lokalizatora.'],
          ['**Licznik pojazdu (CAN)**', 'Licznik producenta, odczytany z magistrali pojazdu.', 'Liczba, która liczy się w książce serwisowej i w umowie leasingowej. Wymaga CAN — zobacz [Dane CAN i OBD](kb:can-and-obd).'],
        ] } },
        { h2: 'Które źródło trafia do trasy', id: 'choice' },
        { p: 'Każda trasa zapisuje nie tylko dystans, ale i to, skąd ten dystans pochodzi, a lista tras to pokazuje. W trybie automatycznym pierwszeństwo ma własny licznik urządzenia, jeśli jest obecny i wiarygodny, a dystans GPS służy jako rozwiązanie zapasowe. Urządzenie można na stałe ustawić na jedno źródło, gdy znasz jego zachowanie i najbardziej zależy Ci na spójności.' },
        { callout: 'note', p: 'Odczyt licznika cofający się albo skaczący o nieprawdopodobną wartość jest odrzucany, a nie przyjmowany. Inaczej lokalizator wymieniony w połowie miesiąca jednym rekordem wymazałby albo wymyśliłby miesięczny przebieg.' },
        { h2: 'Dlaczego nigdy nie zgodzi się dokładnie z deską rozdzielczą', id: 'discrepancy' },
        { ul: [
          'Licznik pojazdu jest kalibrowany na podstawie obrotów koła, a zużycie, rozmiar i ciśnienie opon zmieniają wynik. Prawnie wolno mu zawyżać, a nie wolno zaniżać.',
          'Dystans GPS mierzy drogę między zarejestrowanymi punktami; gęstszy zapis zbliża się do prawdy i nigdy jej całkiem nie osiąga.',
          'Pozycje, którym odmawiamy zaufania, są całkowicie wyłączone z dystansu — zobacz [Dokładność pozycji](kb:position-accuracy).',
          'Ruch poniżej progu szumu nie jest liczony, więc dzień manewrowania po placu nie dodaje nic.',
        ] },
        { p: 'Różnica rzędu kilku procent między dystansem GPS a wskazaniem deski rozdzielczej jest normalna i oczekiwana. Różnica rzędu dziesiątek procent to sygnał wart zbadania — zwykle słaby zasięg na trasie albo bardzo rzadki zapis.' },
        { h2: 'Którego użyć do fakturowania lub rozliczeń', id: 'billing' },
        { p: 'Wybierz jedno źródło i trzymaj się go. Spójność liczy się bardziej niż to, która liczba jest „prawidłowa”: klient fakturowany co miesiąc z dystansu GPS ma porównywalne dane z miesiąca na miesiąc, a klient fakturowany z tego, co akurat było dostępne, ma co miesiąc spór. Gdy umowa odwołuje się do licznika pojazdu, użyj przebiegu z CAN i zapisz to w umowie.' },
      ],
    },
    de: {
      title: 'Strecke und Kilometerstand',
      summary: 'Drei verschiedene Zahlen können „gefahrene Kilometer“ heißen. Welche Sie ansehen — und aus welcher Sie abrechnen.',
      keywords: ['strecke', 'kilometerstand', 'laufleistung', 'gps-strecke', 'abweichung', 'abrechnung'],
      blocks: [
        { p: 'Nichts erzeugt so viele „Ihr System rechnet falsch“-Gespräche wie die Strecke — und fast immer, weil zwei Personen zwei verschiedene Messungen vergleichen.' },
        { h2: 'Die drei Quellen', id: 'sources' },
        { table: { head: ['Quelle', 'Was sie ist', 'Verhalten'], rows: [
          ['**GPS-Strecke**', 'Die Länge der Linie durch die aufgezeichneten Positionen.', 'Immer verfügbar. Auf kurvigen Straßen leicht zu niedrig, weil eine Kurve als Folge gerader Abschnitte gezeichnet wird.'],
          ['**Geräte-Kilometerzähler**', 'Ein laufender Zähler, den der Tracker selbst führt.', 'Über lange Strecken stabiler. Beginnt nach einem Reset oder Tausch des Trackers wieder bei null.'],
          ['**Fahrzeug-Kilometerstand (CAN)**', 'Der Herstellerzähler, vom Fahrzeugbus gelesen.', 'Die Zahl, auf die Serviceheft und Leasingvertrag schauen. Braucht CAN — siehe [CAN- und OBD-Daten](kb:can-and-obd).'],
        ] } },
        { h2: 'Welche eine Fahrt verwendet', id: 'choice' },
        { p: 'Jede Fahrt hält nicht nur ihre Strecke fest, sondern auch deren Herkunft, und die Fahrtenliste zeigt sie. In der Automatik wird der geräteeigene Zähler bevorzugt, sofern vorhanden und plausibel, mit der GPS-Strecke als Rückfallebene. Ein Gerät lässt sich fest auf eine Quelle legen, wenn Sie sein Verhalten kennen und Konsistenz über alles stellen.' },
        { callout: 'note', p: 'Ein Zählerstand, der rückwärts läuft oder unplausibel springt, wird verworfen statt geglaubt. Sonst würde ein mitten im Monat getauschter Tracker mit einem Datensatz einen Monat Laufleistung auslöschen oder erfinden.' },
        { h2: 'Warum es nie exakt zum Tacho passt', id: 'discrepancy' },
        { ul: [
          'Der Fahrzeugzähler ist über Radumdrehungen kalibriert; Reifenverschleiß, -größe und -druck ändern das Ergebnis. Rechtlich darf er zu viel und nie zu wenig anzeigen.',
          'Die GPS-Strecke misst den Weg zwischen abgetasteten Punkten; ein engeres Aufzeichnungsintervall kommt der Wahrheit näher und erreicht sie nie ganz.',
          'Positionen, denen wir nicht trauen, fließen gar nicht in die Strecke ein — siehe [Positionsgenauigkeit](kb:position-accuracy).',
          'Bewegung unterhalb der Rauschschwelle wird nicht gezählt, ein Tag Rangieren trägt also nichts bei.',
        ] },
        { p: 'Ein Unterschied von ein paar Prozent zwischen GPS-Strecke und Tacho ist normal und zu erwarten. Ein Unterschied im Bereich von zehn Prozent und mehr ist ein Signal — meist schlechte Netzabdeckung auf einer Route oder ein sehr langes Aufzeichnungsintervall.' },
        { h2: 'Woraus abgerechnet oder erstattet wird', id: 'billing' },
        { p: 'Wählen Sie eine Quelle und bleiben Sie dabei. Konsistenz zählt mehr als die Frage, welche Zahl „stimmt“: Ein Kunde, der jeden Monat nach der GPS-Strecke abgerechnet wird, hat eine vergleichbare Reihe; ein Kunde, der aus der jeweils verfügbaren Quelle abgerechnet wird, hat jeden Monat eine Diskussion. Verweist ein Vertrag auf den Fahrzeug-Kilometerstand, nutzen Sie die CAN-Laufleistung und schreiben Sie das in den Vertrag.' },
      ],
    },
  },
}
