import type { KbArticle } from '../types.js'

export const drivers: KbArticle = {
  slug: 'drivers',
  category: 'fleet',
  surfaces: { site: true, app: true },
  screen: '/app/drivers',
  doc: {
    en: {
      title: 'Drivers and who was behind the wheel',
      summary: 'The driver roster, identifying drivers with an iButton or RFID card, and assigning a driver to a trip after the fact.',
      keywords: ['driver', 'ibutton', 'rfid', 'identification', 'assignment', 'roster', 'licence', 'shared vehicle'],
      blocks: [
        { p: 'A tracker knows which vehicle moved. Knowing **who** moved it is a separate problem, and it is the one that matters when a vehicle is shared between people.' },
        { h2: 'The roster', id: 'roster' },
        { p: 'Each driver is a record: name, licence number, phone, an active or inactive flag, and — where the vehicles have a reader — an iButton or RFID identifier. Keeping former drivers as **inactive** rather than deleting them preserves the history of who drove what, which is the reason to have a roster at all.' },
        { h2: 'Automatic identification', id: 'ibutton' },
        { p: 'Where a vehicle has a reader wired to the tracker, the driver touches their key fob or card and the tracker reports the identifier with the positions. Match that identifier to a driver record once, and from then on every trip in that vehicle names its driver by itself.' },
        { ul: [
          'The identifier is 8 to 32 hexadecimal characters — copy it from the fob or read it from the vehicle panel.',
          'One identifier belongs to one driver. Assigning a fob that is already registered is refused rather than silently moved, because two drivers sharing an identity makes every trip record ambiguous.',
        ] },
        { callout: 'tip', p: 'Where identification matters — shared pool cars, tachograph-adjacent work, per-driver reporting — a reader is worth more than any software feature. Without it, driver data is only as good as somebody\'s memory a week later.' },
        { h2: 'Assigning by hand', id: 'manual' },
        { p: 'Without a reader, a trip can be assigned to a driver from the trip list. It is honest work rather than automatic truth, so do it while the day is fresh; a week later nobody remembers who took the van at eleven.' },
        { h2: 'What driver data unlocks', id: 'uses' },
        { ul: [
          'Trips filtered by driver, so a route dispute has an answer.',
          'Per-driver behaviour patterns: speeding, idling, hours out.',
          'A defensible answer to "who was driving" for an insurance claim or a parking fine.',
        ] },
        { h2: 'Tell your drivers', id: 'privacy' },
        { p: 'Recording who drove is processing personal data about an identified person, and it is subject to rules — informing them in advance is not optional, and a private-use policy has to be written down. See [Tracking employees lawfully](kb:tracking-employees-lawfully) before you switch identification on.' },
      ],
    },
    lt: {
      title: 'Vairuotojai ir kas sėdėjo prie vairo',
      summary: 'Vairuotojų sąrašas, atpažinimas iButton ar RFID kortele ir vairuotojo priskyrimas kelionei atgaline data.',
      keywords: ['vairuotojas', 'ibutton', 'rfid', 'atpažinimas', 'priskyrimas', 'sąrašas', 'pažymėjimas', 'bendras automobilis'],
      blocks: [
        { p: 'Seklys žino, kuris automobilis judėjo. Žinoti, **kas** jį judino, yra atskira problema, ir kaip tik ji svarbi, kai automobiliu naudojasi keli žmonės.' },
        { h2: 'Sąrašas', id: 'roster' },
        { p: 'Kiekvienas vairuotojas – įrašas: vardas, pažymėjimo numeris, telefonas, aktyvumo žyma ir, kur automobiliai turi skaitytuvą, iButton ar RFID identifikatorius. Buvusius vairuotojus palikus **neaktyvius**, o ne ištrynus, išsaugoma istorija, kas ką vairavo, o kaip tik dėl to sąrašas ir yra.' },
        { h2: 'Automatinis atpažinimas', id: 'ibutton' },
        { p: 'Kur prie seklio prijungtas skaitytuvas, vairuotojas prideda savo raktų pakabuką ar kortelę, ir seklys kartu su pozicijomis siunčia identifikatorių. Vieną kartą susiekite tą identifikatorių su vairuotojo įrašu, ir nuo tol kiekviena kelionė tuo automobiliu vairuotoją įvardija pati.' },
        { ul: [
          'Identifikatorius – 8 iki 32 šešioliktainių simbolių; nukopijuokite nuo pakabuko arba nuskaitykite automobilio skydelyje.',
          'Vienas identifikatorius priklauso vienam vairuotojui. Priskirti jau užregistruotą pakabuką neleidžiama, o ne tyliai perkeliama, nes du vairuotojai, dalijantys vieną tapatybę, padaro dviprasmišką kiekvieną kelionės įrašą.',
        ] },
        { callout: 'tip', p: 'Kur atpažinimas svarbus – bendri automobiliai, su tachografu susijęs darbas, ataskaitos pagal vairuotoją – skaitytuvas vertingesnis už bet kurią programinę funkciją. Be jo vairuotojo duomenys tokie geri, kokia po savaitės yra kažkieno atmintis.' },
        { h2: 'Priskyrimas ranka', id: 'manual' },
        { p: 'Be skaitytuvo kelionę vairuotojui galima priskirti kelionių sąraše. Tai sąžiningas darbas, o ne automatinė tiesa, tad darykite tai, kol diena šviežia; po savaitės niekas nebeprisimena, kas vienuoliktą paėmė furgoną.' },
        { h2: 'Ką atrakina vairuotojų duomenys', id: 'uses' },
        { ul: [
          'Kelionės, filtruojamos pagal vairuotoją, kad ginčas dėl maršruto turėtų atsakymą.',
          'Elgsenos dėsningumus pagal vairuotoją: greičio viršijimus, tuščiąją eigą, valandas kelyje.',
          'Pagrįstą atsakymą į klausimą „kas vairavo" draudimo įvykiui ar baudai už stovėjimą.',
        ] },
        { h2: 'Pasakykite vairuotojams', id: 'privacy' },
        { p: 'Įrašinėti, kas vairavo, reiškia tvarkyti identifikuoto asmens duomenis, o tam taikomos taisyklės – informuoti iš anksto nėra pasirinkimas, ir asmeninio naudojimo tvarka turi būti surašyta. Prieš įjungdami atpažinimą, perskaitykite [Teisėtas darbuotojų sekimas](kb:tracking-employees-lawfully).' },
      ],
    },
    pl: {
      title: 'Kierowcy i kto siedział za kierownicą',
      summary: 'Lista kierowców, identyfikacja iButtonem lub kartą RFID i przypisanie kierowcy do trasy po fakcie.',
      keywords: ['kierowca', 'ibutton', 'rfid', 'identyfikacja', 'przypisanie', 'lista', 'prawo jazdy', 'wspólny pojazd'],
      blocks: [
        { p: 'Lokalizator wie, który pojazd jechał. Wiedzieć, **kto** nim jechał, to osobny problem — i właśnie ten ma znaczenie, gdy pojazdem jeździ kilka osób.' },
        { h2: 'Lista', id: 'roster' },
        { p: 'Każdy kierowca to rekord: imię i nazwisko, numer prawa jazdy, telefon, znacznik aktywności oraz — tam, gdzie pojazdy mają czytnik — identyfikator iButton lub RFID. Pozostawianie byłych kierowców jako **nieaktywnych** zamiast ich usuwania zachowuje historię, kto czym jeździł, a po to właśnie lista istnieje.' },
        { h2: 'Identyfikacja automatyczna', id: 'ibutton' },
        { p: 'Tam, gdzie do lokalizatora podłączono czytnik, kierowca przykłada brelok lub kartę, a lokalizator raportuje identyfikator razem z pozycjami. Powiąż ten identyfikator z rekordem kierowcy raz, a od tej pory każda trasa tym pojazdem sama nazywa swojego kierowcę.' },
        { ul: [
          'Identyfikator ma od 8 do 32 znaków szesnastkowych — skopiuj go z breloka albo odczytaj z panelu pojazdu.',
          'Jeden identyfikator należy do jednego kierowcy. Przypisanie breloka już zarejestrowanego jest odrzucane, a nie po cichu przenoszone, bo dwóch kierowców dzielących jedną tożsamość czyni każdy zapis trasy niejednoznacznym.',
        ] },
        { callout: 'tip', p: 'Tam, gdzie identyfikacja ma znaczenie — auta wspólne, praca zbliżona do tachografu, raportowanie per kierowca — czytnik jest wart więcej niż jakakolwiek funkcja programowa. Bez niego dane o kierowcy są tak dobre, jak czyjaś pamięć tydzień później.' },
        { h2: 'Przypisywanie ręczne', id: 'manual' },
        { p: 'Bez czytnika trasę można przypisać kierowcy z listy tras. To uczciwa praca, a nie automatyczna prawda, więc rób to, póki dzień jest świeży; tydzień później nikt nie pamięta, kto o jedenastej wziął busa.' },
        { h2: 'Co odblokowują dane o kierowcach', id: 'uses' },
        { ul: [
          'Trasy filtrowane po kierowcy, żeby spór o trasę miał odpowiedź.',
          'Wzorce zachowań per kierowca: przekroczenia, praca na postoju, godziny w trasie.',
          'Możliwą do obrony odpowiedź na „kto prowadził" przy szkodzie ubezpieczeniowej albo mandacie.',
        ] },
        { h2: 'Powiedz kierowcom', id: 'privacy' },
        { p: 'Zapisywanie, kto prowadził, to przetwarzanie danych osobowych zidentyfikowanej osoby i podlega przepisom — poinformowanie z wyprzedzeniem nie jest opcjonalne, a zasady użytku prywatnego trzeba spisać. Przed włączeniem identyfikacji przeczytaj [Legalne monitorowanie pracowników](kb:tracking-employees-lawfully).' },
      ],
    },
    de: {
      title: 'Fahrer — und wer am Steuer saß',
      summary: 'Der Fahrerstamm, Fahrererkennung per iButton oder RFID-Karte und das nachträgliche Zuordnen eines Fahrers zu einer Fahrt.',
      keywords: ['fahrer', 'ibutton', 'rfid', 'identifikation', 'zuordnung', 'stammdaten', 'führerschein', 'poolfahrzeug'],
      blocks: [
        { p: 'Ein Tracker weiß, welches Fahrzeug gefahren ist. Zu wissen, **wer** es gefahren hat, ist ein eigenes Problem — und genau das zählt, wenn sich mehrere ein Fahrzeug teilen.' },
        { h2: 'Der Fahrerstamm', id: 'roster' },
        { p: 'Jeder Fahrer ist ein Datensatz: Name, Führerscheinnummer, Telefon, ein Aktiv-Kennzeichen und — wo die Fahrzeuge einen Leser haben — eine iButton- oder RFID-Kennung. Ehemalige Fahrer als **inaktiv** zu führen statt sie zu löschen, bewahrt die Historie, wer was gefahren ist — und dafür gibt es den Stamm.' },
        { h2: 'Automatische Erkennung', id: 'ibutton' },
        { p: 'Wo ein Leser am Tracker hängt, hält der Fahrer seinen Chip oder seine Karte an, und der Tracker meldet die Kennung mit den Positionen. Verknüpfen Sie diese Kennung einmal mit einem Fahrerdatensatz, und ab dann benennt jede Fahrt in diesem Fahrzeug ihren Fahrer selbst.' },
        { ul: [
          'Die Kennung hat 8 bis 32 hexadezimale Zeichen — vom Chip abschreiben oder im Fahrzeugpanel auslesen.',
          'Eine Kennung gehört einem Fahrer. Einen bereits registrierten Chip zuzuweisen wird abgelehnt statt still verschoben, denn zwei Fahrer mit einer Identität machen jeden Fahrtdatensatz mehrdeutig.',
        ] },
        { callout: 'tip', p: 'Wo Erkennung zählt — Poolfahrzeuge, tachographennahe Arbeit, Auswertung je Fahrer — ist ein Leser mehr wert als jede Softwarefunktion. Ohne ihn sind Fahrerdaten so gut wie jemandes Erinnerung eine Woche später.' },
        { h2: 'Von Hand zuordnen', id: 'manual' },
        { p: 'Ohne Leser lässt sich eine Fahrt aus der Fahrtenliste einem Fahrer zuordnen. Das ist ehrliche Handarbeit, keine automatische Wahrheit — tun Sie es, solange der Tag frisch ist; eine Woche später weiß niemand mehr, wer um elf den Transporter genommen hat.' },
        { h2: 'Was Fahrerdaten möglich machen', id: 'uses' },
        { ul: [
          'Nach Fahrer gefilterte Fahrten, damit ein Streit über eine Route eine Antwort hat.',
          'Verhaltensmuster je Fahrer: zu schnell, Leerlauf, Stunden unterwegs.',
          'Eine belastbare Antwort auf „wer ist gefahren" für einen Versicherungsfall oder einen Strafzettel.',
        ] },
        { h2: 'Sagen Sie es Ihren Fahrern', id: 'privacy' },
        { p: 'Festzuhalten, wer gefahren ist, ist die Verarbeitung personenbezogener Daten einer identifizierten Person und unterliegt Regeln — vorherige Information ist nicht optional, und eine Regelung zur Privatnutzung gehört schriftlich festgehalten. Lesen Sie [Mitarbeiter rechtmäßig orten](kb:tracking-employees-lawfully), bevor Sie die Erkennung einschalten.' },
      ],
    },
  },
}
