import type { KbArticle } from '../types.js'

export const emailsToYourCustomers: KbArticle = {
  slug: 'emails-to-your-customers',
  category: 'tsp',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true, entitlement: 'whiteLabel' },
  screen: '/app/branding',
  doc: {
    en: {
      title: 'The e-mail your customers receive',
      summary: 'Which parts of a message carry your brand, how to make the sending address yours too, and how to keep messages arriving.',
      keywords: ['email', 'sender', 'from', 'reply-to', 'branding', 'deliverability', 'spf', 'dkim', 'spam'],
      blocks: [
        { p: 'Your customers get mail from this platform: account activations, password resets, alerts and scheduled reports. This is what those messages look like from their side.' },
        { h2: 'What carries your brand', id: 'branded' },
        { ul: [
          '**The sender name** — your product name, which is the line an inbox shows before the message is opened.',
          '**The reply address** — your support address. A customer who replies reaches you.',
          '**The body** — your logo, your colours, your product name in the text.',
          '**Every link** — an address on your domain, so a click never leaves your brand.',
        ] },
        { h2: 'The sending address', id: 'not-yet' },
        { p: 'Until you set this up, the underlying sending **address** is a shared one rather than an address at your domain. The display name in front of it is already yours, so an inbox shows your name — but a recipient who expands the header sees the technical address behind it.' },
        { p: 'To make that line yours as well, open **Branding → Send mail from your own address**, enter the mailbox and domain you want to send from, and publish the three DNS records shown. Verification can take up to an hour after they appear.' },
        { callout: 'note', p: 'Nothing stops while you wait. Until the records verify, messages keep going out on the shared address exactly as before — a half-finished setup never costs a customer an alert. If the panel says the feature is not available on this installation, it has not been switched on yet; nothing is wrong on your side.' },
        { p: 'If that matters for a particular customer, the practical answer is to make sure your support address is set, so that every reply and every follow-up conversation happens with you.' },
        { h2: 'Keeping mail arriving', id: 'deliverability' },
        { ul: [
          'Ask a new customer to add the sender to their address book once, at handover. It takes thirty seconds and it prevents the most common complaint you will get.',
          'Use real, monitored addresses for alerts. A shared mailbox nobody reads is worse than one named person\'s address.',
          'An address that permanently rejects mail is remembered and not mailed again — this protects delivery for every other message. If one recipient stops receiving mail, that is the first thing to check.',
        ] },
        { h2: 'The language and units they see', id: 'language' },
        { p: 'Messages use each account\'s own language, units and time zone — set per customer account, not per person, because many recipients have no login at all. Set them when you create the account; see [Time zones and units](kb:time-zones-and-units).' },
        { h2: 'Related', id: 'related' },
        { p: 'What is in the messages and who gets them: [Where alerts are delivered](kb:notification-channels). Where the sender name and support address are set: [Branding your dashboard](kb:branding).' },
      ],
    },
    lt: {
      title: 'Laiškai, kuriuos gauna jūsų klientai',
      summary: 'Kurios žinutės dalys su jūsų prekės ženklu, kaip ir siuntimo adresą padaryti savą ir kaip pasirūpinti, kad laiškai pasiektų gavėjus.',
      keywords: ['el. paštas', 'siuntėjas', 'from', 'reply-to', 'prekės ženklas', 'pristatymas', 'spf', 'dkim', 'šlamštas'],
      blocks: [
        { p: 'Jūsų klientai gauna laiškus iš šios platformos: paskyros aktyvavimus, slaptažodžio atstatymus, pranešimus ir suplanuotas ataskaitas. Štai kaip tos žinutės atrodo iš jų pusės.' },
        { h2: 'Kur matomas jūsų prekės ženklas', id: 'branded' },
        { ul: [
          '**Siuntėjo vardas** – jūsų produkto pavadinimas, ta eilutė, kurią pašto dėžutė rodo dar neatvėrus laiško.',
          '**Atsakymo adresas** – jūsų pagalbos adresas. Klientas, kuris atsako, susisiekia su jumis.',
          '**Turinys** – jūsų logotipas, spalvos, jūsų produkto pavadinimas tekste.',
          '**Kiekviena nuoroda** – vedanti į jūsų domeną, tad paspaudęs nuorodą klientas niekada neišeina iš jūsų aplinkos.',
        ] },
        { h2: 'Siuntimo adresas', id: 'not-yet' },
        { p: 'Kol to nesusitvarkėte, pats siuntimo **adresas** yra bendras, o ne adresas jūsų domene. Prieš jį rodomas vardas jau yra jūsų, tad pašto dėžutė rodo jūsų pavadinimą – bet gavėjas, išskleidęs antraštę, mato techninį adresą už jo.' },
        { p: 'Kad ir ta eilutė taptų jūsų, atverkite **Prekės ženklas → Siųskite laiškus savo adresu**, įveskite dėžutės vardą ir domeną, iš kurio norite siųsti, ir paskelbkite tris parodytus DNS įrašus. Patvirtinimas po jų paskelbimo gali užtrukti iki valandos.' },
        { callout: 'note', p: 'Kol laukiate, niekas nesustoja. Kol įrašai nepatvirtinti, žinutės toliau siunčiamos bendru adresu lygiai kaip anksčiau – nebaigtas nustatymas niekada nekainuoja klientui prarasto pranešimo. Jei skydelis sako, kad funkcija šioje sistemoje neprieinama, ji tiesiog dar neįjungta; jūsų pusėje nieko blogo nėra.' },
        { p: 'Jei konkrečiam klientui tai svarbu, praktiškas sprendimas – įsitikinti, kad nustatytas jūsų pagalbos adresas – tada kiekvienas atsakymas ir tolesnis pokalbis vyks su jumis.' },
        { h2: 'Kad laiškai pasiektų', id: 'deliverability' },
        { ul: [
          'Perduodami paskyrą, paprašykite naujo kliento vieną kartą įtraukti siuntėją į adresų knygą. Užtruks trisdešimt sekundžių, o užkirs kelią dažniausiam skundui, kurį gausite.',
          'Pranešimams naudokite tikrus, stebimus adresus. Bendra pašto dėžutė, kurios niekas neskaito, yra blogesnis pasirinkimas nei vienas įvardytas žmogus.',
          'Adresas, kuris negrįžtamai atmeta laiškus, įsimenamas ir jam daugiau nerašoma – taip saugomas visų kitų laiškų pristatymas. Jei vienas gavėjas nustojo gauti laiškus, tai pirmas dalykas, kurį reikia patikrinti.',
        ] },
        { h2: 'Kokia kalba ir kokiais vienetais jie gauna laiškus', id: 'language' },
        { p: 'Žinutės rašomos kiekvienos paskyros kalba, vienetais ir laiko juosta – tai nustatoma kiekvienai kliento paskyrai, o ne kiekvienam žmogui, nes daug gavėjų prisijungimo apskritai neturi. Nustatykite tai kurdami paskyrą; žr. [Laiko juostos ir vienetai](kb:time-zones-and-units).' },
        { h2: 'Susiję', id: 'related' },
        { p: 'Kas yra žinutėse ir kas jas gauna: [Kur pristatomi pranešimai](kb:notification-channels). Kur nustatomas siuntėjo vardas ir pagalbos adresas: [Skydelio ženklinimas](kb:branding).' },
      ],
    },
    pl: {
      title: 'E-maile, które dostają Twoi klienci',
      summary: 'Które części wiadomości mają Twoją markę, jak sprawić, by adres wysyłki też był Twój, i jak zadbać, by wiadomości docierały.',
      keywords: ['e-mail', 'nadawca', 'from', 'reply-to', 'marka', 'dostarczalność', 'spf', 'dkim', 'spam'],
      blocks: [
        { p: 'Twoi klienci dostają pocztę z tej platformy: aktywacje kont, resety haseł, alerty i raporty cykliczne. Tak wyglądają te wiadomości z ich strony.' },
        { h2: 'Co ma Twoją markę', id: 'branded' },
        { ul: [
          '**Nazwa nadawcy** — nazwa Twojego produktu, czyli wiersz, który skrzynka pokazuje przed otwarciem wiadomości.',
          '**Adres odpowiedzi** — Twój adres wsparcia. Klient, który odpowie, trafia do Ciebie.',
          '**Treść** — Twoje logo, Twoje kolory, nazwa Twojego produktu w tekście.',
          '**Każdy link** — wskazujący na Twoją domenę, więc kliknięcie nigdy nie opuszcza Twojej marki.',
        ] },
        { h2: 'Adres wysyłki', id: 'not-yet' },
        { p: 'Dopóki tego nie skonfigurujesz, sam **adres** wysyłki jest wspólny, a nie w Twojej domenie. Nazwa wyświetlana przed nim jest już Twoja, więc skrzynka pokazuje Twoją nazwę — ale odbiorca, który rozwinie nagłówek, zobaczy stojący za nią adres techniczny.' },
        { p: 'Aby i ta linia była Twoja, otwórz **Marka → Wysyłaj wiadomości z własnego adresu**, podaj nazwę skrzynki i domenę, z której chcesz wysyłać, i opublikuj trzy pokazane rekordy DNS. Weryfikacja może potrwać do godziny po ich pojawieniu się.' },
        { callout: 'note', p: 'Nic się nie zatrzymuje, gdy czekasz. Do czasu weryfikacji wiadomości nadal wychodzą ze wspólnego adresu dokładnie jak wcześniej — niedokończona konfiguracja nigdy nie kosztuje klienta alertu. Jeśli panel mówi, że funkcja jest niedostępna w tej instalacji, po prostu nie została jeszcze włączona; po Twojej stronie nic nie jest nie tak.' },
        { p: 'Jeśli dla konkretnego klienta to istotne, praktycznym rozwiązaniem jest upewnienie się, że Twój adres wsparcia jest ustawiony — wtedy każda odpowiedź i każda dalsza rozmowa toczy się z Tobą.' },
        { h2: 'Żeby poczta docierała', id: 'deliverability' },
        { ul: [
          'Przy przekazaniu poproś nowego klienta o jednorazowe dodanie nadawcy do książki adresowej. To trzydzieści sekund, a zapobiega najczęstszej reklamacji, jaką dostaniesz.',
          'Do alertów używaj prawdziwych, monitorowanych adresów. Wspólna skrzynka, której nikt nie czyta, jest gorsza niż jedna wskazana osoba.',
          'Adres, który trwale odrzuca pocztę, zostaje zapamiętany i nie wysyłamy już na niego kolejnych wiadomości — to chroni dostarczalność wszystkich innych wiadomości. Jeśli jeden odbiorca przestał dostawać pocztę, sprawdź to w pierwszej kolejności.',
        ] },
        { h2: 'W jakim języku i jednostkach dostają wiadomości', id: 'language' },
        { p: 'Wiadomości są pisane w języku, jednostkach i strefie czasowej każdego konta — ustawianych na koncie klienta, nie na osobie, bo wielu odbiorców nie ma w ogóle loginu. Ustaw to przy tworzeniu konta; zobacz [Strefy czasowe i jednostki](kb:time-zones-and-units).' },
        { h2: 'Powiązane', id: 'related' },
        { p: 'Co jest w wiadomościach i kto je dostaje: [Dokąd trafiają alerty](kb:notification-channels). Gdzie ustawia się nazwę nadawcy i adres wsparcia: [Marka Twojego panelu](kb:branding).' },
      ],
    },
    de: {
      title: 'E-Mails, die Ihre Kunden erhalten',
      summary: 'Welche Teile einer Nachricht Ihre Marke tragen, wie auch die Absenderadresse Ihre wird, und wie Sie dafür sorgen, dass Post ankommt.',
      keywords: ['e-mail', 'absender', 'from', 'reply-to', 'branding', 'zustellbarkeit', 'spf', 'dkim', 'spam'],
      blocks: [
        { p: 'Ihre Kunden erhalten Post von dieser Plattform: Kontoaktivierungen, Passwort-Resets, Alarme und geplante Berichte. So sehen diese Nachrichten von ihrer Seite aus.' },
        { h2: 'Was Ihre Marke trägt', id: 'branded' },
        { ul: [
          '**Der Absendername** — Ihr Produktname, also die Zeile, die ein Posteingang vor dem Öffnen zeigt.',
          '**Die Antwortadresse** — Ihre Support-Adresse. Wer antwortet, erreicht Sie.',
          '**Der Inhalt** — Ihr Logo, Ihre Farben, Ihr Produktname im Text.',
          '**Jeder Link** — auf Ihre Domain, sodass ein Klick nie Ihre Marke verlässt.',
        ] },
        { h2: 'Die Absenderadresse', id: 'not-yet' },
        { p: 'Solange Sie das nicht eingerichtet haben, ist die eigentliche Versand**adresse** eine gemeinsame und keine Adresse Ihrer Domain. Der Anzeigename davor ist bereits Ihrer, ein Posteingang zeigt also Ihren Namen — wer den Header aufklappt, sieht jedoch die technische Adresse dahinter.' },
        { p: 'Damit auch diese Zeile Ihre wird, öffnen Sie **Marke → E-Mails von Ihrer eigenen Adresse senden**, tragen Postfachnamen und Domain ein, von der Sie senden möchten, und veröffentlichen Sie die drei angezeigten DNS-Einträge. Die Bestätigung kann danach bis zu einer Stunde dauern.' },
        { callout: 'note', p: 'Währenddessen bleibt nichts liegen. Bis zur Bestätigung gehen Nachrichten weiter über die gemeinsame Adresse raus, genau wie zuvor — eine halbfertige Einrichtung kostet einen Kunden nie eine Benachrichtigung. Sagt das Panel, die Funktion sei in dieser Installation nicht verfügbar, ist sie schlicht noch nicht eingeschaltet; auf Ihrer Seite ist nichts falsch.' },
        { p: 'Zählt das bei einem bestimmten Kunden, ist die praktische Abhilfe, Ihre Support-Adresse zu setzen — dann laufen jede Antwort und jedes Folgegespräch über Sie.' },
        { h2: 'Damit Post ankommt', id: 'deliverability' },
        { ul: [
          'Bitten Sie einen neuen Kunden bei der Übergabe, den Absender einmal ins Adressbuch zu nehmen. Dreißig Sekunden — und die häufigste Beschwerde, die Sie bekommen werden, entfällt.',
          'Nutzen Sie für Alarme echte, betreute Adressen. Ein Sammelpostfach, das niemand liest, ist schlechter als eine namentlich benannte Person.',
          'Eine Adresse, die Post dauerhaft ablehnt, wird gemerkt und nicht erneut beschrieben — das schützt die Zustellung aller anderen Nachrichten. Bekommt ein Empfänger keine Post mehr, prüfen Sie das zuerst.',
        ] },
        { h2: 'Sprache und Einheiten des Empfangenen', id: 'language' },
        { p: 'Nachrichten werden in Sprache, Einheiten und Zeitzone des jeweiligen Kontos geschrieben — eingestellt je Kundenkonto, nicht je Person, denn viele Empfänger haben gar keinen Zugang. Stellen Sie es beim Anlegen des Kontos ein; siehe [Zeitzonen und Einheiten](kb:time-zones-and-units).' },
        { h2: 'Verwandt', id: 'related' },
        { p: 'Was in den Nachrichten steht und wer sie bekommt: [Wohin Alarme zugestellt werden](kb:notification-channels). Wo Absendername und Support-Adresse gesetzt werden: [Ihr Dashboard mit Ihrer Marke versehen](kb:branding).' },
      ],
    },
  },
}
