import type { KbArticle } from '../types.js'

export const exportAndEraseData: KbArticle = {
  slug: 'export-and-erase-data',
  category: 'trust',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true },
  screen: '/app/settings',
  doc: {
    en: {
      title: 'Exporting and erasing your data',
      summary: 'Taking a full copy of an account, answering a data request, and permanently removing what should no longer exist.',
      keywords: ['export', 'gdpr', 'erase', 'delete', 'data request', 'ndjson', 'download', 'subject access', 'leaving'],
      blocks: [
        { p: 'Your data is yours. Two things make that concrete: you can take a complete copy whenever you want, and you can have data permanently removed.' },
        { h2: 'Exporting an account', id: 'export' },
        { p: 'Under **Settings → Data**, request an export of an account. It is prepared in the background and appears as a download when it is ready. The file contains everything held for that account: devices, positions, trips, events, rules and users.' },
        { ul: [
          'The format is NDJSON — one record per line. Every spreadsheet, database and scripting language can read it, and unlike a single giant JSON document it can be processed a line at a time.',
          'Files expire seven days after they are generated. Download them and put them where they belong; request a new one later if you need it again.',
          'The export covers one account. In a reseller organisation, run one export per customer — which is also exactly what a customer\'s own data request needs.',
        ] },
        { h2: 'Answering “what do you hold about me?”', id: 'subject-access' },
        { p: 'A driver or a customer is entitled to ask. The export is the raw answer; you normally hand over the parts about that person rather than the whole file, because the file also contains data about everyone else. Filtering it is your job as the controller of that data — see [Tracking employees lawfully](kb:tracking-employees-lawfully).' },
        { h2: 'Erasing a device\'s data', id: 'erase' },
        { p: 'Erasing removes everything a device produced: positions, trips, events and command history. It is the tool for a deletion request, for a vehicle that has left, and for a customer who has ended their contract.' },
        { callout: 'warning', p: 'An erase is permanent and complete. Nothing is kept back for support purposes, and no backup will be searched to bring it back. Export first if you might want any of it.' },
        { p: 'A device must be retired before it can be erased, and there is a deliberate delay between the two. That gap is the only chance to change your mind — see [Retiring and erasing a device](kb:device-lifecycle).' },
        { h2: 'What happens without you asking', id: 'automatic' },
        { p: 'Raw positions age out on their own after thirteen months. You do not have to manage this, and you cannot rely on it to satisfy a deletion request — a request means now, and the retention sweep means eventually. See [Where your data lives](kb:where-your-data-lives).' },
        { h2: 'Leaving', id: 'leaving' },
        { ol: [
          'Export every account you want a copy of.',
          'Download the files while they are still there.',
          'Cancel the subscription deliberately rather than letting an invoice fail — see [What happens if an invoice goes unpaid](kb:unpaid-what-happens).',
          'Erase what should not outlive the relationship.',
        ] },
      ],
    },
    lt: {
      title: 'Duomenų eksportas ir ištrynimas',
      summary: 'Kaip pasiimti visą paskyros kopiją, atsakyti į duomenų prašymą ir negrįžtamai pašalinti tai, ko nebeturi būti.',
      keywords: ['eksportas', 'bdar', 'ištrynimas', 'duomenų prašymas', 'ndjson', 'atsisiuntimas', 'išėjimas'],
      blocks: [
        { p: 'Jūsų duomenys yra jūsų. Tai užtikrina dvi konkrečios galimybės: bet kada galite pasiimti visą kopiją ir bet kada galite pareikalauti duomenis negrįžtamai pašalinti.' },
        { h2: 'Paskyros eksportas', id: 'export' },
        { p: 'Skiltyje **Nustatymai → Duomenys** užsakykite paskyros eksportą. Jis paruošiamas fone ir, kai baigtas, atsiranda kaip atsisiunčiamas failas, kuriame yra viskas, kas laikoma toje paskyroje: įrenginiai, pozicijos, kelionės, įvykiai, taisyklės ir naudotojai.' },
        { ul: [
          'Formatas – NDJSON, po vieną įrašą eilutėje. Jį perskaito kiekviena skaičiuoklė, duomenų bazė ir scenarijų kalba, o, kitaip nei vientisą milžinišką JSON dokumentą, jį galima apdoroti eilutė po eilutės.',
          'Failai nustoja galioti po septynių dienų nuo sugeneravimo. Atsisiųskite jį ir padėkite ten, kur reikia; prireikus vėliau užsakykite iš naujo.',
          'Eksportas apima vieną paskyrą. Perpardavėjo organizacijoje užsakykite po vieną kiekvienam klientui – kaip tik to ir reikia kliento duomenų prašymui.',
        ] },
        { h2: 'Kaip atsakyti „ką apie mane laikote?“', id: 'subject-access' },
        { p: 'Vairuotojas ar klientas turi teisę klausti. Eksportas yra neapdorotas atsakymas; paprastai perduodama tik ta dalis, kuri yra apie tą žmogų, o ne visas failas, nes faile yra ir visų kitų duomenys. Atfiltruoti – jūsų, kaip tų duomenų valdytojo, darbas; žr. [Teisėtas darbuotojų sekimas](kb:tracking-employees-lawfully).' },
        { h2: 'Įrenginio duomenų ištrynimas', id: 'erase' },
        { p: 'Ištrynimas pašalina viską, ką įrenginys sukūrė: pozicijas, keliones, įvykius ir komandų istoriją. Tai įrankis ištrynimo prašymui, automobiliui, kurio autoparke nebėra, ir klientui, kurio sutartis pasibaigė.' },
        { callout: 'warning', p: 'Ištrynimas yra galutinis ir visiškas. Nieko nepasiliekama „palaikymo tikslais“, ir niekas nekraustys atsarginių kopijų, kad tai sugrąžintų. Jei bent ko nors gali prireikti – pirma eksportuokite.' },
        { p: 'Prieš ištrinant įrenginys turi būti išregistruotas, o tarp šių dviejų veiksmų yra sąmoninga pauzė. Ta pauzė – vienintelė proga apsigalvoti; žr. [Įrenginio išregistravimas ir ištrynimas](kb:device-lifecycle).' },
        { h2: 'Kas vyksta jums neprašant', id: 'automatic' },
        { p: 'Neapdorotos pozicijos savaime pasensta po trylikos mėnesių. Jums to tvarkyti nereikia, bet ir pasikliauti tuo vykdant ištrynimo prašymą negalima – prašymas reiškia dabar, o valymas reiškia kada nors. Žr. [Kur laikomi jūsų duomenys](kb:where-your-data-lives).' },
        { h2: 'Išeinant', id: 'leaving' },
        { ol: [
          'Eksportuokite kiekvieną paskyrą, kurios kopijos norite.',
          'Atsisiųskite failus, kol jie dar yra.',
          'Prenumeratą atšaukite sąmoningai, o ne palikdami sąskaitą neapmokėtą – žr. [Kas nutinka neapmokėjus sąskaitos](kb:unpaid-what-happens).',
          'Ištrinkite tai, kas neturi likti pasibaigus bendradarbiavimui.',
        ] },
      ],
    },
    pl: {
      title: 'Eksport i usuwanie danych',
      summary: 'Pobranie pełnej kopii konta, odpowiedź na wniosek o dane i trwałe usunięcie tego, czego nie powinno już być.',
      keywords: ['eksport', 'rodo', 'usuwanie', 'wniosek o dane', 'ndjson', 'pobranie', 'odejście'],
      blocks: [
        { p: 'Twoje dane są Twoje. Nie jest to tylko deklaracja — stoją za nią dwie rzeczy: w każdej chwili możesz pobrać pełną kopię i w każdej chwili możesz zażądać trwałego usunięcia.' },
        { h2: 'Eksport konta', id: 'export' },
        { p: 'W **Ustawienia → Dane** zamów eksport konta. Jest przygotowywany w tle i po ukończeniu pojawia się jako plik do pobrania, zawierający wszystko, co przechowywane dla tego konta: urządzenia, pozycje, trasy, zdarzenia, reguły i użytkowników.' },
        { ul: [
          'Format to NDJSON — jeden rekord na wiersz. Odczyta go każdy arkusz, baza danych i język skryptowy, a w odróżnieniu od jednego wielkiego dokumentu JSON można go przetwarzać wiersz po wierszu.',
          'Pliki wygasają siedem dni po wygenerowaniu. Pobierz go i odłóż tam, gdzie należy; w razie potrzeby zamów ponownie.',
          'Eksport obejmuje jedno konto. W organizacji resellerskiej uruchom po jednym na klienta — i dokładnie tego wymaga wniosek klienta o jego dane.',
        ] },
        { h2: 'Odpowiedź na „co o mnie macie?”', id: 'subject-access' },
        { p: 'Kierowca albo klient ma prawo zapytać. Eksport to surowa odpowiedź; zwykle przekazuje się tę część, która dotyczy tej osoby, a nie cały plik, bo plik zawiera też dane wszystkich innych. Odfiltrowanie to Twoje zadanie jako administratora tych danych — zobacz [Legalne monitorowanie pracowników](kb:tracking-employees-lawfully).' },
        { h2: 'Kasowanie danych urządzenia', id: 'erase' },
        { p: 'Kasowanie usuwa wszystko, co urządzenie wytworzyło: pozycje, trasy, zdarzenia i historię poleceń. To narzędzie do wniosku o usunięcie, do pojazdu, który wyjechał z floty, i do klienta, którego umowa się skończyła.' },
        { callout: 'warning', p: 'Kasowanie jest trwałe i całkowite. Nic nie zostaje „na potrzeby wsparcia” i żadna kopia zapasowa nie zostanie przeszukana, by to przywrócić. Jeśli cokolwiek może się przydać — najpierw eksportuj.' },
        { p: 'Przed usunięciem danych urządzenie musi być wycofane, a między tymi dwiema akcjami jest celowa zwłoka. Ta przerwa to jedyna szansa, by zmienić zdanie — zobacz [Wycofywanie i usuwanie urządzenia](kb:device-lifecycle).' },
        { h2: 'Co dzieje się bez Twojej prośby', id: 'automatic' },
        { p: 'Surowe pozycje same wygasają po trzynastu miesiącach. Nie musisz tym zarządzać, ale nie możesz na tym polegać przy realizacji wniosku o usunięcie — wniosek znaczy teraz, a czyszczenie znaczy kiedyś. Zobacz [Gdzie są Twoje dane](kb:where-your-data-lives).' },
        { h2: 'Gdy odchodzisz', id: 'leaving' },
        { ol: [
          'Wyeksportuj każde konto, którego kopii chcesz.',
          'Pobierz pliki, póki jeszcze są.',
          'Anuluj subskrypcję świadomie, a nie przez dopuszczenie do nieopłaconej faktury — zobacz [Co się dzieje przy braku płatności](kb:unpaid-what-happens).',
          'Usuń to, co nie powinno przeżyć tej relacji.',
        ] },
      ],
    },
    de: {
      title: 'Daten exportieren und löschen',
      summary: 'Eine vollständige Kopie eines Kontos ziehen, eine Datenanfrage beantworten und dauerhaft entfernen, was nicht mehr existieren soll.',
      keywords: ['export', 'dsgvo', 'löschen', 'datenanfrage', 'ndjson', 'download', 'auskunft', 'kündigung'],
      blocks: [
        { p: 'Ihre Daten gehören Ihnen. Zwei Funktionen machen das konkret: Sie können jederzeit eine vollständige Kopie ziehen, und Sie können Daten dauerhaft entfernen lassen.' },
        { h2: 'Ein Konto exportieren', id: 'export' },
        { p: 'Unter **Einstellungen → Daten** fordern Sie den Export eines Kontos an. Er wird im Hintergrund erstellt und erscheint fertig als Download — mit allem, was für dieses Konto vorliegt: Geräte, Positionen, Fahrten, Ereignisse, Regeln und Benutzer.' },
        { ul: [
          'Das Format ist NDJSON — ein Datensatz je Zeile. Jede Tabellenkalkulation, Datenbank und Skriptsprache liest es, und anders als ein einzelnes riesiges JSON-Dokument lässt es sich Zeile für Zeile verarbeiten.',
          'Dateien verfallen sieben Tage nach der Erstellung. Laden Sie die Datei herunter und legen Sie sie ab, wo sie hingehört; bei Bedarf fordern Sie sie später erneut an.',
          'Ein Export umfasst ein Konto. In einer Reseller-Organisation führen Sie einen je Kunde aus — und genau das braucht auch die Datenanfrage eines Kunden.',
        ] },
        { h2: '„Welche Daten haben Sie über mich gespeichert?“ beantworten', id: 'subject-access' },
        { p: 'Ein Fahrer oder Kunde darf fragen. Der Export ist die Rohantwort; üblicherweise geben Sie die Teile über diese Person heraus und nicht die ganze Datei, denn darin stehen auch die Daten aller anderen. Das Filtern ist Ihre Aufgabe als Verantwortlicher — siehe [Mitarbeiter rechtmäßig orten](kb:tracking-employees-lawfully).' },
        { h2: 'Die Daten eines Geräts löschen', id: 'erase' },
        { p: 'Löschen entfernt alles, was ein Gerät erzeugt hat: Positionen, Fahrten, Ereignisse und Befehlsverlauf. Es ist das Werkzeug für ein Löschbegehren, für ein Fahrzeug, das gegangen ist, und für einen Kunden, dessen Vertrag endete.' },
        { callout: 'warning', p: 'Ein Löschvorgang ist endgültig und vollständig. Nichts wird „für den Support“ zurückbehalten, und kein Backup wird durchsucht, um es zurückzuholen. Exportieren Sie vorher, falls Sie etwas davon noch brauchen könnten.' },
        { p: 'Ein Gerät muss vor dem Löschen stillgelegt sein, und zwischen beidem liegt eine bewusste Verzögerung. Diese Lücke ist die einzige Gelegenheit, es sich noch anders zu überlegen — siehe [Gerät stilllegen und löschen](kb:device-lifecycle).' },
        { h2: 'Was ohne Ihr Zutun geschieht', id: 'automatic' },
        { p: 'Rohpositionen laufen nach dreizehn Monaten von selbst aus. Sie müssen das nicht verwalten, dürfen sich aber für ein Löschbegehren nicht darauf verlassen — ein Begehren heißt jetzt, die Bereinigung heißt irgendwann. Siehe [Wo Ihre Daten liegen](kb:where-your-data-lives).' },
        { h2: 'Beim Weggehen', id: 'leaving' },
        { ol: [
          'Exportieren Sie jedes Konto, von dem Sie eine Kopie wollen.',
          'Laden Sie die Dateien herunter, solange sie da sind.',
          'Kündigen Sie bewusst, statt eine Rechnung scheitern zu lassen — siehe [Was bei einer unbezahlten Rechnung passiert](kb:unpaid-what-happens).',
          'Löschen Sie, was die Beziehung nicht überdauern soll.',
        ] },
      ],
    },
  },
}
