import type { KbArticle } from '../types.js'

export const firstSteps: KbArticle = {
  slug: 'first-steps',
  category: 'start',
  surfaces: { site: true, app: true },
  screen: '/app',
  doc: {
    en: {
      title: 'Your first hour',
      summary: 'A checklist that takes a brand-new account to a live map, a working alert and a report you can hand to someone.',
      keywords: ['setup', 'onboarding', 'checklist', 'start', 'first vehicle'],
      blocks: [
        { p: 'Six steps. None of them needs an IT department, and you can stop after step 3 and still have a working live map.' },
        { h2: '1. Add the vehicle', id: 'add' },
        { p: 'Open **Devices → Add device** and type the tracker\'s IMEI — the 15-digit number printed on its label. Give it the name you actually use for the vehicle ("Sprinter 402", not "device 1"), because that name is what appears on the map, in alerts and in every report. See [What an IMEI is](kb:imei).' },
        { h2: '2. Point the tracker at us', id: 'connect' },
        { p: 'A tracker fresh from the box does not know where to send its data. You tell it, once, either by text message to its SIM or with the manufacturer\'s configurator. The device page has an **Onboard** button that shows the exact values for your account — host, port, APN — and can send the configuration text message for you. Full walkthrough: [Connecting a tracker](kb:connect-a-tracker).' },
        { h2: '3. Watch it appear', id: 'appear' },
        { p: 'Within a minute or two of being powered up outdoors, the vehicle shows up on the live map. Until its first position arrives it is listed as **Never reported** — that is a normal state for a few minutes and a diagnosis after an hour. If it stays there, go to [Device not reporting](kb:device-not-reporting).' },
        { callout: 'tip', p: 'Take the vehicle for a five-minute drive. A parked vehicle proves the connection works; a moving one proves the trip detection, the speed and the map trail work too.' },
        { h2: '4. Draw one zone', id: 'zone' },
        { p: 'Go to **Geofences** and draw a shape around the place that matters most — your depot, a customer\'s yard, the border of your service area. It takes about fifteen seconds and it is what makes the next step useful. See [Geofences](kb:geofences).' },
        { h2: '5. Create one alert', id: 'rule' },
        { p: 'In **Rules**, create a rule of kind *Geofence* pointing at the zone you just drew, and add your e-mail as the channel. From now on you are told when a vehicle arrives or leaves, instead of having to look. Start with one rule, not ten — see [Rules and alerts](kb:rules-and-alerts).' },
        { h2: '6. Run a report', id: 'report' },
        { p: 'After a day of driving, **Reports → Mileage** over yesterday gives you the number that usually justifies the whole system. You can export it as CSV or PDF, or have it e-mailed to you every Monday — see [Scheduled reports](kb:scheduled-reports).' },
        { h2: 'Then set two things and forget them', id: 'settle' },
        { ul: [
          '**Time zone and units** for the account, so reports and alert e-mails are grouped and written the way your business thinks — [Time zones and units](kb:time-zones-and-units).',
          '**Who else gets a login**, and with which permissions — [Logins and roles](kb:logins-and-roles).',
        ] },
      ],
    },
    lt: {
      title: 'Pirmoji jūsų valanda',
      summary: 'Sąrašas, per kurį visiškai nauja paskyra virsta gyvu žemėlapiu, veikiančiu pranešimu ir ataskaita, kurią jau galima kam nors paduoti.',
      keywords: ['diegimas', 'pradžia', 'sąrašas', 'pirmas automobilis'],
      blocks: [
        { p: 'Šeši žingsniai. Nė vienam nereikia IT skyriaus, o sustoję po trečio jau turėsite veikiantį gyvą žemėlapį.' },
        { h2: '1. Pridėkite automobilį', id: 'add' },
        { p: 'Atverkite **Įrenginiai → Pridėti įrenginį** ir įveskite seklio IMEI – 15 skaitmenų numerį, atspausdintą ant jo etiketės. Pavadinkite taip, kaip automobilį vadinate iš tikrųjų („Sprinter 402", o ne „įrenginys 1"), nes būtent šis vardas matomas žemėlapyje, pranešimuose ir kiekvienoje ataskaitoje. Žr. [Kas yra IMEI](kb:imei).' },
        { h2: '2. Nukreipkite seklį į mus', id: 'connect' },
        { p: 'Ką tik iš dėžės išimtas seklys nežino, kur siųsti duomenis. Tai pasakote vieną kartą – arba SMS žinute į jo SIM, arba gamintojo konfigūravimo programa. Įrenginio kortelėje yra mygtukas **Prijungti**, kuris parodo tikslias jūsų paskyros reikšmes – serverį, prievadą, APN – ir gali pats išsiųsti konfigūracijos SMS. Visas aprašymas: [Seklio prijungimas](kb:connect-a-tracker).' },
        { h2: '3. Palaukite, kol pasirodys', id: 'appear' },
        { p: 'Praėjus minutei kitai nuo įjungimo lauke, automobilis atsiranda gyvame žemėlapyje. Kol neatkeliavo pirmoji pozicija, jis rodomas kaip **Niekada nesiuntė** – kelias minutes tai normalu, o po valandos tai jau diagnozė. Jei taip ir lieka, eikite į [Įrenginys nesiunčia duomenų](kb:device-not-reporting).' },
        { callout: 'tip', p: 'Pravažiuokite penkias minutes. Stovintis automobilis įrodo, kad veikia ryšys; važiuojantis įrodo, kad veikia ir kelionių aptikimas, ir greitis, ir pėdsakas žemėlapyje.' },
        { h2: '4. Nubrėžkite vieną zoną', id: 'zone' },
        { p: 'Eikite į **Geozonas** ir apibrėžkite svarbiausią vietą – savo bazę, kliento kiemą, aptarnaujamos teritorijos ribą. Tai užtrunka apie penkiolika sekundžių ir kaip tik dėl to kitas žingsnis tampa naudingas. Žr. [Geozonos](kb:geofences).' },
        { h2: '5. Sukurkite vieną pranešimą', id: 'rule' },
        { p: 'Skiltyje **Taisyklės** sukurkite *Geozonos* tipo taisyklę, nurodykite ką tik nubrėžtą zoną ir kaip kanalą įrašykite savo el. paštą. Nuo šiol jums pranešama, kai automobilis atvyksta ar išvyksta – nebereikia tikrinti pačiam. Pradėkite nuo vienos taisyklės, ne nuo dešimties – žr. [Taisyklės ir pranešimai](kb:rules-and-alerts).' },
        { h2: '6. Paleiskite ataskaitą', id: 'report' },
        { p: 'Po dienos važiavimo **Ataskaitos → Rida** už vakar duoda skaičių, kuris paprastai pateisina visą sistemą. Ją galima eksportuoti į CSV ar PDF arba gauti el. paštu kas pirmadienį – žr. [Planinės ataskaitos](kb:scheduled-reports).' },
        { h2: 'Tada nustatykite du dalykus ir pamirškite', id: 'settle' },
        { ul: [
          '**Laiko juostą ir vienetus** paskyrai, kad ataskaitos ir pranešimų laiškai būtų grupuojami ir rašomi taip, kaip mąsto jūsų verslas – [Laiko juostos ir vienetai](kb:time-zones-and-units).',
          '**Kas dar gauna prisijungimą** ir su kokiomis teisėmis – [Prisijungimai ir rolės](kb:logins-and-roles).',
        ] },
      ],
    },
    pl: {
      title: 'Twoja pierwsza godzina',
      summary: 'Lista kroków, która prowadzi od zupełnie nowego konta do mapy na żywo, działającego alertu i raportu, który można komuś przekazać.',
      keywords: ['konfiguracja', 'start', 'lista kroków', 'pierwszy pojazd'],
      blocks: [
        { p: 'Sześć kroków. Żaden nie wymaga działu IT, a po trzecim można przestać i już mieć działającą mapę na żywo.' },
        { h2: '1. Dodaj pojazd', id: 'add' },
        { p: 'Otwórz **Urządzenia → Dodaj urządzenie** i wpisz IMEI lokalizatora — 15-cyfrowy numer nadrukowany na etykiecie. Nadaj nazwę, której naprawdę używasz („Sprinter 402", nie „urządzenie 1"), bo właśnie ta nazwa pojawia się na mapie, w alertach i w każdym raporcie. Zobacz [Czym jest IMEI](kb:imei).' },
        { h2: '2. Skieruj lokalizator na nas', id: 'connect' },
        { p: 'Lokalizator prosto z pudełka nie wie, dokąd wysyłać dane. Mówisz mu to raz — SMS-em na jego kartę SIM albo konfiguratorem producenta. Na karcie urządzenia jest przycisk **Podłącz**, który pokazuje dokładne wartości dla Twojego konta — host, port, APN — i potrafi sam wysłać SMS konfiguracyjny. Pełny opis: [Podłączanie lokalizatora](kb:connect-a-tracker).' },
        { h2: '3. Poczekaj, aż się pojawi', id: 'appear' },
        { p: 'Minutę lub dwie po włączeniu na zewnątrz pojazd pojawia się na mapie. Do pierwszej pozycji widnieje jako **Nigdy nie raportowało** — przez kilka minut to normalne, po godzinie to już diagnoza. Jeśli tak zostanie, przejdź do [Urządzenie nie raportuje](kb:device-not-reporting).' },
        { callout: 'tip', p: 'Przejedź pięć minut. Zaparkowany pojazd dowodzi, że działa łączność; jadący dowodzi, że działa też wykrywanie tras, prędkość i ślad na mapie.' },
        { h2: '4. Narysuj jedną strefę', id: 'zone' },
        { p: 'Wejdź w **Geostrefy** i obrysuj miejsce, które ma największe znaczenie — bazę, plac klienta, granicę obszaru obsługi. Zajmuje to kilkanaście sekund i to właśnie czyni następny krok użytecznym. Zobacz [Geostrefy](kb:geofences).' },
        { h2: '5. Utwórz jeden alert', id: 'rule' },
        { p: 'W **Regułach** utwórz regułę typu *Geostrefa* wskazującą właśnie narysowaną strefę i dodaj swój e-mail jako kanał. Od tej chwili dostajesz informację, gdy pojazd przyjeżdża lub wyjeżdża, zamiast sprawdzać samemu. Zacznij od jednej reguły, nie od dziesięciu — zobacz [Reguły i alerty](kb:rules-and-alerts).' },
        { h2: '6. Uruchom raport', id: 'report' },
        { p: 'Po dniu jazdy **Raporty → Przebieg** za wczoraj daje liczbę, która zwykle uzasadnia cały system. Można ją wyeksportować do CSV lub PDF albo dostawać mailem w każdy poniedziałek — zobacz [Raporty cykliczne](kb:scheduled-reports).' },
        { h2: 'Potem ustaw dwie rzeczy i zapomnij', id: 'settle' },
        { ul: [
          '**Strefę czasową i jednostki** dla konta, żeby raporty i e-maile alertów były grupowane i pisane tak, jak myśli Twoja firma — [Strefy czasowe i jednostki](kb:time-zones-and-units).',
          '**Kto jeszcze dostaje login** i z jakimi uprawnieniami — [Loginy i role](kb:logins-and-roles).',
        ] },
      ],
    },
    de: {
      title: 'Ihre erste Stunde',
      summary: 'Eine Checkliste, die ein brandneues Konto zu einer Live-Karte, einem funktionierenden Alarm und einem vorzeigbaren Bericht führt.',
      keywords: ['einrichtung', 'onboarding', 'checkliste', 'erstes fahrzeug'],
      blocks: [
        { p: 'Sechs Schritte. Keiner braucht eine IT-Abteilung, und nach Schritt 3 können Sie aufhören und haben trotzdem eine funktionierende Live-Karte.' },
        { h2: '1. Fahrzeug anlegen', id: 'add' },
        { p: 'Öffnen Sie **Geräte → Gerät hinzufügen** und geben Sie die IMEI des Trackers ein — die 15-stellige Nummer auf dem Etikett. Vergeben Sie den Namen, den Sie tatsächlich benutzen („Sprinter 402", nicht „Gerät 1"), denn dieser Name erscheint auf der Karte, in Alarmen und in jedem Bericht. Siehe [Was eine IMEI ist](kb:imei).' },
        { h2: '2. Den Tracker auf uns richten', id: 'connect' },
        { p: 'Ein Tracker frisch aus dem Karton weiß nicht, wohin er seine Daten schicken soll. Das sagen Sie ihm einmal — per SMS an seine SIM oder mit dem Konfigurator des Herstellers. Die Geräteseite hat eine Schaltfläche **Einrichten**, die die exakten Werte für Ihr Konto zeigt — Host, Port, APN — und die Konfigurations-SMS für Sie senden kann. Vollständige Anleitung: [Tracker anschließen](kb:connect-a-tracker).' },
        { h2: '3. Auftauchen abwarten', id: 'appear' },
        { p: 'Ein bis zwei Minuten nach dem Einschalten im Freien erscheint das Fahrzeug auf der Live-Karte. Bis zur ersten Position steht es als **Nie gemeldet** — ein paar Minuten lang normal, nach einer Stunde eine Diagnose. Bleibt es dabei, weiter mit [Gerät meldet sich nicht](kb:device-not-reporting).' },
        { callout: 'tip', p: 'Fahren Sie fünf Minuten. Ein geparktes Fahrzeug beweist, dass die Verbindung steht; ein fahrendes beweist zusätzlich Fahrtenerkennung, Geschwindigkeit und Kartenspur.' },
        { h2: '4. Eine Zone zeichnen', id: 'zone' },
        { p: 'Gehen Sie zu **Geozonen** und umranden Sie den wichtigsten Ort — Ihren Hof, den Platz eines Kunden, die Grenze Ihres Einsatzgebiets. Das dauert etwa fünfzehn Sekunden und macht den nächsten Schritt erst nützlich. Siehe [Geozonen](kb:geofences).' },
        { h2: '5. Einen Alarm anlegen', id: 'rule' },
        { p: 'Legen Sie unter **Regeln** eine Regel vom Typ *Geozone* auf die eben gezeichnete Zone an und tragen Sie Ihre E-Mail als Kanal ein. Ab jetzt werden Sie informiert, wenn ein Fahrzeug ankommt oder wegfährt, statt nachsehen zu müssen. Fangen Sie mit einer Regel an, nicht mit zehn — siehe [Regeln und Alarme](kb:rules-and-alerts).' },
        { h2: '6. Einen Bericht laufen lassen', id: 'report' },
        { p: 'Nach einem Fahrtag liefert **Berichte → Kilometer** für gestern die Zahl, die das ganze System meist rechtfertigt. Sie lässt sich als CSV oder PDF exportieren oder jeden Montag zumailen — siehe [Geplante Berichte](kb:scheduled-reports).' },
        { h2: 'Dann zwei Dinge einstellen und vergessen', id: 'settle' },
        { ul: [
          '**Zeitzone und Einheiten** für das Konto, damit Berichte und Alarm-Mails so gruppiert und geschrieben sind, wie Ihr Betrieb denkt — [Zeitzonen und Einheiten](kb:time-zones-and-units).',
          '**Wer sonst einen Zugang bekommt** und mit welchen Rechten — [Zugänge und Rollen](kb:logins-and-roles).',
        ] },
      ],
    },
  },
}
