import type { KbArticle } from '../types.js'

export const geofences: KbArticle = {
  slug: 'geofences',
  category: 'alerts',
  surfaces: { site: true, app: true },
  screen: '/app/geofences',
  doc: {
    en: {
      title: 'Geofences — drawing places that matter',
      summary: 'Polygons, circles and corridors, what crossing an edge means, and how to keep a hundred zones from becoming noise.',
      keywords: ['geofence', 'zone', 'polygon', 'circle', 'corridor', 'area', 'boundary', 'enter', 'exit'],
      blocks: [
        { p: 'A geofence is a shape on the map that a vehicle can be inside or outside of. On its own it does nothing — it becomes useful the moment a rule points at it, and then arrivals and departures come to you instead of you watching for them.' },
        { h2: 'The three shapes', id: 'shapes' },
        { table: { head: ['Shape', 'Use it for'], rows: [
          ['**Polygon**', 'Anything with a real outline: a yard, a site, a district, a customer\'s premises. Click the corners; the last point closes it.'],
          ['**Circle**', 'A point with a radius. Fastest to draw and right for “anywhere near this address”.'],
          ['**Corridor**', 'A route with a width — a delivery run, a permitted road, a pipeline. You draw the centre line and set a buffer in metres on each side.'],
        ] } },
        { h2: 'Drawing one', id: 'draw' },
        { ol: [
          'Choose the type, then draw on the map.',
          'Give it a name you would recognise in an alert at seven in the morning. “Depot” beats “Zone 4”.',
          'Pick a colour. Colour is how a busy map stays readable — one colour per kind of place, not one per zone.',
          'Save.',
        ] },
        { p: 'A saved polygon or circle can be reshaped by dragging its points. A corridor cannot: it is defined by its centre line, and that line is not kept afterwards — to change a corridor you draw a new one.' },
        { callout: 'note', p: 'A shape must not cross itself, and there is an upper size limit. Both restrictions exist because a self-crossing or continent-sized zone has no clear inside, and “inside” is the only question a geofence exists to answer.' },
        { h2: 'What counts as entering and leaving', id: 'transitions' },
        { p: 'A transition is recorded once **two** trusted positions in a row fall on the new side of the edge. One stray fix therefore does not change the state, which is the point. Two consequences follow, and both are deliberate:' },
        { ul: [
          'Positions that failed the validity checks never trigger a transition — see [Position accuracy](kb:position-accuracy). A device with no view of the sky cannot report arriving anywhere.',
          'A vehicle that passes right through a zone between two reports will not register at all. If arrivals at a small zone matter, the vehicle needs to report often enough to land at least once inside it.',
        ] },
        { h2: 'Zones on the map', id: 'display' },
        { p: 'The map draws your zones as a layer, and you can choose which ones to show. On a fleet with a hundred customers, showing all of them buries the vehicles — show the handful you are working with today.' },
        { h2: 'Deleting one', id: 'delete' },
        { callout: 'warning', p: 'Deleting a zone stops every rule that points at it from firing. Past events stay in the record, but there will be no new ones. If you only want quiet for a while, disable the rule instead of deleting the zone.' },
      ],
    },
    lt: {
      title: 'Geozonos — kaip apibrėžti svarbias vietas',
      summary: 'Poligonai, apskritimai ir koridoriai, ką reiškia kirsti ribą ir kaip neleisti šimtui zonų virsti triukšmu.',
      keywords: ['geozona', 'zona', 'poligonas', 'daugiakampis', 'apskritimas', 'koridorius', 'teritorija', 'riba', 'įvažiavimas', 'išvažiavimas'],
      blocks: [
        { p: 'Geozona – tai figūra žemėlapyje, kurios viduje arba išorėje gali būti automobilis. Pati savaime ji nedaro nieko – naudinga tampa tą akimirką, kai į ją nurodo taisyklė; tada atvykimai ir išvykimai ateina pas jus, o ne jūs jų laukiate.' },
        { h2: 'Trys formos', id: 'shapes' },
        { table: { head: ['Forma', 'Kam naudoti'], rows: [
          ['**Poligonas**', 'Viskam, kas turi tikrą kontūrą: kiemui, objektui, rajonui, kliento teritorijai. Spustelėkite kampus; paskutinis taškas ją uždaro.'],
          ['**Apskritimas**', 'Taškui su spinduliu. Greičiausia nubrėžti ir tinka „bet kur netoli šio adreso“.'],
          ['**Koridorius**', 'Maršrutui su pločiu – pristatymo reisui, leistinam keliui, vamzdynui. Brėžiate vidurio liniją ir nurodote buferį metrais į abi puses.'],
        ] } },
        { h2: 'Kaip nubrėžti', id: 'draw' },
        { ol: [
          'Pasirinkite tipą ir brėžkite žemėlapyje.',
          'Suteikite pavadinimą, kurį atpažintumėte pranešime septintą ryto. „Bazė“ geriau nei „4 zona“.',
          'Parinkite spalvą. Spalva – tai, kas leidžia perkrautam žemėlapiui likti įskaitomam: viena spalva vienos rūšies vietoms, o ne viena kiekvienai zonai.',
          'Išsaugokite.',
        ] },
        { p: 'Išsaugotą poligoną ar apskritimą galima pakeisti tempiant jo taškus. Koridoriaus – ne: jį apibrėžia tik vidurio linija, o ji vėliau nesaugoma; norint koridorių pakeisti, brėžiamas naujas.' },
        { callout: 'note', p: 'Figūra negali kirsti pati savęs, ir yra viršutinė dydžio riba. Abu apribojimai egzistuoja todėl, kad pati save kertanti arba žemyno dydžio zona neturi vienareikšmio vidaus, o „viduje“ yra vienintelis klausimas, dėl kurio geozona apskritai egzistuoja.' },
        { h2: 'Kas laikoma įvažiavimu ir išvažiavimu', id: 'transitions' },
        { p: 'Perėjimas įrašomas tik tada, kai **dvi** patikimos pozicijos iš eilės atsiduria naujoje ribos pusėje. Viena atsitiktinė pozicija būsenos nepajudina – būtent to ir siekiama. Iš to seka du dalykai, ir abu sąmoningi:' },
        { ul: [
          'Pozicijos, neišlaikiusios galiojimo patikrų, perėjimo niekada nesukelia – žr. [Pozicijos tikslumas](kb:position-accuracy). Dangaus nematantis įrenginys negali pranešti, kad kur nors atvyko.',
          'Automobilis, kuris tarp dviejų siuntimų pravažiuoja zoną kiaurai, apskritai nebus užfiksuotas. Jei atvykimai į mažą zoną svarbūs, automobilis turi siųsti pakankamai dažnai, kad bent kartą atsidurtų jos viduje.',
        ] },
        { h2: 'Zonos žemėlapyje', id: 'display' },
        { p: 'Žemėlapis piešia jūsų zonas kaip sluoksnį, ir galima pasirinkti, kurias. Kai autoparke šimtas klientų, parodžius visas zonas automobiliai paskęsta – rodykite tas kelias, su kuriomis šiandien dirbate.' },
        { h2: 'Ištrynimas', id: 'delete' },
        { callout: 'warning', p: 'Ištrynus zoną nustoja veikti visos į ją nurodančios taisyklės. Ankstesni įvykiai savo įrašus išlaiko, bet naujų nebus. Jei norite tik laikinos tylos, geriau išjunkite taisyklę, o ne trinkite zoną.' },
      ],
    },
    pl: {
      title: 'Geostrefy — rysowanie miejsc, które mają znaczenie',
      summary: 'Wielokąty, okręgi i korytarze, co znaczy przecięcie granicy i jak sprawić, by sto stref nie stało się szumem.',
      keywords: ['geostrefa', 'strefa', 'wielokąt', 'okrąg', 'korytarz', 'obszar', 'granica', 'wjazd', 'wyjazd'],
      blocks: [
        { p: 'Geostrefa to kształt na mapie — pojazd może być w jego wnętrzu albo poza nim. Sama z siebie nie robi nic — staje się użyteczna w chwili, gdy wskaże ją reguła; wtedy przyjazdy i wyjazdy przychodzą do Ciebie i nie musisz ich pilnować.' },
        { h2: 'Trzy kształty', id: 'shapes' },
        { table: { head: ['Kształt', 'Do czego', ], rows: [
          ['**Wielokąt**', 'Wszystko, co ma realny obrys: plac, teren, dzielnica, posesja klienta. Klikasz narożniki; ostatni punkt zamyka kształt.'],
          ['**Okrąg**', 'Punkt z promieniem. Najszybszy do narysowania i właściwy dla „gdziekolwiek przy tym adresie”.'],
          ['**Korytarz**', 'Trasa z szerokością — stała trasa dostawcza, dozwolona droga, rurociąg. Rysujesz oś, a bufor w metrach ustawiasz po obu stronach.'],
        ] } },
        { h2: 'Rysowanie', id: 'draw' },
        { ol: [
          'Wybierz typ i rysuj na mapie.',
          'Nadaj nazwę, którą rozpoznasz w alercie o siódmej rano. „Baza” jest lepsza niż „Strefa 4”.',
          'Wybierz kolor. Kolor sprawia, że zatłoczona mapa pozostaje czytelna — jeden kolor na rodzaj miejsca, nie jeden na strefę.',
          'Zapisz.',
        ] },
        { p: 'Zapisany wielokąt lub okrąg można przekształcić, przeciągając jego punkty. Korytarza nie: definiuje go wyłącznie oś, a ta nie jest później przechowywana — żeby zmienić korytarz, rysujesz nowy.' },
        { callout: 'note', p: 'Kształt nie może przecinać samego siebie i ma górny limit wielkości. Oba ograniczenia istnieją, bo strefa, która przecina samą siebie, albo strefa wielkości kontynentu nie ma jednoznacznego wnętrza, a „wewnątrz” to jedyne pytanie, dla którego geostrefa w ogóle istnieje.' },
        { h2: 'Co liczy się jako wjazd i wyjazd', id: 'transitions' },
        { p: 'Przejście jest zapisywane dopiero wtedy, gdy **dwie** wiarygodne pozycje z rzędu znajdą się po nowej stronie granicy. Jedna przypadkowa pozycja nie zmienia więc stanu i o to właśnie chodzi. Wynikają z tego dwie rzeczy i obie są celowe:' },
        { ul: [
          'Pozycje, które nie przeszły kontroli poprawności, nigdy nie wywołują przejścia — zobacz [Dokładność pozycji](kb:position-accuracy). Urządzenie, które nie widzi nieba nie może zgłosić, że gdzieś dotarło.',
          'Pojazd, który między dwoma raportami przejedzie strefę na wylot, nie zostanie zarejestrowany w ogóle. Jeśli wjazdy do małej strefy mają znaczenie, pojazd musi raportować dość często, by choć raz znaleźć się w jej wnętrzu.',
        ] },
        { h2: 'Strefy na mapie', id: 'display' },
        { p: 'Mapa rysuje Twoje strefy jako warstwę i możesz wybrać, które. Przy stu klientach pokazanie wszystkich przykrywa pojazdy — pokaż tę garstkę, z którą dziś pracujesz.' },
        { h2: 'Usuwanie', id: 'delete' },
        { callout: 'warning', p: 'Usunięcie strefy zatrzymuje każdą regułę, która ją wskazuje. Dawne zdarzenia zachowują swój zapis, ale nowych nie będzie. Jeśli chcesz tylko chwili ciszy, wyłącz regułę zamiast usuwać strefę.' },
      ],
    },
    de: {
      title: 'Geozonen — Orte zeichnen, auf die es ankommt',
      summary: 'Polygone, Kreise und Korridore, was das Überqueren einer Kante bedeutet und wie hundert Zonen nicht zu Lärm werden.',
      keywords: ['geozone', 'zone', 'polygon', 'kreis', 'korridor', 'gebiet', 'grenze', 'einfahrt', 'ausfahrt'],
      blocks: [
        { p: 'Eine Geozone ist eine Fläche auf der Karte, innerhalb oder außerhalb derer sich ein Fahrzeug befinden kann. Für sich allein tut sie nichts — nützlich wird sie in dem Moment, in dem eine Regel auf sie zeigt; dann kommen Ankünfte und Abfahrten zu Ihnen, statt dass Sie danach schauen.' },
        { h2: 'Die drei Formen', id: 'shapes' },
        { table: { head: ['Form', 'Wofür'], rows: [
          ['**Polygon**', 'Alles mit echtem Umriss: ein Hof, ein Gelände, ein Stadtteil, das Grundstück eines Kunden. Ecken anklicken; der letzte Punkt schließt die Form.'],
          ['**Kreis**', 'Ein Punkt mit Radius. Am schnellsten gezeichnet und richtig für „irgendwo in der Nähe dieser Adresse“.'],
          ['**Korridor**', 'Eine Route mit Breite — eine Tour, eine erlaubte Straße, eine Trasse. Sie zeichnen die Mittellinie und setzen beidseitig einen Puffer in Metern.'],
        ] } },
        { h2: 'Eine zeichnen', id: 'draw' },
        { ol: [
          'Typ wählen, dann auf der Karte zeichnen.',
          'Einen Namen vergeben, den Sie um sieben Uhr morgens in einem Alarm wiedererkennen. „Betriebshof“ schlägt „Zone 4“.',
          'Eine Farbe wählen. Farbe hält eine volle Karte lesbar — eine Farbe je Art von Ort, nicht eine je Zone.',
          'Speichern.',
        ] },
        { p: 'Ein gespeichertes Polygon oder ein Kreis lässt sich durch Ziehen der Punkte umformen. Ein Korridor nicht: Ihn definiert allein seine Mittellinie, und die wird danach nicht aufbewahrt — um einen Korridor zu ändern, zeichnen Sie einen neuen.' },
        { callout: 'note', p: 'Eine Form darf sich nicht selbst schneiden, und es gibt eine Obergrenze für die Größe. Beide Einschränkungen bestehen, weil eine selbstschneidende oder kontinentgroße Zone kein eindeutiges Innen hat — und „innen“ ist die einzige Frage, für die eine Geozone existiert.' },
        { h2: 'Was als Einfahrt und Ausfahrt zählt', id: 'transitions' },
        { p: 'Ein Übergang wird erst festgehalten, wenn **zwei** vertrauenswürdige Positionen nacheinander auf der neuen Seite der Grenze liegen. Eine einzelne Ausreißerposition verschiebt den Zustand also nicht — genau das ist der Zweck. Daraus folgen zwei Dinge, beide gewollt:' },
        { ul: [
          'Positionen, die die Gültigkeitsprüfung nicht bestanden haben, lösen nie einen Übergang aus — siehe [Positionsgenauigkeit](kb:position-accuracy). Ein Gerät ohne freie Sicht zum Himmel kann nirgends eine Ankunft melden.',
          'Ein Fahrzeug, das zwischen zwei Meldungen glatt durch eine Zone fährt, wird gar nicht erfasst. Sind Ankünfte in einer kleinen Zone wichtig, muss das Fahrzeug oft genug melden, um mindestens einmal darin zu landen.',
        ] },
        { h2: 'Zonen auf der Karte', id: 'display' },
        { p: 'Die Karte zeichnet Ihre Zonen als Ebene, und Sie wählen, welche. Bei hundert Kunden begräbt es die Fahrzeuge, wenn Sie alle Zonen einblenden — zeigen Sie die Handvoll, mit der Sie heute arbeiten.' },
        { h2: 'Eine löschen', id: 'delete' },
        { callout: 'warning', p: 'Das Löschen einer Zone verhindert, dass eine darauf zeigende Regel noch auslöst. Vergangene Ereignisse behalten ihren Eintrag, aber neue gibt es nicht. Wollen Sie nur eine Weile Ruhe, deaktivieren Sie die Regel, statt die Zone zu löschen.' },
      ],
    },
  },
}
