import type { KbArticle } from '../types.js'

export const glossary: KbArticle = {
  slug: 'glossary',
  category: 'start',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'Glossary — every term in one place',
      summary: 'Plain-language definitions of the words this product and the tracking industry use, from APN to geofence.',
      keywords: ['glossary', 'terms', 'definitions', 'vocabulary', 'jargon', 'meaning'],
      blocks: [
        { p: 'If a word on a screen is unfamiliar, it is defined here. Terms are grouped by where you meet them.' },
        { h2: 'The hardware', id: 'hardware' },
        { table: { head: ['Term', 'What it means'], rows: [
          ['**Tracker** / device / unit', 'The box in the vehicle. Reads GPS, reads the vehicle, sends over mobile data.'],
          ['**IMEI**', 'The tracker\'s 15-digit serial number. Its identity here — see [What an IMEI is](kb:imei).'],
          ['**SIM**', 'The mobile subscription inside the tracker. Needs a data plan, not a phone plan.'],
          ['**APN**', 'The setting that tells the SIM which mobile gateway to use. Wrong APN = no data, ever — see [SIM cards and APN](kb:sim-and-apn).'],
          ['**Ignition wire**', 'A wire tapped to a circuit that is live only when the engine is on. It is what makes “engine on/off” reliable.'],
          ['**OBD / CAN**', 'The vehicle\'s own data bus. Gives fuel level, mileage, RPM and fault codes when the model supports it — see [CAN and OBD data](kb:can-and-obd).'],
          ['**iButton / RFID**', 'A key fob a driver touches to identify themselves — see [Drivers](kb:drivers).'],
        ] } },
        { h2: 'The positions', id: 'positions' },
        { table: { head: ['Term', 'What it means'], rows: [
          ['**Fix**', 'One calculated position: time, latitude, longitude, speed, satellite count.'],
          ['**Satellites**', 'How many the tracker used for this fix. More is better; zero means the position is a guess and is discarded.'],
          ['**Invalid fix**', 'A position we refuse to trust and never draw or count — see [Position accuracy](kb:position-accuracy).'],
          ['**Record period**', 'How often the tracker saves a position internally.'],
          ['**Send period**', 'How often the tracker uploads what it saved. Different from the record period — see [Reporting intervals](kb:reporting-intervals).'],
          ['**Trail**', 'The recent line behind a vehicle on the live map.'],
        ] } },
        { h2: 'What the platform builds', id: 'derived' },
        { table: { head: ['Term', 'What it means'], rows: [
          ['**Trip**', 'A continuous drive with a start, an end, a distance and a maximum speed — see [How trips are detected](kb:how-trips-are-detected).'],
          ['**Idle**', 'Engine on, vehicle not moving. Counted separately from driving and from parking.'],
          ['**Geofence** / zone', 'A shape you draw on the map. Crossing its edge is an event — see [Geofences](kb:geofences).'],
          ['**Rule**', 'A standing instruction: when this happens, tell these people — see [Rules and alerts](kb:rules-and-alerts).'],
          ['**Event**', 'One thing that happened: entered a zone, went over a limit, lost power, pressed panic.'],
          ['**Cooldown**', 'The quiet period after an alert, so one long problem is one message and not fifty.'],
        ] } },
        { h2: 'The account', id: 'account' },
        { table: { head: ['Term', 'What it means'], rows: [
          ['**Account**', 'A group of vehicles with its own users, zones and reports.'],
          ['**Organization**', 'Everything you own here — one or many accounts, one subscription, one set of admins.'],
          ['**Role**', 'What a login may do: viewer, account manager, organization admin — see [Logins and roles](kb:logins-and-roles).'],
          ['**Audit log**', 'The record of who changed what, and when.'],
          ['**API key**', 'A secret string that lets another system read your data — see [API quick start](kb:api-quickstart).'],
          ['**Webhook**', 'A URL of yours that we call the moment an event happens — see [Webhooks](kb:webhooks).'],
        ] } },
      ],
    },
    lt: {
      title: 'Žodynėlis — visos sąvokos vienoje vietoje',
      summary: 'Paprasta kalba paaiškinti žodžiai, kuriuos vartoja šis produktas ir visa sekimo pramonė – nuo APN iki geozonos.',
      keywords: ['žodynas', 'sąvokos', 'terminai', 'ką reiškia', 'paaiškinimas'],
      blocks: [
        { p: 'Jei ekrane pamatytas žodis nepažįstamas – jis paaiškintas čia. Sąvokos sugrupuotos pagal tai, kur jas sutinkate.' },
        { h2: 'Įranga', id: 'hardware' },
        { table: { head: ['Sąvoka', 'Ką reiškia'], rows: [
          ['**Sekiklis** / įrenginys', 'Dėžutė automobilyje. Skaito GPS, skaito automobilį, siunčia mobiliaisiais duomenimis.'],
          ['**IMEI**', 'Sekiklio 15 skaitmenų serijos numeris. Čia tai jo tapatybė – žr. [Kas yra IMEI](kb:imei).'],
          ['**SIM**', 'Mobiliojo ryšio prenumerata sekiklio viduje. Reikia duomenų plano, ne telefono plano.'],
          ['**APN**', 'Nustatymas, nurodantis SIM kortelei, kurį operatoriaus šliuzą naudoti. Neteisingas APN = duomenų nebus niekada – žr. [SIM kortelės ir APN](kb:sim-and-apn).'],
          ['**Degimo laidas**', 'Laidas, prijungtas prie grandinės, kuri įtampą turi tik varikliui veikiant. Būtent jis padaro „variklis įjungtas / išjungtas“ patikimą.'],
          ['**OBD / CAN**', 'Paties automobilio duomenų magistralė. Duoda kuro lygį, ridą, apsukas ir klaidų kodus, jei modelis palaiko – žr. [CAN ir OBD duomenys](kb:can-and-obd).'],
          ['**iButton / RFID**', 'Raktų pakabukas, kuriuo vairuotojas prisistato – žr. [Vairuotojai](kb:drivers).'],
        ] } },
        { h2: 'Pozicijos', id: 'positions' },
        { table: { head: ['Sąvoka', 'Ką reiškia'], rows: [
          ['**Fiksacija**', 'Viena apskaičiuota pozicija: laikas, platuma, ilguma, greitis, palydovų skaičius.'],
          ['**Palydovai**', 'Kiek jų sekiklis panaudojo šiai fiksacijai. Daugiau – geriau; nulis reiškia, kad pozicija yra spėjimas, ir ji atmetama.'],
          ['**Negaliojanti fiksacija**', 'Pozicija, kuria nepasitikime ir kurios niekada nepiešiame ir neskaičiuojame – žr. [Pozicijos tikslumas](kb:position-accuracy).'],
          ['**Įrašymo periodas**', 'Kaip dažnai sekiklis išsaugo poziciją savo atmintyje.'],
          ['**Siuntimo periodas**', 'Kaip dažnai sekiklis išsiunčia tai, ką išsaugojo. Tai ne tas pat, kas įrašymo periodas – žr. [Siuntimo intervalai](kb:reporting-intervals).'],
          ['**Pėdsakas**', 'Neseniai nueito kelio linija už automobilio gyvame žemėlapyje.'],
        ] } },
        { h2: 'Ką sukuria platforma', id: 'derived' },
        { table: { head: ['Sąvoka', 'Ką reiškia'], rows: [
          ['**Kelionė**', 'Ištisas važiavimas su pradžia, pabaiga, atstumu ir didžiausiu greičiu – žr. [Kaip aptinkamos kelionės](kb:how-trips-are-detected).'],
          ['**Tuščioji eiga**', 'Variklis veikia, automobilis nejuda. Skaičiuojama atskirai nuo važiavimo ir nuo stovėjimo.'],
          ['**Geozona** / zona', 'Jūsų nubrėžta figūra žemėlapyje. Jos ribos kirtimas yra įvykis – žr. [Geozonos](kb:geofences).'],
          ['**Taisyklė**', 'Nuolatinis nurodymas: kai nutinka tai, pranešk tiems – žr. [Taisyklės ir pranešimai](kb:rules-and-alerts).'],
          ['**Įvykis**', 'Vienas nutikimas: įvažiavo į zoną, viršijo greitį, dingo maitinimas, paspaustas pavojaus mygtukas.'],
          ['**Atvėsimo laikas**', 'Tylos tarpas po pranešimo, kad viena ilga problema būtų viena žinutė, o ne penkiasdešimt.'],
        ] } },
        { h2: 'Paskyra', id: 'account' },
        { table: { head: ['Sąvoka', 'Ką reiškia'], rows: [
          ['**Paskyra**', 'Automobilių grupė su savo vartotojais, zonomis ir ataskaitomis.'],
          ['**Organizacija**', 'Viskas, kas čia jūsų – viena ar kelios paskyros, viena prenumerata, vienas administratorių ratas.'],
          ['**Rolė**', 'Ką prisijungimui leidžiama: stebėtojas, paskyros valdytojas, organizacijos administratorius – žr. [Prisijungimai ir rolės](kb:logins-and-roles).'],
          ['**Audito žurnalas**', 'Įrašas, kas ką pakeitė ir kada.'],
          ['**API raktas**', 'Slapta eilutė, leidžianti kitai sistemai skaityti jūsų duomenis – žr. [API pradžia](kb:api-quickstart).'],
          ['**Webhook**', 'Jūsų adresas, kurį iškviečiame tą pačią akimirką, kai įvyksta įvykis – žr. [Webhook\'ai](kb:webhooks).'],
        ] } },
      ],
    },
    pl: {
      title: 'Słowniczek — wszystkie pojęcia w jednym miejscu',
      summary: 'Wyjaśnienia prostym językiem słów używanych przez ten produkt i całą branżę lokalizacji — od APN po geostrefę.',
      keywords: ['słownik', 'pojęcia', 'definicje', 'terminologia', 'znaczenie'],
      blocks: [
        { p: 'Jeśli słowo na ekranie jest nieznane — jest wyjaśnione tutaj. Pojęcia pogrupowano według tego, gdzie się je spotyka.' },
        { h2: 'Sprzęt', id: 'hardware' },
        { table: { head: ['Pojęcie', 'Co oznacza'], rows: [
          ['**Lokalizator** / urządzenie', 'Pudełko w pojeździe. Czyta GPS, czyta pojazd, wysyła danymi komórkowymi.'],
          ['**IMEI**', '15-cyfrowy numer seryjny lokalizatora. Tutaj to jego tożsamość — zobacz [Czym jest IMEI](kb:imei).'],
          ['**SIM**', 'Abonament komórkowy w lokalizatorze. Potrzebny pakiet danych, nie abonament telefoniczny.'],
          ['**APN**', 'Ustawienie mówiące karcie SIM, której bramy operatora użyć. Zły APN = nigdy żadnych danych — zobacz [Karty SIM i APN](kb:sim-and-apn).'],
          ['**Przewód zapłonu**', 'Przewód wpięty w obwód, który ma napięcie tylko przy pracującym silniku. To on czyni „silnik wł./wył.” wiarygodnym.'],
          ['**OBD / CAN**', 'Własna magistrala danych pojazdu. Daje poziom paliwa, przebieg, obroty i kody błędów, jeśli model to obsługuje — zobacz [Dane CAN i OBD](kb:can-and-obd).'],
          ['**iButton / RFID**', 'Brelok, którym kierowca się identyfikuje — zobacz [Kierowcy](kb:drivers).'],
        ] } },
        { h2: 'Pozycje', id: 'positions' },
        { table: { head: ['Pojęcie', 'Co oznacza'], rows: [
          ['**Fix**', 'Jedna wyliczona pozycja: czas, szerokość, długość, prędkość, liczba satelitów.'],
          ['**Satelity**', 'Ile ich lokalizator użył do tego fixa. Więcej znaczy lepiej; zero oznacza, że pozycja to zgadywanie i zostaje odrzucona.'],
          ['**Nieprawidłowy fix**', 'Pozycja, której nie ufamy i której nigdy nie rysujemy ani nie liczymy — zobacz [Dokładność pozycji](kb:position-accuracy).'],
          ['**Okres zapisu**', 'Jak często lokalizator zapisuje pozycję w swojej pamięci.'],
          ['**Okres wysyłki**', 'Jak często lokalizator przesyła to, co zapisał. To co innego niż okres zapisu — zobacz [Częstotliwość raportowania](kb:reporting-intervals).'],
          ['**Ślad**', 'Linia niedawnej trasy za pojazdem na mapie na żywo.'],
        ] } },
        { h2: 'Co buduje platforma', id: 'derived' },
        { table: { head: ['Pojęcie', 'Co oznacza'], rows: [
          ['**Trasa**', 'Ciągły przejazd z początkiem, końcem, dystansem i prędkością maksymalną — zobacz [Jak wykrywane są trasy](kb:how-trips-are-detected).'],
          ['**Praca na postoju**', 'Silnik pracuje, pojazd stoi. Liczone osobno od jazdy i od parkowania.'],
          ['**Geostrefa** / strefa', 'Kształt narysowany przez Ciebie na mapie. Przecięcie jego granicy jest zdarzeniem — zobacz [Geostrefy](kb:geofences).'],
          ['**Reguła**', 'Stała instrukcja: gdy stanie się to, powiadom tych — zobacz [Reguły i alerty](kb:rules-and-alerts).'],
          ['**Zdarzenie**', 'Jedna rzecz, która się stała: wjazd do strefy, przekroczenie limitu, utrata zasilania, przycisk alarmowy.'],
          ['**Odstęp**', 'Okres ciszy po alercie, żeby jeden długi problem był jedną wiadomością, a nie pięćdziesięcioma.'],
        ] } },
        { h2: 'Konto', id: 'account' },
        { table: { head: ['Pojęcie', 'Co oznacza'], rows: [
          ['**Konto**', 'Grupa pojazdów z własnymi użytkownikami, strefami i raportami.'],
          ['**Organizacja**', 'Wszystko, co tu posiadasz — jedno lub wiele kont, jedna subskrypcja, jeden zestaw administratorów.'],
          ['**Rola**', 'Co wolno danemu loginowi: podgląd, menedżer konta, administrator organizacji — zobacz [Loginy i role](kb:logins-and-roles).'],
          ['**Dziennik audytu**', 'Zapis, kto co zmienił i kiedy.'],
          ['**Klucz API**', 'Tajny ciąg pozwalający innemu systemowi czytać Twoje dane — zobacz [Szybki start API](kb:api-quickstart).'],
          ['**Webhook**', 'Twój adres URL, który wywołujemy w chwili wystąpienia zdarzenia — zobacz [Webhooki](kb:webhooks).'],
        ] } },
      ],
    },
    de: {
      title: 'Glossar — alle Begriffe an einem Ort',
      summary: 'Klartext-Definitionen der Wörter, die dieses Produkt und die Ortungsbranche verwenden — von APN bis Geozone.',
      keywords: ['glossar', 'begriffe', 'definitionen', 'fachjargon', 'bedeutung'],
      blocks: [
        { p: 'Wenn ein Wort auf dem Bildschirm unbekannt ist, steht es hier. Die Begriffe sind danach gruppiert, wo sie Ihnen begegnen.' },
        { h2: 'Die Hardware', id: 'hardware' },
        { table: { head: ['Begriff', 'Bedeutung'], rows: [
          ['**Tracker** / Gerät', 'Die Box im Fahrzeug. Liest GPS, liest das Fahrzeug, sendet über Mobilfunkdaten.'],
          ['**IMEI**', 'Die 15-stellige Seriennummer des Trackers. Hier seine Identität — siehe [Was eine IMEI ist](kb:imei).'],
          ['**SIM**', 'Der Mobilfunkvertrag im Tracker. Braucht einen Datentarif, keinen Telefontarif.'],
          ['**APN**', 'Die Einstellung, die der SIM sagt, welches Mobilfunk-Gateway sie nutzt. Falscher APN = nie Daten — siehe [SIM-Karten und APN](kb:sim-and-apn).'],
          ['**Zündungsleitung**', 'Eine Leitung an einem Stromkreis, der nur bei laufendem Motor Spannung führt. Sie macht „Motor an/aus“ verlässlich.'],
          ['**OBD / CAN**', 'Der fahrzeugeigene Datenbus. Liefert Tankfüllstand, Kilometerstand, Drehzahl und Fehlercodes, sofern das Modell es unterstützt — siehe [CAN- und OBD-Daten](kb:can-and-obd).'],
          ['**iButton / RFID**', 'Ein Schlüsselanhänger, mit dem sich ein Fahrer anmeldet — siehe [Fahrer](kb:drivers).'],
        ] } },
        { h2: 'Die Positionen', id: 'positions' },
        { table: { head: ['Begriff', 'Bedeutung'], rows: [
          ['**Fix**', 'Eine berechnete Position: Zeit, Breite, Länge, Geschwindigkeit, Satellitenzahl.'],
          ['**Satelliten**', 'Wie viele der Tracker für diesen Fix genutzt hat. Mehr ist besser; null heißt, die Position ist geraten und wird verworfen.'],
          ['**Ungültiger Fix**', 'Eine Position, der wir nicht trauen und die nie gezeichnet oder gezählt wird — siehe [Positionsgenauigkeit](kb:position-accuracy).'],
          ['**Aufzeichnungsintervall**', 'Wie oft der Tracker eine Position intern speichert.'],
          ['**Meldeintervall**', 'Wie oft der Tracker das Gespeicherte hochlädt. Nicht dasselbe wie das Aufzeichnungsintervall — siehe [Meldeintervalle](kb:reporting-intervals).'],
          ['**Spur**', 'Die jüngste Linie hinter einem Fahrzeug auf der Live-Karte.'],
        ] } },
        { h2: 'Was die Plattform daraus baut', id: 'derived' },
        { table: { head: ['Begriff', 'Bedeutung'], rows: [
          ['**Fahrt**', 'Eine zusammenhängende Fahrt mit Start, Ende, Strecke und Höchstgeschwindigkeit — siehe [Wie Fahrten erkannt werden](kb:how-trips-are-detected).'],
          ['**Leerlauf**', 'Motor an, Fahrzeug steht. Getrennt von Fahren und von Parken gezählt.'],
          ['**Geozone** / Zone', 'Eine von Ihnen gezeichnete Fläche auf der Karte. Das Überqueren ihrer Kante ist ein Ereignis — siehe [Geozonen](kb:geofences).'],
          ['**Regel**', 'Eine Daueranweisung: Wenn dies passiert, diese Personen benachrichtigen — siehe [Regeln und Alarme](kb:rules-and-alerts).'],
          ['**Ereignis**', 'Eine Sache, die passiert ist: Zone betreten, Limit überschritten, Spannungsverlust, Panikknopf gedrückt.'],
          ['**Cooldown**', 'Die Ruhezeit nach einem Alarm, damit ein langes Problem eine Nachricht ergibt und nicht fünfzig.'],
        ] } },
        { h2: 'Das Konto', id: 'account' },
        { table: { head: ['Begriff', 'Bedeutung'], rows: [
          ['**Konto**', 'Eine Gruppe Fahrzeuge mit eigenen Benutzern, Zonen und Berichten.'],
          ['**Organisation**', 'Alles, was Ihnen hier gehört — ein oder mehrere Konten, ein Abonnement, ein Kreis von Admins.'],
          ['**Rolle**', 'Was ein Zugang darf: Betrachter, Kontomanager, Organisations-Admin — siehe [Zugänge und Rollen](kb:logins-and-roles).'],
          ['**Audit-Log**', 'Die Aufzeichnung, wer was wann geändert hat.'],
          ['**API-Schlüssel**', 'Eine geheime Zeichenkette, mit der ein anderes System Ihre Daten lesen darf — siehe [API-Schnellstart](kb:api-quickstart).'],
          ['**Webhook**', 'Eine URL von Ihnen, die wir im Moment eines Ereignisses aufrufen — siehe [Webhooks](kb:webhooks).'],
        ] } },
      ],
    },
  },
}
