import type { KbArticle } from '../types.js'

export const howTripsAreDetected: KbArticle = {
  slug: 'how-trips-are-detected',
  category: 'trips',
  surfaces: { site: true, app: true },
  screen: '/app/trips',
  doc: {
    en: {
      title: 'How a trip is decided',
      summary: 'What starts a trip, what ends it, what counts as idling, and why a short shuffle around the yard is not a journey.',
      keywords: ['trip', 'journey', 'start', 'end', 'idle', 'ignition', 'segmentation', 'missing trip'],
      blocks: [
        { p: 'A tracker sends positions, not trips. Turning one into the other is a judgement, and the judgement is made the same way every time so that today\'s numbers can be compared with last month\'s.' },
        { h2: 'With an ignition wire', id: 'ignition' },
        { p: 'This is the accurate case. The engine starting opens a trip; the engine being off for a couple of minutes closes it. The short pause is deliberate — a stall at a junction, or a driver switching off to open a gate, should not split one delivery run into two trips.' },
        { h2: 'Without an ignition wire', id: 'no-ignition' },
        { p: 'For asset trackers and plug-in devices with nothing to read, movement itself is the signal. A trip opens when the vehicle has been genuinely moving — above walking pace, sustained for about a minute and a half, or after a few hundred metres of travel, whichever comes first. It closes after several minutes with no meaningful displacement.' },
        { callout: 'note', p: 'Both conditions exist so that neither noise nor a red light can open or close a trip. A vehicle stopped at a long traffic light is still on its trip; a vehicle nudged by a car park attendant has not started one.' },
        { h2: 'Idling', id: 'idle' },
        { p: 'Engine on and effectively not moving, for long enough to be deliberate, counts as **idle** time. It is reported separately from driving on each trip, because it is a different cost: fuel burned, hours accumulated, and nothing delivered. Very short stops are not counted as idling — the aim is the ten minutes spent waiting at a loading bay, not the twenty seconds at a give-way sign.' },
        { h2: 'What a trip records', id: 'fields' },
        { ul: [
          'Start and end time and place',
          'Distance, and where that distance came from — see [Distance and odometer](kb:distance-and-odometer)',
          'Maximum and average speed',
          'Idle time within the trip',
          'The driver, where one was identified — see [Drivers](kb:drivers)',
        ] },
        { h2: 'Late data and ongoing trips', id: 'late' },
        { p: 'A vehicle out of coverage delivers its records later, in a burst. Trips affected by that catch-up are rebuilt from the complete data once it arrives — so a trip you looked at while a van was in a tunnel may be correctly longer an hour later. A trip in progress is shown as **ongoing** and its distance keeps growing until it closes.' },
        { h2: 'When a trip is missing', id: 'missing' },
        { ol: [
          'Check the vehicle actually reported during that window — no positions, no trip.',
          'A very short drive may fall under the thresholds. That is deliberate; it prevents a day of yard shuffling appearing as forty journeys.',
          'On a device with no ignition wire, a slow crawl in a car park can look exactly like standing still.',
          'Positions we could not trust are excluded from distance and shape — see [Position accuracy](kb:position-accuracy).',
        ] },
      ],
    },
    lt: {
      title: 'Kaip nusprendžiama, kad tai kelionė',
      summary: 'Kas pradeda kelionę, kas ją baigia, kas laikoma tuščiąja eiga ir kodėl trumpas pasistumdymas kieme nėra reisas.',
      keywords: ['kelionė', 'pradžia', 'pabaiga', 'tuščioji eiga', 'degimas', 'segmentavimas', 'dingusi kelionė'],
      blocks: [
        { p: 'Sekiklis siunčia pozicijas, o ne keliones. Vieno pavertimas kitu yra sprendimas, ir tas sprendimas priimamas visada vienodai, kad šiandienos skaičius būtų galima lyginti su praėjusio mėnesio.' },
        { h2: 'Su degimo laidu', id: 'ignition' },
        { p: 'Tai tikslusis atvejis. Užvestas variklis atveria kelionę; porą minučių išjungtas variklis ją uždaro. Trumpa pauzė yra sąmoninga – užgesęs variklis sankryžoje ar vairuotojas, išjungęs jį atidaryti vartų, neturi vieno pristatymo maršruto suskaldyti į dvi keliones.' },
        { h2: 'Be degimo laido', id: 'no-ignition' },
        { p: 'Turto sekikliams ir kištukiniams įrenginiams, kuriems nėra ko skaityti, signalas yra pats judėjimas. Kelionė atsiveria, kai automobilis tikrai juda – greičiau nei pėsčiomis, išsilaikydamas maždaug pusantros minutės, arba nuvažiavęs kelis šimtus metrų, kas įvyksta pirmiau. Ji užsidaro, kai kelias minutes nebelieka reikšmingo poslinkio.' },
        { callout: 'note', p: 'Abi sąlygos egzistuoja tam, kad nei triukšmas, nei raudonas šviesoforas neatvertų ir neuždarytų kelionės. Prie ilgo šviesoforo stovintis automobilis tebėra kelionėje; aikštelės darbuotojo pastumtas automobilis kelionės nepradėjo.' },
        { h2: 'Tuščioji eiga', id: 'idle' },
        { p: 'Veikiantis variklis ir faktinis nejudėjimas, trunkantis pakankamai ilgai, kad būtų sąmoningas, skaičiuojamas kaip **tuščiosios eigos** laikas. Kiekvienoje kelionėje jis pateikiamas atskirai nuo važiavimo, nes tai kitokia kaina: sudegintas kuras, sukauptos valandos ir nieko nepristatyta. Labai trumpi sustojimai į tuščiąją eigą neįskaitomi – tikslas yra dešimt minučių prie krovos rampos, o ne dvidešimt sekundžių prie „duok kelią“ ženklo.' },
        { h2: 'Ką įrašo kelionė', id: 'fields' },
        { ul: [
          'Pradžios ir pabaigos laiką bei vietą',
          'Atstumą ir tai, iš kur tas atstumas gautas – žr. [Atstumas ir odometras](kb:distance-and-odometer)',
          'Didžiausią ir vidutinį greitį',
          'Tuščiosios eigos laiką kelionės metu',
          'Vairuotoją, jei jis buvo atpažintas – žr. [Vairuotojai](kb:drivers)',
        ] },
        { h2: 'Vėluojantys duomenys ir vykstančios kelionės', id: 'late' },
        { p: 'Be ryšio buvęs automobilis savo įrašus pristato vėliau, vienu pliūpsniu. Šio pasivijimo paliestos kelionės atkeliavus pilniems duomenims perskaičiuojamos iš naujo – tad kelionė, kurią žiūrėjote furgonui esant tunelyje, po valandos teisėtai gali būti ilgesnė. Vykstanti kelionė rodoma kaip **vykstanti**, o jos atstumas auga tol, kol ji užsidaro.' },
        { h2: 'Kai kelionės trūksta', id: 'missing' },
        { ol: [
          'Patikrinkite, ar automobilis tuo metu apskritai siuntė duomenis – nėra pozicijų, nėra kelionės.',
          'Labai trumpas važiavimas gali nesiekti ribų. Tai sąmoninga; taip diena, praleista manevruojant kieme, netampa keturiasdešimt reisų.',
          'Įrenginyje be degimo laido lėtas šliaužimas aikštelėje gali atrodyti lygiai kaip stovėjimas.',
          'Pozicijos, kuriomis negalėjome pasitikėti, į atstumą ir formą neįtraukiamos – žr. [Pozicijos tikslumas](kb:position-accuracy).',
        ] },
      ],
    },
    pl: {
      title: 'Jak rozstrzyga się, że to trasa',
      summary: 'Co zaczyna trasę, co ją kończy, co liczy się jako praca na postoju i dlaczego krótkie manewrowanie po placu to nie przejazd.',
      keywords: ['trasa', 'przejazd', 'początek', 'koniec', 'postój', 'zapłon', 'segmentacja', 'brakująca trasa'],
      blocks: [
        { p: 'Lokalizator wysyła pozycje, a nie trasy. Zamiana jednego w drugie to ocena, i ta ocena zapada zawsze tak samo, żeby dzisiejsze liczby dało się porównać z zeszłomiesięcznymi.' },
        { h2: 'Z przewodem zapłonu', id: 'ignition' },
        { p: 'To przypadek dokładny. Uruchomienie silnika otwiera trasę; wyłączony silnik przez kilka minut ją zamyka. Krótka pauza jest celowa — zgaśnięcie na skrzyżowaniu albo kierowca gaszący silnik, by otworzyć bramę, nie powinny dzielić jednego kursu na dwie trasy.' },
        { h2: 'Bez przewodu zapłonu', id: 'no-ignition' },
        { p: 'Dla lokalizatorów zasobowych i urządzeń wtykowych, które nie mają czego czytać, sygnałem jest sam ruch. Trasa otwiera się, gdy pojazd naprawdę jedzie — szybciej niż pieszo, utrzymując to przez około półtorej minuty, albo po kilkuset metrach przejazdu, cokolwiek nastąpi pierwsze. Zamyka się po kilku minutach bez znaczącego przemieszczenia.' },
        { callout: 'note', p: 'Oba warunki istnieją po to, by ani szum, ani czerwone światło nie otwierały i nie zamykały trasy. Pojazd stojący na długich światłach nadal jest w trasie; pojazd popchnięty przez parkingowego trasy nie zaczął.' },
        { h2: 'Praca na postoju', id: 'idle' },
        { p: 'Silnik pracuje, pojazd faktycznie nie jedzie, i trwa to dość długo, by było celowe — to czas **postoju z pracującym silnikiem**. Na każdej trasie podawany jest osobno od jazdy, bo to inny koszt: spalone paliwo, naliczone godziny i nic dostarczonego. Bardzo krótkie postoje nie są liczone — chodzi o dziesięć minut przy rampie, a nie o dwadzieścia sekund przy znaku ustąp pierwszeństwa.' },
        { h2: 'Co zapisuje trasa', id: 'fields' },
        { ul: [
          'Czas i miejsce początku oraz końca',
          'Dystans i to, skąd ten dystans pochodzi — zobacz [Dystans a licznik](kb:distance-and-odometer)',
          'Prędkość maksymalną i średnią',
          'Czas postoju z pracującym silnikiem w obrębie trasy',
          'Kierowcę, jeśli został zidentyfikowany — zobacz [Kierowcy](kb:drivers)',
        ] },
        { h2: 'Spóźnione dane i trwające trasy', id: 'late' },
        { p: 'Pojazd poza zasięgiem dostarcza swoje zapisy później, jedną paczką. Trasy dotknięte tym nadrobieniem są przeliczane od nowa z kompletnych danych — więc trasa oglądana, gdy bus był w tunelu, godzinę później słusznie może być dłuższa. Trwająca trasa pokazywana jest jako **w toku**, a jej dystans rośnie aż do zamknięcia.' },
        { h2: 'Gdy trasy brakuje', id: 'missing' },
        { ol: [
          'Sprawdź, czy pojazd w tym oknie w ogóle raportował — brak pozycji, brak trasy.',
          'Bardzo krótki przejazd może nie przekroczyć progów. To celowe; zapobiega temu, by dzień manewrowania po placu wyglądał jak czterdzieści kursów.',
          'W urządzeniu bez przewodu zapłonu powolne pełzanie po parkingu wygląda dokładnie jak stanie.',
          'Pozycje, którym nie mogliśmy zaufać, są wyłączone z dystansu i kształtu — zobacz [Dokładność pozycji](kb:position-accuracy).',
        ] },
      ],
    },
    de: {
      title: 'Wie eine Fahrt entschieden wird',
      summary: 'Was eine Fahrt beginnt, was sie beendet, was als Leerlauf zählt und warum ein kurzes Rangieren auf dem Hof keine Fahrt ist.',
      keywords: ['fahrt', 'start', 'ende', 'leerlauf', 'zündung', 'segmentierung', 'fehlende fahrt'],
      blocks: [
        { p: 'Ein Tracker sendet Positionen, keine Fahrten. Das eine ins andere zu übersetzen ist eine Bewertung, und diese Bewertung fällt jedes Mal gleich aus, damit die Zahlen von heute mit denen des Vormonats vergleichbar sind.' },
        { h2: 'Mit Zündungsleitung', id: 'ignition' },
        { p: 'Das ist der genaue Fall. Der startende Motor öffnet eine Fahrt; ein paar Minuten ausgeschalteter Motor schließt sie. Die kurze Pause ist Absicht — ein Abwürgen an der Kreuzung oder ein Fahrer, der zum Toröffnen ausschaltet, soll eine Tour nicht in zwei Fahrten zerlegen.' },
        { h2: 'Ohne Zündungsleitung', id: 'no-ignition' },
        { p: 'Bei Asset-Trackern und Steckgeräten ohne etwas zu lesen ist die Bewegung selbst das Signal. Eine Fahrt öffnet, wenn das Fahrzeug wirklich fährt — schneller als Schrittgeschwindigkeit, etwa anderthalb Minuten anhaltend, oder nach ein paar hundert Metern Wegstrecke, je nachdem was zuerst eintritt. Sie schließt nach mehreren Minuten ohne nennenswerte Ortsveränderung.' },
        { callout: 'note', p: 'Beide Bedingungen gibt es, damit weder Rauschen noch eine rote Ampel eine Fahrt öffnen oder schließen. Ein Fahrzeug an einer langen Ampel ist weiter auf seiner Fahrt; ein vom Parkplatzwärter verschobenes Fahrzeug hat keine begonnen.' },
        { h2: 'Leerlauf', id: 'idle' },
        { p: 'Motor an und faktisch keine Bewegung, lang genug um absichtlich zu sein, zählt als **Leerlauf**. Er wird in jeder Fahrt getrennt vom Fahren ausgewiesen, denn er ist eine andere Kostenart: Kraftstoff verbrannt, Stunden gelaufen, nichts geliefert. Sehr kurze Halte zählen nicht — gemeint sind die zehn Minuten an der Laderampe, nicht die zwanzig Sekunden am Vorfahrtsschild.' },
        { h2: 'Was eine Fahrt festhält', id: 'fields' },
        { ul: [
          'Start- und Endzeit sowie -ort',
          'Strecke — und woher diese Strecke stammt; siehe [Strecke und Kilometerstand](kb:distance-and-odometer)',
          'Höchst- und Durchschnittsgeschwindigkeit',
          'Leerlaufzeit innerhalb der Fahrt',
          'Den Fahrer, sofern erkannt — siehe [Fahrer](kb:drivers)',
        ] },
        { h2: 'Späte Daten und laufende Fahrten', id: 'late' },
        { p: 'Ein Fahrzeug ohne Netz liefert seine Datensätze später, in einem Schub. Von diesem Nachholen betroffene Fahrten werden aus den vollständigen Daten neu aufgebaut — eine Fahrt, die Sie ansahen, während ein Transporter im Tunnel war, kann eine Stunde später zu Recht länger sein. Eine laufende Fahrt wird als **laufend** ausgewiesen, und ihre Strecke wächst bis zum Abschluss.' },
        { h2: 'Wenn eine Fahrt fehlt', id: 'missing' },
        { ol: [
          'Prüfen, ob das Fahrzeug in diesem Zeitfenster überhaupt gemeldet hat — keine Positionen, keine Fahrt.',
          'Eine sehr kurze Fahrt kann unter den Schwellen bleiben. Das ist Absicht; sonst erschiene ein Tag Rangieren als vierzig Fahrten.',
          'Bei einem Gerät ohne Zündungsleitung sieht langsames Kriechen auf dem Parkplatz genau wie Stehen aus.',
          'Positionen, denen wir nicht trauen konnten, fließen weder in Strecke noch Form ein — siehe [Positionsgenauigkeit](kb:position-accuracy).',
        ] },
      ],
    },
  },
}
