import type { KbArticle } from '../types.js'

export const howTrackingWorks: KbArticle = {
  slug: 'how-tracking-works',
  category: 'start',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'How GPS tracking actually works',
      summary: 'The four steps between a vehicle moving and a dot moving on your screen — and what can go wrong at each one.',
      keywords: ['gps', 'satellite', 'gprs', 'how it works', 'basics', 'signal'],
      blocks: [
        { p: 'Nothing in {product} is magic, and knowing the four steps is most of what you need to diagnose a problem yourself. A tracker is a small computer with two radios: one listens to satellites, the other talks on a mobile network.' },
        { h2: 'Step 1 — the tracker works out where it is', id: 'fix' },
        { p: 'The GPS receiver listens for satellites overhead. Once it hears enough of them — four is the practical minimum — it can compute a position. That result is called a **fix**. A fix carries a time, a latitude, a longitude, a speed and the number of satellites used.' },
        { p: 'A tracker that has just been powered up in a new country can take a few minutes to get its first fix. One parked in an underground garage may never get one. This step has nothing to do with your SIM card or your subscription — it is the tracker and the sky.' },
        { h2: 'Step 2 — the tracker stores the fix', id: 'record' },
        { p: 'Trackers do not send every fix the moment they take it; that would drain the battery and the data plan. They **record** on a rule — every so many seconds, every so many metres, or whenever the vehicle turns sharply — and keep the records in internal memory.' },
        { p: 'This is why a vehicle can be perfectly healthy and still be a minute or two "behind" on the map. See [Reporting intervals](kb:reporting-intervals) for the settings that control it.' },
        { h2: 'Step 3 — the tracker sends what it stored', id: 'send' },
        { p: 'On a separate schedule, the tracker opens a connection over the mobile network and sends everything it has saved since last time, as one batch. {product} stores the batch and confirms it; only then does the tracker delete its copy. That handshake is why a van that drives through a tunnel or a dead-zone loses nothing: the records queue up in the tracker and arrive late, in the right order, when signal returns.' },
        { callout: 'note', p: 'A tracker that has been out of coverage for a day will deliver a day of history in one burst. Your map jumps, your trip list fills in, and nothing was lost.' },
        { h2: 'Step 4 — {product} turns records into answers', id: 'process' },
        { p: 'Raw positions are not very useful on their own. As each batch arrives, {product} works out whether the vehicle is on a trip, whether it entered or left one of your zones, whether it went over a speed limit you set, and whether anything you asked to be told about has happened. That is what fills the map, the trip list, the events feed and the reports.' },
        { h2: 'What breaks, and where', id: 'failures' },
        { table: { head: ['Symptom', 'Which step', 'Start here'], rows: [
          ['Vehicle shown in the wrong place, or in the sea', 'Step 1', '[Position accuracy](kb:position-accuracy)'],
          ['Position is a few minutes old, all the time', 'Step 2', '[Reporting intervals](kb:reporting-intervals)'],
          ['Nothing at all since installation', 'Step 3', '[Device not reporting](kb:device-not-reporting)'],
          ['Positions arrive but there are no trips', 'Step 4', '[How trips are detected](kb:how-trips-are-detected)'],
        ] } },
      ],
    },
    lt: {
      title: 'Kaip iš tikrųjų veikia GPS sekimas',
      summary: 'Keturi žingsniai nuo judančio automobilio iki judančio taško ekrane — ir kas kiekviename gali sugesti.',
      keywords: ['gps', 'palydovas', 'gprs', 'kaip veikia', 'pagrindai', 'signalas'],
      blocks: [
        { p: '{product} nėra jokios magijos, o šių keturių žingsnių žinojimas – didžioji dalis to, ko reikia patiems išsiaiškinti problemą. Seklys – tai mažas kompiuteris su dviem radijo imtuvais: vienas klausosi palydovų, kitas kalba mobiliuoju ryšiu.' },
        { h2: '1 žingsnis — seklys nustato, kur yra', id: 'fix' },
        { p: 'GPS imtuvas klausosi virš galvos skriejančių palydovų. Išgirdęs pakankamai – praktinis minimumas yra keturi – jis gali apskaičiuoti poziciją. Šis rezultatas vadinamas **fiksacija**. Fiksacijoje yra laikas, platuma, ilguma, greitis ir naudotų palydovų skaičius.' },
        { p: 'Seklys, ką tik įjungtas naujoje šalyje, pirmos fiksacijos gali ieškoti kelias minutes. Stovintis požeminėje aikštelėje jos gali negauti niekada. Šis žingsnis niekaip nesusijęs su jūsų SIM kortele ar prenumerata – tai tik seklys ir dangus.' },
        { h2: '2 žingsnis — seklys išsaugo fiksaciją', id: 'record' },
        { p: 'Sekliai nesiunčia kiekvienos fiksacijos iškart – taip išsektų ir akumuliatorius, ir duomenų planas. Jie **įrašo** pagal taisyklę – kas tiek sekundžių, kas tiek metrų arba staigiai pasukus – ir laiko įrašus vidinėje atmintyje.' },
        { p: 'Būtent todėl automobilis gali būti visiškai tvarkingas ir vis tiek žemėlapyje „vėluoti" minutę kitą. Žr. [Siuntimo intervalai](kb:reporting-intervals) apie nustatymus, kurie tam vadovauja.' },
        { h2: '3 žingsnis — seklys išsiunčia tai, ką sukaupė', id: 'send' },
        { p: 'Pagal atskirą grafiką seklys užmezga ryšį mobiliuoju tinklu ir vienu paketu išsiunčia viską, ką išsaugojo nuo praėjusio karto. {product} paketą įrašo ir patvirtina; tik tada seklys ištrina savo kopiją. Dėl šio rankos paspaudimo furgonas, pravažiavęs tunelį ar ryšio duobę, nieko nepraranda: įrašai laukia eilėje seklyje ir atkeliauja vėliau, teisinga tvarka, kai ryšys grįžta.' },
        { callout: 'note', p: 'Parą be ryšio buvęs seklys parą istorijos pristatys vienu ypu. Žemėlapis šokteli, kelionių sąrašas užsipildo, o nieko neprarasta.' },
        { h2: '4 žingsnis — {product} iš įrašų padaro atsakymus', id: 'process' },
        { p: 'Vien žalios pozicijos naudos duoda nedaug. Atkeliavus kiekvienam paketui, {product} nustato, ar automobilis važiuoja kelionę, ar įvažiavo į kurią nors jūsų zoną arba iš jos išvažiavo, ar viršijo jūsų nustatytą greitį ir ar neįvyko kas nors, apie ką prašėte pranešti. Tai ir užpildo žemėlapį, kelionių sąrašą, įvykių juostą ir ataskaitas.' },
        { h2: 'Kas genda ir kurioje vietoje', id: 'failures' },
        { table: { head: ['Požymis', 'Kuris žingsnis', 'Pradėkite nuo'], rows: [
          ['Automobilis rodomas ne ten arba jūroje', '1 žingsnis', '[Pozicijos tikslumas](kb:position-accuracy)'],
          ['Pozicija nuolat kelių minučių senumo', '2 žingsnis', '[Siuntimo intervalai](kb:reporting-intervals)'],
          ['Nuo sumontavimo išvis nieko nėra', '3 žingsnis', '[Įrenginys nesiunčia duomenų](kb:device-not-reporting)'],
          ['Pozicijos ateina, bet kelionių nėra', '4 žingsnis', '[Kaip aptinkamos kelionės](kb:how-trips-are-detected)'],
        ] } },
      ],
    },
    pl: {
      title: 'Jak naprawdę działa lokalizacja GPS',
      summary: 'Cztery kroki od jadącego pojazdu do poruszającej się kropki na ekranie — i co może się zepsuć na każdym z nich.',
      keywords: ['gps', 'satelita', 'gprs', 'jak to działa', 'podstawy', 'sygnał'],
      blocks: [
        { p: 'W {product} nie ma żadnej magii, a znajomość tych czterech kroków to większość tego, czego trzeba, by samodzielnie zdiagnozować problem. Lokalizator to mały komputer z dwoma radiami: jedno słucha satelitów, drugie rozmawia w sieci komórkowej.' },
        { h2: 'Krok 1 — lokalizator ustala, gdzie jest', id: 'fix' },
        { p: 'Odbiornik GPS nasłuchuje satelitów nad głową. Gdy usłyszy ich dość — praktyczne minimum to cztery — może obliczyć pozycję. Ten wynik nazywa się **fixem**. Fix zawiera czas, szerokość i długość geograficzną, prędkość oraz liczbę użytych satelitów.' },
        { p: 'Lokalizator dopiero co włączony w nowym kraju może szukać pierwszego fixa kilka minut. Ten zaparkowany w garażu podziemnym może go nie znaleźć nigdy. Ten krok nie ma nic wspólnego z kartą SIM ani abonamentem — to tylko lokalizator i niebo.' },
        { h2: 'Krok 2 — lokalizator zapisuje fix', id: 'record' },
        { p: 'Lokalizatory nie wysyłają każdego fixa od razu; to wyczerpałoby baterię i pakiet danych. **Zapisują** według reguły — co tyle sekund, co tyle metrów albo przy ostrym skręcie — i trzymają zapisy w pamięci wewnętrznej.' },
        { p: 'Dlatego pojazd może być całkowicie sprawny i mimo to „spóźniać się" na mapie o minutę czy dwie. Zobacz [Częstotliwość raportowania](kb:reporting-intervals) — to ustawienia, które tym sterują.' },
        { h2: 'Krok 3 — lokalizator wysyła to, co zapisał', id: 'send' },
        { p: 'Według osobnego harmonogramu lokalizator otwiera połączenie w sieci komórkowej i wysyła wszystko, co zgromadził od ostatniego razu, jedną paczką. {product} zapisuje paczkę i ją potwierdza; dopiero wtedy lokalizator kasuje swoją kopię. To potwierdzenie sprawia, że auto przejeżdżające tunel albo martwą strefę nic nie traci: zapisy czekają w kolejce w urządzeniu i docierają później, we właściwej kolejności, gdy wróci zasięg.' },
        { callout: 'note', p: 'Lokalizator, który był dobę poza zasięgiem, dostarczy dobę historii jednym rzutem. Mapa przeskakuje, lista tras się wypełnia — i nic nie zginęło.' },
        { h2: 'Krok 4 — {product} zamienia zapisy w odpowiedzi', id: 'process' },
        { p: 'Same surowe pozycje niewiele dają. Przy każdej nadchodzącej paczce {product} ustala, czy pojazd jest w trasie, czy wjechał do jednej z Twoich stref lub z niej wyjechał, czy przekroczył ustawiony limit prędkości i czy nie wydarzyło się coś, o czym prosiłeś Cię powiadomić. To wypełnia mapę, listę tras, strumień zdarzeń i raporty.' },
        { h2: 'Co się psuje i gdzie', id: 'failures' },
        { table: { head: ['Objaw', 'Który krok', 'Zacznij tutaj'], rows: [
          ['Pojazd w złym miejscu albo na morzu', 'Krok 1', '[Dokładność pozycji](kb:position-accuracy)'],
          ['Pozycja stale sprzed kilku minut', 'Krok 2', '[Częstotliwość raportowania](kb:reporting-intervals)'],
          ['Od montażu zupełnie nic', 'Krok 3', '[Urządzenie nie raportuje](kb:device-not-reporting)'],
          ['Pozycje przychodzą, ale nie ma tras', 'Krok 4', '[Jak wykrywane są trasy](kb:how-trips-are-detected)'],
        ] } },
      ],
    },
    de: {
      title: 'Wie GPS-Ortung wirklich funktioniert',
      summary: 'Die vier Schritte zwischen einem fahrenden Fahrzeug und einem wandernden Punkt auf dem Bildschirm — und was bei jedem schiefgehen kann.',
      keywords: ['gps', 'satellit', 'gprs', 'funktionsweise', 'grundlagen', 'signal'],
      blocks: [
        { p: 'An {product} ist nichts magisch, und wer diese vier Schritte kennt, kann die meisten Probleme selbst einordnen. Ein Tracker ist ein kleiner Computer mit zwei Funkteilen: eines hört Satelliten zu, das andere spricht im Mobilfunknetz.' },
        { h2: 'Schritt 1 — der Tracker bestimmt seinen Ort', id: 'fix' },
        { p: 'Der GPS-Empfänger hört auf Satelliten über sich. Sobald er genug davon hört — praktisch mindestens vier — kann er eine Position berechnen. Dieses Ergebnis heißt **Fix**. Ein Fix enthält Zeit, Breiten- und Längengrad, Geschwindigkeit und die Zahl der genutzten Satelliten.' },
        { p: 'Ein Tracker, der gerade in einem neuen Land eingeschaltet wurde, braucht für den ersten Fix manchmal einige Minuten. Einer in einer Tiefgarage bekommt vielleicht nie einen. Dieser Schritt hat nichts mit SIM-Karte oder Abo zu tun — hier zählen nur Tracker und Himmel.' },
        { h2: 'Schritt 2 — der Tracker speichert den Fix', id: 'record' },
        { p: 'Tracker senden nicht jeden Fix sofort; das würde Akku und Datentarif aufbrauchen. Sie **speichern** nach einer Regel — alle so viele Sekunden, alle so viele Meter oder bei scharfen Kurven — und halten die Datensätze im internen Speicher.' },
        { p: 'Deshalb kann ein Fahrzeug völlig gesund sein und auf der Karte trotzdem ein bis zwei Minuten „hinterherhinken". Siehe [Sendeintervalle](kb:reporting-intervals) für die Einstellungen dahinter.' },
        { h2: 'Schritt 3 — der Tracker sendet das Gespeicherte', id: 'send' },
        { p: 'Nach einem eigenen Zeitplan baut der Tracker eine Verbindung über das Mobilfunknetz auf und schickt alles Gesammelte als ein Paket. {product} speichert das Paket und bestätigt es; erst dann löscht der Tracker seine Kopie. Dieser Handschlag ist der Grund, warum ein Transporter im Tunnel oder Funkloch nichts verliert: die Datensätze warten im Gerät und kommen später, in der richtigen Reihenfolge, sobald das Netz zurück ist.' },
        { callout: 'note', p: 'Ein Tracker, der einen Tag ohne Netz war, liefert einen Tag Historie in einem Schwung. Die Karte springt, die Fahrtenliste füllt sich — verloren ging nichts.' },
        { h2: 'Schritt 4 — {product} macht aus Datensätzen Antworten', id: 'process' },
        { p: 'Rohe Positionen allein bringen wenig. Mit jedem eintreffenden Paket ermittelt {product}, ob das Fahrzeug auf einer Fahrt ist, ob es eine Ihrer Zonen betreten oder verlassen hat, ob es ein von Ihnen gesetztes Tempolimit überschritten hat und ob etwas passiert ist, worüber Sie informiert werden wollten. Das füllt Karte, Fahrtenliste, Ereignisstrom und Berichte.' },
        { h2: 'Was ausfällt — und wo', id: 'failures' },
        { table: { head: ['Symptom', 'Welcher Schritt', 'Hier anfangen'], rows: [
          ['Fahrzeug am falschen Ort oder im Meer', 'Schritt 1', '[Positionsgenauigkeit](kb:position-accuracy)'],
          ['Position ständig einige Minuten alt', 'Schritt 2', '[Sendeintervalle](kb:reporting-intervals)'],
          ['Seit dem Einbau überhaupt nichts', 'Schritt 3', '[Gerät meldet sich nicht](kb:device-not-reporting)'],
          ['Positionen kommen an, aber keine Fahrten', 'Schritt 4', '[Wie Fahrten erkannt werden](kb:how-trips-are-detected)'],
        ] } },
      ],
    },
  },
}
