import type { KbArticle } from '../types.js'

export const imei: KbArticle = {
  slug: 'imei',
  category: 'devices',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'What an IMEI is, and why it matters here',
      summary: 'The 15-digit number that is the tracker\'s identity — where to find it, and what happens when it is wrong.',
      keywords: ['imei', 'serial number', 'identity', 'label', 'registration', '15 digits'],
      blocks: [
        { p: 'An **IMEI** is a 15-digit serial number burned into the tracker at the factory. Every device that talks on a mobile network has one, and no two are the same.' },
        { h2: 'Why we ask for it', id: 'why' },
        { p: 'When a tracker connects, the very first thing it says is its IMEI. That is how {product} knows whose vehicle just spoke. Nothing else in the message identifies you: not the SIM, not the phone number, not the vehicle name. Register the right IMEI and everything works; register a wrong one and the vehicle never appears, no matter how correct the rest of the setup is.' },
        { h2: 'Where to find it', id: 'find' },
        { ul: [
          'On the sticker on the tracker itself — usually labelled IMEI, sometimes next to a barcode.',
          'On the box the tracker came in.',
          'In the tracker\'s reply to a `getinfo` command sent by SMS, if it is already powered and has a SIM.',
        ] },
        { callout: 'warning', p: 'It is not the SIM card number. A SIM has an **ICCID** (19–20 digits, printed on the plastic) and often a phone number. Neither is the IMEI, and typing one of them here registers a device that will never connect.' },
        { h2: 'One IMEI, one place', id: 'unique' },
        { p: 'An IMEI can be registered in exactly one account at a time — anywhere on the platform, not just in yours. If it is already taken, you get “That IMEI is already registered”, which almost always means one of three things:' },
        { ul: [
          'The device is still registered to the previous owner or to a demo account. It has to be released there first.',
          'You already added it, under a different vehicle name.',
          'A digit is wrong — 15 digits are easy to mistype, and 0/O and 1/I are the usual culprits.',
        ] },
        { h2: 'A device that connects but is not registered', id: 'quarantine' },
        { p: 'If a tracker connects with an IMEI nobody has registered, {product} does not throw it away silently. It is held in a **quarantine** list with the number of attempts it has made, so an admin can claim it into the right account with one click. That list is the fastest way to fix a mistyped IMEI: the real number is sitting in it, exactly as the device sent it.' },
      ],
    },
    lt: {
      title: 'Kas yra IMEI ir kodėl jis čia svarbus',
      summary: '15 skaitmenų numeris, kuris yra sekiklio tapatybė – kur jį rasti ir kas nutinka, kai jis neteisingas.',
      keywords: ['imei', 'serijos numeris', 'tapatybė', 'etiketė', 'registracija', '15 skaitmenų'],
      blocks: [
        { p: '**IMEI** – tai 15 skaitmenų serijos numeris, gamykloje įrašytas į sekiklį. Jį turi kiekvienas mobiliuoju tinklu kalbantis įrenginys, ir nėra dviejų vienodų.' },
        { h2: 'Kodėl jo prašome', id: 'why' },
        { p: 'Prisijungęs sekiklis pirmiausia pasako savo IMEI. Būtent taip {product} sužino, kieno automobilis ką tik prabilo. Daugiau niekas žinutėje jūsų neįvardija: nei SIM, nei telefono numeris, nei automobilio pavadinimas. Užregistravote teisingą IMEI – viskas veikia; užregistravote klaidingą – automobilis nepasirodys, kad ir kaip teisingai būtų sutvarkyta visa kita.' },
        { h2: 'Kur jį rasti', id: 'find' },
        { ul: [
          'Ant lipduko pačiame sekiklyje – dažniausiai su užrašu IMEI, kartais šalia brūkšninio kodo.',
          'Ant dėžutės, kurioje sekiklis atkeliavo.',
          'Nusiuntus sekikliui SMS komandą `getinfo`, jei jis jau įjungtas ir turi SIM.',
        ] },
        { callout: 'warning', p: 'Tai ne SIM kortelės numeris. SIM turi **ICCID** (19–20 skaitmenų, atspausdintas ant plastiko) ir dažnai telefono numerį. Nė vienas iš jų nėra IMEI, ir įvedę bet kurį iš jų čia užregistruosite įrenginį, kuris niekada neprisijungs.' },
        { h2: 'Vienas IMEI – viena vieta', id: 'unique' },
        { p: 'Vienu metu IMEI gali būti užregistruotas lygiai vienoje paskyroje – bet kur platformoje, ne tik jūsų. Jei jis jau užimtas, pamatysite „Toks IMEI jau užregistruotas“, o tai beveik visada reiškia vieną iš trijų dalykų:' },
        { ul: [
          'Įrenginys tebėra užregistruotas ankstesnio savininko arba demonstracinėje paskyroje. Pirmiausia jį reikia ten atlaisvinti.',
          'Jūs jį jau pridėjote, tik kitu automobilio pavadinimu.',
          'Klaidingas vienas skaitmuo – renkant 15 skaitmenų lengva suklysti, o dažniausi kaltininkai yra 0/O ir 1/I.',
        ] },
        { h2: 'Įrenginys prisijungia, bet neužregistruotas', id: 'quarantine' },
        { p: 'Jei sekiklis prisijungia su IMEI, kurio niekas neužregistravo, {product} jo tyliai neišmeta. Jis laikomas **karantino** sąraše kartu su bandymų skaičiumi, kad administratorius vienu paspaudimu galėtų jį priskirti teisingai paskyrai. Šis sąrašas – greičiausias būdas ištaisyti klaidingai įvestą IMEI: tikrasis numeris jame jau yra, parašytas lygiai taip, kaip jį pasako pats įrenginys.' },
      ],
    },
    pl: {
      title: 'Czym jest IMEI i dlaczego jest tu ważny',
      summary: '15-cyfrowy numer będący tożsamością lokalizatora — gdzie go znaleźć i co się dzieje, gdy jest błędny.',
      keywords: ['imei', 'numer seryjny', 'tożsamość', 'etykieta', 'rejestracja', '15 cyfr'],
      blocks: [
        { p: '**IMEI** to 15-cyfrowy numer seryjny wypalony w lokalizatorze w fabryce. Ma go każde urządzenie korzystające z sieci komórkowej i nie ma dwóch takich samych.' },
        { h2: 'Dlaczego o niego prosimy', id: 'why' },
        { p: 'Gdy lokalizator się łączy, pierwszą rzeczą, którą mówi, jest jego IMEI. Tak {product} wie, czyj pojazd właśnie się odezwał. Nic innego w komunikacie Cię nie identyfikuje: ani SIM, ani numer telefonu, ani nazwa pojazdu. Zarejestruj właściwy IMEI, a wszystko działa; zarejestruj zły, a pojazd nigdy się nie pojawi, choćby cała reszta konfiguracji była poprawna.' },
        { h2: 'Gdzie go znaleźć', id: 'find' },
        { ul: [
          'Na naklejce na samym lokalizatorze — zwykle opisanej jako IMEI, czasem obok kodu kreskowego.',
          'Na pudełku, w którym przyszedł.',
          'Wysyłając do lokalizatora SMS-em polecenie `getinfo`, jeśli jest już zasilony i ma kartę SIM.',
        ] },
        { callout: 'warning', p: 'To nie jest numer karty SIM. Karta SIM ma **ICCID** (19–20 cyfr, nadrukowany na plastiku), a często też numer telefonu. Żaden z nich nie jest IMEI, a wpisanie ich tutaj rejestruje urządzenie, które nigdy się nie połączy.' },
        { h2: 'Jeden IMEI, jedno miejsce', id: 'unique' },
        { p: 'IMEI może być zarejestrowany na dokładnie jednym koncie naraz — gdziekolwiek na platformie, nie tylko u Ciebie. Jeśli jest już zajęty, zobaczysz „Ten IMEI jest już zarejestrowany”, co prawie zawsze oznacza jedną z trzech rzeczy:' },
        { ul: [
          'Urządzenie wciąż jest zarejestrowane na poprzedniego właściciela albo na konto demo. Najpierw musi zostać tam zwolnione.',
          'Już je dodałeś, pod inną nazwą pojazdu.',
          'Jedna cyfra jest zła — przy 15 cyfrach łatwo o pomyłkę, a zwykli winowajcy to 0/O i 1/I.',
        ] },
        { h2: 'Urządzenie łączy się, ale nie jest zarejestrowane', id: 'quarantine' },
        { p: 'Jeśli lokalizator łączy się z IMEI, którego nikt nie zarejestrował, {product} nie wyrzuca go po cichu. Trafia na listę **kwarantanny** wraz z liczbą prób, żeby administrator mógł go jednym kliknięciem przypisać do właściwego konta. Ta lista to najszybszy sposób naprawy błędnie wpisanego IMEI: prawdziwy numer już tam leży, zapisany dokładnie tak, jak podaje go urządzenie.' },
      ],
    },
    de: {
      title: 'Was eine IMEI ist — und warum sie hier zählt',
      summary: 'Die 15-stellige Nummer, die die Identität des Trackers ist — wo sie steht und was passiert, wenn sie falsch ist.',
      keywords: ['imei', 'seriennummer', 'identität', 'etikett', 'registrierung', '15 stellen'],
      blocks: [
        { p: 'Eine **IMEI** ist eine 15-stellige Seriennummer, die im Werk in den Tracker gebrannt wird. Jedes Gerät, das im Mobilfunknetz spricht, hat eine, und keine zwei sind gleich.' },
        { h2: 'Warum wir danach fragen', id: 'why' },
        { p: 'Wenn ein Tracker sich verbindet, ist das Erste, was er sagt, seine IMEI. So weiß {product}, wessen Fahrzeug sich gerade gemeldet hat. Nichts sonst in der Nachricht identifiziert Sie: weder die SIM noch die Rufnummer noch der Fahrzeugname. Ist die IMEI richtig registriert, funktioniert alles; ist sie falsch, taucht das Fahrzeug nie auf, so korrekt der Rest der Einrichtung auch ist.' },
        { h2: 'Wo sie steht', id: 'find' },
        { ul: [
          'Auf dem Aufkleber am Tracker selbst — meist mit IMEI beschriftet, manchmal neben einem Barcode.',
          'Auf der Verpackung, in der der Tracker kam.',
          'Per SMS-Befehl `getinfo` an den Tracker, sofern er schon Strom und eine SIM hat.',
        ] },
        { callout: 'warning', p: 'Es ist nicht die Nummer der SIM-Karte. Eine SIM hat eine **ICCID** (19–20 Stellen, auf dem Plastik aufgedruckt) und oft eine Rufnummer. Keine davon ist die IMEI — wer sie hier einträgt, registriert ein Gerät, das sich nie verbinden wird.' },
        { h2: 'Eine IMEI, ein Ort', id: 'unique' },
        { p: 'Eine IMEI kann immer nur in genau einem Konto registriert sein — irgendwo auf der Plattform, nicht nur in Ihrem. Ist sie belegt, erscheint „Diese IMEI ist bereits registriert“, und das bedeutet fast immer eines von drei Dingen:' },
        { ul: [
          'Das Gerät ist noch beim Vorbesitzer oder in einem Demokonto registriert. Dort muss es zuerst freigegeben werden.',
          'Sie haben es bereits hinzugefügt, unter einem anderen Fahrzeugnamen.',
          'Eine Ziffer stimmt nicht — bei 15 Stellen vertippt man sich leicht, üblich sind 0/O und 1/I.',
        ] },
        { h2: 'Ein Gerät verbindet sich, ist aber nicht registriert', id: 'quarantine' },
        { p: 'Verbindet sich ein Tracker mit einer IMEI, die niemand registriert hat, wirft {product} sie nicht stillschweigend weg. Sie landet mit der Zahl ihrer Versuche in einer **Quarantäne**-Liste, sodass ein Admin sie mit einem Klick ins richtige Konto übernehmen kann. Diese Liste ist der schnellste Weg, eine vertippte IMEI zu korrigieren: Die echte Nummer liegt schon darin, genau so geschrieben, wie das Gerät sie nennt.' },
      ],
    },
  },
}
