import type { KbArticle } from '../types.js'

export const loginsAndRoles: KbArticle = {
  slug: 'logins-and-roles',
  category: 'start',
  surfaces: { site: true, app: true },
  screen: '/app/settings',
  doc: {
    en: {
      title: 'Logins, roles and accounts',
      summary: 'Who can see which vehicles, who can change things, and how to give someone access without giving them everything.',
      keywords: ['user', 'permission', 'role', 'access', 'password', 'account', 'viewer', 'admin'],
      blocks: [
        { p: 'Three ideas, and they are easy to mix up. **Account** is a set of vehicles. **Login** is a person\'s e-mail and password. **Role** is what that person is allowed to do.' },
        { h2: 'Accounts group vehicles', id: 'accounts' },
        { p: 'Most small fleets need exactly one account and never think about this again. An account matters when the vehicles belong to different customers, sites or legal entities: each account has its own vehicles, its own zones, its own reports and its own logins, and nothing crosses between them.' },
        { callout: 'note', p: 'If you resell tracking, one account per customer is the whole model — see [Customer accounts](kb:customer-accounts).' },
        { h2: 'The three roles', id: 'roles' },
        { table: { head: ['Role', 'Can see', 'Can change'], rows: [
          ['**Viewer**', 'The map, trips, events and reports of their account', 'Nothing. A safe login for a dispatcher, a customer, or an accountant.'],
          ['**Account manager**', 'Everything in their account', 'Vehicles, drivers, zones, rules, maintenance — the day-to-day.'],
          ['**Organization admin**', 'Every account in the organisation', 'Everything, plus billing, logins, branding and integrations.'],
        ] } },
        { p: 'A role is chosen when the login is created and can be changed later. An admin can only grant a role below their own, so nobody can quietly promote themselves.' },
        { h2: 'Adding someone', id: 'add' },
        { ol: [
          'Open the account you want them to have access to.',
          'Add a login with their e-mail address and a starting password.',
          'Pick the role. When in doubt pick **Viewer** — it is the one that cannot break anything.',
          'Hand them the password. They change it themselves under Settings → Security once signed in.',
        ] },
        { h2: 'Removing someone', id: 'remove' },
        { p: 'Remove the login. It takes effect immediately: their active sessions stop working on the next request, not at some later expiry. Their history — what they did, and when — stays in the audit log, which is the point of having one.' },
        { h2: 'Passwords and sign-in', id: 'passwords' },
        { ul: [
          'Passwords are at least 8 characters and are never visible to anyone, including an admin. An admin can set a new one; nobody can read the old one.',
          'A forgotten password is reset from the sign-in page. The link is e-mailed and expires.',
          'A brand-new self-service account must confirm its e-mail address before it can sign in. Until it does, sign-in is refused — deliberately without saying which of the two things is wrong.',
        ] },
      ],
    },
    lt: {
      title: 'Prisijungimai, rolės ir paskyros',
      summary: 'Kas kokius automobilius mato, kas gali ką keisti ir kaip duoti prieigą, neatiduodant visko.',
      keywords: ['vartotojas', 'teisės', 'rolė', 'prieiga', 'slaptažodis', 'paskyra', 'stebėtojas', 'administratorius'],
      blocks: [
        { p: 'Trys sąvokos, kurias lengva supainioti. **Paskyra** – automobilių rinkinys. **Prisijungimas** – žmogaus el. paštas ir slaptažodis. **Rolė** – ką tam žmogui leidžiama daryti.' },
        { h2: 'Paskyros grupuoja automobilius', id: 'accounts' },
        { p: 'Daugumai mažų autoparkų reikia lygiai vienos paskyros ir daugiau apie tai negalvoti. Paskyros svarbios, kai automobiliai priklauso skirtingiems klientams, objektams ar juridiniams asmenims: kiekviena paskyra turi savo automobilius, savo zonas, savo ataskaitas ir savo prisijungimus, ir niekas tarp jų nepersilieja.' },
        { callout: 'note', p: 'Jei perparduodate sekimą, viena paskyra vienam klientui – tai visas modelis; žr. [Klientų paskyros](kb:customer-accounts).' },
        { h2: 'Trys rolės', id: 'roles' },
        { table: { head: ['Rolė', 'Mato', 'Gali keisti'], rows: [
          ['**Stebėtojas**', 'Savo paskyros žemėlapį, keliones, įvykius ir ataskaitas', 'Nieko. Saugus prisijungimas dispečeriui, klientui ar buhalteriui.'],
          ['**Paskyros valdytojas**', 'Viską savo paskyroje', 'Automobilius, vairuotojus, zonas, taisykles, techninę priežiūrą – kasdienybę.'],
          ['**Organizacijos administratorius**', 'Kiekvieną organizacijos paskyrą', 'Viską, o dar mokėjimus, prisijungimus, prekės ženklą ir integracijas.'],
        ] } },
        { p: 'Rolė parenkama kuriant prisijungimą ir vėliau keičiama. Administratorius gali suteikti tik už savo žemesnę rolę, todėl niekas negali tyliai savęs paaukštinti.' },
        { h2: 'Kaip pridėti žmogų', id: 'add' },
        { ol: [
          'Atverkite paskyrą, prie kurios norite jam suteikti prieigą.',
          'Pridėkite prisijungimą su jo el. pašto adresu ir pradiniu slaptažodžiu.',
          'Parinkite rolę. Jei abejojate, rinkitės **Stebėtoją** – ta, kuri nieko negali sugadinti.',
          'Perduokite slaptažodį. Prisijungęs jis pats jį pasikeis skiltyje Nustatymai → Saugumas.',
        ] },
        { h2: 'Kaip pašalinti žmogų', id: 'remove' },
        { p: 'Pašalinkite prisijungimą. Tai įsigalioja iškart: jo aktyvios sesijos nustoja veikti su kita užklausa, o ne kada nors vėliau pasibaigus galiojimui. Jo istorija – ką ir kada darė – lieka audito žurnale; kaip tik dėl to jis ir yra.' },
        { h2: 'Slaptažodžiai ir prisijungimas', id: 'passwords' },
        { ul: [
          'Slaptažodis – bent 8 simboliai; jo nemato niekas, įskaitant administratorių. Administratorius gali nustatyti naują; perskaityti seno negali niekas.',
          'Pamirštas slaptažodis atstatomas prisijungimo puslapyje. Nuoroda atsiunčiama el. paštu ir turi galiojimo laiką.',
          'Nauja savitarnos paskyra prieš pirmą prisijungimą turi patvirtinti el. pašto adresą. Kol nepatvirtinta, prisijungti neleidžiama – sąmoningai nepasakant, kuris iš dviejų dalykų negerai.',
        ] },
      ],
    },
    pl: {
      title: 'Loginy, role i konta',
      summary: 'Kto widzi które pojazdy, kto może coś zmienić i jak dać dostęp, nie oddając wszystkiego.',
      keywords: ['użytkownik', 'uprawnienia', 'rola', 'dostęp', 'hasło', 'konto', 'podgląd', 'administrator'],
      blocks: [
        { p: 'Trzy pojęcia, łatwe do pomylenia. **Konto** to zbiór pojazdów. **Login** to e-mail i hasło osoby. **Rola** to zakres tego, co ta osoba może robić.' },
        { h2: 'Konta grupują pojazdy', id: 'accounts' },
        { p: 'Większość małych flot potrzebuje dokładnie jednego konta i nigdy więcej o tym nie myśli. Konta zaczynają mieć znaczenie, gdy pojazdy należą do różnych klientów, lokalizacji albo podmiotów: każde konto ma własne pojazdy, strefy, raporty i loginy, a nic się między nimi nie przenika.' },
        { callout: 'note', p: 'Jeśli odsprzedajesz monitoring, jedno konto na klienta to cały model — zobacz [Konta klientów](kb:customer-accounts).' },
        { h2: 'Trzy role', id: 'roles' },
        { table: { head: ['Rola', 'Widzi', 'Może zmieniać'], rows: [
          ['**Podgląd**', 'Mapę, trasy, zdarzenia i raporty swojego konta', 'Nic. Bezpieczny login dla dyspozytora, klienta albo księgowej.'],
          ['**Menedżer konta**', 'Wszystko na swoim koncie', 'Pojazdy, kierowców, strefy, reguły, konserwację — codzienność.'],
          ['**Administrator organizacji**', 'Każde konto w organizacji', 'Wszystko, a do tego płatności, loginy, markę i integracje.'],
        ] } },
        { p: 'Rolę wybiera się przy tworzeniu loginu i można ją później zmienić. Administrator może nadać wyłącznie rolę niższą od własnej, więc nikt nie awansuje się po cichu sam.' },
        { h2: 'Dodawanie osoby', id: 'add' },
        { ol: [
          'Otwórz konto, do którego ma mieć dostęp.',
          'Dodaj login z jej adresem e-mail i hasłem startowym.',
          'Wybierz rolę. W razie wątpliwości wybierz **Podgląd** — tej roli nie da się niczego zepsuć.',
          'Przekaż hasło. Po zalogowaniu zmieni je sama w Ustawieniach → Bezpieczeństwo.',
        ] },
        { h2: 'Usuwanie osoby', id: 'remove' },
        { p: 'Usuń login. Działa natychmiast: aktywne sesje przestają działać przy następnym żądaniu, a nie po jakimś późniejszym wygaśnięciu. Historia jej działań zostaje w dzienniku audytu — po to on jest.' },
        { h2: 'Hasła i logowanie', id: 'passwords' },
        { ul: [
          'Hasło ma co najmniej 8 znaków i nie widzi go nikt, łącznie z administratorem. Administrator może ustawić nowe; starego nie odczyta nikt.',
          'Zapomniane hasło resetuje się ze strony logowania. Link przychodzi mailem i wygasa.',
          'Nowe konto z samodzielnej rejestracji musi potwierdzić adres e-mail przed pierwszym logowaniem. Do tego czasu logowanie jest odrzucane — celowo bez wskazania, która z dwóch rzeczy jest nie tak.',
        ] },
      ],
    },
    de: {
      title: 'Zugänge, Rollen und Konten',
      summary: 'Wer welche Fahrzeuge sieht, wer etwas ändern darf, und wie man Zugriff gibt, ohne alles zu geben.',
      keywords: ['benutzer', 'berechtigung', 'rolle', 'zugriff', 'passwort', 'konto', 'betrachter', 'administrator'],
      blocks: [
        { p: 'Drei Begriffe, die leicht durcheinandergehen. **Konto** ist eine Menge Fahrzeuge. **Zugang** ist E-Mail und Passwort einer Person. **Rolle** ist das, was diese Person darf.' },
        { h2: 'Konten bündeln Fahrzeuge', id: 'accounts' },
        { p: 'Die meisten kleinen Flotten brauchen genau ein Konto und denken danach nie wieder darüber nach. Konten zählen, wenn die Fahrzeuge verschiedenen Kunden, Standorten oder Gesellschaften gehören: Jedes Konto hat eigene Fahrzeuge, Zonen, Berichte und Zugänge, und nichts läuft zwischen ihnen über.' },
        { callout: 'note', p: 'Wer Ortung weiterverkauft, für den ist ein Konto je Kunde das ganze Modell — siehe [Kundenkonten](kb:customer-accounts).' },
        { h2: 'Die drei Rollen', id: 'roles' },
        { table: { head: ['Rolle', 'Sieht', 'Darf ändern'], rows: [
          ['**Betrachter**', 'Karte, Fahrten, Ereignisse und Berichte des eigenen Kontos', 'Nichts. Ein sicherer Zugang für Disposition, Kunden oder Buchhaltung.'],
          ['**Kontomanager**', 'Alles im eigenen Konto', 'Fahrzeuge, Fahrer, Zonen, Regeln, Wartung — das Tagesgeschäft.'],
          ['**Organisations-Admin**', 'Jedes Konto der Organisation', 'Alles, dazu Abrechnung, Zugänge, Branding und Integrationen.'],
        ] } },
        { p: 'Die Rolle wird beim Anlegen des Zugangs gewählt und ist später änderbar. Ein Admin kann nur Rollen unterhalb der eigenen vergeben — niemand befördert sich still selbst.' },
        { h2: 'Jemanden hinzufügen', id: 'add' },
        { ol: [
          'Öffnen Sie das Konto, auf das die Person Zugriff haben soll.',
          'Legen Sie einen Zugang mit ihrer E-Mail-Adresse und einem Startpasswort an.',
          'Wählen Sie die Rolle. Im Zweifel **Betrachter** — damit lässt sich nichts kaputt machen.',
          'Geben Sie das Passwort weiter. Nach dem Anmelden ändert sie es selbst unter Einstellungen → Sicherheit.',
        ] },
        { h2: 'Jemanden entfernen', id: 'remove' },
        { p: 'Löschen Sie den Zugang. Das wirkt sofort: Laufende Sitzungen enden mit der nächsten Anfrage, nicht erst bei irgendeinem Ablauf. Was die Person getan hat und wann, bleibt im Audit-Log — genau dafür gibt es das.' },
        { h2: 'Passwörter und Anmeldung', id: 'passwords' },
        { ul: [
          'Passwörter haben mindestens 8 Zeichen und sind für niemanden sichtbar, auch nicht für Admins. Ein Admin kann ein neues setzen; das alte lesen kann niemand.',
          'Ein vergessenes Passwort wird über die Anmeldeseite zurückgesetzt. Der Link kommt per E-Mail und läuft ab.',
          'Ein neu selbst registriertes Konto muss seine E-Mail-Adresse bestätigen, bevor es sich anmelden kann. Vorher wird die Anmeldung abgelehnt — bewusst ohne zu verraten, welches der beiden Dinge nicht stimmt.',
        ] },
      ],
    },
  },
}
