import type { KbArticle } from '../types.js'

export const maintenance: KbArticle = {
  slug: 'maintenance',
  category: 'fleet',
  surfaces: { site: true, app: true },
  screen: '/app/maintenance',
  doc: {
    en: {
      title: 'Maintenance reminders',
      summary: 'Servicing by kilometres, days or engine hours; applying one interval set to a whole fleet; and what “mark as serviced” does.',
      keywords: ['maintenance', 'service', 'reminder', 'interval', 'oil change', 'engine hours', 'plan', 'due', 'forecast'],
      blocks: [
        { p: 'A reminder is a rule about wear rather than about time on a calendar. It counts down from whichever measure actually wears the vehicle out, and tells you before the number is reached rather than after.' },
        { h2: 'Three ways to count', id: 'measures' },
        { table: { head: ['Interval', 'Right for'], rows: [
          ['**Kilometres**', 'Oil, filters, brakes, tyres — anything driven distance wears out.'],
          ['**Days**', 'Inspections, insurance-linked checks, anything a calendar demands regardless of use.'],
          ['**Engine hours**', 'Machinery, refrigerated units, cranes, anything that works standing still where kilometres understate the wear badly.'],
        ] } },
        { p: 'A reminder can carry more than one interval. Whichever runs out first is the one that becomes due, which is exactly how a service book reads: every 15 000 km or every 12 months, whichever comes first.' },
        { h2: 'Creating one', id: 'create' },
        { ol: [
          'Pick the vehicle and name the job the way a workshop would (“Oil and filter”, not “service”).',
          'Set the interval, or intervals.',
          'Enter the current odometer or hour reading, so the first countdown starts from the truth rather than from zero.',
        ] },
        { h2: 'Plans — one interval set, the whole fleet', id: 'plans' },
        { p: 'A **plan** is a named set of items — oil at one interval, brake inspection at another, an annual check — that can be applied to many vehicles in one action. Applying it creates the reminders that are missing and skips the ones that already exist, so a plan can be re-applied whenever the fleet grows without producing duplicates.' },
        { callout: 'tip', p: 'Build the plan once from your most typical vehicle, then apply it to every similar vehicle. It is the difference between fifteen minutes of setup and an afternoon of repeated forms.' },
        { h2: 'Marking something serviced', id: 'serviced' },
        { p: 'When work is done, mark the reminder serviced. The countdown restarts from the current odometer or date, and an entry is written into the vehicle\'s service log with the cost, the workshop and any notes you add — see [The vehicle card](kb:vehicle-card).' },
        { p: 'That log is the point of the whole feature. Reminders stop a service being missed; the log is what proves it was not, months later, to a buyer or an insurer.' },
        { h2: 'The forecast', id: 'forecast' },
        { p: 'Because the platform knows how far each vehicle actually drives, a kilometre-based reminder can be turned into a date: at this vehicle\'s recent rate, it will be due in about three weeks. That turns a workshop booking from a scramble into a plan.' },
      ],
    },
    lt: {
      title: 'Priežiūros priminimai',
      summary: 'Priežiūra pagal kilometrus, dienas ar variklio valandas; vieno intervalų rinkinio pritaikymas visam parkui; ir ką daro „pažymėti atliktu“.',
      keywords: ['priežiūra', 'servisas', 'priminimas', 'intervalas', 'tepalų keitimas', 'variklio valandos', 'planas', 'prognozė'],
      blocks: [
        { p: 'Priminimas – tai taisyklė apie nusidėvėjimą, o ne apie datą kalendoriuje. Jis skaičiuoja atgal nuo to mato, kuris automobilį iš tikrųjų dėvi, ir praneša prieš pasiekiant skaičių, o ne po to.' },
        { h2: 'Trys skaičiavimo būdai', id: 'measures' },
        { table: { head: ['Intervalas', 'Kam tinka'], rows: [
          ['**Kilometrai**', 'Tepalams, filtrams, stabdžiams, padangoms – visam, ką dėvi nuvažiuotas atstumas.'],
          ['**Dienos**', 'Apžiūroms, su draudimu susijusiems patikrinimams, visam, ko reikalauja kalendorius, nepaisant naudojimo.'],
          ['**Variklio valandos**', 'Technikai, šaldymo agregatams, kranams – visam, kas dirba stovėdamas, kur kilometrai nusidėvėjimą labai sumenkina.'],
        ] } },
        { p: 'Priminimas gali turėti daugiau nei vieną intervalą. Terminas suveikia pagal tą, kuris pasibaigia pirmas – lygiai taip, kaip skamba serviso knygelė: kas 15 000 km arba kas 12 mėnesių, kas įvyksta pirmiau.' },
        { h2: 'Kaip sukurti', id: 'create' },
        { ol: [
          'Pasirinkite automobilį ir pavadinkite darbą taip, kaip pavadintų dirbtuvės („Tepalai ir filtras“, o ne „servisas“).',
          'Nustatykite intervalą arba intervalus.',
          'Įveskite dabartinį odometro ar valandų rodmenį, kad pirmas skaičiavimas prasidėtų nuo tiesos, o ne nuo nulio.',
        ] },
        { h2: 'Planai — vienas intervalų rinkinys visam parkui', id: 'plans' },
        { p: '**Planas** – tai pavadintas darbų rinkinys (tepalai vienu intervalu, stabdžių patikra kitu, metinė apžiūra), kurį vienu veiksmu galima pritaikyti daugeliui automobilių. Pritaikius sukuriami trūkstami priminimai, o esantys praleidžiami, tad planą galima taikyti iš naujo parkui augant, negaminant dublikatų.' },
        { callout: 'tip', p: 'Vieną kartą sudarykite planą pagal tipiškiausią automobilį, o paskui pritaikykite jį kiekvienam panašiam. Tai skirtumas tarp penkiolikos minučių ir popietės, praleistos pildant tas pačias formas.' },
        { h2: 'Kaip pažymėti atliktu', id: 'serviced' },
        { p: 'Atlikus darbą pažymėkite priminimą atliktu. Skaičiavimas prasideda iš naujo nuo dabartinio odometro ar datos, o į automobilio serviso žurnalą įrašomas įrašas su kaina, dirbtuvėmis ir jūsų pastabomis – žr. [Automobilio kortelė](kb:vehicle-card).' },
        { p: 'Tas žurnalas ir yra visos funkcijos esmė. Priminimai neleidžia praleisti serviso; žurnalas po mėnesių įrodo pirkėjui ar draudikui, kad jis nebuvo praleistas.' },
        { h2: 'Prognozė', id: 'forecast' },
        { p: 'Kadangi platforma žino, kiek kiekvienas automobilis iš tikrųjų važiuoja, kilometrais pagrįstą priminimą galima paversti data: pagal šio automobilio pastarojo meto tempą terminas ateis maždaug po trijų savaičių. Taip vizitas į dirbtuves iš skubotos improvizacijos virsta planu.' },
      ],
    },
    pl: {
      title: 'Przypomnienia serwisowe',
      summary: 'Serwis według kilometrów, dni albo motogodzin; zastosowanie jednego zestawu interwałów do całej floty; i co robi „oznacz jako wykonane”.',
      keywords: ['serwis', 'przypomnienie', 'interwał', 'wymiana oleju', 'motogodziny', 'plan', 'termin', 'prognoza'],
      blocks: [
        { p: 'Przypomnienie to reguła o zużyciu, a nie o dacie w kalendarzu. Odlicza od tej miary, która faktycznie zużywa pojazd, i mówi zanim liczba zostanie osiągnięta, a nie po.' },
        { h2: 'Trzy sposoby liczenia', id: 'measures' },
        { table: { head: ['Interwał', 'Właściwy dla'], rows: [
          ['**Kilometry**', 'Olej, filtry, hamulce, opony — wszystko, co zużywa przejechany dystans.'],
          ['**Dni**', 'Przeglądy, kontrole związane z ubezpieczeniem, wszystko, czego wymaga kalendarz niezależnie od użycia.'],
          ['**Motogodziny**', 'Maszyny, agregaty chłodnicze, żurawie — wszystko, co pracuje w miejscu, gdzie kilometry mocno zaniżają zużycie.'],
        ] } },
        { p: 'Przypomnienie może mieć więcej niż jeden interwał. Termin wyznacza ten, który skończy się pierwszy — dokładnie tak, jak czyta się książkę serwisową: co 15 000 km albo co 12 miesięcy, cokolwiek nastąpi wcześniej.' },
        { h2: 'Tworzenie', id: 'create' },
        { ol: [
          'Wybierz pojazd i nazwij pracę tak, jak nazwałby ją warsztat („Olej i filtr”, nie „serwis”).',
          'Ustaw interwał albo interwały.',
          'Wpisz bieżący stan licznika lub motogodzin, żeby pierwsze odliczanie zaczęło się od prawdy, a nie od zera.',
        ] },
        { h2: 'Plany — jeden zestaw interwałów na całą flotę', id: 'plans' },
        { p: '**Plan** to nazwany zestaw pozycji — olej w jednym interwale, kontrola hamulców w drugim, przegląd roczny — który jedną akcją można zastosować do wielu pojazdów. Zastosowanie tworzy brakujące przypomnienia i pomija istniejące, więc plan można stosować ponownie w miarę wzrostu floty bez tworzenia duplikatów.' },
        { callout: 'tip', p: 'Zbuduj plan raz na najbardziej typowym pojeździe, a potem zastosuj go do każdego podobnego. To różnica między kwadransem konfiguracji a popołudniem wypełniania tych samych formularzy.' },
        { h2: 'Oznaczanie jako wykonane', id: 'serviced' },
        { p: 'Po wykonaniu pracy oznacz przypomnienie jako wykonane. Odliczanie startuje od bieżącego licznika lub daty, a do historii serwisowej pojazdu trafia wpis z kosztem, warsztatem i Twoimi uwagami — zobacz [Karta pojazdu](kb:vehicle-card).' },
        { p: 'Ta historia jest sensem całej funkcji. Przypomnienia nie pozwalają przegapić serwisu; historia po miesiącach dowodzi kupującemu albo ubezpieczycielowi, że go nie przegapiono.' },
        { h2: 'Prognoza', id: 'forecast' },
        { p: 'Ponieważ platforma wie, ile każdy pojazd naprawdę jeździ, przypomnienie kilometrowe da się zamienić w datę: przy obecnym tempie tego pojazdu termin wypadnie za jakieś trzy tygodnie. To zamienia wizytę w warsztacie z gorączki w plan.' },
      ],
    },
    de: {
      title: 'Wartungserinnerungen',
      summary: 'Service nach Kilometern, Tagen oder Motorstunden; einen Intervallsatz auf die ganze Flotte anwenden; und was „als erledigt markieren“ bewirkt.',
      keywords: ['wartung', 'service', 'erinnerung', 'intervall', 'ölwechsel', 'motorstunden', 'plan', 'fällig', 'prognose'],
      blocks: [
        { p: 'Eine Erinnerung ist eine Regel über Verschleiß, nicht über ein Kalenderdatum. Sie zählt von dem Maß herunter, das das Fahrzeug tatsächlich abnutzt, und meldet sich, bevor die Zahl erreicht ist, nicht danach.' },
        { h2: 'Drei Zählweisen', id: 'measures' },
        { table: { head: ['Intervall', 'Richtig für'], rows: [
          ['**Kilometer**', 'Öl, Filter, Bremsen, Reifen — alles, was gefahrene Strecke abnutzt.'],
          ['**Tage**', 'Untersuchungen, versicherungsgebundene Prüfungen, alles, was der Kalender unabhängig von der Nutzung verlangt.'],
          ['**Motorstunden**', 'Maschinen, Kühlaggregate, Krane — alles, was im Stand arbeitet, wo Kilometer den Verschleiß stark untertreiben.'],
        ] } },
        { p: 'Eine Erinnerung kann mehrere Intervalle tragen. Fällig wird sie durch das, was zuerst abläuft — genau so, wie ein Serviceheft liest: alle 15.000 km oder alle 12 Monate, je nachdem was früher eintritt.' },
        { h2: 'Eine anlegen', id: 'create' },
        { ol: [
          'Fahrzeug wählen und die Arbeit so benennen, wie eine Werkstatt sie nennt („Öl und Filter“, nicht „Service“).',
          'Intervall oder Intervalle setzen.',
          'Den aktuellen Kilometer- oder Stundenstand eintragen, damit das erste Herunterzählen von der Wahrheit startet und nicht von null.',
        ] },
        { h2: 'Pläne — ein Intervallsatz für die ganze Flotte', id: 'plans' },
        { p: 'Ein **Plan** ist ein benannter Satz von Positionen — Öl in einem Intervall, Bremsenprüfung in einem anderen, eine Jahresuntersuchung — der sich in einer Aktion auf viele Fahrzeuge anwenden lässt. Das Anwenden legt die fehlenden Erinnerungen an und überspringt vorhandene, sodass ein Plan beim Wachsen der Flotte erneut angewandt werden kann, ohne Dubletten zu erzeugen.' },
        { callout: 'tip', p: 'Bauen Sie den Plan einmal am typischsten Fahrzeug und wenden Sie ihn dann auf jedes ähnliche an. Das ist der Unterschied zwischen einer Viertelstunde Einrichtung und einem Nachmittag mit denselben Formularen.' },
        { h2: 'Als erledigt markieren', id: 'serviced' },
        { p: 'Ist die Arbeit getan, markieren Sie die Erinnerung als erledigt. Das Herunterzählen startet vom aktuellen Kilometerstand oder Datum neu, und in die Serviceheft des Fahrzeugs wird ein Eintrag mit Kosten, Werkstatt und Ihren Notizen geschrieben — siehe [Die Fahrzeugkarte](kb:vehicle-card).' },
        { p: 'Dieser Verlauf ist der Sinn der ganzen Funktion. Erinnerungen verhindern einen verpassten Service; der Verlauf beweist Monate später einem Käufer oder Versicherer, dass keiner verpasst wurde.' },
        { h2: 'Die Prognose', id: 'forecast' },
        { p: 'Weil die Plattform weiß, wie viel jedes Fahrzeug wirklich fährt, lässt sich eine kilometerbasierte Erinnerung in ein Datum übersetzen: Bei der jüngsten Laufleistung dieses Fahrzeugs wird sie in etwa drei Wochen fällig. Damit wird aus einem Werkstatttermin statt Hektik eine Planung.' },
      ],
    },
  },
}
