import type { KbArticle } from '../types.js'

export const mapBasics: KbArticle = {
  slug: 'map-basics',
  category: 'map',
  surfaces: { site: true, app: true },
  screen: '/app',
  doc: {
    en: {
      title: 'Reading the live map',
      summary: 'Markers, trails, layers, the 24-hour timeline and the panels behind a selected vehicle.',
      keywords: ['map', 'live', 'marker', 'trail', 'layers', 'cluster', 'follow', 'timeline', 'replay'],
      blocks: [
        { p: 'The map is the page most people keep open all day. Everything on it answers one of two questions: where is the fleet now, and where has this vehicle been today.' },
        { h2: 'The fleet list and the markers', id: 'fleet' },
        { p: 'Vehicles are listed beside the map and drawn on it. Selecting one in either place selects it in the other. The list can be searched, sorted by status, name or speed, and filtered down to just the vehicles in one state — the fastest way to answer "who is out of contact".' },
        { p: 'A marker points in the direction the vehicle was heading. Its colour carries the connection status — see [Device status](kb:device-status). Where many vehicles sit close together, they group into a single cluster that splits apart as you zoom in.' },
        { h2: 'Trails', id: 'trails' },
        { p: 'A trail is the recent line behind a moving vehicle. A gap in a trail is honest, not a rendering bug: it marks a stretch where no trustworthy position arrived, usually a tunnel or a coverage hole. We draw the gap rather than a straight line across it, because a straight line would be a road the vehicle never took.' },
        { h2: 'Layers', id: 'layers' },
        { ul: [
          '**Geofences** — draws your zones over the map. You can choose which ones, so a hundred zones do not bury the vehicles.',
          '**Movement trails** — on or off.',
          '**Device names** — labels beside each marker; useful on a small fleet, noisy on a large one.',
          '**Density overlay** — a heat layer showing where the fleet spends its time.',
        ] },
        { h2: 'The 24-hour timeline', id: 'timeline' },
        { p: 'With a vehicle selected, the strip along the bottom is its last 24 hours. Drag it and the marker moves to where the vehicle was at that moment; press replay and it drives the day back at your chosen speed. It is the quickest possible answer to "where was this van at half past two", with no report to run and no date to type.' },
        { p: 'The span is adjustable and the window can be panned to earlier days. Places where the vehicle sent nothing, or sent a position we could not trust, are marked as such rather than smoothed over.' },
        { h2: 'The vehicle panels', id: 'panels' },
        { p: 'Selecting a vehicle opens its panels: **Overview** (position, speed, ignition, key telemetry), **Events** for this vehicle, **Zones** it relates to, **Parameters** — everything the device reported, exactly as it reported it — and, for those allowed to use them, **Commands** and **Tracking settings**.' },
        { callout: 'tip', p: 'The Parameters panel is the ground truth for any argument about what a device said. It shows the device\'s own values, with the time they were reported.' },
      ],
    },
    lt: {
      title: 'Kaip skaityti gyvą žemėlapį',
      summary: 'Žymekliai, pėdsakai, sluoksniai, 24 valandų juosta ir skydeliai už pasirinkto automobilio.',
      keywords: ['žemėlapis', 'gyvas', 'žymeklis', 'pėdsakas', 'sluoksniai', 'sankaupa', 'juosta', 'peržaidimas'],
      blocks: [
        { p: 'Žemėlapis – puslapis, kurį dauguma laiko atvertą visą dieną. Viskas jame atsako į vieną iš dviejų klausimų: kur parkas yra dabar ir kur šis automobilis šiandien buvo.' },
        { h2: 'Automobilių sąrašas ir žymekliai', id: 'fleet' },
        { p: 'Automobiliai išvardyti šalia žemėlapio ir nupiešti jame. Pasirinkus vieną bet kurioje vietoje, jis pasirenkamas ir kitoje. Sąraše galima ieškoti, rikiuoti pagal būseną, pavadinimą ar greitį ir palikti tik vienos būsenos automobilius – greičiausias būdas atsakyti „kas neturi ryšio".' },
        { p: 'Žymeklis rodo kryptį, kuria automobilis judėjo. Jo spalva perteikia ryšio būseną – žr. [Įrenginio būsena](kb:device-status). Kur daug automobilių stovi arti vienas kito, jie sujungiami į vieną sankaupą, kuri priartinus išsiskiria.' },
        { h2: 'Pėdsakai', id: 'trails' },
        { p: 'Pėdsakas – neseniai nueito kelio linija už judančio automobilio. Tarpas pėdsake yra sąžiningas, o ne piešimo klaida: jis žymi ruožą, kuriame neatkeliavo nė vienos patikimos pozicijos, dažniausiai tunelį ar ryšio duobę. Piešiame tarpą, o ne tiesią liniją per jį, nes tiesi linija būtų kelias, kuriuo automobilis nevažiavo.' },
        { h2: 'Sluoksniai', id: 'layers' },
        { ul: [
          '**Geozonos** – piešia jūsų zonas ant žemėlapio. Galima pasirinkti, kurias, kad šimtas zonų nepalaidotų automobilių.',
          '**Judėjimo pėdsakai** – įjungti arba išjungti.',
          '**Įrenginių pavadinimai** – užrašai prie kiekvieno žymeklio; naudinga mažame parke, triukšminga dideliame.',
          '**Tankio sluoksnis** – šiluminis sluoksnis, rodantis, kur parkas praleidžia laiką.',
        ] },
        { h2: '24 valandų juosta', id: 'timeline' },
        { p: 'Pasirinkus automobilį, juosta apačioje yra jo paskutinės 24 valandos. Patempkite ją – žymeklis nušoka ten, kur automobilis buvo tą akimirką; paspauskite peržaidimą – ir diena pravažiuoja iš naujo jūsų pasirinktu greičiu. Tai greičiausias įmanomas atsakymas į klausimą „kur šis furgonas buvo pusę trijų", nepaleidžiant jokios ataskaitos ir neįvedant jokios datos.' },
        { p: 'Juostos plotį galima keisti, o langą – perstumti į ankstesnes dienas. Vietos, kur automobilis nieko nesiuntė arba atsiuntė poziciją, kuria negalėjome pasitikėti, taip ir pažymimos, o ne užglaistomos.' },
        { h2: 'Automobilio skydeliai', id: 'panels' },
        { p: 'Pasirinkus automobilį atsiveria jo skydeliai: **Apžvalga** (pozicija, greitis, degimas, svarbiausia telemetrija), **Įvykiai** šiam automobiliui, **Zonos**, su kuriomis jis susijęs, **Parametrai** – viskas, ką įrenginys pranešė, lygiai taip, kaip pranešė – ir, kam leidžiama, **Komandos** bei **Sekimo nustatymai**.' },
        { callout: 'tip', p: 'Parametrų skydelis yra tiesos šaltinis bet kuriame ginče apie tai, ką įrenginys pasakė. Jame rodomos paties įrenginio reikšmės kartu su jų pranešimo laiku.' },
      ],
    },
    pl: {
      title: 'Jak czytać mapę na żywo',
      summary: 'Znaczniki, ślady, warstwy, oś 24 godzin i panele wybranego pojazdu.',
      keywords: ['mapa', 'na żywo', 'znacznik', 'ślad', 'warstwy', 'klaster', 'oś czasu', 'odtwarzanie'],
      blocks: [
        { p: 'Mapa to strona, którą większość trzyma otwartą przez cały dzień. Wszystko na niej odpowiada na jedno z dwóch pytań: gdzie flota jest teraz i gdzie ten pojazd był dzisiaj.' },
        { h2: 'Lista floty i znaczniki', id: 'fleet' },
        { p: 'Pojazdy są wypisane obok mapy i narysowane na niej. Wybranie jednego w którymkolwiek miejscu zaznacza go też w drugim. Listę można przeszukiwać, sortować po statusie, nazwie lub prędkości i zawęzić do pojazdów w jednym stanie — najszybszy sposób na odpowiedź „kto nie ma kontaktu".' },
        { p: 'Znacznik wskazuje kierunek, w którym pojazd jechał. Jego kolor niesie status łączności — zobacz [Status urządzenia](kb:device-status). Tam, gdzie wiele pojazdów stoi blisko siebie, łączą się w jeden klaster, który rozpada się przy przybliżaniu.' },
        { h2: 'Ślady', id: 'trails' },
        { p: 'Ślad to linia niedawnej trasy za jadącym pojazdem. Przerwa w śladzie jest uczciwa, a nie błędem rysowania: oznacza odcinek, z którego nie dotarła żadna wiarygodna pozycja, zwykle tunel albo dziurę w zasięgu. Rysujemy przerwę zamiast prostej linii przez nią, bo prosta linia byłaby drogą, którą pojazd nie jechał.' },
        { h2: 'Warstwy', id: 'layers' },
        { ul: [
          '**Geostrefy** — rysuje Twoje strefy na mapie. Można wybrać które, żeby sto stref nie zasypało pojazdów.',
          '**Ślady ruchu** — włączone lub wyłączone.',
          '**Nazwy urządzeń** — etykiety przy znacznikach; przydatne w małej flocie, hałaśliwe w dużej.',
          '**Warstwa gęstości** — mapa ciepła pokazująca, gdzie flota spędza czas.',
        ] },
        { h2: 'Oś 24 godzin', id: 'timeline' },
        { p: 'Po wybraniu pojazdu pasek na dole to jego ostatnie 24 godziny. Przeciągnij go, a znacznik przeskoczy tam, gdzie pojazd był w tej chwili; naciśnij odtwarzanie, a dzień przejedzie od nowa z wybraną prędkością. To najszybsza możliwa odpowiedź na „gdzie ten bus był o wpół do trzeciej", bez uruchamiania raportu i bez wpisywania daty.' },
        { p: 'Zakres można zmieniać, a okno przesuwać na wcześniejsze dni. Miejsca, w których pojazd nic nie wysłał albo wysłał pozycję, której nie dało się zaufać, są tak oznaczone, a nie wygładzone.' },
        { h2: 'Panele pojazdu', id: 'panels' },
        { p: 'Wybranie pojazdu otwiera jego panele: **Przegląd** (pozycja, prędkość, zapłon, kluczowa telemetria), **Zdarzenia** tego pojazdu, **Strefy**, z którymi ma związek, **Parametry** — wszystko, co urządzenie zgłosiło, dokładnie tak, jak zgłosiło — oraz, dla uprawnionych, **Komendy** i **Ustawienia śledzenia**.' },
        { callout: 'tip', p: 'Panel Parametry to źródło prawdy w każdym sporze o to, co urządzenie powiedziało. Pokazuje własne wartości urządzenia wraz z czasem ich zgłoszenia.' },
      ],
    },
    de: {
      title: 'Die Live-Karte lesen',
      summary: 'Marker, Spuren, Ebenen, die 24-Stunden-Leiste und die Panels hinter einem ausgewählten Fahrzeug.',
      keywords: ['karte', 'live', 'marker', 'spur', 'ebenen', 'cluster', 'zeitleiste', 'replay'],
      blocks: [
        { p: 'Die Karte ist die Seite, die die meisten den ganzen Tag offen lassen. Alles darauf beantwortet eine von zwei Fragen: wo ist die Flotte jetzt, und wo war dieses Fahrzeug heute.' },
        { h2: 'Fahrzeugliste und Marker', id: 'fleet' },
        { p: 'Fahrzeuge stehen neben der Karte und sind darauf gezeichnet. Wer eines an einer Stelle auswählt, wählt es an der anderen mit. Die Liste lässt sich durchsuchen, nach Status, Name oder Geschwindigkeit sortieren und auf einen einzigen Zustand filtern — der schnellste Weg zur Frage „wer hat keinen Kontakt".' },
        { p: 'Ein Marker zeigt in die Fahrtrichtung. Seine Farbe trägt den Verbindungsstatus — siehe [Gerätestatus](kb:device-status). Wo viele Fahrzeuge dicht beieinanderstehen, fassen sie sich zu einem Cluster zusammen, das beim Hineinzoomen aufgeht.' },
        { h2: 'Spuren', id: 'trails' },
        { p: 'Eine Spur ist die jüngste Linie hinter einem fahrenden Fahrzeug. Eine Lücke darin ist ehrlich, kein Zeichenfehler: sie markiert einen Abschnitt, aus dem keine vertrauenswürdige Position kam, meist Tunnel oder Funkloch. Wir zeichnen die Lücke statt einer geraden Linie darüber, denn eine gerade Linie wäre eine Strecke, die das Fahrzeug nie gefahren ist.' },
        { h2: 'Ebenen', id: 'layers' },
        { ul: [
          '**Geozonen** — zeichnet Ihre Zonen über die Karte. Sie wählen welche, damit hundert Zonen nicht die Fahrzeuge begraben.',
          '**Bewegungsspuren** — an oder aus.',
          '**Gerätenamen** — Beschriftungen neben den Markern; in kleinen Flotten nützlich, in großen laut.',
          '**Dichte-Overlay** — eine Heatmap, wo die Flotte ihre Zeit verbringt.',
        ] },
        { h2: 'Die 24-Stunden-Leiste', id: 'timeline' },
        { p: 'Bei ausgewähltem Fahrzeug ist der Streifen unten seine letzten 24 Stunden. Ziehen Sie ihn, springt der Marker dorthin, wo das Fahrzeug in diesem Moment war; drücken Sie Replay, fährt der Tag in gewählter Geschwindigkeit noch einmal ab. Das ist die schnellstmögliche Antwort auf „wo war dieser Transporter um halb drei" — ohne Bericht, ohne Datumseingabe.' },
        { p: 'Die Spanne ist einstellbar, das Fenster lässt sich auf frühere Tage schieben. Stellen, an denen das Fahrzeug nichts gesendet hat oder eine Position schickte, der nicht zu trauen war, werden als solche markiert statt geglättet.' },
        { h2: 'Die Fahrzeug-Panels', id: 'panels' },
        { p: 'Ein ausgewähltes Fahrzeug öffnet seine Panels: **Übersicht** (Position, Geschwindigkeit, Zündung, Kerntelemetrie), **Ereignisse** dieses Fahrzeugs, **Zonen**, zu denen es gehört, **Parameter** — alles, was das Gerät gemeldet hat, genau so wie gemeldet — und, für Berechtigte, **Befehle** und **Tracking-Einstellungen**.' },
        { callout: 'tip', p: 'Das Parameter-Panel ist die Faktenlage für jeden Streit darüber, was ein Gerät gesagt hat. Es zeigt die geräteeigenen Werte samt Meldezeitpunkt.' },
      ],
    },
  },
}
