import type { KbArticle } from '../types.js'

export const mapWontLoad: KbArticle = {
  slug: 'map-wont-load',
  category: 'troubleshooting',
  surfaces: { site: true, app: true },
  screen: '/app',
  doc: {
    en: {
      title: 'The map is blank, black or will not load',
      summary: 'Almost always a network blocking the map tiles. How to confirm it in a minute and what to ask IT for.',
      keywords: ['map', 'blank', 'black', 'tiles', 'firewall', 'blocked', 'not loading', 'grey', 'proxy'],
      blocks: [
        { p: 'The vehicles, the list and the data are served by the platform; the **map picture underneath them** comes from a map provider. When everything works except the picture, the picture is what is blocked.' },
        { h2: 'Confirm it in one minute', id: 'confirm' },
        { ol: [
          'Open the same page on a phone using mobile data, not the office Wi-Fi.',
          'If the map appears there and not on the office network, it is the office network. Stop investigating and go to the next section.',
          'If it is blank in both places, try another browser, and then a private window with extensions disabled — an aggressive content blocker can do this on its own.',
        ] },
        { h2: 'What to ask IT for', id: 'it' },
        { p: 'Corporate firewalls, school networks and some VPNs block domains they do not recognise. Ask for the map provider\'s domains to be allowed for outbound HTTPS. The exact addresses appear in the browser\'s network tab as the failing requests — send those to whoever runs the network, rather than a general description.' },
        { callout: 'note', p: 'This is not something that can be fixed from our side. The map tiles are fetched by your browser, directly, so a network that refuses them refuses them before anything of ours is involved.' },
        { h2: 'Other causes worth two minutes', id: 'others' },
        { ul: [
          '**A very old browser.** The map needs modern graphics support. If everything else in the product renders but the map is a grey rectangle, update the browser.',
          '**Hardware acceleration switched off** in the browser\'s settings. This produces exactly a black rectangle.',
          '**A tracking-protection extension.** Try a private window with extensions off before blaming the network.',
          '**A stale page.** A tab left open for days can be running against a version that no longer exists. Reload it fully.',
        ] },
        { h2: 'The map loads but nothing is on it', id: 'no-markers' },
        { p: 'That is a different problem: the picture is fine and there is nothing to draw. Check that a device has reported a valid position — a vehicle with no fix has no place on a map, by design. See [Position accuracy](kb:position-accuracy) and [Device not reporting](kb:device-not-reporting).' },
      ],
    },
    lt: {
      title: 'Žemėlapis tuščias, juodas arba neįsikelia',
      summary: 'Beveik visada tai tinklas, blokuojantis žemėlapio plyteles. Kaip per minutę tuo įsitikinti ir ko paprašyti IT.',
      keywords: ['žemėlapis', 'tuščias', 'juodas', 'plytelės', 'ugniasienė', 'blokuojama', 'neįsikelia', 'proxy'],
      blocks: [
        { p: 'Automobilius, sąrašą ir duomenis pateikia platforma; **žemėlapio paveikslas po jais** ateina iš žemėlapių tiekėjo. Kai veikia viskas, išskyrus paveikslą, būtent paveikslas ir yra blokuojamas.' },
        { h2: 'Įsitikinkite per minutę', id: 'confirm' },
        { ol: [
          'Atverkite tą patį puslapį telefone naudodami mobiliuosius duomenis, o ne biuro Wi-Fi.',
          'Jei ten žemėlapis rodomas, o biuro tinkle – ne, kaltas biuro tinklas. Nustokite tyrinėti ir eikite į kitą skyrių.',
          'Jei tuščias abiejose vietose, pabandykite kitą naršyklę, o paskui privatų langą su išjungtais plėtiniais – agresyvus turinio blokatorius tai gali padaryti pats.',
        ] },
        { h2: 'Ko paprašyti IT', id: 'it' },
        { p: 'Įmonių ugniasienės, mokyklų tinklai ir kai kurie VPN blokuoja domenus, kurių neatpažįsta. Paprašykite leisti išeinančiam HTTPS srautui žemėlapių tiekėjo domenus. Tikslūs adresai matomi naršyklės tinklo skiltyje kaip nepavykusios užklausos – nusiųskite juos tinklą prižiūrinčiam žmogui, o ne bendrą aprašymą.' },
        { callout: 'note', p: 'Iš mūsų pusės to sutvarkyti neįmanoma. Žemėlapio plyteles jūsų naršyklė ima tiesiogiai, tad tinklas, kuris jas atmeta, atmeta dar prieš įsiterpiant kam nors mūsų.' },
        { h2: 'Kitos priežastys, vertos dviejų minučių', id: 'others' },
        { ul: [
          '**Labai sena naršyklė.** Žemėlapiui reikia šiuolaikinės grafikos palaikymo. Jei visa kita produkte piešiama, o žemėlapis – pilkas stačiakampis, atnaujinkite naršyklę.',
          '**Išjungtas aparatinis spartinimas** naršyklės nustatymuose. Tai duoda būtent juodą stačiakampį.',
          '**Sekimo blokavimo plėtinys.** Prieš kaltindami tinklą pabandykite privatų langą su išjungtais plėtiniais.',
          '**Pasenęs puslapis.** Kelias dienas atverta kortelė gali veikti su versija, kurios nebėra. Perkraukite pilnai.',
        ] },
        { h2: 'Žemėlapis įsikelia, bet jame nieko nėra', id: 'no-markers' },
        { p: 'Tai kita problema: paveikslas tvarkingas, tik nėra ko piešti. Patikrinkite, ar įrenginys atsiuntė galiojančią poziciją – automobilis be fiksacijos žemėlapyje vietos neturi, ir taip sumanyta. Žr. [Pozicijos tikslumas](kb:position-accuracy) ir [Įrenginys nesiunčia duomenų](kb:device-not-reporting).' },
      ],
    },
    pl: {
      title: 'Mapa jest pusta, czarna albo się nie ładuje',
      summary: 'Prawie zawsze to sieć blokująca kafelki mapy. Jak potwierdzić to w minutę i o co poprosić IT.',
      keywords: ['mapa', 'pusta', 'czarna', 'kafelki', 'firewall', 'zablokowana', 'nie ładuje', 'proxy'],
      blocks: [
        { p: 'Pojazdy, listę i dane serwuje platforma; **obraz mapy pod nimi** pochodzi od dostawcy map. Gdy działa wszystko poza obrazem, to właśnie obraz jest blokowany.' },
        { h2: 'Potwierdź w minutę', id: 'confirm' },
        { ol: [
          'Otwórz tę samą stronę na telefonie przez dane komórkowe, nie przez firmowe Wi-Fi.',
          'Jeśli tam mapa się pojawia, a w sieci biurowej nie — winna jest sieć biurowa. Przestań szukać i przejdź do następnej sekcji.',
          'Jeśli jest pusta w obu miejscach, spróbuj innej przeglądarki, a potem okna prywatnego z wyłączonymi rozszerzeniami — agresywny bloker treści potrafi to zrobić sam.',
        ] },
        { h2: 'O co poprosić IT', id: 'it' },
        { p: 'Firmowe firewalle, sieci szkolne i niektóre VPN-y blokują domeny, których nie rozpoznają. Poproś o dopuszczenie domen dostawcy map dla ruchu wychodzącego HTTPS. Dokładne adresy widać w zakładce sieci przeglądarki jako nieudane żądania — wyślij je osobie prowadzącej sieć zamiast ogólnego opisu.' },
        { callout: 'note', p: 'Tego nie da się naprawić po naszej stronie. Kafelki mapy pobiera bezpośrednio Twoja przeglądarka, więc sieć, która je odrzuca, odrzuca je zanim cokolwiek naszego weźmie w tym udział.' },
        { h2: 'Inne przyczyny warte dwóch minut', id: 'others' },
        { ul: [
          '**Bardzo stara przeglądarka.** Mapa wymaga nowoczesnej obsługi grafiki. Jeśli reszta produktu się rysuje, a mapa to szary prostokąt, zaktualizuj przeglądarkę.',
          '**Wyłączona akceleracja sprzętowa** w ustawieniach przeglądarki. Daje dokładnie czarny prostokąt.',
          '**Rozszerzenie blokujące śledzenie.** Zanim obwinisz sieć, spróbuj okna prywatnego bez rozszerzeń.',
          '**Nieświeża strona.** Karta otwarta od kilku dni może działać na wersji, której już nie ma. Przeładuj ją w pełni.',
        ] },
        { h2: 'Mapa się ładuje, ale nic na niej nie ma', id: 'no-markers' },
        { p: 'To inny problem: obraz jest w porządku, tylko nie ma czego rysować. Sprawdź, czy urządzenie zgłosiło prawidłową pozycję — pojazd bez fixa nie ma na mapie miejsca, i tak jest z założenia. Zobacz [Dokładność pozycji](kb:position-accuracy) i [Urządzenie nie raportuje](kb:device-not-reporting).' },
      ],
    },
    de: {
      title: 'Die Karte ist leer, schwarz oder lädt nicht',
      summary: 'Fast immer ein Netzwerk, das die Kartenkacheln blockiert. Wie Sie das in einer Minute bestätigen und was Sie von der IT brauchen.',
      keywords: ['karte', 'leer', 'schwarz', 'kacheln', 'firewall', 'blockiert', 'lädt nicht', 'proxy'],
      blocks: [
        { p: 'Fahrzeuge, Liste und Daten liefert die Plattform; das **Kartenbild darunter** kommt von einem Kartenanbieter. Wenn alles funktioniert außer dem Bild, ist genau das Bild blockiert.' },
        { h2: 'In einer Minute bestätigen', id: 'confirm' },
        { ol: [
          'Öffnen Sie dieselbe Seite auf einem Telefon über Mobilfunkdaten, nicht über das Büro-WLAN.',
          'Erscheint die Karte dort und im Büronetz nicht, ist es das Büronetz. Hören Sie mit der Suche auf und gehen Sie zum nächsten Abschnitt.',
          'Ist sie an beiden Orten leer, probieren Sie einen anderen Browser und dann ein privates Fenster ohne Erweiterungen — ein aggressiver Content-Blocker schafft das allein.',
        ] },
        { h2: 'Was die IT tun soll', id: 'it' },
        { p: 'Firmen-Firewalls, Schulnetze und manche VPNs blockieren Domains, die sie nicht kennen. Bitten Sie darum, die Domains des Kartenanbieters für ausgehendes HTTPS freizugeben. Die genauen Adressen stehen im Netzwerk-Tab des Browsers als fehlgeschlagene Anfragen — schicken Sie die an die Netzwerkverantwortlichen statt einer allgemeinen Beschreibung.' },
        { callout: 'note', p: 'Von unserer Seite lässt sich das nicht beheben. Die Kartenkacheln holt Ihr Browser direkt; ein Netzwerk, das sie verweigert, verweigert sie, bevor irgendetwas von uns beteiligt ist.' },
        { h2: 'Andere Ursachen, zwei Minuten wert', id: 'others' },
        { ul: [
          '**Ein sehr alter Browser.** Die Karte braucht moderne Grafikunterstützung. Rendert alles andere und die Karte ist ein graues Rechteck, aktualisieren Sie den Browser.',
          '**Hardwarebeschleunigung abgeschaltet** in den Browsereinstellungen. Das ergibt genau ein schwarzes Rechteck.',
          '**Eine Tracking-Schutz-Erweiterung.** Probieren Sie ein privates Fenster ohne Erweiterungen, bevor Sie das Netzwerk verdächtigen.',
          '**Eine veraltete Seite.** Ein tagelang offener Tab läuft womöglich gegen eine Version, die es nicht mehr gibt. Vollständig neu laden.',
        ] },
        { h2: 'Die Karte lädt, aber es ist nichts darauf', id: 'no-markers' },
        { p: 'Das ist ein anderes Problem: Das Bild ist in Ordnung, es gibt nur nichts zu zeichnen. Prüfen Sie, ob ein Gerät eine gültige Position gemeldet hat — ein Fahrzeug ohne Fix hat auf einer Karte keinen Ort, und das ist Absicht. Siehe [Positionsgenauigkeit](kb:position-accuracy) und [Gerät meldet sich nicht](kb:device-not-reporting).' },
      ],
    },
  },
}
