import type { KbArticle } from '../types.js'

export const notGettingEmails: KbArticle = {
  slug: 'not-getting-emails',
  category: 'troubleshooting',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'Not receiving e-mails',
      summary: 'Alerts, reports, password resets and activation links — where they go missing and how to get them arriving again.',
      keywords: ['email', 'not receiving', 'spam', 'bounce', 'blocked', 'alert', 'password reset', 'activation', 'delivery'],
      blocks: [
        { p: 'Start by finding out whether the message was **sent** or only **not received**. They are different problems with different fixes.' },
        { h2: 'Step 1 — did the thing actually happen?', id: 'happened' },
        { p: 'For an alert: open the events list and look for the event. If it is not there, the rule did not fire, and no channel would have helped. Check the rule is enabled, that its scope covers the vehicle, and that its threshold is what you think it is — see [Rules and alerts](kb:rules-and-alerts).' },
        { p: 'If the event **is** there and no e-mail arrived, the rule fired and the delivery failed. Continue.' },
        { h2: 'Step 2 — is the address on the rule?', id: 'channel' },
        { p: 'An e-mail channel has to be added to the rule with the exact address. A rule with no channels records events silently, which is a perfectly valid configuration and a very easy one to end up with by accident — see [Where alerts are delivered](kb:notification-channels).' },
        { h2: 'Step 3 — the spam folder, once', id: 'spam' },
        { p: 'Look, and if it is there, mark it as not spam and add the sender to the address book. That single action fixes the majority of these reports permanently, and it is worth doing pre-emptively for every new recipient.' },
        { h2: 'Step 4 — has the address been suppressed?', id: 'suppressed' },
        { callout: 'note', p: 'An address that permanently rejects mail — it no longer exists, or a server refused it outright — is remembered and not written to again. This protects delivery for every other message from the platform. If a colleague left and their address now bounces, that address is out of service; use a live one.' },
        { p: 'The pattern to recognise: it worked for months and then stopped for exactly one person. That is almost always this.' },
        { h2: 'Step 5 — a corporate filter', id: 'filter' },
        { p: 'Company mail systems quarantine mail from senders they have not seen before, and often do it without telling the recipient. Ask whoever runs your mail to check the quarantine and allow the sender. Automated mail that arrives reliably for eleven people and never for the twelfth is usually a per-user rule somebody set years ago.' },
        { h2: 'Password resets and activation links', id: 'auth' },
        { ul: [
          'Both are time-limited. An old link fails on purpose — request a fresh one rather than reusing the message from yesterday.',
          'A brand-new self-service account cannot sign in until its address is confirmed. If sign-in is refused and the password is definitely right, look for the activation message first.',
        ] },
        { h2: 'When you need to be certain', id: 'certainty' },
        { p: 'For alerts that genuinely matter — panic, power cut, a high-value load — do not rely on a single channel. Add a second one, so the two fail in different ways rather than together.' },
      ],
    },
    lt: {
      title: 'Negaunu laiškų',
      summary: 'Pranešimai, ataskaitos, slaptažodžio atstatymai ir aktyvavimo nuorodos – kur jie pradingsta ir kaip padaryti, kad vėl ateitų.',
      keywords: ['el. paštas', 'negaunu', 'šlamštas', 'atmesta', 'blokuota', 'pranešimas', 'slaptažodžio atstatymas', 'aktyvavimas'],
      blocks: [
        { p: 'Pradėkite nuo išsiaiškinimo, ar žinutė buvo **išsiųsta**, ar tik **negauta**. Tai skirtingos problemos su skirtingais sprendimais.' },
        { h2: '1 žingsnis — ar tai apskritai įvyko?', id: 'happened' },
        { p: 'Pranešimo atveju: atverkite įvykių sąrašą ir paieškokite įvykio. Jei jo ten nėra, taisyklė nesuveikė, ir joks kanalas nebūtų padėjęs. Patikrinkite, ar taisyklė įjungta, ar jos apimtis aprėpia automobilį ir ar riba tokia, kokią manote esant – žr. [Taisyklės ir pranešimai](kb:rules-and-alerts).' },
        { p: 'Jei įvykis **yra**, o laiškas neatėjo, taisyklė suveikė, o pristatymas nepavyko. Skaitykite toliau.' },
        { h2: '2 žingsnis — ar adresas nurodytas taisyklėje?', id: 'channel' },
        { p: 'El. pašto kanalas turi būti pridėtas prie taisyklės su tiksliu adresu. Taisyklė be kanalų įvykius įrašo tyliai – visiškai galiojanti konfigūracija, į kurią labai lengva netyčia patekti. Žr. [Kur pristatomi pranešimai](kb:notification-channels).' },
        { h2: '3 žingsnis — vieną kartą į šlamšto aplanką', id: 'spam' },
        { p: 'Pažiūrėkite, o radę pažymėkite kaip ne šlamštą ir įtraukite siuntėją į adresų knygą. Šis vienas veiksmas visam laikui išsprendžia daugumą tokių atvejų, ir jį verta atlikti iš anksto kiekvienam naujam gavėjui.' },
        { h2: '4 žingsnis — ar adresas nebuvo sustabdytas?', id: 'suppressed' },
        { callout: 'note', p: 'Adresas, kuris negrįžtamai atmeta laiškus – nebeegzistuoja arba serveris jį atmetė tiesiogiai – įsimenamas ir jam daugiau nerašoma. Taip saugomas visų kitų platformos laiškų pristatymas. Jei kolega išėjo ir jo adresas dabar atšoka, tas adresas nebeveikia; naudokite gyvą.' },
        { p: 'Atpažįstamas modelis: veikė mėnesius, o paskui nustojo lygiai vienam žmogui. Beveik visada tai būtent šis atvejis.' },
        { h2: '5 žingsnis — įmonės filtras', id: 'filter' },
        { p: 'Įmonių pašto sistemos karantinuoja laiškus iš anksčiau nematytų siuntėjų ir dažnai gavėjui apie tai nepraneša. Paprašykite pašto prižiūrėtojo patikrinti karantiną ir leisti siuntėją. Automatinis laiškas, patikimai pasiekiantis vienuolika žmonių ir niekada dvyliktą, dažniausiai yra prieš metus kažkieno sukurta asmeninė taisyklė.' },
        { h2: 'Slaptažodžio atstatymai ir aktyvavimo nuorodos', id: 'auth' },
        { ul: [
          'Abi turi galiojimo laiką. Sena nuoroda neveikia tyčia – užsakykite naują, o ne naudokite vakarykštę žinutę.',
          'Nauja savitarnos paskyra negali prisijungti, kol nepatvirtintas jos adresas. Jei prisijungti neleidžiama, o slaptažodis tikrai teisingas, pirmiausia ieškokite aktyvavimo laiško.',
        ] },
        { h2: 'Kai reikia tikrumo', id: 'certainty' },
        { p: 'Pranešimams, kurie iš tiesų svarbūs – pavojaus mygtukas, maitinimo dingimas, brangus krovinys – nesikliaukite vienu kanalu. Pridėkite antrą, kad jie gestų skirtingai, o ne kartu.' },
      ],
    },
    pl: {
      title: 'Nie dostaję e-maili',
      summary: 'Alerty, raporty, resety haseł i linki aktywacyjne — gdzie giną i jak sprawić, by znów docierały.',
      keywords: ['e-mail', 'nie dostaję', 'spam', 'odbicie', 'zablokowane', 'alert', 'reset hasła', 'aktywacja'],
      blocks: [
        { p: 'Zacznij od ustalenia, czy wiadomość została **wysłana**, czy tylko **nie dotarła**. To różne problemy z różnymi rozwiązaniami.' },
        { h2: 'Krok 1 — czy to w ogóle się wydarzyło?', id: 'happened' },
        { p: 'Przy alercie: otwórz listę zdarzeń i poszukaj zdarzenia. Jeśli go tam nie ma, reguła się nie wyzwoliła i żaden kanał by nie pomógł. Sprawdź, czy reguła jest włączona, czy jej zakres obejmuje pojazd i czy próg jest taki, jak myślisz — zobacz [Reguły i alerty](kb:rules-and-alerts).' },
        { p: 'Jeśli zdarzenie **jest**, a e-mail nie przyszedł, reguła się wyzwoliła i zawiodło dostarczenie. Czytaj dalej.' },
        { h2: 'Krok 2 — czy adres jest w regule?', id: 'channel' },
        { p: 'Kanał e-mail musi być dodany do reguły z dokładnym adresem. Reguła bez kanałów zapisuje zdarzenia po cichu — całkowicie poprawna konfiguracja, w którą bardzo łatwo wpaść przypadkiem. Zobacz [Dokąd trafiają alerty](kb:notification-channels).' },
        { h2: 'Krok 3 — raz do folderu spam', id: 'spam' },
        { p: 'Zajrzyj, a jeśli tam jest, oznacz jako nie-spam i dodaj nadawcę do książki adresowej. To jedno działanie rozwiązuje większość takich zgłoszeń na stałe i warto je wykonać z góry dla każdego nowego odbiorcy.' },
        { h2: 'Krok 4 — czy adres nie został zablokowany?', id: 'suppressed' },
        { callout: 'note', p: 'Adres, który trwale odrzuca pocztę — już nie istnieje albo serwer odmówił wprost — zostaje zapamiętany i nie wysyłamy już na niego kolejnych wiadomości. To chroni dostarczalność wszystkich innych wiadomości z platformy. Jeśli współpracownik odszedł i jego adres teraz odbija, ten adres jest poza służbą; użyj działającego.' },
        { p: 'Wzorzec do rozpoznania: działało miesiącami, a potem przestało dokładnie dla jednej osoby. Prawie zawsze to właśnie to.' },
        { h2: 'Krok 5 — firmowy filtr', id: 'filter' },
        { p: 'Firmowe systemy pocztowe kwarantannują pocztę od nadawców, których wcześniej nie widziały, i często nie mówią o tym odbiorcy. Poproś osobę od poczty o sprawdzenie kwarantanny i dopuszczenie nadawcy. Automatyczna poczta docierająca niezawodnie do jedenastu osób i nigdy do dwunastej to zwykle reguła użytkownika ustawiona lata temu.' },
        { h2: 'Resety haseł i linki aktywacyjne', id: 'auth' },
        { ul: [
          'Oba mają ograniczony czas. Stary link celowo nie działa — zamów nowy zamiast używać wczorajszej wiadomości.',
          'Nowe konto z samodzielnej rejestracji nie zaloguje się, dopóki adres nie zostanie potwierdzony. Jeśli logowanie jest odrzucane, a hasło na pewno dobre, najpierw poszukaj wiadomości aktywacyjnej.',
        ] },
        { h2: 'Gdy potrzebujesz pewności', id: 'certainty' },
        { p: 'Przy alertach, które naprawdę mają znaczenie — przycisk alarmowy, utrata zasilania, cenny ładunek — nie polegaj na jednym kanale. Dodaj drugi, żeby zawodziły w różny sposób, a nie razem.' },
      ],
    },
    de: {
      title: 'Keine E-Mails erhalten',
      summary: 'Alarme, Berichte, Passwort-Resets und Aktivierungslinks — wo sie verloren gehen und wie sie wieder ankommen.',
      keywords: ['e-mail', 'nicht erhalten', 'spam', 'bounce', 'blockiert', 'alarm', 'passwort-reset', 'aktivierung'],
      blocks: [
        { p: 'Klären Sie zuerst, ob die Nachricht **gesendet** wurde oder nur **nicht angekommen** ist. Das sind zwei Probleme mit zwei Lösungen.' },
        { h2: 'Schritt 1 — ist es überhaupt passiert?', id: 'happened' },
        { p: 'Bei einem Alarm: Öffnen Sie die Ereignisliste und suchen Sie nach dem Ereignis. Steht es nicht darin, hat die Regel nicht ausgelöst, und kein Kanal hätte geholfen. Prüfen Sie, ob die Regel aktiv ist, ob ihr Geltungsbereich das Fahrzeug einschließt und ob der Schwellwert der ist, den Sie annehmen — siehe [Regeln und Alarme](kb:rules-and-alerts).' },
        { p: 'Steht das Ereignis **darin** und kam keine E-Mail, hat die Regel ausgelöst und die Zustellung ist gescheitert. Weiterlesen.' },
        { h2: 'Schritt 2 — steht die Adresse an der Regel?', id: 'channel' },
        { p: 'Ein E-Mail-Kanal muss der Regel mit der exakten Adresse hinzugefügt werden. Eine Regel ohne Kanäle zeichnet Ereignisse still auf — eine völlig gültige Konfiguration, in die man sehr leicht versehentlich gerät. Siehe [Wohin Alarme zugestellt werden](kb:notification-channels).' },
        { h2: 'Schritt 3 — einmal in den Spam-Ordner', id: 'spam' },
        { p: 'Nachsehen, und wenn sie dort liegt, als Nicht-Spam markieren und den Absender ins Adressbuch nehmen. Diese eine Handlung löst die Mehrzahl dieser Meldungen dauerhaft, und sie lohnt sich vorbeugend bei jedem neuen Empfänger.' },
        { h2: 'Schritt 4 — wurde die Adresse gesperrt?', id: 'suppressed' },
        { callout: 'note', p: 'Eine Adresse, die Post dauerhaft ablehnt — sie existiert nicht mehr, oder ein Server hat sie rundweg abgewiesen — wird gemerkt und nicht erneut beschrieben. Das schützt die Zustellung aller anderen Nachrichten der Plattform. Ist eine Kollegin gegangen und ihre Adresse prallt jetzt ab, ist diese Adresse außer Dienst; nehmen Sie eine lebende.' },
        { p: 'Das erkennbare Muster: Es lief monatelang und hörte dann bei genau einer Person auf. Fast immer ist es das.' },
        { h2: 'Schritt 5 — ein Unternehmensfilter', id: 'filter' },
        { p: 'Firmen-Mailsysteme stellen Post von unbekannten Absendern in Quarantäne, oft ohne den Empfänger zu informieren. Bitten Sie die Mail-Verantwortlichen, die Quarantäne zu prüfen und den Absender freizugeben. Automatische Post, die bei elf Personen zuverlässig ankommt und bei der zwölften nie, ist meist eine Benutzerregel, die vor Jahren jemand gesetzt hat.' },
        { h2: 'Passwort-Resets und Aktivierungslinks', id: 'auth' },
        { ul: [
          'Beide sind zeitlich begrenzt. Ein alter Link scheitert mit Absicht — fordern Sie einen neuen an, statt die Nachricht von gestern zu benutzen.',
          'Ein neu selbst registriertes Konto kann sich erst anmelden, wenn seine Adresse bestätigt ist. Wird die Anmeldung abgelehnt und das Passwort stimmt sicher, suchen Sie zuerst die Aktivierungsnachricht.',
        ] },
        { h2: 'Wenn Sie sicher sein müssen', id: 'certainty' },
        { p: 'Bei Alarmen, auf die es wirklich ankommt — Panik, Stromausfall, hochwertige Ladung — verlassen Sie sich nicht auf einen Kanal. Nehmen Sie einen zweiten dazu, damit beide unterschiedlich ausfallen statt gemeinsam.' },
      ],
    },
  },
}
