import type { KbArticle } from '../types.js'

export const plansAndLimits: KbArticle = {
  slug: 'plans-and-limits',
  category: 'account',
  surfaces: { site: true, app: true },
  audience: { platformOnly: true },
  screen: '/app/settings',
  doc: {
    en: {
      title: 'What your plan includes',
      summary: 'How plans are structured, what the device limit counts, and which features are tied to which track.',
      keywords: ['plan', 'limit', 'devices', 'features', 'upgrade', 'entitlement', 'included', 'tier'],
      blocks: [
        { p: 'There are two tracks, and which one you are on decides both what you pay and which parts of the product exist for you.' },
        { h2: 'Direct — running your own fleet', id: 'direct' },
        { p: 'One account, priced by how many vehicles you track. Everything operational is included: live map, trips and playback, geofences, rules and alerts, reports with CSV and PDF export, drivers, maintenance and the vehicle records.' },
        { p: 'Not included: white-label branding, custom domains, customer sub-accounts, the REST API and webhooks. Those exist for resellers, and they are the difference between the two tracks.' },
        { h2: 'White-label / reseller — selling tracking to others', id: 'tsp' },
        { p: 'Priced with a base that includes an allowance of devices, plus a per-device rate beyond it. It adds everything the Direct track leaves out — your own brand and domain, one account per customer, API access and webhooks — and removes the device cap. See [What white-label means](kb:white-label-explained).' },
        { h2: 'What the device limit counts', id: 'limit' },
        { ul: [
          '**Active** devices count. A retired device does not — see [Retiring a device](kb:device-lifecycle).',
          'It is a count of registrations, not of vehicles reporting. A tracker in a drawer that is still registered takes a slot.',
          'A virtual device used for testing takes a slot exactly like hardware.',
        ] },
        { callout: 'tip', p: 'If you are at your limit and something needs adding, retire the trackers that left the fleet first. Most fleets are carrying two or three.' },
        { h2: 'Changing plan', id: 'change' },
        { p: 'You can switch at any time from the billing screen. An upgrade takes effect immediately; a downgrade too, with the unused portion credited against the next invoice. Nothing is charged in the moment of switching — the difference lands on the next invoice as proration. See [Billing and invoices](kb:billing-and-invoices).' },
        { h2: 'When a feature is not there', id: 'missing' },
        { p: 'Screens your plan does not include are not shown at all, rather than shown and refusing. If you expected a screen to be there — branding, API keys, webhooks, customer accounts — the plan is the reason. The current prices and what each tier contains are on the pricing page: [see pricing](site:/pricing).' },
      ],
    },
    lt: {
      title: 'Kas įeina į jūsų planą',
      summary: 'Kaip sudaryti planai, ką skaičiuoja įrenginių limitas ir kurios funkcijos susietos su kuria kryptimi.',
      keywords: ['planas', 'limitas', 'įrenginiai', 'funkcijos', 'atnaujinimas', 'įeina', 'pakopa'],
      blocks: [
        { p: 'Yra dvi kryptys, ir tai, kurioje esate, lemia ir kiek mokate, ir kurios produkto dalys jums apskritai egzistuoja.' },
        { h2: 'Tiesioginis — savo parkui valdyti', id: 'direct' },
        { p: 'Viena paskyra, kainuojanti pagal sekamų automobilių skaičių. Viskas, kas operatyvu, įskaičiuota: gyvas žemėlapis, kelionės ir peržaidimas, geozonos, taisyklės ir pranešimai, ataskaitos su CSV ir PDF eksportu, vairuotojai, priežiūra ir automobilių įrašai.' },
        { p: 'Neįskaičiuota: prekės ženklo pritaikymas, nuosavi domenai, klientų subpaskyros, REST API ir webhook\'ai. Jie skirti perpardavėjams ir yra tai, kuo abi kryptys skiriasi.' },
        { h2: 'White-label / perpardavėjams — parduoti sekimą kitiems', id: 'tsp' },
        { p: 'Kaina susideda iš bazės su įskaičiuotu įrenginių kiekiu ir įkainio už kiekvieną viršijantį. Ji prideda viską, ko tiesioginėje kryptyje nėra – savo prekės ženklą ir domeną, po paskyrą kiekvienam klientui, API prieigą ir webhook\'us – ir panaikina įrenginių ribą. Žr. [Ką reiškia white-label](kb:white-label-explained).' },
        { h2: 'Ką skaičiuoja įrenginių limitas', id: 'limit' },
        { ul: [
          'Skaičiuojami **aktyvūs** įrenginiai. Nurašytas – ne; žr. [Įrenginio nurašymas](kb:device-lifecycle).',
          'Tai registracijų, o ne siunčiančių automobilių skaičius. Stalčiuje gulintis, bet vis dar užregistruotas seklys užima vietą.',
          'Testavimui naudojamas virtualus įrenginys užima vietą lygiai kaip geležis.',
        ] },
        { callout: 'tip', p: 'Jei pasiekėte limitą ir reikia ką nors pridėti, pirmiausia nurašykite seklius, kurie paliko parką. Dauguma parkų tokių tempia po du tris.' },
        { h2: 'Plano keitimas', id: 'change' },
        { p: 'Persijungti galima bet kada mokėjimų ekrane. Aukštesnis planas įsigalioja iškart; žemesnis irgi, o nepanaudota dalis įskaitoma į kitą sąskaitą. Persijungimo akimirką niekas nenuskaitoma – skirtumas atsiduria kitoje sąskaitoje kaip proporcinis perskaičiavimas. Žr. [Mokėjimai ir sąskaitos](kb:billing-and-invoices).' },
        { h2: 'Kai funkcijos nėra', id: 'missing' },
        { p: 'Ekranai, kurių jūsų planas neapima, išvis nerodomi, o ne rodomi ir atsisako veikti. Jei tikėjotės, kad ekranas bus – prekės ženklas, API raktai, webhook\'ai, klientų paskyros – priežastis yra planas. Dabartinės kainos ir kas įeina į kiekvieną pakopą – kainodaros puslapyje: [žiūrėti kainas](site:/pricing).' },
      ],
    },
    pl: {
      title: 'Co obejmuje Twój plan',
      summary: 'Jak zbudowane są plany, co liczy limit urządzeń i które funkcje są przypisane do której ścieżki.',
      keywords: ['plan', 'limit', 'urządzenia', 'funkcje', 'upgrade', 'w cenie', 'poziom'],
      blocks: [
        { p: 'Są dwie ścieżki, a to, na której jesteś, decyduje i o tym, ile płacisz, i o tym, które części produktu w ogóle dla Ciebie istnieją.' },
        { h2: 'Bezpośrednia — dla własnej floty', id: 'direct' },
        { p: 'Jedno konto, wyceniane według liczby monitorowanych pojazdów. Wszystko operacyjne jest w cenie: mapa na żywo, trasy i odtwarzanie, geostrefy, reguły i alerty, raporty z eksportem CSV i PDF, kierowcy, serwis i dane pojazdów.' },
        { p: 'Poza ceną: marka własna, domeny własne, subkonta klientów, REST API i webhooki. Te istnieją dla resellerów i to właśnie różni obie ścieżki.' },
        { h2: 'White-label / reseller — sprzedaż monitoringu innym', id: 'tsp' },
        { p: 'Wycena to baza z pulą urządzeń w cenie plus stawka za każde ponad nią. Dodaje wszystko, czego brakuje w ścieżce bezpośredniej — własną markę i domenę, konto na klienta, dostęp do API i webhooki — i znosi limit urządzeń. Zobacz [Co znaczy white-label](kb:white-label-explained).' },
        { h2: 'Co liczy limit urządzeń', id: 'limit' },
        { ul: [
          'Liczą się urządzenia **aktywne**. Wycofane nie — zobacz [Wycofywanie urządzenia](kb:device-lifecycle).',
          'To liczba rejestracji, nie raportujących pojazdów. Lokalizator w szufladzie, wciąż zarejestrowany, zajmuje miejsce.',
          'Urządzenie wirtualne do testów zajmuje miejsce dokładnie jak sprzęt.',
        ] },
        { callout: 'tip', p: 'Jeśli jesteś na limicie i trzeba coś dodać, najpierw wycofaj lokalizatory, które opuściły flotę. Większość flot wozi ze sobą dwa albo trzy.' },
        { h2: 'Zmiana planu', id: 'change' },
        { p: 'Przełączyć się można w każdej chwili z ekranu płatności. Wyższy plan działa od razu; niższy też, a niewykorzystana część zostaje zaliczona na poczet następnej faktury. W chwili przełączenia nic nie jest pobierane — różnica trafia na następną fakturę jako proporcjonalne rozliczenie. Zobacz [Płatności i faktury](kb:billing-and-invoices).' },
        { h2: 'Gdy funkcji nie ma', id: 'missing' },
        { p: 'Ekrany nieobjęte planem nie są pokazywane w ogóle, zamiast być pokazywane i odmawiać działania. Jeśli spodziewałeś się ekranu — marka, klucze API, webhooki, konta klientów — powodem jest plan. Aktualne ceny i zawartość każdego poziomu są na stronie cennika: [zobacz cennik](site:/pricing).' },
      ],
    },
    de: {
      title: 'Was Ihr Tarif enthält',
      summary: 'Wie die Tarife aufgebaut sind, was das Gerätelimit zählt und welche Funktionen an welche Schiene gebunden sind.',
      keywords: ['tarif', 'limit', 'geräte', 'funktionen', 'upgrade', 'enthalten', 'stufe'],
      blocks: [
        { p: 'Es gibt zwei Schienen, und auf welcher Sie sind, entscheidet sowohl über den Preis als auch darüber, welche Teile des Produkts es für Sie überhaupt gibt.' },
        { h2: 'Direkt — die eigene Flotte betreiben', id: 'direct' },
        { p: 'Ein Konto, bepreist nach der Zahl der georteten Fahrzeuge. Alles Operative ist enthalten: Live-Karte, Fahrten und Replay, Geozonen, Regeln und Alarme, Berichte mit CSV- und PDF-Export, Fahrer, Wartung und die Fahrzeugdaten.' },
        { p: 'Nicht enthalten: eigenes Branding, eigene Domains, Kunden-Unterkonten, die REST-API und Webhooks. Die gibt es für Reseller, und sie sind der Unterschied zwischen den Schienen.' },
        { h2: 'White-Label / Reseller — Ortung an andere verkaufen', id: 'tsp' },
        { p: 'Bepreist mit einer Grundgebühr samt Gerätekontingent plus einem Satz je Gerät darüber hinaus. Sie ergänzt alles, was die Direktschiene auslässt — eigene Marke und Domain, ein Konto je Kunde, API-Zugang und Webhooks — und hebt das Gerätelimit auf. Siehe [Was White-Label bedeutet](kb:white-label-explained).' },
        { h2: 'Was das Gerätelimit zählt', id: 'limit' },
        { ul: [
          'Es zählen **aktive** Geräte. Ein stillgelegtes nicht — siehe [Gerät stilllegen](kb:device-lifecycle).',
          'Gezählt werden Registrierungen, nicht meldende Fahrzeuge. Ein Tracker in der Schublade, der noch registriert ist, belegt einen Platz.',
          'Ein virtuelles Testgerät belegt einen Platz genau wie Hardware.',
        ] },
        { callout: 'tip', p: 'Sind Sie am Limit und es muss etwas dazu, legen Sie zuerst die Tracker still, die die Flotte verlassen haben. Die meisten Flotten schleppen zwei oder drei mit.' },
        { h2: 'Tarif wechseln', id: 'change' },
        { p: 'Der Wechsel ist jederzeit im Abrechnungsbildschirm möglich. Ein Upgrade wirkt sofort; ein Downgrade auch, wobei der ungenutzte Teil auf die nächste Rechnung gutgeschrieben wird. Im Moment des Wechsels wird nichts abgebucht — die Differenz erscheint anteilig auf der nächsten Rechnung. Siehe [Abrechnung und Rechnungen](kb:billing-and-invoices).' },
        { h2: 'Wenn eine Funktion fehlt', id: 'missing' },
        { p: 'Bildschirme, die Ihr Tarif nicht enthält, werden gar nicht erst angezeigt, statt angezeigt zu werden und dann abzulehnen. Wenn Sie einen Bildschirm erwartet haben — Branding, API-Schlüssel, Webhooks, Kundenkonten — ist der Tarif der Grund. Die aktuellen Preise und der Inhalt jeder Stufe stehen auf der Preisseite: [Preise ansehen](site:/pricing).' },
      ],
    },
  },
}
