import type { KbArticle } from '../types.js'

export const positionAccuracy: KbArticle = {
  slug: 'position-accuracy',
  category: 'map',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'Position accuracy, drift and positions we throw away',
      summary: 'Why a parked vehicle appears to wander, what makes a fix untrustworthy, and the rule that keeps bad positions out of your numbers.',
      keywords: ['accuracy', 'drift', 'jitter', 'satellites', 'invalid fix', 'null island', 'wrong position', 'sea', 'africa'],
      blocks: [
        { p: 'GPS is very good and it is not perfect. Understanding the three ways it goes wrong explains almost every surprising thing you will see on the map.' },
        { h2: 'Ordinary accuracy', id: 'normal' },
        { p: 'With a clear view of the sky, a fix is typically accurate to a few metres. Buildings, bridges, tunnels and dense forest reflect and block the signal, so accuracy in a city street is worse than on a motorway — sometimes by tens of metres. This is physics, not a defect, and it affects every GPS device including your phone.' },
        { h2: 'Drift: the parked vehicle that keeps moving', id: 'drift' },
        { p: 'A stationary vehicle still receives slightly different positions from one minute to the next. Drawn naively, that produces a small scribble around the parking space and, worse, a few hundred metres of distance added to the day for a vehicle that never moved.' },
        { p: '{product} does not draw it and does not count it. Small position changes below the level at which movement can be distinguished from noise are treated as standing still. The cost of this choice is stated plainly: genuine crawling — a few metres of shunting in a yard — is not drawn either. We would rather lose that than invent kilometres.' },
        { h2: 'Fixes we refuse to trust', id: 'invalid' },
        { p: 'A position is marked **invalid** and excluded from everything when the device could not really see the sky:' },
        { ul: [
          '**Zero satellites** — the device is telling you it guessed.',
          '**Exactly 0° latitude and 0° longitude** — a point in the Atlantic off West Africa, the classic value a device sends when it has nothing. No vehicle of yours is there.',
        ] },
        { callout: 'note', p: 'An exact 0/0 is invalid at any satellite count, including a healthy one. A device that reports 0/0 with thirty satellites is not at that spot — it is masking its position or malfunctioning, and both readings are equally useless as a location.' },
        { h2: 'What an invalid fix cannot affect', id: 'consequences' },
        { p: 'Invalid positions never reach the map trail, trip distance, geofence entry and exit, speeding detection or any report. They do still count as contact — a device that reports invalid fixes is alive, and its power, battery and input events remain meaningful. That distinction matters: "no GPS" is a very different problem from "no contact".' },
        { h2: 'When speed looks wrong', id: 'speed' },
        { p: 'Reported speed comes from the GPS receiver, not from the vehicle\'s speedometer, and the two disagree slightly by design — a speedometer is required to never under-read and typically shows a few percent high. Where a vehicle reports CAN data, its own speed is available as well; see [CAN and OBD data](kb:can-and-obd).' },
        { p: 'A single implausible spike — 200 km/h for one record on a city street — is almost always a bad fix at the edge of a reflection. Look at the trip\'s speed chart: a genuine speed is a curve, and an artefact is a single spike with normal values on both sides.' },
      ],
    },
    lt: {
      title: 'Pozicijos tikslumas, dreifas ir pozicijos, kurias išmetame',
      summary: 'Kodėl stovintis automobilis atrodo klaidžiojantis, kas daro fiksaciją nepatikimą ir kokia taisyklė neleidžia blogoms pozicijoms patekti į jūsų skaičius.',
      keywords: ['tikslumas', 'dreifas', 'paklaida', 'palydovai', 'negaliojanti fiksacija', 'nulinė sala', 'klaidinga pozicija', 'jūra'],
      blocks: [
        { p: 'GPS yra labai geras ir nėra tobulas. Suprasti tris jo klydimo būdus – reiškia paaiškinti beveik viską, kas žemėlapyje nustebina.' },
        { h2: 'Įprastas tikslumas', id: 'normal' },
        { p: 'Esant atviram dangui, fiksacija paprastai tiksli iki kelių metrų. Pastatai, tiltai, tuneliai ir tankus miškas signalą atspindi ir blokuoja, tad tikslumas miesto gatvėje prastesnis nei automagistralėje – kartais dešimtimis metrų. Tai fizika, o ne defektas, ir tai galioja kiekvienam GPS įrenginiui, įskaitant jūsų telefoną.' },
        { h2: 'Dreifas: stovintis automobilis, kuris vis juda', id: 'drift' },
        { p: 'Nejudantis automobilis vis tiek kas minutę gauna šiek tiek kitokias pozicijas. Nubraižius tai tiesmukai, gaunamas mažas keverzonė aplink stovėjimo vietą ir, dar blogiau, kelių šimtų metrų atstumas, pridėtas prie dienos automobiliui, kuris niekur nevažiavo.' },
        { p: '{product} to nepiešia ir neskaičiuoja. Maži pozicijos pokyčiai, mažesni už ribą, ties kuria judėjimą galima atskirti nuo triukšmo, laikomi stovėjimu. Šio pasirinkimo kaina pasakoma atvirai: tikras šliaužimas – keli metrai manevruojant kieme – irgi nepiešiamas. Verčiau prarasime tai, nei prasimanysime kilometrų.' },
        { h2: 'Fiksacijos, kuriomis atsisakome tikėti', id: 'invalid' },
        { p: 'Pozicija pažymima **negaliojančia** ir pašalinama iš visko, kai įrenginys iš tikrųjų nematė dangaus:' },
        { ul: [
          '**Nulis palydovų** – įrenginys pats sako, kad spėjo.',
          '**Lygiai 0° platumos ir 0° ilgumos** – taškas Atlanto vandenyne prie Vakarų Afrikos, klasikinė reikšmė, kurią įrenginys siunčia neturėdamas nieko. Jūsų automobilio ten nėra.',
        ] },
        { callout: 'note', p: 'Tikslus 0/0 negalioja esant bet kokiam palydovų skaičiui, taip pat ir puikiam. Įrenginys, pranešantis 0/0 su trisdešimt palydovų, nėra toje vietoje – jis slepia savo poziciją arba veikia netinkamai, o abu atvejai kaip vieta vienodai bevertai.' },
        { h2: 'Ko negaliojanti fiksacija negali paveikti', id: 'consequences' },
        { p: 'Negaliojančios pozicijos niekada nepatenka nei į pėdsaką žemėlapyje, nei į kelionės atstumą, nei į įvažiavimą ir išvažiavimą iš geozonos, nei į greičio viršijimo aptikimą, nei į jokią ataskaitą. Jos vis dėlto skaitomos kaip ryšys – negaliojančias fiksacijas siunčiantis įrenginys yra gyvas, o jo maitinimo, baterijos ir įėjimų įvykiai lieka prasmingi. Tas skirtumas svarbus: „nėra GPS" ir „nėra ryšio" – labai skirtingos problemos.' },
        { h2: 'Kai greitis atrodo neteisingas', id: 'speed' },
        { p: 'Pranešamas greitis ateina iš GPS imtuvo, o ne iš automobilio spidometro, ir jie šiek tiek nesutampa iš principo – spidometras privalo niekada nerodyti mažiau, todėl paprastai rodo keliais procentais daugiau. Kur automobilis siunčia CAN duomenis, prieinamas ir jo paties greitis; žr. [CAN ir OBD duomenys](kb:can-and-obd).' },
        { p: 'Vienetinis neįtikėtinas šuolis – 200 km/h vieną įrašą miesto gatvėje – beveik visada yra bloga fiksacija ties atspindžio riba. Pažiūrėkite kelionės greičio grafiką: tikras greitis yra kreivė, o artefaktas – vienas smaigalys su normaliomis reikšmėmis iš abiejų pusių.' },
      ],
    },
    pl: {
      title: 'Dokładność pozycji, dryf i pozycje, które odrzucamy',
      summary: 'Dlaczego zaparkowany pojazd wydaje się wędrować, co czyni fixa niewiarygodnym i jaka reguła trzyma złe pozycje z dala od Twoich liczb.',
      keywords: ['dokładność', 'dryf', 'szum', 'satelity', 'nieprawidłowy fix', 'null island', 'zła pozycja', 'morze'],
      blocks: [
        { p: 'GPS jest bardzo dobry i nie jest doskonały. Zrozumienie trzech sposobów, w jakie się myli, wyjaśnia niemal wszystko, co zaskakuje na mapie.' },
        { h2: 'Zwykła dokładność', id: 'normal' },
        { p: 'Przy odsłoniętym niebie fix jest zwykle dokładny do kilku metrów. Budynki, mosty, tunele i gęsty las odbijają i blokują sygnał, więc dokładność w miejskiej ulicy jest gorsza niż na autostradzie — czasem o dziesiątki metrów. To fizyka, nie usterka, i dotyczy każdego urządzenia GPS, również Twojego telefonu.' },
        { h2: 'Dryf: zaparkowany pojazd, który wciąż jedzie', id: 'drift' },
        { p: 'Stojący pojazd i tak z minuty na minutę dostaje nieco inne pozycje. Narysowane wprost, dają małą bazgrołę wokół miejsca postoju i, co gorsza, kilkaset metrów dystansu dopisanego do dnia pojazdowi, który nigdzie nie pojechał.' },
        { p: '{product} tego nie rysuje i nie liczy. Drobne zmiany pozycji poniżej progu, przy którym ruch da się odróżnić od szumu, traktowane są jako postój. Koszt tego wyboru mówimy wprost: prawdziwe pełzanie — kilka metrów manewrowania na placu — też nie zostaje narysowane. Wolimy to stracić, niż wymyślać kilometry.' },
        { h2: 'Fixy, którym odmawiamy zaufania', id: 'invalid' },
        { p: 'Pozycja jest oznaczana jako **nieprawidłowa** i wykluczana ze wszystkiego, gdy urządzenie naprawdę nie widziało nieba:' },
        { ul: [
          '**Zero satelitów** — urządzenie samo mówi, że zgadywało.',
          '**Dokładnie 0° szerokości i 0° długości** — punkt na Atlantyku u wybrzeży Afryki Zachodniej, klasyczna wartość wysyłana, gdy urządzenie nie ma nic. Żadnego Twojego pojazdu tam nie ma.',
        ] },
        { callout: 'note', p: 'Dokładne 0/0 jest nieprawidłowe przy każdej liczbie satelitów, także przy dobrej. Urządzenie raportujące 0/0 przy trzydziestu satelitach nie jest w tym miejscu — maskuje swoją pozycję albo działa wadliwie, a oba odczyty są jako lokalizacja tak samo bezużyteczne.' },
        { h2: 'Na co nieprawidłowy fix nie może wpłynąć', id: 'consequences' },
        { p: 'Nieprawidłowe pozycje nigdy nie trafiają do śladu na mapie, dystansu trasy, wjazdów i wyjazdów ze stref, wykrywania przekroczeń prędkości ani do żadnego raportu. Nadal liczą się jednak jako kontakt — urządzenie raportujące nieprawidłowe fixy żyje, a jego zdarzenia zasilania, baterii i wejść pozostają istotne. To rozróżnienie ma znaczenie: „brak GPS" to zupełnie inny problem niż „brak kontaktu".' },
        { h2: 'Gdy prędkość wygląda źle', id: 'speed' },
        { p: 'Raportowana prędkość pochodzi z odbiornika GPS, nie z prędkościomierza pojazdu, i te dwie z założenia nieco się różnią — prędkościomierz nie może zaniżać i zwykle pokazuje kilka procent więcej. Tam, gdzie pojazd wysyła dane CAN, dostępna jest też jego własna prędkość; zobacz [Dane CAN i OBD](kb:can-and-obd).' },
        { p: 'Pojedynczy nieprawdopodobny skok — 200 km/h przez jeden rekord na miejskiej ulicy — to prawie zawsze zły fix na krawędzi odbicia. Spójrz na wykres prędkości trasy: prawdziwa prędkość to krzywa, a artefakt to pojedynczy szpic z normalnymi wartościami po obu stronach.' },
      ],
    },
    de: {
      title: 'Positionsgenauigkeit, Drift und verworfene Positionen',
      summary: 'Warum ein geparktes Fahrzeug zu wandern scheint, was einen Fix unglaubwürdig macht und welche Regel schlechte Positionen aus Ihren Zahlen hält.',
      keywords: ['genauigkeit', 'drift', 'rauschen', 'satelliten', 'ungültiger fix', 'null island', 'falsche position', 'meer'],
      blocks: [
        { p: 'GPS ist sehr gut und nicht perfekt. Wer die drei Arten kennt, wie es danebenliegt, erklärt damit fast alles Überraschende auf der Karte.' },
        { h2: 'Normale Genauigkeit', id: 'normal' },
        { p: 'Bei freier Himmelssicht ist ein Fix typischerweise auf wenige Meter genau. Gebäude, Brücken, Tunnel und dichter Wald reflektieren und blockieren das Signal, deshalb ist die Genauigkeit in einer Stadtstraße schlechter als auf der Autobahn — manchmal um Zehnermeter. Das ist Physik, kein Defekt, und betrifft jedes GPS-Gerät, auch Ihr Telefon.' },
        { h2: 'Drift: das geparkte Fahrzeug, das weiterfährt', id: 'drift' },
        { p: 'Ein stehendes Fahrzeug empfängt von Minute zu Minute leicht unterschiedliche Positionen. Naiv gezeichnet ergibt das ein kleines Gekritzel um den Stellplatz und, schlimmer, ein paar hundert Meter Tagesstrecke für ein Fahrzeug, das nie gefahren ist.' },
        { p: '{product} zeichnet das nicht und zählt es nicht. Positionsänderungen unterhalb der Schwelle, ab der Bewegung von Rauschen unterscheidbar ist, gelten als Stillstand. Der Preis dieser Entscheidung wird offen genannt: echtes Kriechen — ein paar Meter Rangieren auf dem Hof — wird ebenfalls nicht gezeichnet. Lieber verlieren wir das, als Kilometer zu erfinden.' },
        { h2: 'Fixe, denen wir nicht trauen', id: 'invalid' },
        { p: 'Eine Position gilt als **ungültig** und wird von allem ausgeschlossen, wenn das Gerät den Himmel wirklich nicht sehen konnte:' },
        { ul: [
          '**Null Satelliten** — das Gerät sagt Ihnen selbst, dass es geraten hat.',
          '**Exakt 0° Breite und 0° Länge** — ein Punkt im Atlantik vor Westafrika, der klassische Wert, den ein Gerät sendet, wenn es nichts hat. Keines Ihrer Fahrzeuge ist dort.',
        ] },
        { callout: 'note', p: 'Ein exaktes 0/0 ist bei jeder Satellitenzahl ungültig, auch bei einer guten. Ein Gerät, das 0/0 mit dreißig Satelliten meldet, ist nicht dort — es maskiert seine Position oder ist defekt, und beide Lesarten sind als Ort gleich wertlos.' },
        { h2: 'Was ein ungültiger Fix nicht beeinflussen kann', id: 'consequences' },
        { p: 'Ungültige Positionen erreichen nie die Kartenspur, die Fahrtstrecke, Zonen-Ein- und -Austritte, die Tempoüberschreitung oder irgendeinen Bericht. Als Kontakt zählen sie trotzdem — ein Gerät, das ungültige Fixe meldet, lebt, und seine Strom-, Batterie- und Eingangsereignisse bleiben aussagekräftig. Diese Unterscheidung zählt: „kein GPS" ist ein ganz anderes Problem als „kein Kontakt".' },
        { h2: 'Wenn die Geschwindigkeit falsch aussieht', id: 'speed' },
        { p: 'Die gemeldete Geschwindigkeit kommt vom GPS-Empfänger, nicht vom Tacho des Fahrzeugs, und beide weichen konstruktionsbedingt leicht ab — ein Tacho darf nie zu wenig anzeigen und liegt typischerweise ein paar Prozent darüber. Liefert ein Fahrzeug CAN-Daten, steht zusätzlich seine eigene Geschwindigkeit bereit; siehe [CAN- und OBD-Daten](kb:can-and-obd).' },
        { p: 'Ein einzelner unplausibler Ausschlag — 200 km/h für einen Datensatz in einer Stadtstraße — ist fast immer ein schlechter Fix am Rand einer Reflexion. Sehen Sie ins Geschwindigkeitsdiagramm der Fahrt: eine echte Geschwindigkeit ist eine Kurve, ein Artefakt ist eine einzelne Spitze mit normalen Werten davor und danach.' },
      ],
    },
  },
}
