import type { KbArticle } from '../types.js'

export const reportingIntervals: KbArticle = {
  slug: 'reporting-intervals',
  category: 'devices',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'Reporting intervals — how often the tracker speaks',
      summary: 'The six sliders that decide map freshness, data cost and battery life, and the trap of the roaming profile.',
      keywords: ['interval', 'send period', 'record period', 'frequency', 'data usage', 'battery', 'sliders', 'tracking settings'],
      blocks: [
        { p: 'Under **Tracking settings** on a device you can change how often it records and reports, without any SMS and at no cost. Two different things are being set, and telling them apart is the whole article.' },
        { h2: 'Record versus report', id: 'record-vs-report' },
        { ul: [
          '**Record** = when the tracker saves a position to its own memory. This is what gives a trip its shape — the corners, the detours, the exact route line.',
          '**Report** = when the tracker uploads what it has saved. This is what decides how fresh the live map is.',
        ] },
        { p: 'They are independent. A tracker can record every 5 seconds and report every 2 minutes: the route drawn later is perfectly detailed, and the marker on the live map is up to two minutes behind. That combination is the sensible default for most fleets.' },
        { h2: 'The six settings', id: 'settings' },
        { table: { head: ['Setting', 'What it changes'], rows: [
          ['**How often it reports while driving**', 'Live-map freshness during a trip. Lower = more current, more data.'],
          ['**How often it records while driving**', 'Detail of the route line and of speed data.'],
          ['**Record every … metres**', 'A distance trigger, so a fast road produces as much detail as a slow one.'],
          ['**Record on a turn of … degrees**', 'A turn trigger, so corners are captured even between the time and distance triggers. It is what stops a route looking like it cut across a block.'],
          ['**How often it records while parked**', 'Proof-of-presence for a stationary vehicle.'],
          ['**How often it reports while parked**', 'How quickly you learn a parked vehicle has moved or lost power.'],
        ] } },
        { h2: 'Watch the estimate, not the numbers', id: 'estimate' },
        { p: 'As you move the sliders, the page shows how much mobile data those settings will use per day and per month. Treat it as a floor: turns add extra records that no formula can predict. If your SIM has a small allowance, this estimate is the number to plan against — see [SIM cards and APN](kb:sim-and-apn).' },
        { h2: 'Zero means never', id: 'zero' },
        { callout: 'warning', p: 'On these trackers a send period of **0** does not mean “as fast as possible” — it means **do not transmit at all**. A device set that way records diligently and never says a word. If a tracker has gone quiet right after a settings change, this is the first thing to check.' },
        { h2: 'The roaming profile', id: 'roaming' },
        { p: 'These settings apply to the tracker\'s **home** network profile. Most Teltonika devices carry a separate profile for roaming, and it commonly ships configured not to transmit at all — a sensible factory default when nobody knows what roaming will cost.' },
        { p: 'The practical effect: a vehicle that works perfectly at home goes silent the moment it crosses a border, and comes back to life on the way home. If your fleet crosses borders, the roaming profile has to be configured deliberately.' },
        { h2: 'A change is queued, not instant', id: 'queue' },
        { p: 'The tracker may be asleep or out of coverage, so a change waits in a queue and is delivered the next time the device connects. The panel shows the state of each setting: waiting, sent, confirmed, or — occasionally — a note that the device kept its own value. What is shown is always what the **device** last confirmed, never what someone hoped it would be.' },
      ],
    },
    lt: {
      title: 'Siuntimo intervalai — kaip dažnai sekiklis prabyla',
      summary: 'Šeši slankikliai, lemiantys žemėlapio šviežumą, duomenų kainą ir baterijos tarnavimo laiką, ir tarptinklinio profilio spąstai.',
      keywords: ['intervalas', 'siuntimo periodas', 'įrašymo periodas', 'dažnis', 'duomenys', 'baterija', 'slankikliai', 'sekimo nustatymai'],
      blocks: [
        { p: 'Įrenginio skiltyje **Sekimo nustatymai** galima keisti, kaip dažnai jis dirba – be jokių SMS ir nemokamai. Nustatomi du skirtingi dalykai, ir juos atskirti – visas šio straipsnio turinys.' },
        { h2: 'Įrašymas ir siuntimas — ne tas pat', id: 'record-vs-report' },
        { ul: [
          '**Įrašymas** = kada sekiklis išsaugo poziciją savo atmintyje. Būtent tai suteikia kelionei formą – posūkius, aplinkkelius, tikslią maršruto liniją.',
          '**Siuntimas** = kada sekiklis išsiunčia tai, ką išsaugojo. Būtent tai lemia, koks šviežias yra gyvas žemėlapis.',
        ] },
        { p: 'Jie nepriklausomi. Sekiklis gali įrašinėti kas 5 sekundes, o siųsti kas 2 minutes: vėliau nubraižytas maršrutas bus nepriekaištingai detalus, o taškas gyvame žemėlapyje atsiliks iki dviejų minučių. Daugumai autoparkų tai protingiausias derinys.' },
        { h2: 'Šeši nustatymai', id: 'settings' },
        { table: { head: ['Nustatymas', 'Ką keičia'], rows: [
          ['**Kaip dažnai siunčia važiuojant**', 'Gyvo žemėlapio šviežumą kelionės metu. Mažiau = aktualiau, bet daugiau duomenų.'],
          ['**Kaip dažnai įrašo važiuojant**', 'Maršruto linijos ir greičio duomenų detalumą.'],
          ['**Įrašyti kas … metrų**', 'Įrašymo sąlyga pagal atstumą, kad greitkelis duotų tiek pat detalumo, kiek ir lėta gatvė.'],
          ['**Įrašyti pasukus … laipsnių**', 'Užfiksuoja posūkius net tarp įrašymo pagal laiką ir pagal atstumą. Kaip tik dėl to maršrutas neatrodo tarsi kirtęs kvartalą skersai.'],
          ['**Kaip dažnai įrašo stovint**', 'Stovinčio automobilio buvimo įrodymą.'],
          ['**Kaip dažnai siunčia stovint**', 'Kaip greitai sužinosite, kad stovintis automobilis pajudėjo ar neteko maitinimo.'],
        ] } },
        { h2: 'Žiūrėkite į įvertinimą, o ne į skaičius', id: 'estimate' },
        { p: 'Judinant slankiklius puslapis rodo, kiek mobiliųjų duomenų tos pozicijos kainuos per parą ir per mėnesį. Laikykite tai apatine riba: posūkiai prideda įrašų, kurių jokia formulė nenuspės. Jei SIM limitas mažas, planuokite pagal šį skaičių – žr. [SIM kortelės ir APN](kb:sim-and-apn).' },
        { h2: 'Nulis reiškia „niekada“', id: 'zero' },
        { callout: 'warning', p: 'Šiuose sekikliuose siuntimo periodas **0** reiškia ne „kuo greičiau“, o **visai nesiųsti**. Taip nustatytas įrenginys stropiai įrašinėja ir netaria nė žodžio. Jei sekiklis nutilo iškart po nustatymų pakeitimo – tai pirmas dalykas, kurį reikia patikrinti.' },
        { h2: 'Tarptinklinio ryšio profilis', id: 'roaming' },
        { p: 'Šie nustatymai galioja sekiklio **namų** tinklo profiliui. Dauguma Teltonika įrenginių turi atskirą profilį tarptinkliniam ryšiui, ir jis dažniausiai iš gamyklos sukonfigūruotas išvis nesiųsti – protingas numatytasis nustatymas, kai niekas nežino, kiek tarptinklinis ryšys kainuos.' },
        { p: 'Praktinis padarinys: namuose nepriekaištingai veikiantis automobilis nutyla vos kirtęs sieną ir atgyja pakeliui namo. Jei jūsų autoparkas kerta sienas, tarptinklinį profilį reikia sukonfigūruoti sąmoningai.' },
        { h2: 'Pakeitimas patenka į eilę, o ne įvyksta iškart', id: 'queue' },
        { p: 'Sekiklis gali miegoti arba būti be ryšio, todėl pakeitimas laukia eilėje ir pristatomas kitą kartą įrenginiui prisijungus. Skydelis rodo kiekvieno nustatymo būseną: laukiama, išsiųsta, patvirtinta arba – retkarčiais – kad įrenginys pasiliko savo reikšmę. Rodoma visada tai, ką paskutinį kartą patvirtino **įrenginys**, o ne tai, ko kas nors tikėjosi.' },
      ],
    },
    pl: {
      title: 'Częstotliwość raportowania — jak często lokalizator się odzywa',
      summary: 'Sześć suwaków decydujących o świeżości mapy, koszcie danych i żywotności baterii, oraz pułapka profilu roamingowego.',
      keywords: ['interwał', 'okres wysyłki', 'okres zapisu', 'częstotliwość', 'zużycie danych', 'bateria', 'suwaki', 'ustawienia śledzenia'],
      blocks: [
        { p: 'W **Ustawieniach śledzenia** urządzenia można zmienić, jak często pracuje — bez żadnego SMS-a i bez kosztów. Ustawiane są dwie różne rzeczy, a ich rozróżnienie to cała treść tego artykułu.' },
        { h2: 'Zapis kontra wysyłka', id: 'record-vs-report' },
        { ul: [
          '**Zapis** = kiedy lokalizator zapisuje pozycję we własnej pamięci. To nadaje trasie kształt — zakręty, objazdy, dokładną linię przejazdu.',
          '**Wysyłka** = kiedy lokalizator przesyła to, co zapisał. To decyduje, jak świeża jest mapa na żywo.',
        ] },
        { p: 'Są niezależne. Lokalizator może zapisywać co 5 sekund, a wysyłać co 2 minuty: narysowana później trasa będzie doskonale szczegółowa, a kropka na mapie na żywo spóźniona nawet o dwie minuty. Dla większości flot to rozsądny domyślny zestaw.' },
        { h2: 'Sześć ustawień', id: 'settings' },
        { table: { head: ['Ustawienie', 'Co zmienia'], rows: [
          ['**Jak często raportuje w czasie jazdy**', 'Świeżość mapy na żywo podczas trasy. Mniej = aktualniej, więcej danych.'],
          ['**Jak często zapisuje w czasie jazdy**', 'Szczegółowość linii trasy i danych o prędkości.'],
          ['**Zapis co … metrów**', 'Wyzwalacz dystansowy, żeby szybka droga dawała tyle samo szczegółów co wolna.'],
          ['**Zapis przy skręcie o … stopni**', 'Łapie zakręty nawet pomiędzy wyzwalaczem czasu i dystansu. To dzięki temu trasa nie wygląda, jakby ścięła róg przez kwartał zabudowy.'],
          ['**Jak często zapisuje na postoju**', 'Dowód obecności stojącego pojazdu.'],
          ['**Jak często raportuje na postoju**', 'Jak szybko dowiesz się, że zaparkowany pojazd ruszył albo stracił zasilanie.'],
        ] } },
        { h2: 'Patrz na szacunek, nie na liczby', id: 'estimate' },
        { p: 'Przy przesuwaniu suwaków strona pokazuje, ile danych będą kosztować te pozycje dziennie i miesięcznie. Traktuj to jako dolną granicę: zakręty dodają zapisy, których żaden wzór nie przewidzi. Przy małym pakiecie danych to właśnie ta liczba wyznacza ustawienia — zobacz [Karty SIM i APN](kb:sim-and-apn).' },
        { h2: 'Zero znaczy nigdy', id: 'zero' },
        { callout: 'warning', p: 'W tych lokalizatorach okres wysyłki **0** nie znaczy „tak szybko, jak się da” — znaczy **w ogóle nie nadawaj**. Tak ustawione urządzenie pilnie zapisuje i nie mówi ani słowa. Jeśli lokalizator zamilkł zaraz po zmianie ustawień, sprawdź to w pierwszej kolejności.' },
        { h2: 'Profil roamingowy', id: 'roaming' },
        { p: 'Te ustawienia dotyczą profilu sieci **macierzystej**. Większość urządzeń Teltonika ma osobny profil dla roamingu i zwykle wychodzi on z fabryki ustawiony tak, by w ogóle nie nadawać — rozsądne domyślne ustawienie, gdy nikt nie wie, ile roaming będzie kosztować.' },
        { p: 'Praktyczny skutek: pojazd działający bez zarzutu w kraju milknie z chwilą przekroczenia granicy i ożywa w drodze powrotnej. Jeśli flota przekracza granice, profil roamingowy trzeba skonfigurować świadomie.' },
        { h2: 'Zmiana trafia do kolejki, nie działa natychmiast', id: 'queue' },
        { p: 'Lokalizator może spać albo być poza zasięgiem, więc zmiana czeka w kolejce i zostaje dostarczona przy następnym połączeniu urządzenia. Panel pokazuje stan każdego ustawienia: oczekuje, wysłano, potwierdzono albo — czasem — że urządzenie zachowało własną wartość. Pokazywane jest zawsze to, co ostatnio potwierdziło **urządzenie**, a nie to, czego ktoś się spodziewał.' },
      ],
    },
    de: {
      title: 'Meldeintervalle — wie oft der Tracker spricht',
      summary: 'Die sechs Regler, die Kartenaktualität, Datenkosten und Akkulaufzeit bestimmen — und die Falle des Roaming-Profils.',
      keywords: ['intervall', 'sendeintervall', 'aufzeichnungsintervall', 'frequenz', 'datenverbrauch', 'akku', 'regler', 'tracking-einstellungen'],
      blocks: [
        { p: 'Unter **Tracking-Einstellungen** eines Geräts lässt sich ändern, wie oft es arbeitet — ohne SMS und kostenlos. Dabei werden zwei verschiedene Dinge eingestellt, und sie auseinanderzuhalten ist der ganze Artikel.' },
        { h2: 'Aufzeichnen oder Senden — der Unterschied', id: 'record-vs-report' },
        { ul: [
          '**Aufzeichnen** = wann der Tracker eine Position in seinen eigenen Speicher schreibt. Das gibt einer Fahrt ihre Form — Kurven, Umwege, die exakte Streckenlinie.',
          '**Senden** = wann der Tracker das Gespeicherte hochlädt. Das bestimmt, wie aktuell die Live-Karte ist.',
        ] },
        { p: 'Beides ist unabhängig. Ein Tracker kann alle 5 Sekunden aufzeichnen und alle 2 Minuten senden: Die später gezeichnete Strecke ist perfekt detailliert, der Punkt auf der Live-Karte bis zu zwei Minuten hinterher. Für die meisten Flotten ist genau das die sinnvolle Voreinstellung.' },
        { h2: 'Die sechs Einstellungen', id: 'settings' },
        { table: { head: ['Einstellung', 'Was sie ändert'], rows: [
          ['**Wie oft während der Fahrt gesendet wird**', 'Aktualität der Live-Karte während einer Fahrt. Kleiner = aktueller, mehr Daten.'],
          ['**Wie oft während der Fahrt aufgezeichnet wird**', 'Detailgrad der Streckenlinie und der Geschwindigkeitsdaten.'],
          ['**Aufzeichnen alle … Meter**', 'Ein Distanzauslöser, damit eine Schnellstraße genauso viel Detail liefert wie eine langsame Straße.'],
          ['**Aufzeichnen bei … Grad Kurvenwinkel**', 'Erfasst Kurven auch zwischen Zeit- und Distanzauslöser. Genau das verhindert, dass eine Strecke aussieht, als hätte sie den Block abgeschnitten.'],
          ['**Wie oft im Stand aufgezeichnet wird**', 'Anwesenheitsnachweis für ein stehendes Fahrzeug.'],
          ['**Wie oft im Stand gesendet wird**', 'Wie schnell Sie erfahren, dass ein geparktes Fahrzeug bewegt wurde oder den Strom verloren hat.'],
        ] } },
        { h2: 'Achten Sie auf die Schätzung, nicht auf die Zahlen', id: 'estimate' },
        { p: 'Beim Verschieben der Regler zeigt die Seite, wie viele Mobilfunkdaten diese Positionen pro Tag und pro Monat kosten. Nehmen Sie sie als Untergrenze: Kurven erzeugen Zusatzdatensätze, die keine Formel vorhersagt. Bei kleinem SIM-Volumen ist diese Schätzung die Zahl, an der Sie sich orientieren müssen — siehe [SIM-Karten und APN](kb:sim-and-apn).' },
        { h2: 'Null bedeutet nie', id: 'zero' },
        { callout: 'warning', p: 'Bei diesen Trackern heißt ein Meldeintervall von **0** nicht „so schnell wie möglich“ — es heißt **gar nicht senden**. Ein so eingestelltes Gerät zeichnet fleißig auf und sagt kein Wort. Ist ein Tracker direkt nach einer Einstellungsänderung verstummt, prüfen Sie das zuerst.' },
        { h2: 'Das Roaming-Profil', id: 'roaming' },
        { p: 'Diese Einstellungen gelten für das **Heimnetz**-Profil des Trackers. Die meisten Teltonika-Geräte führen ein eigenes Profil fürs Roaming, und es kommt üblicherweise so konfiguriert, dass gar nicht gesendet wird — eine vernünftige Werksvoreinstellung, solange niemand weiß, was Roaming kostet.' },
        { p: 'Der praktische Effekt: Ein Fahrzeug, das zu Hause tadellos läuft, verstummt beim Grenzübertritt und lebt auf dem Rückweg wieder auf. Fährt Ihre Flotte über Grenzen, muss das Roaming-Profil bewusst eingerichtet werden.' },
        { h2: 'Eine Änderung wird eingereiht und ist nicht sofort wirksam', id: 'queue' },
        { p: 'Der Tracker kann schlafen oder ohne Netz sein, deshalb wartet eine Änderung in einer Warteschlange und wird beim nächsten Verbinden zugestellt. Das Panel zeigt den Zustand jeder Einstellung: wartend, gesendet, bestätigt oder — gelegentlich — dass das Gerät seinen eigenen Wert behalten hat. Angezeigt wird immer, was das **Gerät** zuletzt bestätigt hat, nie das, was jemand erhofft hat.' },
      ],
    },
  },
}
