import type { KbArticle } from '../types.js'

export const reportTypes: KbArticle = {
  slug: 'report-types',
  category: 'reports',
  surfaces: { site: true, app: true },
  screen: '/app/reports',
  doc: {
    en: {
      title: 'Which report answers which question',
      summary: 'Six reports, the question each one is for, and how to export the answer as CSV or PDF.',
      keywords: ['report', 'mileage', 'trips', 'stops', 'overspeed', 'geofence', 'engine hours', 'csv', 'pdf', 'export'],
      blocks: [
        { p: 'Reports run over a date range, for one vehicle or the whole fleet. Choose by the question you are trying to answer, not by the name.' },
        { h2: 'The six', id: 'six' },
        { table: { head: ['Report', 'Answers'], rows: [
          ['**Mileage**', '“How far did each vehicle go?” One line per vehicle per day: how many trips, and the distance. The number for cost per kilometre, reimbursement and lease limits.'],
          ['**Trips**', '“Where did it go, and when?” The only report that lists journeys individually: start, end, distance, which source that distance came from, top speed and idle time.'],
          ['**Stops**', '“How much of the day was spent standing?” One line per vehicle per day: how many trips, and the total idle time inside them.'],
          ['**Overspeed**', '“Who drove too fast, and how fast?” One line per vehicle per day: how many events, and the highest speed reached.'],
          ['**Geofence**', '“How much zone traffic was there?” One line per vehicle per day: entries and exits, counted across all zones together.'],
          ['**Engine hours**', '“How long did the engine run?” One line per vehicle per day. The measure for machinery and for vehicles that work standing still, where kilometres say nothing.'],
        ] } },
        { callout: 'note', p: 'Five of the six are daily summaries: one line per vehicle per day, not one line per event. Only **Trips** lists journeys individually, and one run of it returns at most 5 000 of them. If you need which zone, which moment or which driver, that detail is in the events list, the trip list and [Replaying a day](kb:playback) — not in these reports.' },
        { h2: 'Getting the answer out', id: 'export' },
        { ul: [
          '**CSV** for anything that continues into a spreadsheet or an accounting system.',
          '**PDF** for anything that goes to a customer or into a file. It carries the report type, the range and the moment it was generated, so it can be checked later.',
        ] },
        { h2: 'Ranges and grouping', id: 'ranges' },
        { p: 'Days are cut according to the account\'s time zone, so a night shift that crosses midnight lands where your business would put it. If two people get different totals for “last week”, the first thing to compare is not the data but the range and the time zone — see [Time zones and units](kb:time-zones-and-units).' },
        { callout: 'note', p: 'A report reflects the data that had arrived when you ran it. A vehicle whose records were delayed by poor coverage may change the previous day\'s totals slightly once they land. For an invoice, run the report a day after the period closes rather than in the last hour of it.' },
        { h2: 'Reports on a schedule', id: 'scheduled' },
        { p: 'Any report you run regularly should not be run by hand. A weekly mileage report that arrives on Monday morning gets read; the same report that has to be remembered does not — see [Scheduled reports](kb:scheduled-reports).' },
      ],
    },
    lt: {
      title: 'Kuri ataskaita atsako į kurį klausimą',
      summary: 'Šešios ataskaitos, kokiam klausimui kiekviena skirta ir kaip atsakymą eksportuoti į CSV ar PDF.',
      keywords: ['ataskaita', 'rida', 'kelionės', 'sustojimai', 'greičio viršijimas', 'geozona', 'variklio valandos', 'csv', 'pdf'],
      blocks: [
        { p: 'Ataskaitos paleidžiamos už datų intervalą, vienam automobiliui arba visam parkui. Rinkitės pagal klausimą, į kurį bandote atsakyti, o ne pagal pavadinimą.' },
        { h2: 'Šešios', id: 'six' },
        { table: { head: ['Ataskaita', 'Atsako'], rows: [
          ['**Rida**', '„Kiek kiekvienas automobilis nuvažiavo?“ Viena eilutė per automobilį per dieną: kiek kelionių ir koks atstumas. Skaičius kilometro savikainai, kompensacijoms ir lizingo limitams.'],
          ['**Kelionės**', '„Kur važiavo ir kada?“ Vienintelė ataskaita, kurioje reisai surašyti po vieną: pradžia, pabaiga, atstumas, iš kur tas atstumas gautas, didžiausias greitis ir stovėjimo su varikliu laikas.'],
          ['**Sustojimai**', '„Kiek dienos praleista stovint?“ Viena eilutė per automobilį per dieną: kiek kelionių ir kiek jose iš viso stovėta su veikiančiu varikliu.'],
          ['**Greičio viršijimas**', '„Kas važiavo per greitai ir kaip greitai?“ Viena eilutė per automobilį per dieną: kiek įvykių ir koks didžiausias pasiektas greitis.'],
          ['**Geozonos**', '„Kiek buvo judėjimo per zonas?“ Viena eilutė per automobilį per dieną: įvažiavimai ir išvažiavimai, suskaičiuoti per visas zonas kartu.'],
          ['**Variklio valandos**', '„Kiek veikė variklis?“ Viena eilutė per automobilį per dieną. Matas technikai ir stovint dirbantiems automobiliams, kur kilometrai nieko nepasako.'],
        ] } },
        { callout: 'note', p: 'Penkios iš šešių yra dienos suvestinės: viena eilutė per automobilį per dieną, o ne viena eilutė per įvykį. Tik **Kelionės** surašo reisus po vieną, ir vienu paleidimu grąžina daugiausia 5 000. Jei reikia kurios zonos, kurios akimirkos ar kurio vairuotojo – tai yra įvykių sąraše, kelionių sąraše ir [Dienos peržaidime](kb:playback), o ne šiose ataskaitose.' },
        { h2: 'Kaip išsinešti atsakymą', id: 'export' },
        { ul: [
          '**CSV** – viskam, kas keliauja toliau į skaičiuoklę ar apskaitos sistemą.',
          '**PDF** – viskam, kas eina klientui ar į bylą. Jame nurodytas ataskaitos tipas, intervalas ir sugeneravimo momentas, tad vėliau galima pasitikrinti.',
        ] },
        { h2: 'Intervalai ir grupavimas', id: 'ranges' },
        { p: 'Dienos kerpamos pagal paskyros laiko juostą, tad naktinė pamaina, peržengianti vidurnaktį, atsiduria ten, kur ją dėtų jūsų verslas. Jei du žmonės gauna skirtingas „praėjusios savaitės“ sumas, pirmiausia lyginti reikia ne duomenis, o intervalą ir laiko juostą – žr. [Laiko juostos ir vienetai](kb:time-zones-and-units).' },
        { callout: 'note', p: 'Ataskaita atspindi duomenis, atkeliavusius iki jos paleidimo. Automobilis, kurio įrašai vėlavo dėl prastos aprėpties, atkeliavus gali šiek tiek pakeisti praėjusios dienos sumas. Sąskaitai ataskaitą paleiskite kitą dieną po laikotarpio pabaigos, o ne paskutinę jo valandą.' },
        { h2: 'Ataskaitos pagal grafiką', id: 'scheduled' },
        { p: 'Bet kurios reguliariai paleidžiamos ataskaitos nereikėtų paleidinėti ranka. Savaitinė ridos ataskaita, atkeliaujanti pirmadienio rytą, perskaitoma; ta pati ataskaita, kurią reikia prisiminti – ne. Žr. [Planinės ataskaitos](kb:scheduled-reports).' },
      ],
    },
    pl: {
      title: 'Który raport odpowiada na które pytanie',
      summary: 'Sześć raportów, pytanie, do którego każdy służy, i jak wyeksportować odpowiedź do CSV lub PDF.',
      keywords: ['raport', 'przebieg', 'trasy', 'postoje', 'przekroczenia', 'geostrefa', 'motogodziny', 'csv', 'pdf'],
      blocks: [
        { p: 'Raporty uruchamia się na zakres dat, dla jednego pojazdu albo całej floty. Wybieraj według pytania, na które szukasz odpowiedzi, nie według nazwy.' },
        { h2: 'Sześć raportów', id: 'six' },
        { table: { head: ['Raport', 'Odpowiada na'], rows: [
          ['**Przebieg**', '„Ile przejechał każdy pojazd?” Jeden wiersz na pojazd na dzień: ile tras i jaki dystans. Liczba do kosztu kilometra, rozliczeń i limitów leasingowych.'],
          ['**Trasy**', '„Dokąd jechał i kiedy?” Jedyny raport, który wymienia trasy pojedynczo: początek, koniec, dystans, źródło tego dystansu, prędkość maksymalna i czas postoju z pracującym silnikiem.'],
          ['**Postoje**', '„Ile dnia zeszło na staniu?” Jeden wiersz na pojazd na dzień: ile tras i ile łącznie w nich postoju z pracującym silnikiem.'],
          ['**Prędkość**', '„Kto jechał za szybko i jak szybko?” Jeden wiersz na pojazd na dzień: ile zdarzeń i jaka najwyższa osiągnięta prędkość.'],
          ['**Geostrefy**', '„Ile było ruchu przez strefy?” Jeden wiersz na pojazd na dzień: wjazdy i wyjazdy, policzone łącznie dla wszystkich stref.'],
          ['**Godziny pracy**', '„Jak długo pracował silnik?” Jeden wiersz na pojazd na dzień. Miara dla maszyn i pojazdów pracujących na postoju, gdzie kilometry nic nie mówią.'],
        ] } },
        { callout: 'note', p: 'Pięć z sześciu to zestawienia dzienne: jeden wiersz na pojazd na dzień, a nie jeden wiersz na zdarzenie. Tylko **Trasy** wymieniają kursy pojedynczo i jedno uruchomienie zwraca ich najwyżej 5 000. Jeśli potrzebujesz, która strefa, która chwila albo który kierowca — ten szczegół jest na liście zdarzeń, na liście tras i w [Odtwarzaniu dnia](kb:playback), a nie w tych raportach.' },
        { h2: 'Wyniesienie odpowiedzi', id: 'export' },
        { ul: [
          '**CSV** do wszystkiego, co idzie dalej do arkusza albo systemu księgowego.',
          '**PDF** do wszystkiego, co trafia do klienta albo do akt. Zawiera typ raportu, zakres i moment wygenerowania, więc da się to później sprawdzić.',
        ] },
        { h2: 'Zakresy i grupowanie', id: 'ranges' },
        { p: 'Dni są cięte według strefy czasowej konta, więc nocna zmiana przechodząca przez północ ląduje tam, gdzie umieściłaby ją Twoja firma. Jeśli dwie osoby dostają różne sumy za „zeszły tydzień”, najpierw porównaj nie dane, tylko zakres i strefę czasową — zobacz [Strefy czasowe i jednostki](kb:time-zones-and-units).' },
        { callout: 'note', p: 'Raport odzwierciedla dane, które dotarły do momentu jego uruchomienia. Pojazd, którego zapisy opóźnił słaby zasięg, po ich dotarciu może nieco zmienić sumy z poprzedniego dnia. Do faktury uruchom raport dzień po zamknięciu okresu, a nie w jego ostatniej godzinie.' },
        { h2: 'Raporty według harmonogramu', id: 'scheduled' },
        { p: 'Raportu uruchamianego regularnie nie powinno się uruchamiać ręcznie. Tygodniowy raport przebiegu, który przychodzi w poniedziałek rano, zostaje przeczytany; ten sam raport, o którym trzeba pamiętać — nie. Zobacz [Raporty cykliczne](kb:scheduled-reports).' },
      ],
    },
    de: {
      title: 'Welcher Bericht welche Frage beantwortet',
      summary: 'Sechs Berichte, die Frage hinter jedem, und wie Sie die Antwort als CSV oder PDF exportieren.',
      keywords: ['bericht', 'kilometer', 'fahrten', 'halte', 'tempoüberschreitung', 'geozone', 'motorstunden', 'csv', 'pdf'],
      blocks: [
        { p: 'Berichte laufen über einen Zeitraum, für ein Fahrzeug oder die ganze Flotte. Wählen Sie nach der Frage, die Sie beantworten wollen, nicht nach dem Namen.' },
        { h2: 'Die sechs', id: 'six' },
        { table: { head: ['Bericht', 'Beantwortet'], rows: [
          ['**Kilometer**', '„Wie weit ist jedes Fahrzeug gefahren?“ Eine Zeile je Fahrzeug und Tag: wie viele Fahrten und welche Strecke. Die Zahl für Kilometerkosten, Erstattung und Leasinggrenzen.'],
          ['**Fahrten**', '„Wohin ist es gefahren, und wann?“ Der einzige Bericht, der Fahrten einzeln auflistet: Start, Ende, Strecke, aus welcher Quelle diese Strecke stammt, Höchstgeschwindigkeit und Leerlaufzeit.'],
          ['**Stopps**', '„Wie viel vom Tag stand das Fahrzeug?“ Eine Zeile je Fahrzeug und Tag: wie viele Fahrten und wie viel Leerlauf insgesamt darin.'],
          ['**Tempo**', '„Wer ist zu schnell gefahren, und wie schnell?“ Eine Zeile je Fahrzeug und Tag: wie viele Ereignisse und welche Höchstgeschwindigkeit.'],
          ['**Geofence**', '„Wie viel Zonenverkehr gab es?“ Eine Zeile je Fahrzeug und Tag: Ein- und Ausfahrten, über alle Zonen zusammengezählt.'],
          ['**Motorstunden**', '„Wie lange lief der Motor?“ Eine Zeile je Fahrzeug und Tag. Das Maß für Maschinen und für Fahrzeuge, die im Stand arbeiten, wo Kilometer nichts sagen.'],
        ] } },
        { callout: 'note', p: 'Fünf der sechs sind Tagesauswertungen: eine Zeile je Fahrzeug und Tag, nicht eine Zeile je Ereignis. Nur **Fahrten** listet einzelne Fahrten auf, und ein Lauf liefert höchstens 5 000 davon. Wenn Sie wissen müssen, welche Zone, welcher Moment oder welcher Fahrer — dieses Detail steht in der Ereignisliste, der Fahrtenliste und in [Einen Tag wiedergeben](kb:playback), nicht in diesen Berichten.' },
        { h2: 'Die Antwort mitnehmen', id: 'export' },
        { ul: [
          '**CSV** für alles, was in einer Tabelle oder Buchhaltung weiterläuft.',
          '**PDF** für alles, was zu einem Kunden oder in eine Akte geht. Es trägt Berichtstyp, Zeitraum und Erstellungszeitpunkt, ist also später prüfbar.',
        ] },
        { h2: 'Zeiträume und Gruppierung', id: 'ranges' },
        { p: 'Tage werden nach der Zeitzone des Kontos geschnitten, damit eine Nachtschicht über Mitternacht dort landet, wo Ihr Betrieb sie hinlegen würde. Kommen zwei Leute für „letzte Woche“ auf verschiedene Summen, vergleichen Sie zuerst nicht die Daten, sondern Zeitraum und Zeitzone — siehe [Zeitzonen und Einheiten](kb:time-zones-and-units).' },
        { callout: 'note', p: 'Ein Bericht zeigt die Daten, die beim Ausführen vorlagen. Ein Fahrzeug, dessen Datensätze wegen schlechter Abdeckung verzögert waren, kann die Summen des Vortags nach Eintreffen leicht verändern. Für eine Rechnung führen Sie den Bericht einen Tag nach Periodenende aus, nicht in dessen letzter Stunde.' },
        { h2: 'Berichte nach Zeitplan', id: 'scheduled' },
        { p: 'Was Sie regelmäßig ausführen, sollten Sie nicht von Hand ausführen. Ein wöchentlicher Kilometerbericht, der Montagfrüh ankommt, wird gelesen; derselbe Bericht, an den man denken muss, nicht — siehe [Geplante Berichte](kb:scheduled-reports).' },
      ],
    },
  },
}
