import type { KbArticle } from '../types.js'

export const routePlanner: KbArticle = {
  slug: 'route-planner',
  category: 'trips',
  surfaces: { site: true, app: true },
  screen: '/app/routing',
  doc: {
    en: {
      title: 'Planning the order of a day\'s stops',
      summary: 'Give the planner your stops and it returns the shortest visiting order over real roads — and the two things it deliberately does not do.',
      keywords: ['route', 'planner', 'optimise', 'stops', 'order', 'delivery', 'roundtrip', 'itinerary'],
      blocks: [
        { p: 'A driver with eight addresses and a map on the passenger seat will find an order that works. The planner finds the shortest one, over the actual road network, in about a second.' },
        { h2: 'Giving it the stops', id: 'input' },
        { ul: [
          '**Click the map** to drop each stop where it belongs. Fastest for a handful of places you can see.',
          '**Paste a list**, one stop per line as `latitude,longitude` with an optional label after a second comma. This is the way in for stops that already exist in a spreadsheet or another system.',
        ] },
        { p: 'Up to twelve stops. The limit is not arbitrary: the number of possible orders grows explosively, and twelve is where an exact answer still arrives while somebody is looking at the screen. A longer day is two routes.' },
        { h2: 'Roundtrip or not', id: 'roundtrip' },
        { p: 'Tick **Return to start** when the vehicle comes back to the depot, and the last leg home is counted in the total. Leave it off for a run that ends at the last customer — a courier finishing near home, or a vehicle staying out overnight. The two answers can be genuinely different orders, not just different totals.' },
        { h2: 'Reading the result', id: 'result' },
        { p: 'The stops are renumbered into the order you should drive them in, each row shows the distance and time to the next one, and the total is at the bottom. The route is drawn on the map, following real roads rather than straight lines between points.' },
        { callout: 'note', p: 'The times are free-flow driving times over the road network. They contain no traffic, no loading, no waiting and no coffee. Treat the total as the floor of the day, not the plan for it — add your own per-stop time before promising anyone a window.' },
        { h2: 'What it deliberately does not do', id: 'not' },
        { ul: [
          '**It does not know your vehicles.** There are no capacities, no time windows and no driver shifts. It answers one question — the shortest order for these stops — and answers it well.',
          '**It does not dispatch.** The order is not sent to a driver or attached to a vehicle; it is a plan on your screen to act on.',
          '**It does not learn.** Yesterday\'s traffic does not change today\'s answer.',
        ] },
        { h2: 'Where the addresses come from', id: 'addresses' },
        { p: 'The planner takes coordinates, not street addresses. If your stops live as addresses in another system, convert them there once and keep the coordinates — a customer\'s yard entrance is rarely the point a geocoder picks for their postal address, and the difference is exactly the last hundred metres a driver has to guess at.' },
      ],
    },
    lt: {
      title: 'Dienos sustojimų tvarkos planavimas',
      summary: 'Nurodykite sustojimus, ir planuoklė grąžins trumpiausią aplankymo tvarką tikrais keliais – ir du dalykus, kurių ji sąmoningai nedaro.',
      keywords: ['maršrutas', 'planuoklė', 'optimizavimas', 'sustojimai', 'tvarka', 'pristatymas', 'žiedinis maršrutas'],
      blocks: [
        { p: 'Vairuotojas su aštuoniais adresais ir žemėlapiu ant keleivio sėdynės ras tinkamą tvarką. Planuoklė tikru kelių tinklu randa trumpiausią maždaug per sekundę.' },
        { h2: 'Kaip nurodyti sustojimus', id: 'input' },
        { ul: [
          '**Spustelėkite žemėlapį** ir sudėkite kiekvieną sustojimą ten, kur jam vieta. Greičiausias būdas, kai taškų nedaug ir juos matote.',
          '**Įklijuokite sąrašą** – po vieną sustojimą eilutėje, `platuma,ilguma`, o po antro kablelio galima pridėti pavadinimą. Taip sustojimai perkeliami iš skaičiuoklės ar kitos sistemos.',
        ] },
        { p: 'Iki dvylikos sustojimų. Riba nėra atsitiktinė: galimų tvarkų skaičius auga kaip lavina, o ties dvylika tikslus atsakymas dar spėja ateiti, kol žmogus žiūri į ekraną. Ilgesnė diena – du maršrutai.' },
        { h2: 'Su grįžimu ar be', id: 'roundtrip' },
        { p: 'Pažymėkite **Grįžti į pradžią**, kai automobilis grįžta į bazę – tada paskutinė atkarpa atgal į bazę įskaičiuojama į sumą. Nežymėkite, kai reisas baigiasi pas paskutinį klientą – kurjeris baigia netoli namų arba automobilis lieka nakvoti kelyje. Abu atsakymai gali būti iš tiesų skirtingos tvarkos, o ne vien skirtingos sumos.' },
        { h2: 'Kaip skaityti rezultatą', id: 'result' },
        { p: 'Sustojimai pernumeruojami ta tvarka, kuria juos reikia aplankyti, kiekvienoje eilutėje matyti atstumas ir laikas iki kito sustojimo, o apačioje – bendra suma. Maršrutas nubraižomas žemėlapyje tikrais keliais, o ne tiesiomis linijomis tarp taškų.' },
        { callout: 'note', p: 'Laikai – laisvo važiavimo trukmės kelių tinkle. Juose nėra nei kamščių, nei krovos, nei laukimo, nei kavos. Laikykite sumą dienos apatine riba, o ne pačiu planu – prieš žadėdami kam nors laiko langą, pridėkite savo laiką kiekvienam sustojimui.' },
        { h2: 'Ko ji sąmoningai nedaro', id: 'not' },
        { ul: [
          '**Nežino jūsų automobilių.** Nėra nei talpų, nei laiko langų, nei vairuotojų pamainų. Ji atsako į vieną klausimą – kokia trumpiausia šių sustojimų tvarka – ir atsako gerai.',
          '**Neskirsto užduočių.** Tvarka nesiunčiama vairuotojui ir nepririšama prie automobilio; tai planas jūsų ekrane, pagal kurį veikiate.',
          '**Nesimoko.** Vakarykščiai kamščiai šiandienos atsakymo nekeičia.',
        ] },
        { h2: 'Iš kur imami adresai', id: 'addresses' },
        { p: 'Planuoklė priima koordinates, o ne gatvių adresus. Jei sustojimai kitoje sistemoje saugomi kaip adresai, vieną kartą juos ten konvertuokite ir laikykite koordinates – kliento kiemo įvažiavimas retai sutampa su tašku, kurį geokoderis parenka jo pašto adresui, o tas skirtumas ir yra tas paskutinis šimtas metrų, kurį vairuotojui tenka spėlioti.' },
      ],
    },
    pl: {
      title: 'Planowanie kolejności przystanków',
      summary: 'Podaj przystanki, a planer zwróci najkrótszą kolejność objazdu po realnych drogach — oraz dwie rzeczy, których celowo nie robi.',
      keywords: ['trasa', 'planer', 'optymalizacja', 'przystanki', 'kolejność', 'dostawa', 'pętla'],
      blocks: [
        { p: 'Kierowca z ośmioma adresami i mapą na siedzeniu pasażera znajdzie kolejność, która działa. Planer znajduje najkrótszą, po rzeczywistej sieci dróg, w około sekundę.' },
        { h2: 'Podawanie przystanków', id: 'input' },
        { ul: [
          '**Klikaj mapę** i postaw każdy przystanek tam, gdzie jego miejsce. Najszybsze dla kilku widocznych punktów.',
          '**Wklej listę** — po jednym przystanku w wierszu jako `szerokość,długość`, z opcjonalną etykietą po drugim przecinku. To droga z arkusza albo z innego systemu.',
        ] },
        { p: 'Do dwunastu przystanków. Limit nie jest przypadkowy: liczba możliwych kolejności rośnie wykładniczo, a dwanaście to granica, przy której dokładna odpowiedź wciąż zdąży, zanim ktoś odejdzie od ekranu. Dłuższy dzień to dwie trasy.' },
        { h2: 'Z powrotem do bazy czy bez', id: 'roundtrip' },
        { p: 'Zaznacz **Powrót do startu**, gdy pojazd wraca do bazy — wtedy ostatni odcinek do domu wlicza się do sumy. Zostaw odznaczone dla trasy kończącej się u ostatniego klienta: kuriera kończącego blisko domu albo pojazdu zostającego w trasie na noc. Obie odpowiedzi mogą być naprawdę różnymi kolejnościami, nie tylko różnymi sumami.' },
        { h2: 'Czytanie wyniku', id: 'result' },
        { p: 'Przystanki są przenumerowane w kolejności przejazdu, każdy wiersz pokazuje dystans i czas do następnego, a suma jest na dole. Trasa rysowana jest na mapie po rzeczywistych drogach, a nie prostymi liniami między punktami.' },
        { callout: 'note', p: 'To czasy przejazdu po sieci drogowej bez zakłóceń. Nie ma w nich korków, załadunku, czekania ani kawy. Traktuj sumę jako dolną granicę dnia, a nie jako plan — zanim komuś obiecasz okno czasowe, dodaj własny czas na każdy przystanek.' },
        { h2: 'Czego celowo nie robi', id: 'not' },
        { ul: [
          '**Nie zna Twoich pojazdów.** Nie ma ładowności, okien czasowych ani zmian kierowców. Odpowiada na jedno pytanie — najkrótsza kolejność tych przystanków — i odpowiada dobrze.',
          '**Nie wysyła zleceń.** Kolejność nie jest wysyłana kierowcy ani przypisywana do pojazdu; to plan na Twoim ekranie.',
          '**Nie uczy się.** Wczorajszy ruch nie zmienia dzisiejszej odpowiedzi.',
        ] },
        { h2: 'Skąd biorą się adresy', id: 'addresses' },
        { p: 'Planer przyjmuje współrzędne, nie adresy. Jeśli przystanki są w innym systemie jako adresy, zamień je tam raz na współrzędne i trzymaj współrzędne — wjazd na plac klienta rzadko pokrywa się z punktem, który geokoder wybiera dla jego adresu pocztowego, a ta różnica to właśnie ostatnie sto metrów, które kierowca musi zgadywać.' },
      ],
    },
    de: {
      title: 'Die Reihenfolge der Stopps eines Tages planen',
      summary: 'Geben Sie dem Planer Ihre Stopps, und er liefert die kürzeste Besuchsreihenfolge über echte Straßen — und zwei Dinge, die er bewusst nicht tut.',
      keywords: ['route', 'planer', 'optimieren', 'stopps', 'reihenfolge', 'lieferung', 'rundfahrt'],
      blocks: [
        { p: 'Ein Fahrer mit acht Adressen und einer Karte auf dem Beifahrersitz findet eine Reihenfolge, die funktioniert. Der Planer findet die kürzeste, über das tatsächliche Straßennetz, in etwa einer Sekunde.' },
        { h2: 'Die Stopps eingeben', id: 'input' },
        { ul: [
          '**Auf die Karte klicken** und jeden Stopp dort setzen, wo er hingehört. Am schnellsten für eine Handvoll sichtbarer Orte.',
          '**Eine Liste einfügen** — ein Stopp je Zeile als `Breite,Länge`, optional mit Bezeichnung nach einem zweiten Komma. Das ist der Weg aus einer Tabellenkalkulation oder einem anderen System.',
        ] },
        { p: 'Bis zu zwölf Stopps. Die Grenze ist nicht willkürlich: Die Zahl möglicher Reihenfolgen wächst explosionsartig, und bei zwölf kommt eine exakte Antwort noch an, während jemand auf den Bildschirm schaut. Ein längerer Tag sind zwei Routen.' },
        { h2: 'Mit oder ohne Rückweg', id: 'roundtrip' },
        { p: 'Setzen Sie den Haken bei **Zurück zum Start**, wenn das Fahrzeug zum Hof zurückkehrt — dann zählt die letzte Etappe nach Hause in die Summe. Lassen Sie den Haken weg für eine Tour, die beim letzten Kunden endet: ein Kurier, der in Wohnnähe aufhört, oder ein Fahrzeug, das draußen übernachtet. Die beiden Antworten können wirklich verschiedene Reihenfolgen sein, nicht nur verschiedene Summen.' },
        { h2: 'Das Ergebnis lesen', id: 'result' },
        { p: 'Die Stopps werden in Fahrreihenfolge neu nummeriert, jede Zeile zeigt Strecke und Zeit zum nächsten, und die Summe steht unten. Die Route wird auf der Karte gezeichnet — über echte Straßen, nicht als Luftlinie zwischen Punkten.' },
        { callout: 'note', p: 'Die Zeiten sind Fahrzeiten bei freier Fahrt über das Straßennetz. Kein Verkehr, kein Beladen, kein Warten, kein Kaffee. Nehmen Sie die Summe als Untergrenze des Tages, nicht als Plan — rechnen Sie Ihre eigene Zeit je Stopp dazu, bevor Sie jemandem ein Zeitfenster zusagen.' },
        { h2: 'Was er bewusst nicht tut', id: 'not' },
        { ul: [
          '**Er kennt Ihre Fahrzeuge nicht.** Keine Kapazitäten, keine Zeitfenster, keine Fahrerschichten. Er beantwortet eine Frage — die kürzeste Reihenfolge dieser Stopps — und die gut.',
          '**Er disponiert nicht.** Die Reihenfolge wird keinem Fahrer geschickt und keinem Fahrzeug zugeordnet; sie ist ein Plan auf Ihrem Bildschirm.',
          '**Er lernt nicht.** Der Verkehr von gestern ändert die Antwort von heute nicht.',
        ] },
        { h2: 'Woher die Adressen kommen', id: 'addresses' },
        { p: 'Der Planer nimmt Koordinaten, keine Straßenadressen. Liegen Ihre Stopps in einem anderen System als Adressen vor, rechnen Sie sie dort einmal um und behalten Sie die Koordinaten — die Hofeinfahrt eines Kunden ist selten der Punkt, den ein Geocoder für seine Postanschrift wählt, und genau diese Differenz sind die letzten hundert Meter, die ein Fahrer erraten muss.' },
      ],
    },
  },
}
