import type { KbArticle } from '../types.js'

export const rulesAndAlerts: KbArticle = {
  slug: 'rules-and-alerts',
  category: 'alerts',
  surfaces: { site: true, app: true },
  screen: '/app/rules',
  doc: {
    en: {
      title: 'Rules — being told instead of looking',
      summary: 'How a rule is built, what the cooldown protects you from, and why one long problem should be one message.',
      keywords: ['rule', 'alert', 'notification', 'cooldown', 'overspeed', 'scope', 'trigger', 'automation'],
      blocks: [
        { p: 'A rule is a standing instruction: when this happens to these vehicles, tell these people. Everything that arrives in your inbox, your phone or your webhook comes from one.' },
        { h2: 'What a rule is made of', id: 'anatomy' },
        { table: { head: ['Part', 'Meaning'], rows: [
          ['**Kind**', 'What to watch for — see [Event types](kb:event-types) for all nine.'],
          ['**Settings**', 'The threshold, where the kind needs one: a speed, a zone, a voltage, a percentage.'],
          ['**Scope**', 'Which vehicles. Leave it empty and the rule covers the whole account, including vehicles added later.'],
          ['**Channels**', 'Where the alert goes — see [Notification channels](kb:notification-channels).'],
          ['**Cooldown**', 'The minimum quiet time between alerts from this rule for the same vehicle.'],
        ] } },
        { h2: 'The cooldown is the important field', id: 'cooldown' },
        { p: 'Without it, a vehicle sitting just over a speed limit for twenty minutes could produce an alert for every position it sends. Nobody reads the fifteenth message, so in practice they stop reading the first one too.' },
        { callout: 'note', p: 'A continuing condition is recorded as **one** event with a start and an end, not as a stream of separate ones. A twenty-two-minute overspeed is one entry in the events list, and it grows an end time as it continues.' },
        { p: 'Choose the cooldown from how you would act, not from how often the thing happens. If a second alert within the hour would not change what you do, an hour is your cooldown.' },
        { h2: 'Start with one rule', id: 'start-small' },
        { p: 'The common mistake is creating twelve rules on the first afternoon and turning them all off in the second week. Create the one whose answer you would act on today — usually arrival at a zone, or a vehicle moving outside working hours — and live with it for a week before adding another.' },
        { h2: 'Scope on purpose', id: 'scope' },
        { p: 'An account-wide rule automatically covers vehicles you add later, which is right for a policy that applies to the whole fleet ("tell me about any power cut"). A rule limited to specific vehicles is right for something local ("this refrigerated van only"). Pick deliberately: the wrong choice shows up months later as either silence about a new vehicle or noise about an irrelevant one.' },
        { h2: 'Turning a rule off', id: 'disable' },
        { p: 'A rule has an enable switch. Use it for a temporary quiet period — during a depot move, or while a faulty sensor is being replaced — instead of deleting the rule and rebuilding it from memory afterwards.' },
      ],
    },
    lt: {
      title: 'Taisyklės — kai pranešama jums, o ne jūs tikrinate',
      summary: 'Kaip sudaryta taisyklė, nuo ko saugo atvėsimo laikas ir kodėl viena ilga problema turi būti viena žinutė.',
      keywords: ['taisyklė', 'pranešimas', 'atvėsimas', 'greičio viršijimas', 'apimtis', 'automatika'],
      blocks: [
        { p: 'Taisyklė – nuolatinis nurodymas: kai su šiais automobiliais nutinka tai, pranešk šiems žmonėms. Viskas, kas atkeliauja į jūsų pašto dėžutę, telefoną ar webhook, kyla iš kurios nors taisyklės.' },
        { h2: 'Iš ko sudaryta taisyklė', id: 'anatomy' },
        { table: { head: ['Dalis', 'Reikšmė'], rows: [
          ['**Tipas**', 'Ko tykoti – visus devynis žr. [Įvykių tipai](kb:event-types).'],
          ['**Nustatymai**', 'Riba, jei tam tipui jos reikia: greitis, zona, įtampa, procentas.'],
          ['**Apimtis**', 'Kurie automobiliai. Palikus tuščią, taisyklė apima visą paskyrą, įskaitant vėliau pridėtus automobilius.'],
          ['**Kanalai**', 'Kur keliauja pranešimas – žr. [Pranešimų kanalai](kb:notification-channels).'],
          ['**Atvėsimo laikas**', 'Mažiausia tylos trukmė tarp šios taisyklės pranešimų apie tą patį automobilį.'],
        ] } },
        { h2: 'Atvėsimo laikas — svarbiausias laukas', id: 'cooldown' },
        { p: 'Be jo automobilis, dvidešimt minučių važiuojantis vos virš greičio ribos, galėtų sukelti pranešimą už kiekvieną atsiųstą poziciją. Penkioliktos žinutės niekas neskaito, tad praktiškai nustojama skaityti ir pirmąją.' },
        { callout: 'note', p: 'Besitęsianti sąlyga įrašoma kaip **vienas** įvykis su pradžia ir pabaiga, o ne kaip srautas atskirų. Dvidešimt dvi minutes trukęs greičio viršijimas yra vienas įrašas įvykių sąraše, kuriam besitęsiant priauga pabaigos laikas.' },
        { p: 'Atvėsimo laiką rinkitės pagal tai, kaip elgtumėtės, o ne pagal tai, kaip dažnai tai nutinka. Jei antras pranešimas per valandą nepakeistų jūsų veiksmų, jūsų atvėsimo laikas yra valanda.' },
        { h2: 'Pradėkite nuo vienos taisyklės', id: 'start-small' },
        { p: 'Dažna klaida – pirmą popietę sukurti dvylika taisyklių ir antrą savaitę jas visas išjungti. Sukurkite tą, į kurios atsakymą reaguotumėte šiandien – dažniausiai tai atvykimas į zoną arba automobilio judėjimas ne darbo metu – ir pagyvenkite su ja savaitę, prieš pridėdami kitą.' },
        { h2: 'Apimtį rinkitės sąmoningai', id: 'scope' },
        { p: 'Visą paskyrą apimanti taisyklė automatiškai aprėpia vėliau pridėtus automobilius, ir tai teisinga politikai, galiojančiai visam parkui („pranešk apie bet kokį maitinimo dingimą"). Konkrečiais automobiliais apribota taisyklė teisinga vietiniam dalykui („tik šis šaldytuvas"). Rinkitės sąmoningai: netinkamas pasirinkimas išlenda po mėnesių arba kaip tyla apie naują automobilį, arba kaip triukšmas apie nesvarbų.' },
        { h2: 'Kaip išjungti taisyklę', id: 'disable' },
        { p: 'Taisyklė turi įjungimo jungiklį. Naudokite jį laikinai tylai – bazės perkraustymo metu ar kol keičiamas sugedęs daviklis – užuot taisyklę ištrynę ir vėliau atstatinėję iš atminties.' },
      ],
    },
    pl: {
      title: 'Reguły — być informowanym zamiast sprawdzać',
      summary: 'Z czego składa się reguła, przed czym chroni cooldown i dlaczego jeden długi problem powinien być jedną wiadomością.',
      keywords: ['reguła', 'alert', 'powiadomienie', 'cooldown', 'przekroczenie prędkości', 'zakres', 'automatyzacja'],
      blocks: [
        { p: 'Reguła to stała instrukcja: gdy stanie się to z tymi pojazdami, powiadom tych ludzi. Wszystko, co trafia do Twojej skrzynki, telefonu albo webhooka, pochodzi z jakiejś reguły.' },
        { h2: 'Z czego składa się reguła', id: 'anatomy' },
        { table: { head: ['Element', 'Znaczenie'], rows: [
          ['**Rodzaj**', 'Czego pilnować — wszystkie dziewięć zobacz w [Rodzaje zdarzeń](kb:event-types).'],
          ['**Ustawienia**', 'Próg, jeśli dany rodzaj go potrzebuje: prędkość, strefa, napięcie, procent.'],
          ['**Zakres**', 'Które pojazdy. Zostaw pusty, a reguła obejmie całe konto, w tym pojazdy dodane później.'],
          ['**Kanały**', 'Dokąd idzie alert — zobacz [Kanały powiadomień](kb:notification-channels).'],
          ['**Cooldown**', 'Minimalny czas ciszy między alertami tej reguły dla tego samego pojazdu.'],
        ] } },
        { h2: 'Cooldown to najważniejsze pole', id: 'cooldown' },
        { p: 'Bez niego pojazd jadący dwadzieścia minut tuż powyżej limitu mógłby wygenerować alert przy każdej wysłanej pozycji. Piętnastej wiadomości nikt nie czyta, więc w praktyce przestaje się czytać także pierwszą.' },
        { callout: 'note', p: 'Trwający stan jest zapisywany jako **jedno** zdarzenie z początkiem i końcem, a nie jako strumień osobnych. Dwudziestodwuminutowe przekroczenie prędkości to jeden wpis na liście zdarzeń, któremu w trakcie przyrasta czas zakończenia.' },
        { p: 'Cooldown wybieraj z tego, jak byś zareagował, a nie z tego, jak często to się zdarza. Jeśli drugi alert w ciągu godziny nie zmieniłby Twojego działania, Twój cooldown to godzina.' },
        { h2: 'Zacznij od jednej reguły', id: 'start-small' },
        { p: 'Typowy błąd to utworzenie dwunastu reguł pierwszego popołudnia i wyłączenie ich wszystkich w drugim tygodniu. Utwórz tę, na której odpowiedź zareagowałbyś dziś — zwykle przyjazd do strefy albo ruch pojazdu poza godzinami pracy — i pożyj z nią tydzień, zanim dodasz kolejną.' },
        { h2: 'Zakres świadomie', id: 'scope' },
        { p: 'Reguła obejmująca całe konto automatycznie pokrywa pojazdy dodane później, i to właściwe dla polityki dotyczącej całej floty („informuj o każdej utracie zasilania"). Reguła ograniczona do wybranych pojazdów jest właściwa dla czegoś lokalnego („tylko ta chłodnia"). Wybieraj świadomie: zły wybór wychodzi po miesiącach albo jako cisza o nowym pojeździe, albo jako hałas o nieistotnym.' },
        { h2: 'Wyłączanie reguły', id: 'disable' },
        { p: 'Reguła ma przełącznik włączenia. Użyj go na czasową ciszę — podczas przeprowadzki bazy albo gdy wymieniany jest wadliwy czujnik — zamiast usuwać regułę i odtwarzać ją potem z pamięci.' },
      ],
    },
    de: {
      title: 'Regeln — informiert werden statt nachsehen',
      summary: 'Woraus eine Regel besteht, wovor der Cooldown schützt und warum ein langes Problem eine Nachricht sein sollte.',
      keywords: ['regel', 'alarm', 'benachrichtigung', 'cooldown', 'tempoüberschreitung', 'geltungsbereich', 'automatisierung'],
      blocks: [
        { p: 'Eine Regel ist eine Daueranweisung: wenn das mit diesen Fahrzeugen passiert, sag diesen Leuten Bescheid. Alles, was in Ihrem Postfach, auf Ihrem Telefon oder in Ihrem Webhook ankommt, stammt aus einer.' },
        { h2: 'Woraus eine Regel besteht', id: 'anatomy' },
        { table: { head: ['Teil', 'Bedeutung'], rows: [
          ['**Art**', 'Worauf geachtet wird — alle neun in [Ereignistypen](kb:event-types).'],
          ['**Einstellungen**', 'Der Schwellwert, wo die Art einen braucht: Geschwindigkeit, Zone, Spannung, Prozentwert.'],
          ['**Geltungsbereich**', 'Welche Fahrzeuge. Leer gelassen gilt die Regel für das ganze Konto, auch für später hinzugefügte Fahrzeuge.'],
          ['**Kanäle**', 'Wohin der Alarm geht — siehe [Benachrichtigungskanäle](kb:notification-channels).'],
          ['**Cooldown**', 'Die Mindestruhezeit zwischen Alarmen dieser Regel für dasselbe Fahrzeug.'],
        ] } },
        { h2: 'Der Cooldown ist das wichtige Feld', id: 'cooldown' },
        { p: 'Ohne ihn könnte ein Fahrzeug, das zwanzig Minuten knapp über einem Limit fährt, für jede gesendete Position einen Alarm erzeugen. Die fünfzehnte Nachricht liest niemand, also hört man in der Praxis auch bei der ersten auf zu lesen.' },
        { callout: 'note', p: 'Ein anhaltender Zustand wird als **ein** Ereignis mit Beginn und Ende festgehalten, nicht als Strom einzelner. Eine 22-minütige Tempoüberschreitung ist ein Eintrag in der Ereignisliste, dem im Verlauf eine Endzeit zuwächst.' },
        { p: 'Wählen Sie den Cooldown danach, wie Sie handeln würden, nicht danach, wie oft die Sache passiert. Würde ein zweiter Alarm innerhalb der Stunde nichts an Ihrem Handeln ändern, ist eine Stunde Ihr Cooldown.' },
        { h2: 'Fangen Sie mit einer Regel an', id: 'start-small' },
        { p: 'Der übliche Fehler ist, am ersten Nachmittag zwölf Regeln anzulegen und sie in der zweiten Woche alle abzuschalten. Legen Sie die an, auf deren Antwort Sie heute reagieren würden — meist Ankunft in einer Zone oder Bewegung außerhalb der Arbeitszeit — und leben Sie eine Woche damit, bevor die nächste kommt.' },
        { h2: 'Geltungsbereich mit Absicht', id: 'scope' },
        { p: 'Eine kontoweite Regel erfasst später hinzugefügte Fahrzeuge automatisch, und das ist richtig für eine Vorgabe, die der ganzen Flotte gilt („melde jeden Stromausfall"). Eine auf bestimmte Fahrzeuge begrenzte Regel ist richtig für Lokales („nur dieser Kühltransporter"). Wählen Sie bewusst: die falsche Wahl zeigt sich Monate später entweder als Stille über ein neues Fahrzeug oder als Lärm über ein belangloses.' },
        { h2: 'Eine Regel abschalten', id: 'disable' },
        { p: 'Jede Regel hat einen Aktivierungsschalter. Nutzen Sie ihn für eine vorübergehende Ruhephase — während eines Betriebshofumzugs oder solange ein defekter Sensor getauscht wird — statt die Regel zu löschen und sie danach aus dem Gedächtnis neu zu bauen.' },
      ],
    },
  },
}
