import type { KbArticle } from '../types.js'

export const scheduledReports: KbArticle = {
  slug: 'scheduled-reports',
  category: 'reports',
  surfaces: { site: true, app: true },
  screen: '/app/reports',
  doc: {
    en: {
      title: 'Reports that arrive on their own',
      summary: 'Setting up a recurring report, choosing recipients, and the one thing about the hour that catches people out.',
      keywords: ['scheduled', 'recurring', 'weekly', 'daily', 'email report', 'automatic', 'recipients', 'utc'],
      blocks: [
        { p: 'A report you have to remember to run is a report that stops being run in month three. Scheduling turns it into something that happens whether anyone thinks about it or not.' },
        { h2: 'Setting one up', id: 'setup' },
        { ol: [
          'Choose the report type — see [Which report answers which question](kb:report-types).',
          'Choose the cadence: daily, or weekly on a chosen weekday.',
          'Choose the hour it should be sent.',
          'List the recipients, separated by commas. They do not need logins here.',
        ] },
        { h2: 'The hour is in UTC', id: 'utc' },
        { callout: 'warning', p: 'The send hour is entered in **UTC**, not in your local time. In central Europe that is one hour behind local time in winter and two in summer — so a report scheduled for 6 will arrive at 7 in winter and 8 in summer. Pick the UTC hour that lands where you want it in the season you care about, and expect the clock change to shift it.' },
        { p: 'The report **contents** are a different matter: they are grouped into days by the account\'s time zone, so the data covers the day your business means even though the delivery hour is set in UTC.' },
        { h2: 'Choosing recipients', id: 'recipients' },
        { p: 'Recipients are addresses, not users. That is deliberate — a weekly mileage summary usually goes to a bookkeeper, an owner or a customer, and none of them need an account here to receive a PDF.' },
        { p: 'Because there is no user behind an address, the report is written in the **account\'s** language and units. Set those once under Settings → Reports and e-mails; see [Time zones and units](kb:time-zones-and-units).' },
        { h2: 'When one stops arriving', id: 'stopped' },
        { ul: [
          'Check the schedule still exists and its recipients are right — a deleted schedule leaves no trace in an inbox.',
          'Check the address still accepts mail. An address that permanently bounced is not written to again.',
          'Check the spam folder once, then add the sender to the address book. This is the usual cause when it worked for months and then stopped for one person.',
        ] },
        { p: 'More on delivery problems: [Not getting e-mails](kb:not-getting-emails).' },
        { h2: 'A sensible starting set', id: 'starter' },
        { ul: [
          '**Weekly mileage**, Monday morning, to whoever handles costs.',
          '**Daily trips** for one vehicle, to the person responsible for it, when you are investigating something specific — then delete it when the question is answered.',
        ] },
      ],
    },
    lt: {
      title: 'Ataskaitos, kurios atkeliauja pačios',
      summary: 'Kaip nustatyti pasikartojančią ataskaitą, kaip parinkti gavėjus ir vienas dalykas apie valandą, ant kurio žmonės užkliūva.',
      keywords: ['planinė', 'pasikartojanti', 'savaitinė', 'kasdienė', 'ataskaita paštu', 'automatinė', 'gavėjai', 'utc'],
      blocks: [
        { p: 'Ataskaita, kurią reikia prisiminti paleisti, trečią mėnesį nustoja būti paleidžiama. Planavimas paverčia ją tuo, kas vyksta nepriklausomai nuo to, ar kas nors apie tai galvoja.' },
        { h2: 'Kaip nustatyti', id: 'setup' },
        { ol: [
          'Pasirinkite ataskaitos tipą – žr. [Kuri ataskaita atsako į kurį klausimą](kb:report-types).',
          'Pasirinkite dažnį: kasdien arba kas savaitę pasirinktą savaitės dieną.',
          'Pasirinkite siuntimo valandą.',
          'Surašykite gavėjus, atskirdami kableliais. Jiems prisijungimo čia nereikia.',
        ] },
        { h2: 'Valanda nurodoma UTC', id: 'utc' },
        { callout: 'warning', p: 'Siuntimo valanda įvedama **UTC**, o ne jūsų vietos laiku. Lietuvoje tai reiškia dvi valandas vasarą ir tris žiemą – tad 6 valandai suplanuota ataskaita žiemą atkeliaus 8, o vasarą 9. Rinkitės tokią UTC valandą, kuri pataiko ten, kur norite, tuo metų laiku, kuris jums svarbus, ir tikėkitės, kad laikrodžio pasukimas ją pastums.' },
        { p: 'Ataskaitos **turinys** – kitas reikalas: jis grupuojamas į dienas pagal paskyros laiko juostą, tad duomenys aprėpia būtent tą dieną, kurią turi omenyje jūsų verslas, nors pristatymo valanda nurodyta UTC.' },
        { h2: 'Kaip parinkti gavėjus', id: 'recipients' },
        { p: 'Gavėjai yra adresai, o ne vartotojai. Tai sąmoninga – savaitinė ridos suvestinė paprastai keliauja buhalteriui, savininkui ar klientui, ir nė vienam iš jų nereikia paskyros, kad gautų PDF.' },
        { p: 'Kadangi už adreso nėra vartotojo, ataskaita rašoma **paskyros** kalba ir vienetais. Nustatykite juos vieną kartą skiltyje Nustatymai → Ataskaitos ir el. laiškai; žr. [Laiko juostos ir vienetai](kb:time-zones-and-units).' },
        { h2: 'Kai ataskaita nustoja ateiti', id: 'stopped' },
        { ul: [
          'Patikrinkite, ar grafikas tebeegzistuoja ir ar gavėjai teisingi – ištrintas grafikas pašto dėžutėje jokio pėdsako nepalieka.',
          'Patikrinkite, ar adresas dar priima paštą. Į negrįžtamai atmetusį adresą daugiau nerašoma.',
          'Vieną kartą pažiūrėkite į šlamšto aplanką ir įtraukite siuntėją į adresų knygą. Tai įprasta priežastis, kai mėnesius veikė, o paskui vienam žmogui nustojo.',
        ] },
        { p: 'Daugiau apie pristatymo problemas: [Negaunu laiškų](kb:not-getting-emails).' },
        { h2: 'Protingas pradinis rinkinys', id: 'starter' },
        { ul: [
          '**Savaitinė rida**, pirmadienio rytą, tam, kas rūpinasi sąnaudomis.',
          '**Kasdienės kelionės** vienam automobiliui – už jį atsakingam žmogui, kai kažką konkrečiai tiriate; atsakius į klausimą, grafiką ištrinkite.',
        ] },
      ],
    },
    pl: {
      title: 'Raporty, które przychodzą same',
      summary: 'Jak ustawić raport cykliczny, jak wybrać odbiorców i jedna rzecz o godzinie, na której ludzie się potykają.',
      keywords: ['cykliczny', 'harmonogram', 'tygodniowy', 'dzienny', 'raport mailem', 'automatyczny', 'odbiorcy', 'utc'],
      blocks: [
        { p: 'Raport, o którego uruchomieniu trzeba pamiętać, w trzecim miesiącu przestaje być uruchamiany. Harmonogram zamienia go w coś, co dzieje się niezależnie od tego, czy ktoś o tym myśli.' },
        { h2: 'Konfiguracja', id: 'setup' },
        { ol: [
          'Wybierz typ raportu — zobacz [Który raport odpowiada na które pytanie](kb:report-types).',
          'Wybierz częstotliwość: codziennie albo co tydzień w wybrany dzień.',
          'Wybierz godzinę wysyłki.',
          'Wypisz odbiorców, oddzielając przecinkami. Nie potrzebują tu loginów.',
        ] },
        { h2: 'Godzina jest w UTC', id: 'utc' },
        { callout: 'warning', p: 'Godzinę wysyłki podaje się w **UTC**, nie w czasie lokalnym. W Polsce to godzina mniej zimą i dwie latem — więc raport zaplanowany na 6 przyjdzie o 7 zimą i o 8 latem. Wybierz taką godzinę UTC, która trafia tam, gdzie chcesz, w interesującej Cię porze roku, i licz się z przesunięciem po zmianie czasu.' },
        { p: '**Treść** raportu to inna sprawa: jest grupowana w dni według strefy czasowej konta, więc dane obejmują ten dzień, który ma na myśli Twoja firma, choć godzina wysyłki jest w UTC.' },
        { h2: 'Wybór odbiorców', id: 'recipients' },
        { p: 'Odbiorcy to adresy, nie użytkownicy. To celowe — tygodniowe zestawienie przebiegu zwykle idzie do księgowej, właściciela albo klienta, a żadne z nich nie potrzebuje tu konta, by dostać PDF.' },
        { p: 'Ponieważ za adresem nie stoi użytkownik, raport jest pisany w języku i jednostkach **konta**. Ustaw je raz w Ustawienia → Raporty i e-maile; zobacz [Strefy czasowe i jednostki](kb:time-zones-and-units).' },
        { h2: 'Gdy raport przestaje przychodzić', id: 'stopped' },
        { ul: [
          'Sprawdź, czy harmonogram nadal istnieje i czy odbiorcy są właściwi — skasowany harmonogram nie zostawia śladu w skrzynce.',
          'Sprawdź, czy adres nadal przyjmuje pocztę. Na adres, który trwale odbił, nie piszemy ponownie.',
          'Zajrzyj raz do spamu, a potem dodaj nadawcę do książki adresowej. To typowa przyczyna, gdy działało miesiącami i nagle przestało dla jednej osoby.',
        ] },
        { p: 'Więcej o problemach z dostarczaniem: [Nie dostaję e-maili](kb:not-getting-emails).' },
        { h2: 'Rozsądny zestaw startowy', id: 'starter' },
        { ul: [
          '**Tygodniowy przebieg**, poniedziałek rano, do osoby od kosztów.',
          '**Dzienne trasy** jednego pojazdu do osoby za niego odpowiedzialnej, gdy coś konkretnego badasz — a po uzyskaniu odpowiedzi skasuj harmonogram.',
        ] },
      ],
    },
    de: {
      title: 'Berichte, die von selbst kommen',
      summary: 'Einen wiederkehrenden Bericht einrichten, Empfänger wählen — und die eine Sache mit der Uhrzeit, über die alle stolpern.',
      keywords: ['geplant', 'wiederkehrend', 'wöchentlich', 'täglich', 'bericht per mail', 'automatisch', 'empfänger', 'utc'],
      blocks: [
        { p: 'Ein Bericht, an dessen Ausführung man denken muss, wird im dritten Monat nicht mehr ausgeführt. Ein Zeitplan macht daraus etwas, das passiert, ob jemand daran denkt oder nicht.' },
        { h2: 'Einrichten', id: 'setup' },
        { ol: [
          'Berichtstyp wählen — siehe [Welcher Bericht welche Frage beantwortet](kb:report-types).',
          'Takt wählen: täglich oder wöchentlich an einem bestimmten Wochentag.',
          'Die Versandstunde wählen.',
          'Empfänger auflisten, durch Kommas getrennt. Sie brauchen hier keinen Zugang.',
        ] },
        { h2: 'Die Uhrzeit ist UTC', id: 'utc' },
        { callout: 'warning', p: 'Die Versandstunde wird in **UTC** eingetragen, nicht in Ihrer Ortszeit. In Mitteleuropa ist das im Winter eine und im Sommer zwei Stunden hinter der Ortszeit — ein für 6 geplanter Bericht kommt also im Winter um 7 und im Sommer um 8. Wählen Sie die UTC-Stunde, die in der für Sie wichtigen Jahreszeit richtig landet, und rechnen Sie mit der Verschiebung durch die Zeitumstellung.' },
        { p: 'Der **Inhalt** des Berichts ist eine andere Sache: er wird nach der Zeitzone des Kontos in Tage gruppiert, deckt also den Tag ab, den Ihr Betrieb meint — auch wenn die Versandstunde in UTC steht.' },
        { h2: 'Empfänger wählen', id: 'recipients' },
        { p: 'Empfänger sind Adressen, keine Benutzer. Das ist Absicht — eine wöchentliche Kilometerübersicht geht meist an eine Buchhaltung, einen Inhaber oder einen Kunden, und keiner davon braucht hier ein Konto, um ein PDF zu erhalten.' },
        { p: 'Weil hinter einer Adresse kein Benutzer steht, wird der Bericht in Sprache und Einheiten des **Kontos** geschrieben. Stellen Sie das einmal unter Einstellungen → Berichte und E-Mails ein; siehe [Zeitzonen und Einheiten](kb:time-zones-and-units).' },
        { h2: 'Wenn einer ausbleibt', id: 'stopped' },
        { ul: [
          'Prüfen, ob der Zeitplan noch existiert und die Empfänger stimmen — ein gelöschter Zeitplan hinterlässt in keinem Postfach eine Spur.',
          'Prüfen, ob die Adresse noch Post annimmt. An eine dauerhaft zurückgekommene Adresse wird nicht erneut geschrieben.',
          'Einmal in den Spam-Ordner sehen, dann den Absender ins Adressbuch nehmen. Das ist die übliche Ursache, wenn es monatelang lief und dann bei einer Person aufhörte.',
        ] },
        { p: 'Mehr zu Zustellproblemen: [Keine E-Mails](kb:not-getting-emails).' },
        { h2: 'Ein sinnvoller Startsatz', id: 'starter' },
        { ul: [
          '**Wöchentliche Kilometer**, Montagfrüh, an die Person, die die Kosten verantwortet.',
          '**Tägliche Fahrten** eines Fahrzeugs an die dafür zuständige Person, solange Sie etwas Bestimmtes untersuchen — und danach den Zeitplan löschen.',
        ] },
      ],
    },
  },
}
