import type { KbArticle } from '../types.js'

export const shareALiveLink: KbArticle = {
  slug: 'share-a-live-link',
  category: 'map',
  surfaces: { site: true, app: true },
  screen: '/app',
  doc: {
    en: {
      title: 'Sharing a vehicle with someone who has no login',
      summary: 'Expiring public tracking links: what the recipient sees, what they cannot see, and how to take it back.',
      keywords: ['share', 'link', 'public', 'customer', 'eta', 'tracking link', 'expire', 'revoke'],
      blocks: [
        { p: 'A customer waiting for a delivery does not need an account, a password or a tour of your dashboard. They need one page that shows one van moving. That is what a share link is.' },
        { h2: 'Creating one', id: 'create' },
        { ol: [
          'Open the vehicle and choose **Share**.',
          'Pick how long it should stay valid — an hour, eight hours, a day, or a week.',
          'Give it a label for your own records (“Courier ETA”, “Site delivery Tuesday”). The label is for you, not for them.',
          'Copy the link. It is shown once, so copy it before you close the dialog.',
        ] },
        { h2: 'What the recipient sees', id: 'sees' },
        { ul: [
          'One vehicle on a live map, updating as it moves.',
          'Nothing else: no other vehicles, no trips, no history, no driver, no reports, no way into your account.',
        ] },
        { p: 'When the link expires, the page says so plainly rather than showing a last known position forever. A stale position presented as live is worse than no page at all.' },
        { h2: 'The link is the key', id: 'security' },
        { callout: 'warning', p: 'Anyone holding the URL can open it — there is no password. Treat it like a key: send it to the person who needs it, choose the shortest duration that does the job, and revoke it if it ends up somewhere it should not.' },
        { h2: 'Revoking', id: 'revoke' },
        { p: 'Active links are listed on the vehicle with the time remaining on each. Revoking one is immediate: whoever holds it loses access on their next refresh. Revocation cannot be undone — you create a new link instead.' },
        { h2: 'Choosing the duration', id: 'duration' },
        { p: 'Match it to the errand, not to convenience. A one-hour link for a delivery in progress expires on its own before anybody has to remember it. A week-long link forwarded once lives on a stranger\'s phone for a week.' },
      ],
    },
    lt: {
      title: 'Kaip parodyti automobilį tam, kas neturi prisijungimo',
      summary: 'Ribotos trukmės viešos sekimo nuorodos: ką gavėjas mato, ko nemato ir kaip nuorodą atsiimti.',
      keywords: ['dalintis', 'nuoroda', 'viešas', 'klientas', 'eta', 'sekimo nuoroda', 'atšaukti'],
      blocks: [
        { p: 'Siuntos laukiančiam klientui nereikia nei paskyros, nei slaptažodžio, nei ekskursijos po jūsų skydelį. Jam reikia vieno puslapio, kuriame juda vienas furgonas. Kaip tik tai ir yra dalijimosi nuoroda.' },
        { h2: 'Kaip sukurti', id: 'create' },
        { ol: [
          'Atverkite automobilį ir pasirinkite **Bendrinti**.',
          'Parinkite, kiek laiko ji galios – valandą, aštuonias valandas, parą ar savaitę.',
          'Suteikite pavadinimą sau („Kurjerio ETA“, „Antradienio pristatymas į objektą“). Pavadinimas skirtas jums, ne gavėjui.',
          'Nukopijuokite nuorodą. Ji parodoma vieną kartą, tad kopijuokite prieš uždarydami langą.',
        ] },
        { h2: 'Ką mato gavėjas', id: 'sees' },
        { ul: [
          'Vieną automobilį gyvame žemėlapyje, atsinaujinantį jam judant.',
          'Daugiau nieko: jokių kitų automobilių, kelionių, istorijos, vairuotojo, ataskaitų ir jokio kelio į jūsų paskyrą.',
        ] },
        { p: 'Nuorodai nustojus galioti, puslapis tai pasako tiesiai, o ne amžinai rodo paskutinę žinomą poziciją. Sena pozicija, pateikta kaip gyva, blogiau nei jokio puslapio.' },
        { h2: 'Nuoroda ir yra raktas', id: 'security' },
        { callout: 'warning', p: 'Ją atverti gali bet kas, kas turi adresą – jokio slaptažodžio nėra. Elkitės kaip su raktu: siųskite tam, kam reikia, rinkitės trumpiausią darbui pakankamą trukmę ir atšaukite, jei ji atsidūrė ten, kur neturėtų.' },
        { h2: 'Atšaukimas', id: 'revoke' },
        { p: 'Aktyvios nuorodos išvardytos prie automobilio kartu su likusiu kiekvienos laiku. Atšaukimas įsigalioja iškart: turintysis nuorodą prieigą praranda kitą kartą atnaujinęs puslapį. Atšaukimo atšaukti negalima – vietoj to kuriama nauja nuoroda.' },
        { h2: 'Kaip pasirinkti trukmę', id: 'duration' },
        { p: 'Derinkite ją prie užduoties, o ne prie patogumo. Valandos trukmės nuoroda vykstančiam pristatymui pati nustoja galioti dar prieš tai, kai kam nors tenka apie ją prisiminti. Savaitės trukmės nuoroda, kartą persiųsta toliau, savaitę gyvena svetimo žmogaus telefone.' },
      ],
    },
    pl: {
      title: 'Udostępnianie pojazdu komuś bez loginu',
      summary: 'Wygasające publiczne linki śledzenia: co widzi odbiorca, czego nie widzi i jak link odebrać.',
      keywords: ['udostępnianie', 'link', 'publiczny', 'klient', 'eta', 'link śledzenia', 'unieważnić'],
      blocks: [
        { p: 'Klient czekający na dostawę nie potrzebuje konta, hasła ani wycieczki po Twoim panelu. Potrzebuje jednej strony, na której jedzie jeden bus. Właśnie tym jest link udostępniania.' },
        { h2: 'Tworzenie', id: 'create' },
        { ol: [
          'Otwórz pojazd i wybierz **Udostępnij**.',
          'Wybierz, jak długo ma być ważny — godzinę, osiem godzin, dobę albo tydzień.',
          'Nadaj etykietę na własny użytek („ETA kuriera”, „Dostawa na budowę we wtorek”). Etykieta jest dla Ciebie, nie dla odbiorcy.',
          'Skopiuj link. Pokazuje się raz, więc skopiuj go przed zamknięciem okna.',
        ] },
        { h2: 'Co widzi odbiorca', id: 'sees' },
        { ul: [
          'Jeden pojazd na mapie na żywo, aktualizowany w miarę jazdy.',
          'Nic więcej: żadnych innych pojazdów, tras, historii, kierowcy, raportów ani drogi do Twojego konta.',
        ] },
        { p: 'Gdy link wygasa, strona mówi o tym wprost, zamiast wiecznie pokazywać ostatnią znaną pozycję. Stara pozycja podana jako bieżąca jest gorsza niż brak strony.' },
        { h2: 'Link jest kluczem', id: 'security' },
        { callout: 'warning', p: 'Otworzy go każdy, kto ma adres — nie ma hasła. Traktuj go jak klucz: wyślij osobie, która go potrzebuje, wybierz najkrótszy wystarczający czas i unieważnij, jeśli trafił tam, gdzie nie powinien.' },
        { h2: 'Unieważnianie', id: 'revoke' },
        { p: 'Aktywne linki są wypisane przy pojeździe wraz z pozostałym czasem każdego. Unieważnienie działa natychmiast: posiadacz traci dostęp przy następnym odświeżeniu. Unieważnienia nie da się cofnąć — tworzy się nowy link.' },
        { h2: 'Wybór czasu ważności', id: 'duration' },
        { p: 'Dopasuj go do zadania, nie do wygody. Godzinny link do trwającej dostawy wygasa sam, zanim ktokolwiek musi o nim pamiętać. Tygodniowy link, raz przesłany dalej, żyje tydzień w telefonie obcej osoby.' },
      ],
    },
    de: {
      title: 'Ein Fahrzeug mit jemandem ohne Zugang teilen',
      summary: 'Ablaufende öffentliche Tracking-Links: was der Empfänger sieht, was nicht, und wie Sie den Link zurücknehmen.',
      keywords: ['teilen', 'link', 'öffentlich', 'kunde', 'eta', 'tracking-link', 'widerrufen'],
      blocks: [
        { p: 'Ein Kunde, der auf eine Lieferung wartet, braucht kein Konto, kein Passwort und keine Führung durch Ihr Dashboard. Er braucht eine Seite, auf der ein Transporter fährt. Genau das ist ein Freigabelink.' },
        { h2: 'Einen erstellen', id: 'create' },
        { ol: [
          'Fahrzeug öffnen und **Teilen** wählen.',
          'Gültigkeitsdauer wählen — eine Stunde, acht Stunden, einen Tag oder eine Woche.',
          'Eine Bezeichnung für Ihre eigenen Unterlagen vergeben („Kurier-ETA“, „Baustellenlieferung Dienstag“). Sie ist für Sie, nicht für den Empfänger.',
          'Link kopieren. Er wird einmal angezeigt — kopieren Sie ihn, bevor Sie den Dialog schließen.',
        ] },
        { h2: 'Was der Empfänger sieht', id: 'sees' },
        { ul: [
          'Ein Fahrzeug auf einer Live-Karte, das sich mitbewegt.',
          'Sonst nichts: keine anderen Fahrzeuge, keine Fahrten, keinen Verlauf, keinen Fahrer, keine Berichte, keinen Weg in Ihr Konto.',
        ] },
        { p: 'Läuft der Link ab, sagt die Seite das klar, statt ewig eine letzte bekannte Position zu zeigen. Eine alte Position, als live präsentiert, ist schlimmer als gar keine Seite.' },
        { h2: 'Der Link ist der Schlüssel', id: 'security' },
        { callout: 'warning', p: 'Wer die URL hat, kann sie öffnen — ein Passwort gibt es nicht. Behandeln Sie sie wie einen Schlüssel: Schicken Sie sie der Person, die sie braucht, wählen Sie die kürzeste ausreichende Dauer und widerrufen Sie sie, wenn sie an einem falschen Ort landet.' },
        { h2: 'Widerrufen', id: 'revoke' },
        { p: 'Aktive Links stehen beim Fahrzeug mit ihrer Restlaufzeit. Ein Widerruf wirkt sofort: Der Inhaber verliert beim nächsten Aktualisieren den Zugriff. Ein Widerruf lässt sich nicht rückgängig machen — stattdessen erstellen Sie einen neuen Link.' },
        { h2: 'Die Dauer wählen', id: 'duration' },
        { p: 'Richten Sie sie nach dem Auftrag, nicht nach Bequemlichkeit. Ein Ein-Stunden-Link für eine laufende Lieferung läuft von selbst ab, bevor sich jemand daran erinnern muss. Ein Wochenlink, einmal weitergeleitet, lebt eine Woche im Telefon eines Fremden.' },
      ],
    },
  },
}
