import type { KbArticle } from '../types.js'

export const simAndApn: KbArticle = {
  slug: 'sim-and-apn',
  category: 'devices',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'SIM cards, APN and mobile data',
      summary: 'What kind of SIM a tracker needs, what an APN is, how much data tracking really uses, and what roaming costs you.',
      keywords: ['sim', 'apn', 'data', 'roaming', 'iot sim', 'm2m', 'mobile', 'gprs', 'operator'],
      blocks: [
        { p: 'A tracker without working mobile data is a very expensive way to store positions nobody will ever see. Getting the SIM right is half of a successful installation, and it is the half people skip.' },
        { h2: 'What kind of SIM', id: 'kind' },
        { p: 'Any SIM with a **data** allowance works. You do not need calls or texts for normal operation — although a SIM that can receive an SMS makes the initial setup much easier, because that is how the tracker is told where to send its data.' },
        { ul: [
          '**IoT / M2M SIMs** are the usual choice: cheap, small allowances, often multi-network and priced per month rather than per gigabyte.',
          '**A normal consumer SIM** works fine. Watch for ones that suspend themselves after weeks of low use, or that force a captive-portal login.',
          '**Avoid** prepaid SIMs that expire on inactivity. A tracker uses so little data that the operator may decide the card is abandoned.',
        ] },
        { h2: 'The APN', id: 'apn' },
        { p: 'An **APN** (Access Point Name) is the name of the gateway the SIM must use to reach the internet. Your phone fills it in automatically; a tracker usually does not. If the APN is missing or wrong the tracker registers on the network, shows signal, and still cannot send a single byte — which is why “the SIM has signal” is not the same as “the SIM works”.' },
        { p: 'The APN comes from whoever sold you the SIM. It is one word, sometimes with a username and password. Ask for all three. The device page will put the APN into the configuration message for you — see [Connecting a tracker](kb:connect-a-tracker).' },
        { callout: 'tip', p: 'Test the SIM in a phone first. If the phone can browse with that SIM and the correct APN, the tracker will get data too. It removes an entire class of doubt in two minutes.' },
        { h2: 'How much data does tracking use?', id: 'usage' },
        { p: 'Far less than people expect. A position record is a few dozen bytes, and trackers send them in batches. A vehicle driving eight hours a day at a normal reporting rate lands in the region of 10–40 MB a month. Even a generous plan is rarely the cost driver — the settings that move this number are described in [Reporting intervals](kb:reporting-intervals), where {product} shows a live estimate as you change them.' },
        { h2: 'Roaming', id: 'roaming' },
        { p: 'If your vehicles cross borders, the SIM must be allowed to roam and you should know what roaming costs. Two failure modes are common: a SIM that simply stops working outside its home country, and one that works but bills at a rate nobody checked. A multi-network IoT SIM avoids both and is worth the small premium for any international fleet.' },
        { h2: 'When the SIM is the problem', id: 'symptoms' },
        { table: { head: ['What you see', 'Likely cause'], rows: [
          ['Never reported anything, ever', 'Wrong or missing APN, or the SIM is not activated'],
          ['Worked, then stopped on the same day for every vehicle', 'Data allowance exhausted, or the operator suspended the cards'],
          ['Works at home, silent abroad', 'Roaming not enabled'],
          ['Works, but reports arrive in long-delayed bursts', 'Poor coverage — normal behaviour, nothing was lost'],
        ] } },
      ],
    },
    lt: {
      title: 'SIM kortelės, APN ir mobilieji duomenys',
      summary: 'Kokios SIM reikia sekikliui, kas yra APN, kiek duomenų iš tiesų suvartoja sekimas ir kiek kainuoja tarptinklinis ryšys.',
      keywords: ['sim', 'apn', 'duomenys', 'tarptinklinis', 'roaming', 'iot sim', 'm2m', 'operatorius'],
      blocks: [
        { p: 'Sekiklis be veikiančių mobiliųjų duomenų – labai brangus būdas kaupti pozicijas, kurių niekas niekada nepamatys. Tinkama SIM kortelė – pusė sėkmingo montavimo, ir kaip tik tą pusę žmonės praleidžia.' },
        { h2: 'Kokios SIM reikia', id: 'kind' },
        { p: 'Tinka bet kuri SIM su **duomenų** limitu. Skambučių ar žinučių įprastam darbui nereikia – nors SIM, galinti priimti SMS, labai palengvina pradinį nustatymą, nes būtent taip sekikliui pasakoma, kur siųsti duomenis.' },
        { ul: [
          '**IoT / M2M kortelės** – įprastas pasirinkimas: pigios, nedideli limitai, dažnai kelių tinklų ir apmokestinamos mėnesiui, o ne už gigabaitą.',
          '**Įprasta vartotojo SIM** puikiai tinka. Saugokitės tų, kurios pačios užsiblokuoja po kelių savaičių mažo naudojimo arba reikalauja prisijungti per naršyklės langą.',
          '**Venkite** išankstinio mokėjimo kortelių, kurios pasibaigia dėl neveiklumo. Sekiklis naudoja tiek mažai duomenų, kad operatorius gali nuspręsti, jog kortelė apleista.',
        ] },
        { h2: 'APN', id: 'apn' },
        { p: '**APN** (Access Point Name) – tai šliuzo, per kurį SIM turi pasiekti internetą, vardas. Telefonas jį įrašo automatiškai, sekiklis – dažniausiai ne. Jei APN nėra arba jis neteisingas, sekiklis užsiregistruoja tinkle, rodo signalą ir vis tiek negali išsiųsti nė vieno baito. Todėl „SIM turi signalą“ ir „SIM veikia“ nėra tas pat.' },
        { p: 'APN gaunate iš to, kas pardavė SIM kortelę. Tai vienas žodis, kartais su naudotojo vardu ir slaptažodžiu. Paprašykite visų trijų. Įrenginio kortelė APN į konfigūracijos žinutę įrašys už jus – žr. [Sekiklio prijungimas](kb:connect-a-tracker).' },
        { callout: 'tip', p: 'Pirma išbandykite SIM telefone. Jei su ta kortele ir teisingu APN telefonas naršo, sekiklis duomenis irgi gaus. Per dvi minutes pašalinama ištisa abejonių klasė.' },
        { h2: 'Kiek duomenų suvartoja sekimas?', id: 'usage' },
        { p: 'Kur kas mažiau, nei tikimasi. Pozicijos įrašas – kelios dešimtys baitų, o sekikliai juos siunčia paketais. Automobilis, važiuojantis aštuonias valandas per parą įprastu dažniu, per mėnesį sunaudoja maždaug 10–40 MB. Net dosnus planas retai lemia kainą – nustatymus, kurie šį skaičių keičia, aprašo [Siuntimo intervalai](kb:reporting-intervals), kur {product} juos keičiant iškart rodo įvertį.' },
        { h2: 'Tarptinklinis ryšys', id: 'roaming' },
        { p: 'Jei automobiliai kerta sienas, SIM turi turėti leidimą veikti tarptinkliniu ryšiu, o jūs turite žinoti, kiek tai kainuoja. Dažni du gedimo būdai: kortelė, kuri už savo šalies ribų tiesiog nustoja veikti, ir tokia, kuri veikia, bet apmokestinama tarifu, kurio niekas nepatikrino. Kelių tinklų IoT kortelė išvengia abiejų ir tarptautiniam parkui verta nedidelio priedo.' },
        { h2: 'Kai kalta SIM kortelė', id: 'symptoms' },
        { table: { head: ['Ką matote', 'Tikėtina priežastis'], rows: [
          ['Niekada nieko nesiuntė', 'Neteisingas arba nenustatytas APN, arba SIM neaktyvuota'],
          ['Veikė, o paskui tą pačią dieną nutilo visi automobiliai', 'Baigėsi duomenų limitas arba operatorius užblokavo korteles'],
          ['Namuose veikia, užsienyje tyli', 'Neįjungtas tarptinklinis ryšys'],
          ['Veikia, bet duomenys ateina ilgai vėluojančiais pliūpsniais', 'Prasta aprėptis – normalu, niekas neprarasta'],
        ] } },
      ],
    },
    pl: {
      title: 'Karty SIM, APN i transmisja danych',
      summary: 'Jakiej karty SIM potrzebuje lokalizator, czym jest APN, ile danych naprawdę zużywa monitoring i ile kosztuje roaming.',
      keywords: ['sim', 'apn', 'dane', 'roaming', 'iot sim', 'm2m', 'operator', 'gprs'],
      blocks: [
        { p: 'Lokalizator bez działającej transmisji danych to bardzo drogi sposób gromadzenia pozycji, których nikt nigdy nie zobaczy. Dobra karta SIM to połowa udanego montażu — i to właśnie tę połowę ludzie pomijają.' },
        { h2: 'Jaka karta SIM', id: 'kind' },
        { p: 'Nadaje się każda karta z pakietem **danych**. Do normalnej pracy nie są potrzebne rozmowy ani SMS-y — choć karta, która potrafi odebrać SMS, mocno ułatwia pierwszą konfigurację, bo właśnie tak mówi się lokalizatorowi, dokąd wysyłać dane.' },
        { ul: [
          '**Karty IoT / M2M** to typowy wybór: tanie, małe pakiety, często wielosieciowe i rozliczane miesięcznie, a nie za gigabajt.',
          '**Zwykła karta abonencka** działa dobrze. Uważaj na te, które same się blokują po tygodniach niskiego użycia albo wymuszają logowanie przez portal.',
          '**Unikaj** kart prepaid wygasających przy braku aktywności. Lokalizator zużywa tak mało danych, że operator może uznać kartę za porzuconą.',
        ] },
        { h2: 'APN', id: 'apn' },
        { p: '**APN** (Access Point Name) to nazwa bramy, przez którą karta SIM ma wychodzić do internetu. Telefon wypełnia to automatycznie; lokalizator zwykle nie. Gdy APN jest zły albo go brak, lokalizator rejestruje się w sieci, pokazuje zasięg i mimo to nie wyśle ani jednego bajtu — dlatego „karta ma zasięg” to nie to samo co „karta działa”.' },
        { p: 'APN podaje ten, kto sprzedał kartę. To jedno słowo, czasem z nazwą użytkownika i hasłem. Poproś o wszystkie trzy. Karta urządzenia wstawi APN do wiadomości konfiguracyjnej za Ciebie — zobacz [Podłączanie lokalizatora](kb:connect-a-tracker).' },
        { callout: 'tip', p: 'Najpierw przetestuj kartę w telefonie. Jeśli telefon z tą kartą i właściwym APN przegląda internet, lokalizator też dostanie dane. To usuwa całą klasę wątpliwości w dwie minuty.' },
        { h2: 'Ile danych zużywa monitoring?', id: 'usage' },
        { p: 'Znacznie mniej, niż się wydaje. Rekord pozycji to kilkadziesiąt bajtów, a lokalizatory wysyłają je paczkami. Pojazd jeżdżący osiem godzin dziennie przy normalnej częstotliwości mieści się w okolicy 10–40 MB miesięcznie. Nawet hojny pakiet rzadko decyduje o koszcie — ustawienia zmieniające tę liczbę opisuje [Częstotliwość raportowania](kb:reporting-intervals), gdzie {product} pokazuje szacunek na bieżąco.' },
        { h2: 'Roaming', id: 'roaming' },
        { p: 'Jeśli pojazdy przekraczają granice, karta musi mieć włączony roaming, a Ty powinieneś wiedzieć, ile on kosztuje. Częste są dwa scenariusze: karta, która poza krajem po prostu przestaje działać, i taka, która działa, ale nalicza stawkę, której nikt nie sprawdził. Wielosieciowa karta IoT unika obu i dla floty międzynarodowej warta jest niewielkiej dopłaty.' },
        { h2: 'Gdy problemem jest karta SIM', id: 'symptoms' },
        { table: { head: ['Co widzisz', 'Prawdopodobna przyczyna'], rows: [
          ['Nigdy niczego nie zaraportowało', 'Zły lub brakujący APN albo nieaktywowana karta'],
          ['Działało, a potem tego samego dnia zamilkły wszystkie pojazdy', 'Wyczerpany pakiet danych albo operator zawiesił karty'],
          ['W kraju działa, za granicą cisza', 'Wyłączony roaming'],
          ['Działa, ale dane przychodzą mocno opóźnionymi paczkami', 'Słaby zasięg — normalne, nic nie zginęło'],
        ] } },
      ],
    },
    de: {
      title: 'SIM-Karten, APN und Mobilfunkdaten',
      summary: 'Welche SIM ein Tracker braucht, was ein APN ist, wie viel Daten Ortung wirklich verbraucht und was Roaming kostet.',
      keywords: ['sim', 'apn', 'daten', 'roaming', 'iot-sim', 'm2m', 'mobilfunk', 'anbieter'],
      blocks: [
        { p: 'Ein Tracker ohne funktionierende Mobilfunkdaten ist eine sehr teure Art, Positionen zu speichern, die niemand je sieht. Die richtige SIM ist die halbe erfolgreiche Installation — und genau diese Hälfte wird übersprungen.' },
        { h2: 'Welche SIM', id: 'kind' },
        { p: 'Jede SIM mit **Datenvolumen** funktioniert. Telefonie und SMS sind für den normalen Betrieb nicht nötig — eine SIM, die eine SMS empfangen kann, macht die Ersteinrichtung allerdings deutlich leichter, denn so erfährt der Tracker, wohin er senden soll.' },
        { ul: [
          '**IoT-/M2M-SIMs** sind die übliche Wahl: günstig, kleine Volumina, oft netzübergreifend und monatlich statt pro Gigabyte abgerechnet.',
          '**Eine normale Verbraucher-SIM** geht auch. Achten Sie auf Karten, die sich nach Wochen geringer Nutzung selbst sperren oder ein Captive-Portal erzwingen.',
          '**Vermeiden** Sie Prepaid-Karten, die bei Inaktivität verfallen. Ein Tracker verbraucht so wenig, dass der Anbieter die Karte für aufgegeben halten kann.',
        ] },
        { h2: 'Der APN', id: 'apn' },
        { p: 'Ein **APN** (Access Point Name) ist der Name des Gateways, über das die SIM ins Internet muss. Ihr Telefon trägt ihn automatisch ein, ein Tracker meist nicht. Fehlt der APN oder ist er falsch, bucht sich der Tracker ins Netz ein, zeigt Empfang und bekommt trotzdem kein einziges Byte hinaus — deshalb ist „die SIM hat Empfang“ nicht dasselbe wie „die SIM funktioniert“.' },
        { p: 'Den APN nennt Ihnen, wer die SIM verkauft hat. Es ist ein Wort, manchmal mit Benutzername und Passwort. Fragen Sie nach allen dreien. Die Geräteseite setzt den APN für Sie in die Konfigurationsnachricht — siehe [Tracker anschließen](kb:connect-a-tracker).' },
        { callout: 'tip', p: 'Testen Sie die SIM zuerst im Handy. Surft das Handy mit dieser Karte und dem richtigen APN, bekommt auch der Tracker Daten. Das räumt in zwei Minuten eine ganze Reihe von Zweifeln aus.' },
        { h2: 'Wie viele Daten verbraucht Ortung?', id: 'usage' },
        { p: 'Weit weniger als erwartet. Ein Positionsdatensatz ist ein paar Dutzend Byte, und Tracker senden gebündelt. Ein Fahrzeug, das acht Stunden am Tag bei normaler Meldeintervall fährt, landet bei etwa 10–40 MB im Monat. Selbst ein großzügiger Tarif treibt selten die Kosten — die Einstellungen, die diese Zahl bewegen, beschreibt [Meldeintervalle](kb:reporting-intervals), wo {product} beim Verstellen eine laufende Schätzung anzeigt.' },
        { h2: 'Roaming', id: 'roaming' },
        { p: 'Fahren Ihre Fahrzeuge über Grenzen, muss die SIM roamen dürfen — und Sie sollten wissen, was das kostet. Zwei Fehlerbilder sind häufig: eine Karte, die außerhalb des Heimatlands schlicht aufhört zu arbeiten, und eine, die arbeitet, aber zu einem Tarif abrechnet, den niemand geprüft hat. Eine netzübergreifende IoT-SIM vermeidet beides und ist den kleinen Aufpreis für jede internationale Flotte wert.' },
        { h2: 'Wenn die SIM das Problem ist', id: 'symptoms' },
        { table: { head: ['Was Sie sehen', 'Wahrscheinliche Ursache'], rows: [
          ['Hat nie irgendetwas gemeldet', 'Falscher oder fehlender APN, oder die SIM ist nicht aktiviert'],
          ['Lief, dann am selben Tag bei allen Fahrzeugen Stille', 'Datenvolumen aufgebraucht oder Karten vom Anbieter gesperrt'],
          ['Zu Hause aktiv, im Ausland still', 'Roaming nicht freigeschaltet'],
          ['Läuft, aber Meldungen kommen in stark verspäteten Schüben', 'Schlechte Abdeckung — normal, verloren ging nichts'],
        ] } },
      ],
    },
  },
}
