import type { KbArticle } from '../types.js'

export const timeZonesAndUnits: KbArticle = {
  slug: 'time-zones-and-units',
  category: 'reports',
  surfaces: { site: true, app: true },
  screen: '/app/settings',
  doc: {
    en: {
      title: 'Time zones, language and units — two settings, not one',
      summary: 'Why your screen and your colleague\'s e-mail can disagree, and which of the two settings controls which.',
      keywords: ['timezone', 'units', 'km', 'miles', 'litres', 'gallons', 'language', 'date format', 'display', 'account'],
      blocks: [
        { p: 'There are two separate places to set language, units and time, and they answer two different questions. Nearly every confusion here comes from changing one and expecting the other to follow.' },
        { h2: 'Display preferences — what you see', id: 'display' },
        { p: 'These live in your browser and apply to you alone: the interface language, 12- or 24-hour clock, date format, time zone for display, and whether distances are kilometres or miles and volumes litres or gallons.' },
        { p: 'Change them freely. Nobody else is affected, nothing about the stored data changes, and switching back and forth costs nothing.' },
        { h2: 'Account settings — what the server produces', id: 'account' },
        { p: 'These belong to the account and apply to everything the server writes or calculates on its behalf:' },
        { ul: [
          '**Reporting time zone** — where the day boundary sits. A night shift crossing midnight is grouped into the day your business would put it in.',
          '**Language** — the language of alert e-mails and scheduled reports.',
          '**Units** — the units used in those same e-mails and reports.',
        ] },
        { callout: 'note', p: 'Alert recipients are often people with no login here — a workshop, a customer, a driver\'s private address. There is no personal preference to read for them, so the account decides. That is why this setting exists separately.' },
        { h2: 'The two questions', id: 'summary' },
        { table: { head: ['Question', 'Setting'], rows: [
          ['"Why is my dashboard in the wrong language?"', 'Display preferences — yours, in this browser.'],
          ['"Why did my customer get a report in the wrong language?"', 'Account settings.'],
          ['"Why does a report cut days at the wrong hour?"', 'Account reporting time zone.'],
          ['"Why does my colleague see a different time on the same trip?"', 'Their display time zone differs from yours. The underlying moment is identical.'],
        ] } },
        { h2: 'Everything is stored in UTC', id: 'utc' },
        { p: 'Every moment in the system is recorded in UTC and converted only when it is displayed or written into a report. This is what makes a fleet that crosses borders coherent — a trip from Warsaw to Berlin has one true chronology, and each viewer sees it in their own clock without the stored data ever changing.' },
        { p: 'One consequence worth knowing: the hour of a **scheduled report** is entered in UTC, unlike everything else on the screen. See [Scheduled reports](kb:scheduled-reports).' },
      ],
    },
    lt: {
      title: 'Laiko juostos, kalba ir vienetai — du nustatymai, ne vienas',
      summary: 'Kodėl jūsų ekranas ir kolegos laiškas gali nesutapti ir kuris iš dviejų nustatymų ką valdo.',
      keywords: ['laiko juosta', 'vienetai', 'km', 'mylios', 'litrai', 'galonai', 'kalba', 'datos formatas', 'paskyra'],
      blocks: [
        { p: 'Kalbą, vienetus ir laiką galima nustatyti dviejose atskirose vietose, ir jos atsako į du skirtingus klausimus. Beveik visa painiava čia kyla pakeitus vieną ir tikintis, kad seks kitas.' },
        { h2: 'Rodymo nuostatos — ką matote jūs', id: 'display' },
        { p: 'Jos gyvena jūsų naršyklėje ir galioja tik jums: sąsajos kalba, 12 ar 24 valandų laikrodis, datos formatas, rodymo laiko juosta ir tai, ar atstumai kilometrais, ar myliomis, o tūriai litrais ar galonais.' },
        { p: 'Keiskite drąsiai. Nieko kito tai nepaliečia, saugomi duomenys nesikeičia, o perjungimas pirmyn atgal nieko nekainuoja.' },
        { h2: 'Paskyros nustatymai — ką gamina serveris', id: 'account' },
        { p: 'Jie priklauso paskyrai ir galioja viskam, ką serveris jos vardu parašo ar apskaičiuoja:' },
        { ul: [
          '**Ataskaitų laiko juosta** – kur eina dienos riba. Naktinė pamaina, peržengianti vidurnaktį, priskiriama tai dienai, kuriai ją priskirtų jūsų verslas.',
          '**Kalba** – pranešimų laiškų ir planinių ataskaitų kalba.',
          '**Vienetai** – tuose pačiuose laiškuose ir ataskaitose naudojami vienetai.',
        ] },
        { callout: 'note', p: 'Pranešimų gavėjai dažnai yra žmonės, neturintys čia prisijungimo – dirbtuvės, klientas, privatus vairuotojo adresas. Jokių asmeninių nuostatų jiems perskaityti nėra, tad sprendžia paskyra. Kaip tik todėl šis nustatymas yra atskiras.' },
        { h2: 'Du klausimai', id: 'summary' },
        { table: { head: ['Klausimas', 'Nustatymas'], rows: [
          ['„Kodėl mano skydelis ne ta kalba?"', 'Rodymo nuostatos – jūsų, šioje naršyklėje.'],
          ['„Kodėl mano klientas gavo ataskaitą ne ta kalba?"', 'Paskyros nustatymai.'],
          ['„Kodėl ataskaita kerpa dienas ne ta valanda?"', 'Paskyros ataskaitų laiko juosta.'],
          ['„Kodėl kolega toje pačioje kelionėje mato kitokį laiką?"', 'Jo rodymo laiko juosta kitokia nei jūsų. Pati akimirka identiška.'],
        ] } },
        { h2: 'Viskas saugoma UTC', id: 'utc' },
        { p: 'Kiekviena sistemos akimirka įrašoma UTC ir konvertuojama tik tada, kai rodoma arba rašoma į ataskaitą. Kaip tik dėl to sienas kertantis parkas išlieka nuoseklus – kelionė iš Varšuvos į Berlyną turi vieną tikrą chronologiją, o kiekvienas žiūrintysis mato ją savo laikrodžiu, saugomiems duomenims nė kiek nesikeičiant.' },
        { p: 'Vienas padarinys, kurį verta žinoti: **planinės ataskaitos** valanda įvedama UTC, priešingai nei visa kita ekrane. Žr. [Planinės ataskaitos](kb:scheduled-reports).' },
      ],
    },
    pl: {
      title: 'Strefy czasowe, język i jednostki — dwa ustawienia, nie jedno',
      summary: 'Dlaczego Twój ekran i e-mail współpracownika mogą się różnić i które z dwóch ustawień czym steruje.',
      keywords: ['strefa czasowa', 'jednostki', 'km', 'mile', 'litry', 'galony', 'język', 'format daty', 'konto'],
      blocks: [
        { p: 'Język, jednostki i czas ustawia się w dwóch osobnych miejscach, które odpowiadają na dwa różne pytania. Niemal całe zamieszanie bierze się stąd, że ktoś zmienia jedno i oczekuje, że drugie za nim pójdzie.' },
        { h2: 'Preferencje wyświetlania — co widzisz Ty', id: 'display' },
        { p: 'Żyją w Twojej przeglądarce i dotyczą tylko Ciebie: język interfejsu, zegar 12- lub 24-godzinny, format daty, strefa czasowa wyświetlania oraz to, czy dystanse są w kilometrach czy milach, a objętości w litrach czy galonach.' },
        { p: 'Zmieniaj je swobodnie. Nikogo innego to nie dotyczy, nic w przechowywanych danych się nie zmienia, a przełączanie tam i z powrotem nic nie kosztuje.' },
        { h2: 'Ustawienia konta — co produkuje serwer', id: 'account' },
        { p: 'Należą do konta i dotyczą wszystkiego, co serwer w jego imieniu zapisuje lub wylicza:' },
        { ul: [
          '**Strefa czasowa raportowania** — gdzie leży granica doby. Nocna zmiana przechodząca przez północ trafia do tego dnia, do którego przypisałaby ją Twoja firma.',
          '**Język** — język e-maili alertowych i raportów cyklicznych.',
          '**Jednostki** — jednostki używane w tych samych e-mailach i raportach.',
        ] },
        { callout: 'note', p: 'Odbiorcy alertów to często osoby bez loginu — warsztat, klient, prywatny adres kierowcy. Nie ma dla nich żadnych osobistych preferencji do odczytania, więc decyduje konto. Dlatego to ustawienie istnieje osobno.' },
        { h2: 'Dwa pytania', id: 'summary' },
        { table: { head: ['Pytanie', 'Ustawienie'], rows: [
          ['„Dlaczego mój panel jest w złym języku?"', 'Preferencje wyświetlania — Twoje, w tej przeglądarce.'],
          ['„Dlaczego mój klient dostał raport w złym języku?"', 'Ustawienia konta.'],
          ['„Dlaczego raport tnie dni o złej godzinie?"', 'Strefa czasowa raportowania konta.'],
          ['„Dlaczego kolega widzi inny czas na tej samej trasie?"', 'Jego strefa wyświetlania różni się od Twojej. Sama chwila jest identyczna.'],
        ] } },
        { h2: 'Wszystko przechowujemy w UTC', id: 'utc' },
        { p: 'Każda chwila w systemie jest zapisana w UTC i przeliczana dopiero przy wyświetleniu albo zapisie do raportu. To sprawia, że flota przekraczająca granice pozostaje spójna — trasa z Warszawy do Berlina ma jedną prawdziwą chronologię, a każdy ogląda ją na własnym zegarze, bez żadnej zmiany w przechowywanych danych.' },
        { p: 'Jeden skutek wart zapamiętania: godzinę **raportu cyklicznego** podaje się w UTC, inaczej niż wszystko inne na ekranie. Zobacz [Raporty cykliczne](kb:scheduled-reports).' },
      ],
    },
    de: {
      title: 'Zeitzonen, Sprache und Einheiten — zwei Einstellungen, nicht eine',
      summary: 'Warum Ihr Bildschirm und die E-Mail Ihrer Kollegin auseinandergehen können — und welche der beiden Einstellungen was steuert.',
      keywords: ['zeitzone', 'einheiten', 'km', 'meilen', 'liter', 'gallonen', 'sprache', 'datumsformat', 'konto'],
      blocks: [
        { p: 'Sprache, Einheiten und Zeit lassen sich an zwei getrennten Stellen einstellen, und die beantworten zwei verschiedene Fragen. Fast jede Verwirrung hier entsteht, weil jemand das eine ändert und erwartet, dass das andere folgt.' },
        { h2: 'Anzeigeeinstellungen — was Sie sehen', id: 'display' },
        { p: 'Sie liegen in Ihrem Browser und gelten nur für Sie: Oberflächensprache, 12- oder 24-Stunden-Uhr, Datumsformat, Anzeigezeitzone und ob Strecken in Kilometern oder Meilen und Volumina in Litern oder Gallonen erscheinen.' },
        { p: 'Ändern Sie sie frei. Niemand sonst ist betroffen, an den gespeicherten Daten ändert sich nichts, und Hin- und Herschalten kostet nichts.' },
        { h2: 'Kontoeinstellungen — was der Server erzeugt', id: 'account' },
        { p: 'Sie gehören dem Konto und gelten für alles, was der Server in dessen Namen schreibt oder berechnet:' },
        { ul: [
          '**Berichts-Zeitzone** — wo die Tagesgrenze liegt. Eine Nachtschicht über Mitternacht wird dem Tag zugeordnet, dem Ihr Betrieb sie zuordnen würde.',
          '**Sprache** — die Sprache von Alarm-E-Mails und geplanten Berichten.',
          '**Einheiten** — die Einheiten in genau diesen E-Mails und Berichten.',
        ] },
        { callout: 'note', p: 'Alarmempfänger sind oft Menschen ohne Zugang hier — eine Werkstatt, ein Kunde, die private Adresse eines Fahrers. Für sie gibt es keine persönliche Einstellung zum Auslesen, also entscheidet das Konto. Deshalb existiert diese Einstellung getrennt.' },
        { h2: 'Die zwei Fragen', id: 'summary' },
        { table: { head: ['Frage', 'Einstellung'], rows: [
          ['„Warum ist mein Dashboard in der falschen Sprache?"', 'Anzeigeeinstellungen — Ihre, in diesem Browser.'],
          ['„Warum hat mein Kunde einen Bericht in der falschen Sprache bekommen?"', 'Kontoeinstellungen.'],
          ['„Warum schneidet ein Bericht die Tage zur falschen Stunde?"', 'Berichts-Zeitzone des Kontos.'],
          ['„Warum sieht die Kollegin bei derselben Fahrt eine andere Zeit?"', 'Ihre Anzeigezeitzone ist eine andere. Der Zeitpunkt selbst ist identisch.'],
        ] } },
        { h2: 'Alles wird in UTC gespeichert', id: 'utc' },
        { p: 'Jeder Zeitpunkt im System wird in UTC festgehalten und erst bei der Anzeige oder beim Schreiben eines Berichts umgerechnet. Das hält eine grenzüberschreitende Flotte stimmig — eine Fahrt von Warschau nach Berlin hat eine wahre Chronologie, und jeder sieht sie auf seiner eigenen Uhr, ohne dass sich die gespeicherten Daten je ändern.' },
        { p: 'Eine Folge, die man kennen sollte: die Stunde eines **geplanten Berichts** wird in UTC eingetragen, anders als alles andere auf dem Bildschirm. Siehe [Geplante Berichte](kb:scheduled-reports).' },
      ],
    },
  },
}
