import type { KbArticle } from '../types.js'

export const trackingEmployeesLawfully: KbArticle = {
  slug: 'tracking-employees-lawfully',
  category: 'trust',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'Tracking employees lawfully',
      summary: 'A practical checklist for tracking vehicles driven by staff in the EU: what to tell them, what to write down, and what not to do.',
      keywords: ['gdpr', 'privacy', 'employees', 'legal', 'consent', 'legitimate interest', 'works council', 'private use'],
      blocks: [
        { p: 'Tracking a vehicle an employee drives is processing personal data about that employee. It is normal, lawful and widespread — and it comes with obligations that are cheap to meet in advance and expensive to meet after a complaint.' },
        { callout: 'note', p: 'This is a practical summary, not legal advice. National rules differ, and in several countries employee representatives have a formal say. When in doubt, ask a lawyer in the country the drivers work in — it is an hour of somebody\'s time.' },
        { h2: 'Have a reason, and write it down', id: 'purpose' },
        { p: 'You need a specific purpose. “Because we can” is not one. Good purposes are concrete: dispatching the nearest vehicle, proving a delivery, recovering a stolen van, meeting a duty of care, verifying working time.' },
        { p: 'The usual lawful basis for an employer is **legitimate interest**, not consent. Consent from an employee is generally considered unreliable, because someone who cannot realistically refuse has not really consented. Legitimate interest requires you to weigh your purpose against the driver\'s privacy and to record that you did.' },
        { h2: 'Tell people before you start', id: 'inform' },
        { p: 'Drivers must know that the vehicle is tracked, what is collected, why, how long it is kept, who can see it, and how they can ask for their own data. This belongs in a short written notice given before tracking begins — not in a paragraph nobody read three years ago.' },
        { h2: 'Collect what you need and no more', id: 'minimise' },
        { ul: [
          'Track working hours, not private life. A vehicle that goes home at night does not need to be watched all night.',
          'Where private use is permitted, say in writing what happens outside working hours. In many countries continuous tracking of private journeys is not defensible.',
          'Turn on only the features you actually need. Driver identification, for instance, is a real increase in personal data and needs a reason of its own — see [Drivers](kb:drivers).',
        ] },
        { h2: 'Limit who can look', id: 'access' },
        { p: 'Give managers a login scoped to the vehicles they are responsible for, and give the **Viewer** role to people who only need to look. Fewer people with access is both better practice and a smaller thing to explain later — see [Logins and roles](kb:logins-and-roles).' },
        { h2: 'Do not use it as a stick', id: 'discipline' },
        { p: 'Using tracking data for disciplinary decisions is where most disputes actually start. Where you intend to, say so in advance and in writing, follow whatever process applies to you, and let the driver see the same data you are looking at. A history that is shown to the person it describes is far harder to argue with than one produced as a surprise.' },
        { h2: 'Be ready for the two requests', id: 'rights' },
        { ul: [
          '**“What do you hold about me?”** — you can export it; see [Exporting and erasing your data](kb:export-and-erase-data).',
          '**“Delete it.”** — you can erase device data permanently; see [Retiring and erasing a device](kb:device-lifecycle). Be aware that other obligations, such as tachograph or tax records, may require you to keep some of it.',
        ] },
        { h2: 'A one-page policy is enough', id: 'policy' },
        { p: 'Most small fleets need one page: what is tracked, why, when it is on, who sees it, how long it is kept, and who to ask. Write it once, hand it to every driver, and the entire subject stops being a risk.' },
      ],
    },
    lt: {
      title: 'Teisėtas darbuotojų sekimas',
      summary: 'Praktinis patikros sąrašas tiems, kurie ES seka darbuotojų vairuojamus automobilius: ką jiems pasakyti, ką surašyti ir ko nedaryti.',
      keywords: ['bdar', 'privatumas', 'darbuotojai', 'teisė', 'sutikimas', 'teisėtas interesas', 'asmeninis naudojimas'],
      blocks: [
        { p: 'Sekti automobilį, kurį vairuoja darbuotojas, reiškia tvarkyti to darbuotojo asmens duomenis. Tai normalu, teisėta ir plačiai paplitę – ir kartu tai atsineša pareigų, kurias iš anksto įvykdyti pigu, o po skundo brangu.' },
        { callout: 'note', p: 'Tai praktinė santrauka, o ne teisinė konsultacija. Nacionalinės taisyklės skiriasi, o kai kuriose šalyse darbuotojų atstovai turi formalią teisę pasisakyti. Abejodami paklauskite teisininko toje šalyje, kurioje dirba vairuotojai – tai vos valanda kažkieno laiko.' },
        { h2: 'Turėkite priežastį ir ją surašykite', id: 'purpose' },
        { p: 'Reikia konkretaus tikslo. „Nes galime“ – ne tikslas. Geri tikslai konkretūs: pasiųsti artimiausią automobilį, įrodyti pristatymą, susigrąžinti pavogtą furgoną, įvykdyti rūpestingumo pareigą, patikrinti darbo laiką.' },
        { p: 'Įprastas teisinis pagrindas darbdaviui yra **teisėtas interesas**, o ne sutikimas. Darbuotojo sutikimas paprastai laikomas nepatikimu, nes tas, kuris realiai negali atsisakyti, iš tikrųjų nesutiko. Teisėtas interesas reikalauja pasverti savo tikslą ir vairuotojo privatumą ir tą svarstymą užfiksuoti.' },
        { h2: 'Pasakykite žmonėms prieš pradedant', id: 'inform' },
        { p: 'Vairuotojai turi žinoti: kad automobilis sekamas, kas renkama, kodėl, kiek laiko saugoma, kas gali matyti ir kaip jie gali paprašyti savo duomenų. Tai turi būti trumpas rašytinis pranešimas, įteiktas prieš pradedant sekti, o ne pastraipa, kurios prieš trejus metus niekas neskaitė.' },
        { h2: 'Rinkite tiek, kiek reikia, ir ne daugiau', id: 'minimise' },
        { ul: [
          'Sekite darbo laiką, o ne asmeninį gyvenimą. Automobilio, kuris nakčiai važiuoja namo, nereikia stebėti visą naktį.',
          'Jei leidžiamas asmeninis naudojimas, raštu nurodykite, kas vyksta ne darbo valandomis. Daugelyje šalių nuolatinis asmeninių kelionių sekimas nėra pateisinamas.',
          'Įjunkite tuos nustatymus, kuriuos iš tikrųjų naudojate. Pavyzdžiui, vairuotojų atpažinimas iš tikrųjų padidina renkamų asmens duomenų kiekį, todėl reikia atskiros priežasties – žr. [Vairuotojai](kb:drivers).',
        ] },
        { h2: 'Apribokite, kas gali žiūrėti', id: 'access' },
        { p: 'Vadovams duokite prisijungimą, apribotą tais automobiliais, už kuriuos jie atsakingi, o tiems, kam tereikia žiūrėti – **Stebėtojo** rolę. Kuo mažiau žmonių turi prieigą, tuo geresnė praktika ir tuo mažiau teks aiškinti vėliau – žr. [Prisijungimai ir rolės](kb:logins-and-roles).' },
        { h2: 'Nenaudokite duomenų kaip lazdos', id: 'discipline' },
        { p: 'Sekimo duomenų naudojimas drausminiams sprendimams – vieta, kur iš tikrųjų prasideda dauguma ginčų. Jei taip ketinate daryti, pasakykite tai iš anksto ir raštu, laikykitės jums taikomos procedūros ir leiskite vairuotojui matyti tuos pačius duomenis, į kuriuos žiūrite jūs. Su istorija, parodyta žmogui, apie kurį ji kalba, ginčytis kur kas sunkiau nei su pateikta kaip staigmena.' },
        { h2: 'Būkite pasiruošę dviem prašymams', id: 'rights' },
        { ul: [
          '**„Kokius duomenis apie mane turite?“** – galite juos eksportuoti; žr. [Duomenų eksportas ir ištrynimas](kb:export-and-erase-data).',
          '**„Ištrinkite.“** – įrenginio duomenis galima ištrinti negrįžtamai; žr. [Įrenginio išregistravimas ir ištrynimas](kb:device-lifecycle). Atminkite, kad kitos pareigos, pavyzdžiui, tachografo ar mokesčių įrašai, gali reikalauti dalį jų išsaugoti.',
        ] },
        { h2: 'Penkių eilučių tvarkos pakanka', id: 'policy' },
        { p: 'Daugumai mažų autoparkų užtenka vieno lapo: kas sekama, kodėl, kada įjungta, kas mato, kiek laiko saugoma ir ko klausti. Parašykite vieną kartą, įteikite kiekvienam vairuotojui – ir visa ši tema nustoja būti rizika.' },
      ],
    },
    pl: {
      title: 'Legalne monitorowanie pracowników',
      summary: 'Praktyczna lista kontrolna przy monitorowaniu pojazdów prowadzonych przez pracowników w UE: co im powiedzieć, co spisać i czego nie robić.',
      keywords: ['rodo', 'prywatność', 'pracownicy', 'prawo', 'zgoda', 'uzasadniony interes', 'użytek prywatny'],
      blocks: [
        { p: 'Monitorowanie pojazdu prowadzonego przez pracownika to przetwarzanie danych osobowych tego pracownika. Jest to normalne, legalne i powszechne — i wiąże się z obowiązkami, które taniej spełnić z wyprzedzeniem, a drogo po skardze.' },
        { callout: 'note', p: 'To praktyczne streszczenie, nie porada prawna. Przepisy krajowe się różnią, a w kilku krajach przedstawiciele pracowników mają formalny głos. W razie wątpliwości zapytaj prawnika w kraju, w którym pracują kierowcy — to godzina czyjegoś czasu.' },
        { h2: 'Miej powód i zapisz go', id: 'purpose' },
        { p: 'Potrzebujesz konkretnego celu. „Bo możemy” nim nie jest. Dobre cele są konkretne: wysłanie najbliższego pojazdu, udowodnienie dostawy, odzyskanie skradzionego busa, dopełnienie obowiązku staranności, weryfikacja czasu pracy.' },
        { p: 'Typową podstawą prawną dla pracodawcy jest **uzasadniony interes**, a nie zgoda. Zgoda pracownika jest generalnie uważana za niewiarygodną, bo ktoś, kto realnie nie może odmówić, tak naprawdę nie wyraził zgody. Uzasadniony interes wymaga wyważenia celu wobec prywatności kierowcy i udokumentowania, że to zrobiłeś.' },
        { h2: 'Powiedz ludziom, zanim zaczniesz', id: 'inform' },
        { p: 'Kierowcy muszą wiedzieć: że pojazd jest monitorowany, co jest zbierane, po co, jak długo trzymane, kto może to zobaczyć i jak mogą poprosić o własne dane. To powinno znaleźć się w krótkiej pisemnej informacji przekazanej przed rozpoczęciem monitoringu — a nie do akapitu, którego nikt nie przeczytał trzy lata temu.' },
        { h2: 'Zbieraj tyle, ile potrzeba, i nie więcej', id: 'minimise' },
        { ul: [
          'Monitoruj czas pracy, a nie życie prywatne. Pojazd jadący na noc do domu nie musi być obserwowany całą noc.',
          'Tam, gdzie użytek prywatny jest dozwolony, zapisz, co dzieje się poza godzinami pracy. W wielu krajach ciągłe śledzenie prywatnych przejazdów jest nie do obrony.',
          'Włączaj tylko te ustawienia, z których naprawdę korzystasz. Identyfikacja kierowcy to realny przyrost danych osobowych i wymaga własnego uzasadnienia — zobacz [Kierowcy](kb:drivers).',
        ] },
        { h2: 'Ogranicz, kto może patrzeć', id: 'access' },
        { p: 'Menedżerom daj login ograniczony do pojazdów, za które odpowiadają, a osobom, które mają tylko patrzeć — rolę **Podgląd**. Mniej osób z dostępem to i lepsza praktyka, i mniej do wyjaśniania później — zobacz [Loginy i role](kb:logins-and-roles).' },
        { h2: 'Nie używaj tego jako kija', id: 'discipline' },
        { p: 'Wykorzystanie danych z monitoringu do decyzji dyscyplinarnych to miejsce, gdzie naprawdę zaczyna się większość sporów. Jeśli zamierzasz to robić, powiedz o tym z wyprzedzeniem i na piśmie, zastosuj obowiązującą Cię procedurę i pozwól kierowcy zobaczyć te same dane, na które patrzysz. Z historią pokazaną osobie, której dotyczy, dużo trudniej polemizować niż z przedstawioną jako niespodzianka.' },
        { h2: 'Bądź gotów na dwa wnioski', id: 'rights' },
        { ul: [
          '**„Co o mnie macie?”** — możesz to wyeksportować; zobacz [Eksport i usuwanie danych](kb:export-and-erase-data).',
          '**„Usuńcie to.”** — dane urządzenia można trwale usunąć; zobacz [Wycofywanie i usuwanie urządzenia](kb:device-lifecycle). Pamiętaj, że inne obowiązki, jak zapisy tachografu czy podatkowe, mogą wymagać zachowania części z nich.',
        ] },
        { h2: 'Pięciolinijkowa polityka wystarczy', id: 'policy' },
        { p: 'Większości małych flot wystarczy jedna strona: co jest monitorowane, po co, kiedy jest włączone, kto to widzi, jak długo trzymane i kogo pytać. Napisz ją raz i wręcz każdemu kierowcy — i cały ten temat przestaje być ryzykiem.' },
      ],
    },
    de: {
      title: 'Mitarbeiter rechtmäßig orten',
      summary: 'Eine praktische Checkliste für die Ortung von Dienstfahrzeugen in der EU: was Sie sagen, was Sie aufschreiben und was Sie lassen sollten.',
      keywords: ['dsgvo', 'datenschutz', 'mitarbeiter', 'recht', 'einwilligung', 'berechtigtes interesse', 'betriebsrat', 'privatnutzung'],
      blocks: [
        { p: 'Ein Fahrzeug zu orten, das ein Mitarbeiter fährt, ist die Verarbeitung personenbezogener Daten dieses Mitarbeiters. Das ist normal, rechtmäßig und verbreitet — und es bringt Pflichten mit, die im Voraus billig und nach einer Beschwerde teuer sind.' },
        { callout: 'note', p: 'Dies ist eine praktische Zusammenfassung, keine Rechtsberatung. Nationale Regeln unterscheiden sich, und in mehreren Ländern haben Arbeitnehmervertretungen ein formales Mitspracherecht — in Deutschland ist die Einführung solcher Systeme nach § 87 Abs. 1 Nr. 6 BetrVG mitbestimmungspflichtig, sofern ein Betriebsrat besteht. Im Zweifel fragen Sie eine Anwältin im Land der Fahrer; das ist eine Stunde Zeit.' },
        { h2: 'Einen Grund haben — und aufschreiben', id: 'purpose' },
        { p: 'Sie brauchen einen konkreten Zweck. „Weil wir können“ ist keiner. Gute Zwecke sind greifbar: das nächstgelegene Fahrzeug disponieren, eine Lieferung nachweisen, einen gestohlenen Transporter zurückholen, einer Fürsorgepflicht nachkommen, Arbeitszeit prüfen.' },
        { p: 'Die übliche Rechtsgrundlage für Arbeitgeber ist das **berechtigte Interesse**, nicht die Einwilligung. Eine Einwilligung von Beschäftigten gilt allgemein als nicht freiwillig, weil, wer realistischerweise nicht ablehnen kann,, nicht wirklich eingewilligt hat. Berechtigtes Interesse verlangt, Ihren Zweck gegen die Privatsphäre der Fahrer abzuwägen und diese Abwägung zu dokumentieren.' },
        { h2: 'Vorher informieren', id: 'inform' },
        { p: 'Fahrer müssen wissen: dass das Fahrzeug geortet wird, was erhoben wird, warum, wie lange es bleibt, wer es sehen kann und wie sie ihre eigenen Daten anfordern können. Das gehört in eine kurze schriftliche Information vor Beginn der Ortung — nicht in einen Absatz, den vor drei Jahren niemand gelesen hat.' },
        { h2: 'Nur erheben, was nötig ist', id: 'minimise' },
        { ul: [
          'Erfassen Sie Arbeitszeit, nicht Privatleben. Ein Fahrzeug, das nachts nach Hause fährt, muss nicht die ganze Nacht beobachtet werden.',
          'Wo Privatnutzung erlaubt ist, halten Sie schriftlich fest, was außerhalb der Arbeitszeit passiert. In vielen Ländern ist eine durchgehende Ortung privater Fahrten nicht haltbar.',
          'Schalten Sie ein, was Sie tatsächlich nutzen. Fahrererkennung etwa ist ein echter Zuwachs an personenbezogenen Daten und braucht einen eigenen Grund — siehe [Fahrer](kb:drivers).',
        ] },
        { h2: 'Zugriff begrenzen', id: 'access' },
        { p: 'Geben Sie Führungskräften einen Zugang, der auf ihre Fahrzeuge begrenzt ist, und Personen, die nur schauen müssen, die Rolle **Betrachter**. Weniger Zugriffsberechtigte sind bessere Praxis und später weniger zu erklären — siehe [Zugänge und Rollen](kb:logins-and-roles).' },
        { h2: 'Nicht als Druckmittel verwenden', id: 'discipline' },
        { p: 'Ortungsdaten für arbeitsrechtliche Entscheidungen zu nutzen ist der Punkt, an dem die meisten Streitigkeiten tatsächlich beginnen. Wenn Sie das vorhaben, sagen Sie es vorher und schriftlich, halten Sie das für Sie geltende Verfahren ein und lassen Sie den Fahrer dieselben Daten sehen, auf die Sie schauen. Ein Verlauf, der der betroffenen Person gezeigt wird, ist weit schwerer zu bestreiten als eine, die als Überraschung präsentiert wird.' },
        { h2: 'Auf zwei Anfragen vorbereitet sein', id: 'rights' },
        { ul: [
          '**„Welche Daten haben Sie über mich gespeichert?“** — Sie können es exportieren; siehe [Daten exportieren und löschen](kb:export-and-erase-data).',
          '**„Löschen Sie sie.“** — Gerätedaten lassen sich endgültig löschen; siehe [Gerät stilllegen und löschen](kb:device-lifecycle). Beachten Sie, dass andere Pflichten, etwa Tachographen- oder Steuerunterlagen, die Aufbewahrung eines Teils verlangen können.',
        ] },
        { h2: 'Eine Richtlinie in fünf Zeilen genügt', id: 'policy' },
        { p: 'Die meisten kleinen Flotten brauchen eine Seite: was geortet wird, warum, wann es an ist, wer es sieht, wie lange es bleibt und wen man fragt. Einmal schreiben, jedem Fahrer aushändigen — und das ganze Thema hört auf, ein Risiko zu sein.' },
      ],
    },
  },
}
