import type { KbArticle } from '../types.js'

export const unpaidWhatHappens: KbArticle = {
  slug: 'unpaid-what-happens',
  category: 'account',
  surfaces: { site: true, app: true },
  audience: { platformOnly: true },
  doc: {
    en: {
      title: 'What happens if an invoice goes unpaid',
      summary: 'The full sequence — grace period, three warnings, then the fleet stops reporting — and exactly what is and is not lost.',
      keywords: ['unpaid', 'overdue', 'suspended', 'stopped', 'lapse', 'cancel', 'restore', 'grace'],
      blocks: [
        { p: 'Nothing here is a surprise, and nothing here deletes anything. The sequence is written down so that a payment problem is a scheduling problem rather than an emergency.' },
        { h2: 'Step 1 — Stripe retries the card', id: 'retries' },
        { p: 'A failed payment is retried on a schedule over several days. Service continues untouched throughout. Most failures — an expired card, a bank\'s fraud check, a temporary limit — are resolved here without anybody noticing.' },
        { h2: 'Step 2 — the grace period', id: 'grace' },
        { p: 'If the retries do not succeed, a grace period of about two weeks begins. Everything keeps working. This is the window in which almost every real case is settled: a card is updated, an accounting department pays, someone comes back from leave.' },
        { h2: 'Step 3 — three warnings', id: 'warnings' },
        { p: 'When grace ends, the administrators on the account are e-mailed three times on consecutive days: three days\' notice, then two days\', then one. Each names the date the fleet stops and links straight to the billing screen.' },
        { callout: 'note', p: 'The warnings are not optional and cannot be skipped. If we cannot deliver them — no working address on file, or mail delivery failing — the suspension does not happen either. Nobody is cut off silently.' },
        { h2: 'Step 4 — the fleet stops reporting', id: 'suspension' },
        { p: 'One day after the final warning — the one that gives one day\'s notice — the platform stops accepting data from the account\'s trackers. This is the actual consequence, and it is worth being precise about what it does and does not mean.' },
        { table: { head: ['What happens', 'What does not change'], rows: [
          ['New positions are refused at the door.', 'Nothing is deleted. Not one position, trip, event or report.'],
          ['The live map stops advancing.', 'You can still sign in and read the entire history.'],
          ['Alerts and scheduled reports stop, because there is no new data.', 'Your devices, zones, rules, drivers and settings all stay exactly as they were.'],
          ['The trackers keep recording in their own memory.', 'The trackers are not reconfigured, reset or touched in any way.'],
        ] } },
        { h2: 'Step 5 — paying restores everything', id: 'restore' },
        { p: 'Settle the invoice and the account is reinstated on the next check, without anyone having to ask. The last known position of every vehicle is still there, so the map is populated the moment it comes back rather than starting empty.' },
        { p: 'The trackers themselves then deliver what they recorded while the account was suspended, as far back as their own memory reaches. How much that is depends on the device and its reporting settings — expect a partial catch-up rather than a complete one.' },
        { h2: 'If you meant to cancel', id: 'cancel' },
        { p: 'Cancel deliberately in the Stripe portal rather than by letting an invoice fail. Cancelling stops billing cleanly; letting it lapse produces three warning e-mails first and reaches the same place two weeks later. Export anything you want to keep before you go — see [Exporting and erasing your data](kb:export-and-erase-data).' },
      ],
    },
    lt: {
      title: 'Kas nutinka neapmokėjus sąskaitos',
      summary: 'Visa seka – atidėjimo laikotarpis, trys įspėjimai, tada autoparkas nustoja siųsti duomenis – ir tiksliai, kas prarandama, o kas ne.',
      keywords: ['neapmokėta', 'pradelsta', 'sustabdyta', 'atjungta', 'atšaukimas', 'atstatymas', 'atidėjimas'],
      blocks: [
        { p: 'Čia nėra nieko netikėto ir niekas nieko netrina. Seka surašyta tam, kad mokėjimo problema būtų grafiko klausimas, o ne nelaimė.' },
        { h2: '1 žingsnis — Stripe kartoja kortelės nuskaitymą', id: 'retries' },
        { p: 'Nepavykęs mokėjimas kartojamas pagal grafiką kelias dienas. Paslauga visą tą laiką veikia be pokyčių. Dauguma nesėkmių – pasibaigusi kortelė, banko sukčiavimo patikra, laikinas limitas – išsprendžiama čia, niekam net nepastebint.' },
        { h2: '2 žingsnis — atidėjimo laikotarpis', id: 'grace' },
        { p: 'Jei pakartotiniai bandymai nepavyksta, prasideda maždaug dviejų savaičių atidėjimo laikotarpis. Viskas toliau veikia. Būtent per šį laikotarpį išsisprendžia beveik kiekvienas tikras atvejis: atnaujinama kortelė, buhalterija sumoka, kažkas grįžta iš atostogų.' },
        { h2: '3 žingsnis — trys įspėjimai', id: 'warnings' },
        { p: 'Pasibaigus atidėjimui, paskyros administratoriams tris dienas iš eilės siunčiami laiškai: likus trims dienoms, likus dviem ir galutinis likus vienai. Kiekviename nurodyta data, kada autoparkas sustos, ir tiesioginė nuoroda į mokėjimų ekraną.' },
        { callout: 'note', p: 'Įspėjimai nėra pasirenkami ir jų praleisti negalima. Jei jų pristatyti negalime – nėra veikiančio adreso arba laiškai nepasiekia adresato – neįvyksta ir atjungimas. Tyliai neatjungiamas niekas.' },
        { h2: '4 žingsnis — autoparkas nustoja siųsti duomenis', id: 'suspension' },
        { p: 'Praėjus dienai po galutinio įspėjimo – to paties, kuriame parašyta „viena diena“ – platforma nustoja priimti duomenis iš paskyros sekiklių. Tai ir yra tikrasis padarinys, todėl verta tiksliai pasakyti, ką jis reiškia, o ko ne.' },
        { table: { head: ['Kas įvyksta', 'Kas ne'], rows: [
          ['Naujos pozicijos atmetamos jau prie durų.', 'Nieko neištrinama. Nė vienos pozicijos, kelionės, įvykio ar ataskaitos.'],
          ['Gyvas žemėlapis nustoja judėti.', 'Vis dar galite prisijungti ir skaityti visą istoriją.'],
          ['Pranešimai ir suplanuotos ataskaitos sustoja, nes nebėra naujų duomenų.', 'Jūsų įrenginiai, zonos, taisyklės, vairuotojai ir nustatymai lieka lygiai tokie patys.'],
          ['Sekikliai toliau įrašinėja į savo atmintį.', 'Sekikliai nekonfigūruojami iš naujo, neatstatomi į gamyklinius nustatymus ir apskritai neliečiami.'],
        ] } },
        { h2: '5 žingsnis — sumokėjus viskas atkuriama', id: 'restore' },
        { p: 'Apmokėkite sąskaitą, ir paskyra atkuriama per kitą patikrą – nieko prašyti nereikia. Paskutinė žinoma kiekvieno automobilio pozicija tebėra vietoje, tad grįžus žemėlapis iškart būna užpildytas, o ne tuščias.' },
        { p: 'Tada patys sekikliai atsiunčia tai, ką įrašė, kol jų duomenys buvo nepriimami, tiek, kiek siekia jų pačių atmintis. Kiek to bus, priklauso nuo įrenginio ir jo siuntimo nustatymų – tikėkitės dalinio, o ne visiško pasivijimo.' },
        { h2: 'Jei norėjote atšaukti', id: 'cancel' },
        { p: 'Atšaukite sąmoningai Stripe portale, o ne palikdami sąskaitą neapmokėtą. Atšaukimas švariai sustabdo mokėjimus; palikus sąskaitą neapmokėtą, pirma ateis trys įspėjamieji laiškai, o po dviejų savaičių atsidursite ten pat. Prieš išeidami eksportuokite tai, ką norite pasilikti – žr. [Duomenų eksportas ir ištrynimas](kb:export-and-erase-data).' },
      ],
    },
    pl: {
      title: 'Co się dzieje przy braku płatności',
      summary: 'Pełna sekwencja — okres karencji, trzy ostrzeżenia, potem flota przestaje raportować — i dokładnie, co jest, a co nie jest tracone.',
      keywords: ['brak płatności', 'zaległość', 'zawieszenie', 'odcięcie', 'anulowanie', 'przywrócenie', 'karencja'],
      blocks: [
        { p: 'Nic tu nie jest niespodzianką i nic tu niczego nie usuwa. Sekwencja jest spisana po to, by problem z płatnością był kwestią harmonogramu, a nie awarią.' },
        { h2: 'Krok 1 — Stripe ponawia obciążenie karty', id: 'retries' },
        { p: 'Nieudana płatność jest ponawiana według harmonogramu przez kilka dni. Usługa przez cały ten czas działa bez zmian. Większość niepowodzeń — wygasła karta, kontrola antyfraudowa banku, chwilowy limit — rozwiązuje się właśnie tutaj i nikt tego nie zauważa.' },
        { h2: 'Krok 2 — okres karencji', id: 'grace' },
        { p: 'Jeśli ponowienia nie pomogą, zaczyna się około dwutygodniowa karencja. Wszystko działa dalej. To okno, w którym rozstrzyga się niemal każdy prawdziwy przypadek: karta zostaje zaktualizowana, księgowość płaci, ktoś wraca z urlopu.' },
        { h2: 'Krok 3 — trzy ostrzeżenia', id: 'warnings' },
        { p: 'Po zakończeniu karencji administratorzy konta dostają e-maile przez trzy kolejne dni: trzy dni przed terminem, dwa dni przed i ostatni na dzień przed. Każdy podaje datę zatrzymania floty i prowadzi prosto do ekranu płatności.' },
        { callout: 'note', p: 'Ostrzeżenia nie są opcjonalne i nie da się ich pominąć. Jeśli nie możemy ich dostarczyć — brak działającego adresu albo poczta nie dochodzi — zawieszenie też nie następuje. Nikt nie jest odcinany po cichu.' },
        { h2: 'Krok 4 — flota przestaje raportować', id: 'suspension' },
        { p: 'Dzień po ostatnim ostrzeżeniu — tym, które mówi o jednym dniu — platforma przestaje przyjmować dane z lokalizatorów konta. To jest właściwa konsekwencja i warto precyzyjnie powiedzieć, co znaczy, a czego nie.' },
        { table: { head: ['Co się dzieje', 'Co się nie dzieje'], rows: [
          ['Nowe pozycje są odrzucane już przy wejściu.', 'Nic nie jest usuwane. Ani jedna pozycja, trasa, zdarzenie czy raport.'],
          ['Mapa na żywo przestaje się przesuwać.', 'Nadal możesz się zalogować i czytać całą historię.'],
          ['Alerty i raporty cykliczne ustają, bo nie ma nowych danych.', 'Twoje urządzenia, strefy, reguły, kierowcy i ustawienia zostają dokładnie takie, jakie były.'],
          ['Lokalizatory dalej zapisują we własnej pamięci.', 'Lokalizatory nie są przekonfigurowywane, resetowane ani w żaden sposób ruszane.'],
        ] } },
        { h2: 'Krok 5 — zapłata przywraca wszystko', id: 'restore' },
        { p: 'Ureguluj fakturę, a konto zostaje przywrócone przy następnym cyklu sprawdzania, bez konieczności proszenia kogokolwiek. Ostatnia znana pozycja każdego pojazdu wciąż tam jest, więc mapa po powrocie jest od razu wypełniona, a nie pusta.' },
        { p: 'Potem same lokalizatory dostarczają to, co zapisały, gdy były odrzucane — na tyle, na ile sięga ich własna pamięć. Ile tego będzie, zależy od urządzenia i jego ustawień wysyłki — spodziewaj się nadrobienia częściowego, nie pełnego.' },
        { h2: 'Jeśli chciałeś anulować', id: 'cancel' },
        { p: 'Anuluj świadomie w portalu Stripe, a nie przez dopuszczenie do nieopłaconej faktury. Anulowanie zamyka rozliczenia czysto; dopuszczenie do wygaśnięcia najpierw wygeneruje trzy e-maile ostrzegawcze i dwa tygodnie później doprowadzi do tego samego miejsca. Przed odejściem wyeksportuj, co chcesz zachować — zobacz [Eksport i usuwanie danych](kb:export-and-erase-data).' },
      ],
    },
    de: {
      title: 'Was bei einer unbezahlten Rechnung passiert',
      summary: 'Die vollständige Abfolge — Nachfrist, drei Warnungen, dann meldet die Flotte nicht mehr — und was genau verloren geht und was nicht.',
      keywords: ['unbezahlt', 'überfällig', 'gesperrt', 'abgeschaltet', 'kündigung', 'wiederherstellung', 'kulanz'],
      blocks: [
        { p: 'Nichts hier ist eine Überraschung, und nichts hier löscht etwas. Die Abfolge ist aufgeschrieben, damit ein Zahlungsproblem eine Terminfrage bleibt und kein Notfall wird.' },
        { h2: 'Schritt 1 — Stripe versucht die Karte erneut', id: 'retries' },
        { p: 'Eine fehlgeschlagene Zahlung wird über mehrere Tage nach Plan wiederholt. Der Dienst läuft die ganze Zeit unverändert. Die meisten Fehlschläge — abgelaufene Karte, Betrugsprüfung der Bank, ein temporäres Limit — klären sich hier, ohne dass es jemand bemerkt.' },
        { h2: 'Schritt 2 — die Nachfrist', id: 'grace' },
        { p: 'Führen die Wiederholungen nicht zum Erfolg, beginnt eine Nachfrist von etwa zwei Wochen. Alles läuft weiter. In diesem Fenster klärt sich nahezu jeder reale Fall: Eine Karte wird erneuert, die Buchhaltung zahlt, jemand kommt aus dem Urlaub zurück.' },
        { h2: 'Schritt 3 — drei Warnungen', id: 'warnings' },
        { p: 'Nach der Nachfrist erhalten die Administratoren des Kontos an drei aufeinanderfolgenden Tagen E-Mails: drei Tage vorher, zwei Tage vorher und eine letzte einen Tag vorher. Jede nennt das Datum, an dem die Flotte stoppt, und führt direkt zum Abrechnungsseite.' },
        { callout: 'note', p: 'Die Warnungen sind nicht optional und nicht überspringbar. Können wir sie nicht zustellen — keine funktionierende Adresse hinterlegt oder die Mail kommt nicht an — findet auch keine Sperrung statt. Niemand wird stillschweigend abgeschaltet.' },
        { h2: 'Schritt 4 — die Flotte meldet nicht mehr', id: 'suspension' },
        { p: 'Einen Tag nach der letzten Warnung — derjenigen, die von einem Tag spricht — nimmt die Plattform keine Daten der Tracker dieses Kontos mehr an. Das ist die tatsächliche Folge, und es lohnt sich, genau zu sagen, was sie bedeutet und was nicht.' },
        { table: { head: ['Was passiert', 'Was nicht'], rows: [
          ['Neue Positionen werden nicht mehr angenommen.', 'Nichts wird gelöscht. Keine Position, keine Fahrt, kein Ereignis, kein Bericht.'],
          ['Die Live-Karte bewegt sich nicht mehr.', 'Sie können sich weiter anmelden und die gesamte Verlauf lesen.'],
          ['Alarme und geplante Berichte hören auf, weil es keine neuen Daten gibt.', 'Ihre Geräte, Zonen, Regeln, Fahrer und Einstellungen bleiben exakt so, wie sie waren.'],
          ['Die Tracker zeichnen in ihrem eigenen Speicher weiter auf.', 'Die Tracker werden nicht umkonfiguriert, nicht zurückgesetzt und überhaupt nicht angefasst.'],
        ] } },
        { h2: 'Schritt 5 — die Zahlung stellt alles wieder her', id: 'restore' },
        { p: 'Begleichen Sie die Rechnung, und das Konto wird beim nächsten Durchlauf reaktiviert, ohne dass jemand darum bitten muss. Die letzte bekannte Position jedes Fahrzeugs ist noch da, die Karte ist also sofort gefüllt statt leer.' },
        { p: 'Danach liefern die Tracker selbst nach, was sie während der Abweisung aufgezeichnet haben — so weit ihr eigener Speicher reicht. Wie viel das ist, hängt vom Gerät und seinen Sendeeinstellungen ab; rechnen Sie mit einem teilweisen, nicht mit einem vollständigen Nachholen.' },
        { h2: 'Wenn Sie kündigen wollten', id: 'cancel' },
        { p: 'Kündigen Sie bewusst im Stripe-Portal, statt eine Rechnung scheitern zu lassen. Eine Kündigung stoppt die Abrechnung sauber; ein Verfallenlassen erzeugt erst drei Warn-E-Mails und landet zwei Wochen später am selben Punkt. Exportieren Sie vorher, was Sie behalten wollen — siehe [Daten exportieren und löschen](kb:export-and-erase-data).' },
      ],
    },
  },
}
