import type { KbArticle } from '../types.js'

export const vehicleCard: KbArticle = {
  slug: 'vehicle-card',
  category: 'fleet',
  surfaces: { site: true, app: true },
  screen: '/app/devices',
  doc: {
    en: {
      title: 'The vehicle card: profile, documents and service history',
      summary: 'Where the facts about a vehicle live — make, VIN, purchase, papers with expiry dates, and everything that has been done to it.',
      keywords: ['vehicle', 'card', 'profile', 'vin', 'documents', 'insurance', 'inspection', 'expiry', 'service log'],
      blocks: [
        { p: 'The tracker produces the movement data. The vehicle card holds everything else you know about the vehicle, in the same place, so nobody has to open a filing cabinet to answer a question about it.' },
        { h2: 'Profile', id: 'profile' },
        { p: 'Make, model, year, VIN, fuel type, status, purchase date and purchase price, plus the assigned driver. The purchase fields are what let a cost per kilometre mean anything: without them you have running costs and no capital.' },
        { h2: 'Documents', id: 'documents' },
        { p: 'Insurance, roadworthiness certificates, permits, leases — each with a type, a number and a valid-until date. The card shows the days remaining, and an expired document is shown as overdue rather than quietly dropping off the list.' },
        { callout: 'tip', p: 'Expiring documents are also collected across the fleet, so one screen answers “what runs out this month” — which is exactly the question that otherwise gets answered by a roadside check.' },
        { h2: 'Service log', id: 'service' },
        { p: 'Everything that has been done to the vehicle, with the date, the odometer or engine-hour reading, the cost and the workshop. Entries appear here automatically when a maintenance reminder is marked as done, and can be added by hand for work that was never scheduled.' },
        { p: 'The total cost is summed for you. Over a couple of years that total, next to the purchase price and the mileage, is the number that decides whether to keep a vehicle or replace it.' },
        { h2: 'Why fill it in', id: 'why' },
        { ul: [
          'A vehicle sold is a vehicle whose history you can hand over.',
          'An insurance claim asks for the VIN and the documents, usually on a bad day.',
          'A cost per kilometre that includes service and purchase is a real number; one that includes only fuel is a comforting one.',
          'The person who knows all this by heart eventually leaves.',
        ] },
        { h2: 'Related', id: 'related' },
        { p: 'Scheduled servicing lives next door in [Maintenance reminders](kb:maintenance), and the mileage those reminders count is explained in [Distance and odometer](kb:distance-and-odometer).' },
      ],
    },
    lt: {
      title: 'Automobilio kortelė: profilis, dokumentai ir serviso istorija',
      summary: 'Kur gyvena faktai apie automobilį – markė, VIN, pirkimas, dokumentai su galiojimo datomis ir viskas, kas su juo padaryta.',
      keywords: ['automobilis', 'kortelė', 'profilis', 'vin', 'dokumentai', 'draudimas', 'techninė apžiūra', 'galiojimas', 'serviso žurnalas'],
      blocks: [
        { p: 'Sekiklis gamina judėjimo duomenis. Automobilio kortelė laiko visa kita, ką apie automobilį žinote, toje pačioje vietoje, kad atsakant į klausimą nereikėtų atidarinėti dokumentų spintos.' },
        { h2: 'Profilis', id: 'profile' },
        { p: 'Markė, modelis, metai, VIN, kuro tipas, būsena, pirkimo data ir kaina bei priskirtas vairuotojas. Būtent pirkimo laukai leidžia kilometro savikainai ką nors reikšti: be jų turite eksploatacijos išlaidas ir jokio kapitalo.' },
        { h2: 'Dokumentai', id: 'documents' },
        { p: 'Draudimas, techninės apžiūros pažymos, leidimai, lizingo sutartys – kiekvienas su tipu, numeriu ir galiojimo data. Kortelė rodo likusias dienas, o pasibaigęs dokumentas rodomas kaip pradelstas, o ne tyliai iškrenta iš sąrašo.' },
        { callout: 'tip', p: 'Besibaigiantys dokumentai renkami ir per visą parką, tad vienas ekranas atsako „kas baigiasi šį mėnesį“ – kaip tik tas klausimas, į kurį kitaip atsako patikra kelyje.' },
        { h2: 'Serviso žurnalas', id: 'service' },
        { p: 'Viskas, kas su automobiliu padaryta, su data, odometro ar variklio valandų rodmeniu, kaina ir dirbtuvėmis. Įrašai čia atsiranda automatiškai, kai priežiūros priminimas pažymimas atliktu, ir gali būti pridėti ranka darbams, kurių niekas neplanavo.' },
        { p: 'Bendra suma sudedama už jus. Per porą metų ta suma šalia pirkimo kainos ir ridos yra tas skaičius, kuris nulemia, ar automobilį laikyti, ar keisti.' },
        { h2: 'Kodėl verta pildyti', id: 'why' },
        { ul: [
          'Parduotas automobilis – tas, kurio istoriją galite perduoti.',
          'Draudimo įvykiui reikia VIN ir dokumentų, ir dažniausiai blogą dieną.',
          'Kilometro savikaina, į kurią įskaičiuotas servisas ir pirkimas, yra tikras skaičius; ta, kurioje tik kuras – raminantis.',
          'Žmogus, kuris visa tai žino mintinai, kada nors išeis.',
        ] },
        { h2: 'Susiję', id: 'related' },
        { p: 'Planinė priežiūra gyvena greta – [Priežiūros priminimai](kb:maintenance), o ridą, kurią tie priminimai skaičiuoja, paaiškina [Atstumas ir odometras](kb:distance-and-odometer).' },
      ],
    },
    pl: {
      title: 'Karta pojazdu: profil, dokumenty i historia serwisowa',
      summary: 'Gdzie mieszkają fakty o pojeździe — marka, VIN, zakup, dokumenty z terminami ważności i wszystko, co przy nim zrobiono.',
      keywords: ['pojazd', 'karta', 'profil', 'vin', 'dokumenty', 'ubezpieczenie', 'przegląd', 'termin', 'historia serwisowa'],
      blocks: [
        { p: 'Lokalizator produkuje dane o ruchu. Karta pojazdu trzyma wszystko inne, co o pojeździe wiesz, w jednym miejscu — żeby nikt nie musiał otwierać szafy z dokumentami, by odpowiedzieć na pytanie.' },
        { h2: 'Profil', id: 'profile' },
        { p: 'Marka, model, rok, VIN, rodzaj paliwa, status, data i cena zakupu oraz przypisany kierowca. To właśnie pola zakupu sprawiają, że koszt kilometra cokolwiek znaczy: bez nich masz koszty eksploatacji i żadnego kapitału.' },
        { h2: 'Dokumenty', id: 'documents' },
        { p: 'Ubezpieczenie, przeglądy, zezwolenia, umowy leasingu — każdy z typem, numerem i datą ważności. Karta pokazuje pozostałe dni, a dokument po terminie widnieje jako zaległy, zamiast po cichu wypaść z listy.' },
        { callout: 'tip', p: 'Kończące się dokumenty są też zbierane w skali floty, więc jeden ekran odpowiada na „co kończy się w tym miesiącu” — dokładnie to pytanie, na które inaczej odpowiada kontrola drogowa.' },
        { h2: 'Historia serwisowa', id: 'service' },
        { p: 'Wszystko, co przy pojeździe zrobiono, z datą, stanem licznika lub motogodzin, kosztem i warsztatem. Wpisy pojawiają się tu automatycznie, gdy przypomnienie serwisowe zostaje oznaczone jako wykonane, i można je dodać ręcznie dla prac, których nikt nie planował.' },
        { p: 'Suma kosztów jest liczona za Ciebie. Po paru latach ta suma, obok ceny zakupu i przebiegu, jest liczbą decydującą, czy pojazd zatrzymać, czy wymienić.' },
        { h2: 'Po co to wypełniać', id: 'why' },
        { ul: [
          'Sprzedany pojazd to pojazd, którego historię możesz przekazać.',
          'Szkoda ubezpieczeniowa wymaga VIN-u i dokumentów, zwykle w zły dzień.',
          'Koszt kilometra obejmujący serwis i zakup to prawdziwa liczba; ten obejmujący samo paliwo to liczba pocieszająca.',
          'Osoba, która wie to wszystko na pamięć, kiedyś odejdzie.',
        ] },
        { h2: 'Powiązane', id: 'related' },
        { p: 'Planowany serwis mieszka obok — [Przypomnienia serwisowe](kb:maintenance) — a przebieg, który te przypomnienia liczą, wyjaśnia [Dystans a licznik](kb:distance-and-odometer).' },
      ],
    },
    de: {
      title: 'Die Fahrzeugkarte: Profil, Dokumente und Serviceheft',
      summary: 'Wo die Fakten zu einem Fahrzeug liegen — Marke, FIN, Anschaffung, Papiere mit Ablaufdatum und alles, was daran gemacht wurde.',
      keywords: ['fahrzeug', 'karte', 'profil', 'fin', 'dokumente', 'versicherung', 'hauptuntersuchung', 'ablauf', 'serviceheft'],
      blocks: [
        { p: 'Der Tracker liefert die Bewegungsdaten. Die Fahrzeugkarte hält alles andere, was Sie über das Fahrzeug wissen, am selben Ort — damit niemand einen Aktenschrank öffnen muss, um eine Frage dazu zu beantworten.' },
        { h2: 'Profil', id: 'profile' },
        { p: 'Marke, Modell, Baujahr, FIN, Kraftstoffart, Status, Kaufdatum und Kaufpreis sowie der zugeordnete Fahrer. Erst die Kauffelder machen Kilometerkosten aussagekräftig: Ohne sie haben Sie Betriebskosten und kein Kapital.' },
        { h2: 'Dokumente', id: 'documents' },
        { p: 'Versicherung, Prüfbescheinigungen, Genehmigungen, Leasingverträge — jeweils mit Art, Nummer und Gültigkeitsdatum. Die Karte zeigt die verbleibenden Tage, und ein abgelaufenes Dokument erscheint als überfällig, statt still von der Liste zu fallen.' },
        { callout: 'tip', p: 'Ablaufende Dokumente werden auch flottenweit gesammelt, sodass eine einzige Ansicht die Frage „was läuft diesen Monat ab“ beantwortet — genau die Frage, die sonst eine Straßenkontrolle beantwortet.' },
        { h2: 'Serviceheft', id: 'service' },
        { p: 'Alles, was am Fahrzeug gemacht wurde, mit Datum, Kilometer- oder Motorstundenstand, Kosten und Werkstatt. Einträge entstehen automatisch, wenn eine Wartungserinnerung als erledigt markiert wird, und lassen sich von Hand für ungeplante Arbeiten ergänzen.' },
        { p: 'Die Gesamtkosten werden für Sie summiert. Über ein paar Jahre ist diese Summe neben Kaufpreis und Laufleistung die Zahl, die entscheidet, ob ein Fahrzeug bleibt oder ersetzt wird.' },
        { h2: 'Warum ausfüllen', id: 'why' },
        { ul: [
          'Ein verkauftes Fahrzeug ist eines, dessen Verlauf Sie übergeben können.',
          'Ein Versicherungsfall fragt nach FIN und Dokumenten, meist an einem schlechten Tag.',
          'Kilometerkosten mit Service und Anschaffung sind eine echte Zahl; solche mit nur Kraftstoff eine tröstliche.',
          'Die Person, die all das auswendig weiß, geht irgendwann.',
        ] },
        { h2: 'Verwandt', id: 'related' },
        { p: 'Geplante Wartung wohnt nebenan in [Wartungserinnerungen](kb:maintenance), und die Laufleistung, die diese Erinnerungen zählen, erklärt [Strecke und Kilometerstand](kb:distance-and-odometer).' },
      ],
    },
  },
}
