import type { KbArticle } from '../types.js'

export const webhooks: KbArticle = {
  slug: 'webhooks',
  category: 'integrations',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true, entitlement: 'webhooks' },
  screen: '/app/webhooks',
  doc: {
    en: {
      title: 'Webhooks — events pushed to your system',
      summary: 'Registering an endpoint, verifying the signature, handling retries, and why you must not trust an unverified payload.',
      keywords: ['webhook', 'push', 'event', 'signature', 'hmac', 'retry', 'idempotency', 'endpoint', 'integration'],
      blocks: [
        { p: 'A webhook is an HTTPS address of yours that we call the moment something happens. It replaces polling: instead of asking every minute whether anything is new, you are told.' },
        { h2: 'Setting one up', id: 'setup' },
        { ol: [
          'Create the webhook with your endpoint URL. It must be HTTPS — a signature proves who sent a payload, it does not hide what is in it.',
          'Choose which event kinds you want. Select none and you receive them all.',
          'Copy the signing secret. Like an API key, it is shown once and cannot be retrieved afterwards.',
        ] },
        { h2: 'What a delivery looks like', id: 'payload' },
        { code: '{\n  "kind": "geofence",\n  "deviceId": "<device-id>",\n  "at": "2026-09-03T09:41:12Z",\n  "payload": { "geofenceId": "<geofence-id>", "name": "Depot", "transition": "exit" }\n}' },
        { p: 'Two headers travel with it:' },
        { ul: [
          '`X-Signature` — `sha256=<hex>`, an HMAC-SHA256 of the exact body bytes, using your signing secret.',
          '`X-Webhook-Id` — a stable identifier for this event, for idempotency.',
        ] },
        { h2: 'Verify before you trust', id: 'verify' },
        { callout: 'warning', p: 'Your endpoint is on the public internet, and anyone who finds the URL can post to it. Compute the HMAC over the **raw body bytes** and compare it with `X-Signature` before doing anything with the content. A webhook handler that acts on an unverified payload is an open door with your name on it.' },
        { p: 'Use a constant-time comparison, and read the raw body before any JSON parsing — a framework that re-serialises the body will produce a different byte sequence and a signature that never matches.' },
        { h2: 'Retries and idempotency', id: 'retries' },
        { p: 'A delivery that fails — a non-2xx response, a timeout, a dropped connection — is retried with exponential backoff. That means the same event can arrive more than once, which is the correct trade-off: better twice than never.' },
        { p: 'Use `X-Webhook-Id` as an idempotency key. Record the ones you have processed and ignore repeats. This is the single most common thing missing from a webhook integration.' },
        { h2: 'Answer fast, work later', id: 'fast' },
        { p: 'Return 2xx as soon as you have stored the delivery, and do the real work afterwards in your own queue. An endpoint that takes ten seconds to think will time out and be retried, and then you have both a slow integration and duplicate deliveries.' },
        { h2: 'Watching it work', id: 'monitor' },
        { p: 'The webhook page lists recent deliveries with their response status, so a failing endpoint is visible here rather than only in your own logs. A webhook can also be disabled without deleting it — useful while you are deploying a change to the receiver.' },
        { h2: 'Event kinds', id: 'kinds' },
        { p: 'The same nine kinds a rule can watch for. See [Every event type](kb:event-types).' },
      ],
    },
    lt: {
      title: 'Webhook\'ai — įvykiai, siunčiami į jūsų sistemą',
      summary: 'Adreso registravimas, parašo tikrinimas, kartojimų tvarkymas ir kodėl nepatikrintu turiniu pasitikėti negalima.',
      keywords: ['webhook', 'įvykis', 'parašas', 'hmac', 'kartojimas', 'idempotencija', 'integracija'],
      blocks: [
        { p: 'Webhook – tai jūsų HTTPS adresas, kurį iškviečiame tą pačią akimirką, kai kas nors nutinka. Jis pakeičia apklausą: užuot kas minutę klausę, ar yra kas nauja, sulaukiate pranešimo.' },
        { h2: 'Kaip nustatyti', id: 'setup' },
        { ol: [
          'Sukurkite webhook\'ą su savo galinio taško adresu. Jis privalo būti HTTPS – parašas įrodo, kas siuntinį atsiuntė, bet neslepia, kas jame yra.',
          'Pasirinkite, kokių įvykių tipų norite. Nepasirinkus nė vieno, gaunami visi.',
          'Nukopijuokite pasirašymo raktą. Kaip ir API raktas, jis parodomas vieną kartą ir vėliau neatgaunamas.',
        ] },
        { h2: 'Kaip atrodo pristatymas', id: 'payload' },
        { code: '{\n  "kind": "geofence",\n  "deviceId": "<device-id>",\n  "at": "2026-09-03T09:41:12Z",\n  "payload": { "geofenceId": "<geofence-id>", "name": "Depot", "transition": "exit" }\n}' },
        { p: 'Kartu keliauja dvi antraštės:' },
        { ul: [
          '`X-Signature` – `sha256=<hex>`, tikslių turinio baitų HMAC-SHA256 su jūsų pasirašymo raktu.',
          '`X-Webhook-Id` – pastovus šio įvykio identifikatorius idempotencijai.',
        ] },
        { h2: 'Pirma patikrinkite, tada pasitikėkite', id: 'verify' },
        { callout: 'warning', p: 'Jūsų galinis taškas yra viešame internete, ir bet kas, radęs adresą, gali į jį siųsti užklausas. Prieš ką nors darydami su turiniu, apskaičiuokite HMAC nuo **neapdorotų turinio baitų** ir palyginkite su `X-Signature`. Webhook\'o apdorojiklis, veikiantis pagal nepatikrintą turinį, yra atviros durys su jūsų vardu.' },
        { p: 'Palyginimą atlikite pastovaus laiko metodu ir skaitykite neapdorotą turinį prieš bet kokį JSON apdorojimą – karkasas, kuris turinį serializuoja iš naujo, duos kitą baitų seką ir parašą, kuris niekada nesutaps.' },
        { h2: 'Kartojimai ir idempotencija', id: 'retries' },
        { p: 'Nepavykęs pristatymas – ne 2xx atsakymas, laiko limitas, nutrūkęs ryšys – kartojamas didėjančiais intervalais. Tai reiškia, kad tas pats įvykis gali atkeliauti daugiau nei kartą, ir tai teisingas kompromisas: geriau du kartus nei niekada.' },
        { p: 'Naudokite `X-Webhook-Id` kaip idempotencijos raktą. Įsirašykite, ką jau apdorojote, ir pakartojimus ignoruokite. Kaip tik šito webhook\'o integracijose trūksta dažniausiai.' },
        { h2: 'Atsakykite greitai, dirbkite vėliau', id: 'fast' },
        { p: 'Grąžinkite 2xx, vos tik įrašėte pristatymą, o tikrą darbą atlikite paskui savo eilėje. Galinis taškas, kuris mąsto dešimt sekundžių, viršys laiko limitą, ir pristatymas bus pakartotas – tada turėsite ir lėtą integraciją, ir dubliuotus pristatymus.' },
        { h2: 'Kaip stebėti', id: 'monitor' },
        { p: 'Webhook\'ų puslapis rodo pastaruosius pristatymus su jų atsakymo būsena, tad neveikiantis galinis taškas matomas čia, o ne tik jūsų žurnaluose. Webhook\'ą galima ir išjungti jo netrinant – patogu, kol diegiate gavėjo pakeitimą.' },
        { h2: 'Įvykių tipai', id: 'kinds' },
        { p: 'Tie patys devyni tipai, kuriuos gali stebėti taisyklė. Žr. [Visi įvykių tipai](kb:event-types).' },
      ],
    },
    pl: {
      title: 'Webhooki — zdarzenia wypychane do Twojego systemu',
      summary: 'Rejestracja punktu końcowego, weryfikacja podpisu, obsługa ponowień i dlaczego nie wolno ufać niezweryfikowanej treści.',
      keywords: ['webhook', 'zdarzenie', 'podpis', 'hmac', 'ponowienie', 'idempotencja', 'punkt końcowy', 'integracja'],
      blocks: [
        { p: 'Webhook to Twój adres HTTPS, który wywołujemy w chwili, gdy coś się dzieje. Zastępuje odpytywanie: zamiast pytać co minutę, czy jest coś nowego, dostajesz informację.' },
        { h2: 'Konfiguracja', id: 'setup' },
        { ol: [
          'Utwórz webhook z adresem swojego punktu końcowego. Musi być HTTPS — podpis dowodzi, kto wysłał ładunek, ale nie ukrywa jego treści.',
          'Wybierz rodzaje zdarzeń, które chcesz. Nie wybierając żadnego, dostajesz wszystkie.',
          'Skopiuj sekret podpisu. Jak klucz API, pokazuje się raz i później nie da się go odzyskać.',
        ] },
        { h2: 'Jak wygląda dostarczenie', id: 'payload' },
        { code: '{\n  "kind": "geofence",\n  "deviceId": "<device-id>",\n  "at": "2026-09-03T09:41:12Z",\n  "payload": { "geofenceId": "<geofence-id>", "name": "Depot", "transition": "exit" }\n}' },
        { p: 'Towarzyszą mu dwa nagłówki:' },
        { ul: [
          '`X-Signature` — `sha256=<hex>`, HMAC-SHA256 dokładnych bajtów treści z użyciem Twojego sekretu.',
          '`X-Webhook-Id` — stabilny identyfikator tego zdarzenia, do idempotencji.',
        ] },
        { h2: 'Najpierw zweryfikuj, potem ufaj', id: 'verify' },
        { callout: 'warning', p: 'Twój punkt końcowy jest w publicznym internecie i każdy, kto pozna adres, może na niego wysyłać. Zanim cokolwiek zrobisz z treścią, policz HMAC z **surowych bajtów treści** i porównaj z `X-Signature`. Handler webhooka działający na niezweryfikowanej treści to otwarte drzwi z Twoim nazwiskiem.' },
        { p: 'Porównuj metodą o stałym czasie i czytaj surową treść przed jakimkolwiek parsowaniem JSON — framework, który serializuje treść na nowo, wyprodukuje inną sekwencję bajtów i podpis, który nigdy nie pasuje.' },
        { h2: 'Ponowienia i idempotencja', id: 'retries' },
        { p: 'Nieudane dostarczenie — odpowiedź spoza 2xx, timeout, zerwane połączenie — jest ponawiane z rosnącym odstępem. To znaczy, że to samo zdarzenie może przyjść więcej niż raz, i jest to właściwy kompromis: lepiej dwa razy niż nigdy.' },
        { p: 'Użyj `X-Webhook-Id` jako klucza idempotencji. Zapisuj przetworzone identyfikatory i ignoruj powtórki. To najczęściej brakujący element w integracjach webhookowych.' },
        { h2: 'Odpowiadaj szybko, pracuj później', id: 'fast' },
        { p: 'Zwróć 2xx, gdy tylko zapiszesz dostarczenie, a właściwą pracę wykonaj potem we własnej kolejce. Punkt końcowy myślący dziesięć sekund przekroczy timeout i zostanie ponowiony — a wtedy masz i wolną integrację, i duplikaty.' },
        { h2: 'Obserwowanie', id: 'monitor' },
        { p: 'Strona webhooków wypisuje ostatnie dostarczenia wraz ze statusem odpowiedzi, więc punkt końcowy, który zawodzi widać tutaj, a nie tylko we własnych logach. Webhook można też wyłączyć bez usuwania — przydatne podczas wdrażania zmiany w usłudze odbierającej.' },
        { h2: 'Rodzaje zdarzeń', id: 'kinds' },
        { p: 'Te same dziewięć rodzajów, których może pilnować reguła. Zobacz [Wszystkie rodzaje zdarzeń](kb:event-types).' },
      ],
    },
    de: {
      title: 'Webhooks — Ereignisse in Ihr System geschoben',
      summary: 'Endpunkt registrieren, Signatur prüfen, Wiederholungen behandeln — und warum Sie einer ungeprüften Nutzlast nicht trauen dürfen.',
      keywords: ['webhook', 'ereignis', 'signatur', 'hmac', 'wiederholung', 'idempotenz', 'endpunkt', 'integration'],
      blocks: [
        { p: 'Ein Webhook ist eine HTTPS-Adresse von Ihnen, die wir in dem Moment aufrufen, in dem etwas passiert. Er ersetzt das Polling: Statt jede Minute zu fragen, ob es Neues gibt, werden Sie informiert.' },
        { h2: 'Einrichten', id: 'setup' },
        { ol: [
          'Webhook mit der URL Ihres Endpunkts anlegen. Sie muss HTTPS sein — eine Signatur belegt, wer die Nutzlast geschickt hat, sie verbirgt aber nicht, was darin steht.',
          'Ereignisarten wählen. Wählen Sie keine, erhalten Sie alle.',
          'Das Signaturschlüssel kopieren. Wie ein API-Schlüssel wird es einmal angezeigt und ist danach nicht mehr abrufbar.',
        ] },
        { h2: 'Wie eine Zustellung aussieht', id: 'payload' },
        { code: '{\n  "kind": "geofence",\n  "deviceId": "<device-id>",\n  "at": "2026-09-03T09:41:12Z",\n  "payload": { "geofenceId": "<geofence-id>", "name": "Depot", "transition": "exit" }\n}' },
        { p: 'Zwei Header werden mitgeschickt:' },
        { ul: [
          '`X-Signature` — `sha256=<hex>`, ein HMAC-SHA256 über die exakten Body-Bytes mit Ihrem Signaturschlüssel.',
          '`X-Webhook-Id` — eine stabile Kennung dieses Ereignisses, für Idempotenz.',
        ] },
        { h2: 'Erst prüfen, dann vertrauen', id: 'verify' },
        { callout: 'warning', p: 'Ihr Endpunkt steht im öffentlichen Internet, und wer die URL findet, kann Anfragen an ihn schicken. Berechnen Sie den HMAC über die **rohen Body-Bytes** und vergleichen Sie ihn mit `X-Signature`, bevor Sie mit dem Inhalt irgendetwas tun. Ein Webhook-Handler, der auf ungeprüfte Nutzlast reagiert, ist eine offene Tür, an der Ihr Name steht.' },
        { p: 'Vergleichen Sie beide Werte in konstanter Zeit und lesen Sie den rohen Body vor jedem JSON-Parsing — ein Framework, das den Body neu serialisiert, erzeugt eine andere Bytefolge und eine Signatur, die nie passt.' },
        { h2: 'Wiederholungen und Idempotenz', id: 'retries' },
        { p: 'Eine fehlgeschlagene Zustellung — eine Antwort außerhalb des 2xx-Bereichs, ein Timeout, eine abgebrochene Verbindung — wird mit exponentiell wachsendem Abstand wiederholt. Dasselbe Ereignis kann also mehr als einmal ankommen, und das ist der richtige Kompromiss: lieber zweimal als nie.' },
        { p: 'Nutzen Sie `X-Webhook-Id` als Idempotenzschlüssel. Speichern Sie die bereits verarbeiteten IDs und ignorieren Sie Wiederholungen. Das ist das, was in Webhook-Integrationen am häufigsten fehlt.' },
        { h2: 'Schnell antworten, später arbeiten', id: 'fast' },
        { p: 'Geben Sie 2xx zurück, sobald Sie die Zustellung gespeichert haben, und erledigen Sie die eigentliche Arbeit danach in Ihrer eigenen Warteschlange. Ein Endpunkt, der zehn Sekunden nachdenkt, läuft in einen Timeout und wird wiederholt — dann haben Sie eine langsame Integration und Dubletten.' },
        { h2: 'Im Blick behalten', id: 'monitor' },
        { p: 'Die Webhook-Seite listet die jüngsten Zustellungen mit ihrem Antwortstatus, ein ausfallender Endpunkt ist also hier sichtbar und nicht nur in Ihren eigenen Logs. Ein Webhook lässt sich auch deaktivieren, statt ihn zu löschen — praktisch, während Sie eine Änderung am Empfänger ausrollen.' },
        { h2: 'Ereignisarten', id: 'kinds' },
        { p: 'Dieselben neun Arten, auf die eine Regel achten kann. Siehe [Alle Ereignistypen](kb:event-types).' },
      ],
    },
  },
}
