import type { KbArticle } from '../types.js'

export const whereYourDataLives: KbArticle = {
  slug: 'where-your-data-lives',
  category: 'trust',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'Where your data lives and how long it stays',
      summary: 'Storage location, retention windows, who can reach your data, and the separation between accounts.',
      keywords: ['data', 'storage', 'eu', 'retention', 'gdpr', 'security', 'isolation', 'backup', 'how long'],
      blocks: [
        { p: 'Vehicle tracking data says where your business was, hour by hour. Knowing where it is kept and for how long is a reasonable thing to ask before you rely on it.' },
        { h2: 'Where it is stored', id: 'where' },
        { p: 'Application data and telemetry are stored in the European Union. Where a supporting service handles limited metadata outside the EEA, those transfers are covered by the EU Standard Contractual Clauses. The full list of processors and what each of them touches is published and kept current — the data-protection documents on the public site are the authoritative version.' },
        { h2: 'How long it is kept', id: 'retention' },
        { table: { head: ['Data', 'Kept for'], rows: [
          ['**Raw positions**', 'Thirteen months. Long enough for a full year-on-year comparison, which is the longest window anyone actually needs.'],
          ['**Trips and events**', 'Events and a trip\'s route follow the positions they are derived from. A trip\'s summary — when, how far, how fast — is kept beyond that, so a year-on-year comparison still works after the route itself is gone.'],
          ['**Audit log**', 'For as long as the account exists. It is append-only and nothing prunes it — a record of who changed what is only worth anything if it cannot be shortened.'],
          ['**Data exports**', 'Seven days from the moment they are generated, then removed.'],
        ] } },
        { p: 'Retention runs continuously rather than as an annual clear-out, so the limit is real rather than a promise to tidy up one day.' },
        { h2: 'Who can see it', id: 'access' },
        { ul: [
          '**People you gave a login to**, within the account and role you chose for them — see [Logins and roles](kb:logins-and-roles).',
          '**Nobody in another account.** The boundary is enforced on every request. There is no query, report, export or API key that reaches across it.',
          '**Nobody through a share link, beyond the single vehicle it shows**, for the limited time you chose — see [Sharing a live link](kb:share-a-live-link).',
        ] },
        { h2: 'What is not done with it', id: 'never' },
        { p: 'Your data is not sold, not shared with advertisers, and not used to build a product for someone else. It is yours: you can export all of it at any time, and you can have it erased — see [Exporting and erasing your data](kb:export-and-erase-data).' },
        { h2: 'Continuity', id: 'backup' },
        { p: 'The database is backed up continuously, and the backups are verified rather than assumed. Trackers also hold their own recent records, which is a second layer: a device that cannot deliver keeps its data and sends it when it can.' },
        { h2: 'The formal documents', id: 'legal' },
        { p: 'The privacy notice, the data-processing agreement and the sub-processor list are published on the public site and are the version that counts. This article is a plain-language summary, not a substitute for them.' },
      ],
    },
    lt: {
      title: 'Kur laikomi jūsų duomenys ir kiek laiko',
      summary: 'Saugojimo vieta, saugojimo terminai, kas gali duomenis pasiekti ir kaip atskiriamos paskyros.',
      keywords: ['duomenys', 'saugojimas', 'es', 'terminas', 'bdar', 'saugumas', 'izoliacija', 'kopijos', 'kiek laiko'],
      blocks: [
        { p: 'Automobilių sekimo duomenys pasakoja, kur jūsų verslas buvo valanda po valandos. Prieš jais pasikliaujant, visiškai protinga paklausti, kur jie laikomi ir kiek laiko.' },
        { h2: 'Kur laikoma', id: 'where' },
        { p: 'Programos duomenys ir telemetrija saugomi Europos Sąjungoje. Kai pagalbinė paslauga tvarko ribotus metaduomenis už EEE ribų, tokiems perdavimams taikomos ES standartinės sutarčių sąlygos. Visas tvarkytojų sąrašas ir tai, prie kokių duomenų kiekvienas iš jų prieina, skelbiamas ir nuolat atnaujinamas – oficiali versija yra duomenų apsaugos dokumentai viešoje svetainėje.' },
        { h2: 'Kiek laiko saugoma', id: 'retention' },
        { table: { head: ['Duomenys', 'Saugoma'], rows: [
          ['**Neapdorotos pozicijos**', 'Trylika mėnesių. Pakanka išsamiam palyginimui su praėjusiais metais – ilgiausiam laikotarpiui, kurio kam nors iš tikrųjų reikia.'],
          ['**Kelionės ir įvykiai**', 'Įvykiai ir kelionės maršrutas saugomi tiek pat, kiek pozicijos, iš kurių išvesti. Kelionės santrauka – kada, kiek nuvažiuota, kaip greitai – lieka ir po to, tad palyginimas su praėjusiais metais veikia ir dingus pačiam maršrutui.'],
          ['**Audito žurnalas**', 'Tol, kol egzistuoja paskyra. Jis tik papildomas, niekada netrumpinamas – įrašas, kas ką pakeitė, ko nors vertas tik tada, kai jo negalima sutrumpinti.'],
          ['**Duomenų eksportai**', 'Septynios dienos nuo sugeneravimo, paskui pašalinami.'],
        ] } },
        { p: 'Valymas vyksta nuolat, o ne kartą per metus, tad terminas yra tikras, o ne pažadas kada nors ateityje.' },
        { h2: 'Kas gali matyti', id: 'access' },
        { ul: [
          '**Žmonės, kuriems davėte prisijungimą**, toje paskyroje ir su ta role, kurią jiems suteikėte – žr. [Prisijungimai ir rolės](kb:logins-and-roles).',
          '**Niekas iš kitos paskyros.** Riba užtikrinama kiekvienoje užklausoje. Nėra užklausos, ataskaitos, eksporto ar API rakto, kuris ją peržengtų.',
          '**Per bendrinimo nuorodą niekas nemato daugiau nei vieno automobilio** ir ne ilgiau, nei jūsų pasirinkta – žr. [Bendrinimo nuoroda](kb:share-a-live-link).',
        ] },
        { h2: 'Ko su jais nedaroma', id: 'never' },
        { p: 'Jūsų duomenys neparduodami, jais nesidalijama su reklamuotojais ir iš jų nekuriamas produktas kam nors kitam. Jie jūsų: bet kada galite juos visus eksportuoti arba pareikalauti, kad jie būtų ištrinti – žr. [Duomenų eksportas ir ištrynimas](kb:export-and-erase-data).' },
        { h2: 'Tęstinumas', id: 'backup' },
        { p: 'Duomenų bazė nuolat kopijuojama, o kopijos tikrinamos, o ne laikomos savaime geromis. Sekikliai taip pat laiko savo paskutinius įrašus – tai antras sluoksnis: pristatyti negalintis įrenginys duomenis pasilieka ir išsiunčia, kai gali.' },
        { h2: 'Formalūs dokumentai', id: 'legal' },
        { p: 'Privatumo pranešimas, duomenų tvarkymo sutartis ir tvarkytojų sąrašas skelbiami viešoje svetainėje ir yra ta versija, kuri galioja. Šis straipsnis – paprastos kalbos santrauka, o ne jų pakaitalas.' },
      ],
    },
    pl: {
      title: 'Gdzie są Twoje dane i jak długo tam zostają',
      summary: 'Miejsce przechowywania, okresy retencji, kto ma dostęp i jak rozdzielone są konta.',
      keywords: ['dane', 'przechowywanie', 'ue', 'retencja', 'rodo', 'bezpieczeństwo', 'izolacja', 'kopie', 'jak długo'],
      blocks: [
        { p: 'Dane z monitoringu pojazdów mówią, gdzie Twoja firma była, godzina po godzinie. Zanim się na nich oprzesz, całkiem rozsądnie jest zapytać, gdzie i jak długo są trzymane.' },
        { h2: 'Gdzie są przechowywane', id: 'where' },
        { p: 'Dane aplikacji i telemetria są przechowywane w Unii Europejskiej. Gdy usługa pomocnicza przetwarza ograniczone metadane poza EOG, takie transfery są objęte standardowymi klauzulami umownymi UE. Pełna lista podmiotów przetwarzających i tego, do czego każdy z nich ma dostęp, jest publikowana i aktualizowana — wersją wiążącą są dokumenty ochrony danych na stronie publicznej.' },
        { h2: 'Jak długo są trzymane', id: 'retention' },
        { table: { head: ['Dane', 'Trzymane przez'], rows: [
          ['**Surowe pozycje**', 'Trzynaście miesięcy. Dość na pełne porównanie rok do roku, czyli najdłuższe okno, jakiego ktokolwiek naprawdę potrzebuje.'],
          ['**Trasy i zdarzenia**', 'Zdarzenia i przebieg trasy są trzymane tak długo jak pozycje, z których powstały. Podsumowanie trasy — kiedy, ile kilometrów, jak szybko — zostaje dłużej, więc porównanie rok do roku działa także wtedy, gdy sam przebieg już zniknął.'],
          ['**Dziennik audytu**', 'Tak długo, jak istnieje konto. Jest tylko dopisywany i nic go nie skraca — zapis tego, kto co zmienił, jest coś wart tylko wtedy, gdy nie da się go skrócić.'],
          ['**Eksporty danych**', 'Siedem dni od wygenerowania, potem usuwane.'],
        ] } },
        { p: 'Czyszczenie działa w sposób ciągły, a nie raz do roku, więc horyzont jest realny, a nie obietnicą na kiedyś.' },
        { h2: 'Kto może je zobaczyć', id: 'access' },
        { ul: [
          '**Osoby, którym dałeś login**, na koncie i roli, jakie im nadałeś — zobacz [Loginy i role](kb:logins-and-roles).',
          '**Nikt z innego konta.** Granica jest egzekwowana przy każdym żądaniu. Nie ma zapytania, raportu, eksportu ani klucza API, który by ją przekroczył.',
          '**Nikt przez link udostępniania — poza jednym pojazdem**, i tylko przez wybrany przez Ciebie czas — zobacz [Link udostępniania](kb:share-a-live-link).',
        ] },
        { h2: 'Czego się z nimi nie robi', id: 'never' },
        { p: 'Twoje dane nie są sprzedawane, nie są udostępniane reklamodawcom i nie służą do budowy produktu dla kogoś innego. Są Twoje: w każdej chwili możesz je wyeksportować i w każdej chwili możesz zażądać ich usunięcia — zobacz [Eksport i usuwanie danych](kb:export-and-erase-data).' },
        { h2: 'Ciągłość', id: 'backup' },
        { p: 'Baza danych jest kopiowana w sposób ciągły, a kopie są weryfikowane, a nie przyjmowane na wiarę. Lokalizatory trzymają też własne ostatnie zapisy — to druga warstwa: urządzenie, które nie może dostarczyć, zachowuje dane i wysyła je, gdy może.' },
        { h2: 'Dokumenty formalne', id: 'legal' },
        { p: 'Polityka prywatności, umowa powierzenia i lista podmiotów podprzetwarzających są opublikowane na stronie publicznej i to one się liczą. Ten artykuł jest streszczeniem prostym językiem, a nie ich zamiennikiem.' },
      ],
    },
    de: {
      title: 'Wo Ihre Daten liegen und wie lange sie bleiben',
      summary: 'Speicherort, Aufbewahrungsfristen, wer Zugriff hat und wie Konten getrennt sind.',
      keywords: ['daten', 'speicherung', 'eu', 'aufbewahrung', 'dsgvo', 'sicherheit', 'trennung', 'backup', 'wie lange'],
      blocks: [
        { p: 'Ortungsdaten sagen, wo Ihr Betrieb Stunde für Stunde war. Zu fragen, wo sie liegen und wie lange, ist eine vernünftige Frage, bevor Sie sich darauf verlassen.' },
        { h2: 'Wo sie liegen', id: 'where' },
        { p: 'Anwendungsdaten und Telemetrie werden in der Europäischen Union gespeichert. Verarbeitet ein unterstützender Dienst begrenzte Metadaten außerhalb des EWR, sind diese Übermittlungen durch die EU-Standardvertragsklauseln abgedeckt. Die vollständige Liste der Auftragsverarbeiter und dessen, was jeder von ihnen berührt, wird veröffentlicht und aktuell gehalten — maßgeblich sind die Datenschutzdokumente auf der öffentlichen Website.' },
        { h2: 'Wie lange sie bleiben', id: 'retention' },
        { table: { head: ['Daten', 'Aufbewahrt'], rows: [
          ['**Rohpositionen**', 'Dreizehn Monate. Genug für einen vollständigen Jahresvergleich — das längste Fenster, das wirklich jemand braucht.'],
          ['**Fahrten und Ereignisse**', 'Ereignisse und der Streckenverlauf einer Fahrt werden so lange aufbewahrt wie die Positionen, aus denen sie stammen. Die Zusammenfassung einer Fahrt — wann, wie weit, wie schnell — bleibt darüber hinaus erhalten, sodass ein Jahresvergleich auch dann noch funktioniert, wenn die Strecke selbst weg ist.'],
          ['**Audit-Log**', 'So lange, wie das Konto besteht. Es wird nur ergänzt und von nichts gekürzt — ein Nachweis darüber, wer was geändert hat, ist nur dann etwas wert, wenn er sich nicht kürzen lässt.'],
          ['**Datenexporte**', 'Sieben Tage ab Erstellung, danach entfernt.'],
        ] } },
        { p: 'Die Bereinigung läuft fortlaufend statt als jährliche Aufräumaktion — der Horizont ist real und kein Versprechen für irgendwann.' },
        { h2: 'Wer sie sehen kann', id: 'access' },
        { ul: [
          '**Personen, denen Sie einen Zugang gegeben haben**, im Konto und in der Rolle, die Sie vergeben haben — siehe [Zugänge und Rollen](kb:logins-and-roles).',
          '**Niemand aus einem anderen Konto.** Die Grenze wird bei jeder Anfrage durchgesetzt. Es gibt keine Abfrage, keinen Bericht, keinen Export und keine API-Schlüssel, die darüber hinausreichen.',
          '**Niemand über einen Freigabelink über ein Fahrzeug hinaus**, und nur für die von Ihnen gewählte Dauer — siehe [Freigabelink](kb:share-a-live-link).',
        ] },
        { h2: 'Was damit nicht geschieht', id: 'never' },
        { p: 'Ihre Daten werden nicht verkauft, nicht an Werbetreibende weitergegeben und nicht genutzt, um ein Produkt für jemand anderen zu bauen. Sie gehören Ihnen: Sie können sie jederzeit vollständig exportieren und jederzeit löschen lassen — siehe [Daten exportieren und löschen](kb:export-and-erase-data).' },
        { h2: 'Fortbestand', id: 'backup' },
        { p: 'Die Datenbank wird fortlaufend gesichert, und die Sicherungen werden geprüft statt angenommen. Auch die Tracker speichern ihre jüngsten Datensätze — eine zweite Schicht: Ein Gerät, das nicht zustellen kann, behält seine Daten und sendet sie, sobald es geht.' },
        { h2: 'Die formalen Dokumente', id: 'legal' },
        { p: 'Datenschutzhinweis, Auftragsverarbeitungsvertrag und Unterauftragsverarbeiterliste sind auf der öffentlichen Website veröffentlicht und sind die maßgebliche Fassung. Dieser Artikel ist eine Zusammenfassung in verständlicher Sprache, kein Ersatz dafür.' },
      ],
    },
  },
}
