import type { KbArticle } from '../types.js'

export const whereYourDataLives: KbArticle = {
  slug: 'where-your-data-lives',
  category: 'trust',
  surfaces: { site: true, app: true },
  doc: {
    en: {
      title: 'Where your data lives and how long it stays',
      summary: 'Storage location, retention windows, who can reach your data, and the separation between accounts.',
      keywords: ['data', 'storage', 'eu', 'retention', 'gdpr', 'security', 'isolation', 'backup', 'how long'],
      blocks: [
        { p: 'Vehicle tracking data says where your business was, hour by hour. Knowing where it is kept and for how long is a reasonable thing to ask before you rely on it.' },
        { h2: 'Where it is stored', id: 'where' },
        { p: 'Application data and telemetry are stored in the European Union. Where a supporting service handles limited metadata outside the EEA, those transfers are covered by the EU Standard Contractual Clauses. The full list of processors and what each of them touches is published and kept current — the data-protection documents on the public site are the authoritative version.' },
        { h2: 'How long it is kept', id: 'retention' },
        { table: { head: ['Data', 'Kept for'], rows: [
          ['**Raw positions**', 'Thirteen months. Long enough for a full year-on-year comparison, which is the longest window anyone actually needs.'],
          ['**Trips, events and reports**', 'Derived from positions and kept alongside them.'],
          ['**Audit log**', 'Kept as the record of who changed what.'],
          ['**Data exports**', 'Seven days from the moment they are generated, then removed.'],
        ] } },
        { p: 'Retention runs continuously rather than as an annual clear-out, so the horizon is real and not a promise about someday.' },
        { h2: 'Who can see it', id: 'access' },
        { ul: [
          '**People you gave a login to**, within the account and role you gave them — see [Logins and roles](kb:logins-and-roles).',
          '**Nobody in another account.** The boundary is enforced on every request. There is no query, report, export or API key that reaches across it.',
          '**Nobody through a share link beyond one vehicle**, for the limited time you chose — see [Sharing a live link](kb:share-a-live-link).',
        ] },
        { h2: 'What is not done with it', id: 'never' },
        { p: 'Your data is not sold, not shared with advertisers, and not used to build a product for someone else. It is yours: you can export all of it at any time, and you can have it erased — see [Exporting and erasing your data](kb:export-and-erase-data).' },
        { h2: 'Continuity', id: 'backup' },
        { p: 'The database is backed up continuously, and the backups are verified rather than assumed. Trackers also hold their own recent records, which is a second layer: a device that cannot deliver keeps its data and sends it when it can.' },
        { h2: 'The formal documents', id: 'legal' },
        { p: 'The privacy notice, the data-processing agreement and the sub-processor list are published on the public website and are the version that counts. This article is a plain-language summary, not a substitute for them.' },
      ],
    },
    lt: {
      title: 'Kur laikomi jūsų duomenys ir kiek laiko',
      summary: 'Saugojimo vieta, saugojimo terminai, kas gali duomenis pasiekti ir kaip atskiriamos paskyros.',
      keywords: ['duomenys', 'saugojimas', 'es', 'terminas', 'bdar', 'saugumas', 'izoliacija', 'kopijos', 'kiek laiko'],
      blocks: [
        { p: 'Automobilių sekimo duomenys pasakoja, kur jūsų verslas buvo valanda po valandos. Prieš jais pasikliaujant visiškai protinga paklausti, kur jie laikomi ir kiek laiko.' },
        { h2: 'Kur laikoma', id: 'where' },
        { p: 'Programos duomenys ir telemetrija saugomi Europos Sąjungoje. Kai pagalbinė paslauga tvarko ribotus metaduomenis už EEE ribų, tokiems perdavimams taikomos ES standartinės sutarčių sąlygos. Visas tvarkytojų sąrašas ir tai, ką kiekvienas iš jų liečia, skelbiamas ir atnaujinamas – autoritetinga versija yra duomenų apsaugos dokumentai viešoje svetainėje.' },
        { h2: 'Kiek laiko saugoma', id: 'retention' },
        { table: { head: ['Duomenys', 'Saugoma'], rows: [
          ['**Žalios pozicijos**', 'Trylika mėnesių. Pakanka pilnam palyginimui su praėjusiais metais – ilgiausiam langui, kurio kam nors iš tikrųjų reikia.'],
          ['**Kelionės, įvykiai ir ataskaitos**', 'Išvedami iš pozicijų ir saugomi kartu su jomis.'],
          ['**Audito žurnalas**', 'Saugomas kaip įrašas, kas ką pakeitė.'],
          ['**Duomenų eksportai**', 'Septynios dienos nuo sugeneravimo, paskui pašalinami.'],
        ] } },
        { p: 'Valymas vyksta nuolat, o ne kartą per metus, tad terminas yra tikras, o ne pažadas kada nors.' },
        { h2: 'Kas gali matyti', id: 'access' },
        { ul: [
          '**Žmonės, kuriems davėte prisijungimą**, toje paskyroje ir toje rolėje, kurią suteikėte – žr. [Prisijungimai ir rolės](kb:logins-and-roles).',
          '**Niekas iš kitos paskyros.** Riba užtikrinama kiekvienoje užklausoje. Nėra užklausos, ataskaitos, eksporto ar API rakto, kuris ją peržengtų.',
          '**Niekas per dalijimosi nuorodą daugiau nei vieną automobilį** ir ilgiau nei jūsų pasirinktą laiką – žr. [Dalijimosi nuoroda](kb:share-a-live-link).',
        ] },
        { h2: 'Ko su jais nedaroma', id: 'never' },
        { p: 'Jūsų duomenys neparduodami, nedalijami su reklamuotojais ir nenaudojami kurti produktą kam nors kitam. Jie jūsų: bet kada galite juos visus eksportuoti ir bet kada galite pareikalauti juos ištrinti – žr. [Duomenų eksportas ir ištrynimas](kb:export-and-erase-data).' },
        { h2: 'Tęstinumas', id: 'backup' },
        { p: 'Duomenų bazė nuolat kopijuojama, o kopijos tikrinamos, o ne laikomos savaime geromis. Sekliai taip pat laiko savo paskutinius įrašus – tai antras sluoksnis: pristatyti negalintis įrenginys duomenis pasilieka ir išsiunčia, kai gali.' },
        { h2: 'Formalūs dokumentai', id: 'legal' },
        { p: 'Privatumo pranešimas, duomenų tvarkymo sutartis ir tvarkytojų sąrašas skelbiami viešoje svetainėje ir yra ta versija, kuri galioja. Šis straipsnis – paprastos kalbos santrauka, o ne jų pakaitalas.' },
      ],
    },
    pl: {
      title: 'Gdzie są Twoje dane i jak długo tam zostają',
      summary: 'Miejsce przechowywania, okresy retencji, kto ma dostęp i jak rozdzielone są konta.',
      keywords: ['dane', 'przechowywanie', 'ue', 'retencja', 'rodo', 'bezpieczeństwo', 'izolacja', 'kopie', 'jak długo'],
      blocks: [
        { p: 'Dane z monitoringu pojazdów mówią, gdzie Twoja firma była, godzina po godzinie. Zapytanie, gdzie i jak długo są trzymane, jest zanim się na nich oprzesz całkiem rozsądne.' },
        { h2: 'Gdzie są przechowywane', id: 'where' },
        { p: 'Dane aplikacji i telemetria są przechowywane w Unii Europejskiej. Gdy usługa pomocnicza przetwarza ograniczone metadane poza EOG, takie transfery są objęte standardowymi klauzulami umownymi UE. Pełna lista podmiotów przetwarzających i tego, czego dotyka każdy z nich, jest publikowana i aktualizowana — wersją wiążącą są dokumenty ochrony danych na stronie publicznej.' },
        { h2: 'Jak długo są trzymane', id: 'retention' },
        { table: { head: ['Dane', 'Trzymane przez'], rows: [
          ['**Surowe pozycje**', 'Trzynaście miesięcy. Dość na pełne porównanie rok do roku, czyli najdłuższe okno, jakiego ktokolwiek naprawdę potrzebuje.'],
          ['**Trasy, zdarzenia i raporty**', 'Wyprowadzane z pozycji i trzymane razem z nimi.'],
          ['**Dziennik audytu**', 'Trzymany jako zapis, kto co zmienił.'],
          ['**Eksporty danych**', 'Siedem dni od wygenerowania, potem usuwane.'],
        ] } },
        { p: 'Czyszczenie działa w sposób ciągły, a nie raz do roku, więc horyzont jest realny, a nie obietnicą na kiedyś.' },
        { h2: 'Kto może je zobaczyć', id: 'access' },
        { ul: [
          '**Osoby, którym dałeś login**, w koncie i roli, jakie im nadałeś — zobacz [Loginy i role](kb:logins-and-roles).',
          '**Nikt z innego konta.** Granica jest egzekwowana przy każdym żądaniu. Nie ma zapytania, raportu, eksportu ani klucza API, który by ją przekroczył.',
          '**Nikt przez link udostępniania poza jednym pojazdem** i poza wybranym przez Ciebie czasem — zobacz [Link udostępniania](kb:share-a-live-link).',
        ] },
        { h2: 'Czego się z nimi nie robi', id: 'never' },
        { p: 'Twoje dane nie są sprzedawane, nie są udostępniane reklamodawcom i nie służą do budowy produktu dla kogoś innego. Są Twoje: w każdej chwili możesz je wyeksportować i w każdej chwili możesz zażądać ich usunięcia — zobacz [Eksport i usuwanie danych](kb:export-and-erase-data).' },
        { h2: 'Ciągłość', id: 'backup' },
        { p: 'Baza danych jest kopiowana w sposób ciągły, a kopie są weryfikowane, a nie zakładane. Lokalizatory trzymają też własne ostatnie zapisy — to druga warstwa: urządzenie, które nie może dostarczyć, zachowuje dane i wysyła je, gdy może.' },
        { h2: 'Dokumenty formalne', id: 'legal' },
        { p: 'Informacja o prywatności, umowa powierzenia i lista podprzetwarzających są opublikowane na stronie publicznej i to one się liczą. Ten artykuł jest streszczeniem prostym językiem, a nie ich zamiennikiem.' },
      ],
    },
    de: {
      title: 'Wo Ihre Daten liegen und wie lange sie bleiben',
      summary: 'Speicherort, Aufbewahrungsfristen, wer Zugriff hat und wie Konten getrennt sind.',
      keywords: ['daten', 'speicherung', 'eu', 'aufbewahrung', 'dsgvo', 'sicherheit', 'trennung', 'backup', 'wie lange'],
      blocks: [
        { p: 'Ortungsdaten sagen, wo Ihr Betrieb Stunde für Stunde war. Zu fragen, wo sie liegen und wie lange, ist eine vernünftige Frage, bevor man sich darauf verlässt.' },
        { h2: 'Wo sie liegen', id: 'where' },
        { p: 'Anwendungsdaten und Telemetrie werden in der Europäischen Union gespeichert. Verarbeitet ein unterstützender Dienst begrenzte Metadaten außerhalb des EWR, sind diese Übermittlungen durch die EU-Standardvertragsklauseln abgedeckt. Die vollständige Liste der Verarbeiter und dessen, was jeder von ihnen berührt, wird veröffentlicht und aktuell gehalten — maßgeblich sind die Datenschutzdokumente auf der öffentlichen Website.' },
        { h2: 'Wie lange sie bleiben', id: 'retention' },
        { table: { head: ['Daten', 'Aufbewahrt'], rows: [
          ['**Rohpositionen**', 'Dreizehn Monate. Genug für einen vollständigen Jahresvergleich — das längste Fenster, das wirklich jemand braucht.'],
          ['**Fahrten, Ereignisse und Berichte**', 'Aus Positionen abgeleitet und mit ihnen aufbewahrt.'],
          ['**Audit-Log**', 'Bleibt als Nachweis, wer was geändert hat.'],
          ['**Datenexporte**', 'Sieben Tage ab Erstellung, danach entfernt.'],
        ] } },
        { p: 'Die Bereinigung läuft fortlaufend statt als jährliche Aufräumaktion — der Horizont ist real und kein Versprechen für irgendwann.' },
        { h2: 'Wer sie sehen kann', id: 'access' },
        { ul: [
          '**Personen, denen Sie einen Zugang gegeben haben**, im Konto und in der Rolle, die Sie vergeben haben — siehe [Zugänge und Rollen](kb:logins-and-roles).',
          '**Niemand aus einem anderen Konto.** Die Grenze wird bei jeder Anfrage durchgesetzt. Es gibt keine Abfrage, keinen Bericht, keinen Export und keinen API-Schlüssel, der darüber hinausreicht.',
          '**Niemand über einen Freigabelink über ein Fahrzeug hinaus**, und nur für die von Ihnen gewählte Dauer — siehe [Freigabelink](kb:share-a-live-link).',
        ] },
        { h2: 'Was damit nicht geschieht', id: 'never' },
        { p: 'Ihre Daten werden nicht verkauft, nicht an Werbetreibende weitergegeben und nicht genutzt, um ein Produkt für jemand anderen zu bauen. Sie gehören Ihnen: Sie können sie jederzeit vollständig exportieren und jederzeit löschen lassen — siehe [Daten exportieren und löschen](kb:export-and-erase-data).' },
        { h2: 'Fortbestand', id: 'backup' },
        { p: 'Die Datenbank wird fortlaufend gesichert, und die Sicherungen werden geprüft statt angenommen. Auch die Tracker halten ihre jüngsten Datensätze — eine zweite Schicht: ein Gerät, das nicht zustellen kann, behält seine Daten und sendet sie, sobald es geht.' },
        { h2: 'Die formalen Dokumente', id: 'legal' },
        { p: 'Datenschutzhinweis, Auftragsverarbeitungsvertrag und Unterauftragsverarbeiterliste sind auf der öffentlichen Website veröffentlicht und sind die maßgebliche Fassung. Dieser Artikel ist eine Zusammenfassung in Klartext, kein Ersatz dafür.' },
      ],
    },
  },
}
