import type { KbArticle } from '../types.js'

export const whiteLabelExplained: KbArticle = {
  slug: 'white-label-explained',
  category: 'tsp',
  surfaces: { site: true, app: true },
  audience: { adminOnly: true },
  doc: {
    en: {
      title: 'What white-label actually means here',
      summary: 'Which parts of the product carry your brand, which parts your customers never see, and what you are responsible for.',
      keywords: ['white label', 'reseller', 'tsp', 'brand', 'own product', 'customers', 'partner'],
      blocks: [
        { p: 'White-label means your customers use this platform as **your** product. They sign in on your domain, see your name and colours, receive mail with your name on it, and never encounter the platform behind it.' },
        { h2: 'What your customers see', id: 'see' },
        { ul: [
          'Your domain in the address bar, with its own certificate — see [Your own domain](kb:custom-domain).',
          'Your logo in the sidebar and on the sign-in page, your colours throughout, your icon in the browser tab.',
          'Your product name in the tab title and in the messages the platform sends.',
          'Your support address as the reply address on every notification.',
        ] },
        { h2: 'What they never see', id: 'hidden' },
        { p: 'The platform\'s own name, marks and pages are absent from a branded deployment — not hidden behind a setting, but not rendered at all. Where a piece of branding is not configured, the space stays empty rather than falling back to ours. An unset logo shows no logo.' },
        { callout: 'note', p: 'This is why the branding screen is worth ten minutes of care: on your own domain, a blank is a blank. Filling it in is what makes the product look finished to your customer.' },
        { h2: 'How the accounts fit together', id: 'structure' },
        { p: 'You have one organisation. Inside it, each of your customers gets an **account**: their own vehicles, zones, rules, reports and logins, with nothing crossing between them. You see across all of them; each customer sees only their own. See [Customer accounts](kb:customer-accounts).' },
        { h2: 'Who does what', id: 'responsibility' },
        { table: { head: ['You', 'The platform'], rows: [
          ['Sell, price and invoice your customers however you like.', 'Bills you once, for the whole organisation.'],
          ['Support your customers as their supplier.', 'Supports you.'],
          ['Choose, install and configure the hardware.', 'Speaks the trackers\' protocol and stores the data.'],
          ['Own the customer relationship and the contract.', 'Stays out of it — we never contact your customers.'],
        ] } },
        { h2: 'The first hour as a reseller', id: 'start' },
        { ol: [
          'Set your brand: name, colours, logo, favicon, support address — [Branding your dashboard](kb:branding).',
          'Add your domain and publish two DNS records — [Your own domain](kb:custom-domain).',
          'Create your first customer account and its login — [Customer accounts](kb:customer-accounts).',
          'Add their trackers and hand over the login — [Connecting a tracker](kb:connect-a-tracker).',
        ] },
      ],
    },
    lt: {
      title: 'Ką čia iš tikrųjų reiškia white-label',
      summary: 'Kurios produkto dalys nešioja jūsų prekės ženklą, ko jūsų klientai niekada nemato ir už ką atsakote jūs.',
      keywords: ['white label', 'perpardavėjas', 'tsp', 'prekės ženklas', 'savo produktas', 'klientai', 'partneris'],
      blocks: [
        { p: 'White-label reiškia, kad jūsų klientai naudoja šią platformą kaip **jūsų** produktą. Jie prisijungia jūsų domene, mato jūsų pavadinimą ir spalvas, gauna laiškus su jūsų vardu ir su platforma už jų niekada nesusiduria.' },
        { h2: 'Ką mato jūsų klientai', id: 'see' },
        { ul: [
          'Jūsų domeną adreso juostoje su savo sertifikatu – žr. [Nuosavas domenas](kb:custom-domain).',
          'Jūsų logotipą šoninėje juostoje ir prisijungimo puslapyje, jūsų spalvas visur, jūsų piktogramą naršyklės kortelėje.',
          'Jūsų produkto pavadinimą kortelės antraštėje ir platformos siunčiamose žinutėse.',
          'Jūsų pagalbos adresą kaip atsakymo adresą kiekviename pranešime.',
        ] },
        { h2: 'Ko jie nemato niekada', id: 'hidden' },
        { p: 'Pačios platformos pavadinimo, ženklų ir puslapių prekės ženklu pažymėtame diegime nėra – ne paslėpti už nustatymo, o išvis nepiešiami. Kur prekės ženklo dalis nesukonfigūruota, vieta lieka tuščia, o ne užpildoma mūsų. Nenustatytas logotipas reiškia jokio logotipo.' },
        { callout: 'note', p: 'Kaip tik todėl prekės ženklo ekranas vertas dešimties minučių dėmesio: savame domene tuščia vieta lieka tuščia. Ją užpildžius produktas jūsų klientui atrodo baigtas.' },
        { h2: 'Kaip susidėlioja paskyros', id: 'structure' },
        { p: 'Jūs turite vieną organizaciją. Joje kiekvienas jūsų klientas gauna **paskyrą**: savo automobilius, zonas, taisykles, ataskaitas ir prisijungimus, ir niekas tarp jų nepersilieja. Jūs matote visas; kiekvienas klientas – tik savo. Žr. [Klientų paskyros](kb:customer-accounts).' },
        { h2: 'Kas už ką atsako', id: 'responsibility' },
        { table: { head: ['Jūs', 'Platforma'], rows: [
          ['Parduodate, kainuojate ir sąskaitas savo klientams rašote kaip norite.', 'Sąskaitą rašo jums vieną, už visą organizaciją.'],
          ['Aptarnaujate savo klientus kaip jų tiekėjas.', 'Aptarnauja jus.'],
          ['Renkatės, montuojate ir konfigūruojate įrangą.', 'Kalba seklių protokolu ir saugo duomenis.'],
          ['Valdote santykį su klientu ir sutartį.', 'Į tai nesikiša – su jūsų klientais niekada nesusisiekiame.'],
        ] } },
        { h2: 'Pirmoji perpardavėjo valanda', id: 'start' },
        { ol: [
          'Nustatykite savo prekės ženklą: pavadinimą, spalvas, logotipą, piktogramą, pagalbos adresą – [Skydelio ženklinimas](kb:branding).',
          'Pridėkite savo domeną ir paskelbkite du DNS įrašus – [Nuosavas domenas](kb:custom-domain).',
          'Sukurkite pirmąją kliento paskyrą ir jos prisijungimą – [Klientų paskyros](kb:customer-accounts).',
          'Pridėkite jų seklius ir perduokite prisijungimą – [Seklio prijungimas](kb:connect-a-tracker).',
        ] },
      ],
    },
    pl: {
      title: 'Co tak naprawdę znaczy tu white-label',
      summary: 'Które części produktu noszą Twoją markę, czego Twoi klienci nigdy nie widzą i za co odpowiadasz.',
      keywords: ['white label', 'reseller', 'tsp', 'marka', 'własny produkt', 'klienci', 'partner'],
      blocks: [
        { p: 'White-label znaczy, że Twoi klienci używają tej platformy jako **Twojego** produktu. Logują się w Twojej domenie, widzą Twoją nazwę i kolory, dostają maile z Twoim nazwiskiem i nigdy nie natrafiają na platformę stojącą z tyłu.' },
        { h2: 'Co widzą Twoi klienci', id: 'see' },
        { ul: [
          'Twoją domenę w pasku adresu, z własnym certyfikatem — zobacz [Własna domena](kb:custom-domain).',
          'Twoje logo w pasku bocznym i na stronie logowania, Twoje kolory wszędzie, Twoją ikonę w karcie przeglądarki.',
          'Twoją nazwę produktu w tytule karty i w wiadomościach wysyłanych przez platformę.',
          'Twój adres wsparcia jako adres odpowiedzi w każdym powiadomieniu.',
        ] },
        { h2: 'Czego nigdy nie widzą', id: 'hidden' },
        { p: 'Własna nazwa, znaki i strony platformy są w brandowanej instalacji nieobecne — nie schowane za ustawieniem, tylko w ogóle nierysowane. Tam, gdzie element marki nie jest skonfigurowany, miejsce zostaje puste, a nie wypełnione naszym. Nieustawione logo oznacza brak logo.' },
        { callout: 'note', p: 'Dlatego ekran marki wart jest dziesięciu minut uwagi: we własnej domenie pustka zostaje pustką. Wypełnienie jej sprawia, że produkt wygląda dla klienta na skończony.' },
        { h2: 'Jak układają się konta', id: 'structure' },
        { p: 'Masz jedną organizację. Wewnątrz niej każdy Twój klient dostaje **konto**: własne pojazdy, strefy, reguły, raporty i loginy, bez żadnego przenikania między nimi. Ty widzisz wszystkie; każdy klient tylko swoje. Zobacz [Konta klientów](kb:customer-accounts).' },
        { h2: 'Kto za co odpowiada', id: 'responsibility' },
        { table: { head: ['Ty', 'Platforma'], rows: [
          ['Sprzedajesz, wyceniasz i fakturujesz swoich klientów, jak chcesz.', 'Wystawia jedną fakturę Tobie, za całą organizację.'],
          ['Obsługujesz swoich klientów jako ich dostawca.', 'Obsługuje Ciebie.'],
          ['Wybierasz, montujesz i konfigurujesz sprzęt.', 'Mówi protokołem lokalizatorów i przechowuje dane.'],
          ['Prowadzisz relację z klientem i umowę.', 'Trzyma się z boku — nigdy nie kontaktujemy się z Twoimi klientami.'],
        ] } },
        { h2: 'Pierwsza godzina resellera', id: 'start' },
        { ol: [
          'Ustaw markę: nazwę, kolory, logo, favikonę, adres wsparcia — [Marka panelu](kb:branding).',
          'Dodaj domenę i opublikuj dwa rekordy DNS — [Własna domena](kb:custom-domain).',
          'Utwórz pierwsze konto klienta i jego login — [Konta klientów](kb:customer-accounts).',
          'Dodaj jego lokalizatory i przekaż login — [Podłączanie lokalizatora](kb:connect-a-tracker).',
        ] },
      ],
    },
    de: {
      title: 'Was White-Label hier wirklich bedeutet',
      summary: 'Welche Teile des Produkts Ihre Marke tragen, was Ihre Kunden nie sehen und wofür Sie verantwortlich sind.',
      keywords: ['white label', 'reseller', 'tsp', 'marke', 'eigenes produkt', 'kunden', 'partner'],
      blocks: [
        { p: 'White-Label heißt: Ihre Kunden nutzen diese Plattform als **Ihr** Produkt. Sie melden sich auf Ihrer Domain an, sehen Ihren Namen und Ihre Farben, erhalten Post mit Ihrem Namen und begegnen der Plattform dahinter nie.' },
        { h2: 'Was Ihre Kunden sehen', id: 'see' },
        { ul: [
          'Ihre Domain in der Adresszeile, mit eigenem Zertifikat — siehe [Eigene Domain](kb:custom-domain).',
          'Ihr Logo in der Seitenleiste und auf der Anmeldeseite, Ihre Farben durchgehend, Ihr Icon im Browser-Tab.',
          'Ihren Produktnamen im Tab-Titel und in den Nachrichten, die die Plattform versendet.',
          'Ihre Support-Adresse als Antwortadresse jeder Benachrichtigung.',
        ] },
        { h2: 'Was sie nie sehen', id: 'hidden' },
        { p: 'Der eigene Name, die Marken und die Seiten der Plattform fehlen in einer gebrandeten Installation — nicht hinter einer Einstellung versteckt, sondern gar nicht gerendert. Wo ein Brandingelement nicht gesetzt ist, bleibt der Platz leer statt auf unseres zurückzufallen. Kein Logo gesetzt heißt kein Logo.' },
        { callout: 'note', p: 'Deshalb sind zehn sorgfältige Minuten im Branding-Bildschirm gut investiert: auf Ihrer eigenen Domain bleibt eine Lücke eine Lücke. Sie zu füllen lässt das Produkt für Ihren Kunden fertig wirken.' },
        { h2: 'Wie die Konten zusammenpassen', id: 'structure' },
        { p: 'Sie haben eine Organisation. Darin bekommt jeder Ihrer Kunden ein **Konto**: eigene Fahrzeuge, Zonen, Regeln, Berichte und Zugänge, ohne dass etwas übergreift. Sie sehen über alle hinweg; jeder Kunde nur sein eigenes. Siehe [Kundenkonten](kb:customer-accounts).' },
        { h2: 'Wer was macht', id: 'responsibility' },
        { table: { head: ['Sie', 'Die Plattform'], rows: [
          ['Verkaufen, bepreisen und fakturieren Ihre Kunden, wie Sie wollen.', 'Rechnet einmal mit Ihnen ab, für die ganze Organisation.'],
          ['Betreuen Ihre Kunden als deren Lieferant.', 'Betreut Sie.'],
          ['Wählen, montieren und konfigurieren die Hardware.', 'Spricht das Protokoll der Tracker und speichert die Daten.'],
          ['Besitzen die Kundenbeziehung und den Vertrag.', 'Hält sich heraus — wir kontaktieren Ihre Kunden nie.'],
        ] } },
        { h2: 'Die erste Stunde als Reseller', id: 'start' },
        { ol: [
          'Marke setzen: Name, Farben, Logo, Favicon, Support-Adresse — [Ihr Dashboard branden](kb:branding).',
          'Domain hinzufügen und zwei DNS-Einträge veröffentlichen — [Eigene Domain](kb:custom-domain).',
          'Erstes Kundenkonto samt Zugang anlegen — [Kundenkonten](kb:customer-accounts).',
          'Deren Tracker hinzufügen und den Zugang übergeben — [Tracker anschließen](kb:connect-a-tracker).',
        ] },
      ],
    },
  },
}
