/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TspRouteImport } from './routes/tsp'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubprocessorsRouteImport } from './routes/subprocessors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWebhooksRouteImport } from './routes/app.webhooks'
import { Route as AppTripsRouteImport } from './routes/app.trips'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRulesRouteImport } from './routes/app.rules'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppMaintenanceRouteImport } from './routes/app.maintenance'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppGeofencesRouteImport } from './routes/app.geofences'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppDriversRouteImport } from './routes/app.drivers'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppCommandsRouteImport } from './routes/app.commands'
import { Route as AppBrandingRouteImport } from './routes/app.branding'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApiKeysRouteImport } from './routes/app.api-keys'

const TspRoute = TspRouteImport.update({
  id: '/tsp',
  path: '/tsp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubprocessorsRoute = SubprocessorsRouteImport.update({
  id: '/subprocessors',
  path: '/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppGeofencesRoute = AppGeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandsRoute = AppCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandingRoute = AppBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dpa': typeof DpaRoute
  '/impressum': typeof ImpressumRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/tsp': typeof TspRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/events': typeof AppEventsRoute
  '/app/geofences': typeof AppGeofencesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/map': typeof AppMapRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rules': typeof AppRulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trips': typeof AppTripsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dpa': typeof DpaRoute
  '/impressum': typeof ImpressumRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/tsp': typeof TspRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/events': typeof AppEventsRoute
  '/app/geofences': typeof AppGeofencesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/map': typeof AppMapRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rules': typeof AppRulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trips': typeof AppTripsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dpa': typeof DpaRoute
  '/impressum': typeof ImpressumRoute
  '/pilot': typeof PilotRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/tsp': typeof TspRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/events': typeof AppEventsRoute
  '/app/geofences': typeof AppGeofencesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/map': typeof AppMapRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rules': typeof AppRulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trips': typeof AppTripsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dpa'
    | '/impressum'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/terms'
    | '/tsp'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/billing'
    | '/app/branding'
    | '/app/commands'
    | '/app/devices'
    | '/app/drivers'
    | '/app/events'
    | '/app/geofences'
    | '/app/history'
    | '/app/maintenance'
    | '/app/map'
    | '/app/notifications'
    | '/app/reports'
    | '/app/rules'
    | '/app/settings'
    | '/app/trips'
    | '/app/webhooks'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dpa'
    | '/impressum'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/terms'
    | '/tsp'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/billing'
    | '/app/branding'
    | '/app/commands'
    | '/app/devices'
    | '/app/drivers'
    | '/app/events'
    | '/app/geofences'
    | '/app/history'
    | '/app/maintenance'
    | '/app/map'
    | '/app/notifications'
    | '/app/reports'
    | '/app/rules'
    | '/app/settings'
    | '/app/trips'
    | '/app/webhooks'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dpa'
    | '/impressum'
    | '/pilot'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/terms'
    | '/tsp'
    | '/app/api-keys'
    | '/app/audit'
    | '/app/billing'
    | '/app/branding'
    | '/app/commands'
    | '/app/devices'
    | '/app/drivers'
    | '/app/events'
    | '/app/geofences'
    | '/app/history'
    | '/app/maintenance'
    | '/app/map'
    | '/app/notifications'
    | '/app/reports'
    | '/app/rules'
    | '/app/settings'
    | '/app/trips'
    | '/app/webhooks'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DpaRoute: typeof DpaRoute
  ImpressumRoute: typeof ImpressumRoute
  PilotRoute: typeof PilotRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubprocessorsRoute: typeof SubprocessorsRoute
  TermsRoute: typeof TermsRoute
  TspRoute: typeof TspRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tsp': {
      id: '/tsp'
      path: '/tsp'
      fullPath: '/tsp'
      preLoaderRoute: typeof TspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subprocessors': {
      id: '/subprocessors'
      path: '/subprocessors'
      fullPath: '/subprocessors'
      preLoaderRoute: typeof SubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trips': {
      id: '/app/trips'
      path: '/trips'
      fullPath: '/app/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rules': {
      id: '/app/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/geofences': {
      id: '/app/geofences'
      path: '/geofences'
      fullPath: '/app/geofences'
      preLoaderRoute: typeof AppGeofencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drivers': {
      id: '/app/drivers'
      path: '/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commands': {
      id: '/app/commands'
      path: '/commands'
      fullPath: '/app/commands'
      preLoaderRoute: typeof AppCommandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branding': {
      id: '/app/branding'
      path: '/branding'
      fullPath: '/app/branding'
      preLoaderRoute: typeof AppBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBrandingRoute: typeof AppBrandingRoute
  AppCommandsRoute: typeof AppCommandsRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppDriversRoute: typeof AppDriversRoute
  AppEventsRoute: typeof AppEventsRoute
  AppGeofencesRoute: typeof AppGeofencesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMapRoute: typeof AppMapRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTripsRoute: typeof AppTripsRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppBrandingRoute: AppBrandingRoute,
  AppCommandsRoute: AppCommandsRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppDriversRoute: AppDriversRoute,
  AppEventsRoute: AppEventsRoute,
  AppGeofencesRoute: AppGeofencesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMapRoute: AppMapRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRulesRoute: AppRulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTripsRoute: AppTripsRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DpaRoute: DpaRoute,
  ImpressumRoute: ImpressumRoute,
  PilotRoute: PilotRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubprocessorsRoute: SubprocessorsRoute,
  TermsRoute: TermsRoute,
  TspRoute: TspRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
