/**
 * Regenerates `src/meta.ts` from the articles.
 *
 * `KB_META` is the ROOT entry point's answer to "may this reader open that article, what is it
 * called, and what is it about" — the three things a help link needs before any body is loaded.
 * Keeping it by hand is how a renamed article keeps its old label on six screens, so it is derived
 * instead, and `__tests__/kb.spec.ts` asserts the file on disk still matches the articles. Run:
 *
 *   pnpm --filter @orbetra/kb gen:meta
 *
 * The test is the gate; this script is the fix. Neither is optional — a generated file nobody
 * checks is a file that goes stale.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { KB_ARTICLES } from '../src/content.js'
import { KB_LANGS, type KbArticle } from '../src/types.js'

const q = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
const langMap = (pick: (a: KbArticle, l: (typeof KB_LANGS)[number]) => string, a: KbArticle): string[] =>
  KB_LANGS.map((l) => `${l}: ${q(pick(a, l))}`)

const entry = (a: KbArticle): string => {
  const lines = [
    `    slug: ${q(a.slug)},`,
    `    category: ${q(a.category)},`,
    `    surfaces: { site: ${a.surfaces.site}, app: ${a.surfaces.app} },`,
  ]
  if (a.audience !== undefined) {
    const parts: string[] = []
    if (a.audience.adminOnly !== undefined) parts.push(`adminOnly: ${a.audience.adminOnly}`)
    if (a.audience.platformOnly !== undefined) parts.push(`platformOnly: ${a.audience.platformOnly}`)
    if (a.audience.entitlement !== undefined) parts.push(`entitlement: ${q(a.audience.entitlement)}`)
    lines.push(`    audience: { ${parts.join(', ')} },`)
  }
  if (a.screen !== undefined) lines.push(`    screen: ${q(a.screen)},`)
  lines.push(`    title: { ${langMap((x, l) => x.doc[l].title, a).join(', ')} },`)
  lines.push(`    summary: {`)
  for (const l of KB_LANGS) lines.push(`      ${l}: ${q(a.doc[l].summary)},`)
  lines.push(`    },`)
  return `  {\n${lines.join('\n')}\n  },`
}

const header = `import type { KbArticleMeta } from './types.js'

/**
 * Every article's metadata, in the same reading order as the content — GENERATED by
 * \`scripts/gen-meta.ts\` and asserted identical to the articles by the package's own tests. Edit an
 * article, run \`pnpm --filter @orbetra/kb gen:meta\`, and a stale entry here fails the suite rather
 * than silently mislabelling a help link.
 *
 * It exists so the ROOT entry point can answer "may this reader open that article, what is it
 * called, and what is it about" without loading a single article body. Titles and summaries only —
 * enough for a help link's label and for a route's \`head\`, which are the two things that must be
 * resolvable before the bodies are.
 */
export const KB_META: readonly KbArticleMeta[] = [
`

const out = header + KB_ARTICLES.map(entry).join('\n') + '\n]\n'
const target = fileURLToPath(new URL('../src/meta.ts', import.meta.url))
writeFileSync(target, out)
process.stdout.write(`wrote ${KB_ARTICLES.length} entries to src/meta.ts\n`)
