import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import catalogue from '../dictionaries/catalogue.json' with { type: 'json' }
import { FrameError } from './errors.js'

/**
 * AVL ID dictionaries, generated from the wiki per-model tables
 * (PROJECT_PLAN §3.7 dictionary rule). Runtime code never hardcodes AVL IDs
 * outside these files; unknown IDs pass through as `io_<id>` downstream.
 */
/**
 * A dictionary is keyed by the TABLE it came from, not by a product family.
 *
 * Family was the wrong unit and it cost us correctness: 105 Teltonika models render only ~34
 * distinct AVL tables — FMB120 and FMC130 are byte-identical today, while FMB640 shares only 264
 * ids with FMB120 and 211 of those MEAN SOMETHING DIFFERENT. Meanwhile nothing selected a family at
 * all (the parameter had a default and the one caller passed undefined), so every device on the
 * platform decoded against the FMB1xx table: a TAT tamper-detection event surfaced to the customer
 * as "Agricultural State Flags P4". Tables are generated by tools/avl-dict; see catalogue.json.
 */
export type AvlTable = string

export interface AvlDictionaryEntry {
  name: string
  bytes: string
  type: string
  multiplier?: string
  units?: string
  description?: string
}

export interface DictionaryFile {
  /** the generated files carry `table`; the legacy hand-written ones carried `family` */
  table?: string
  family?: string
  source_url: string
  retrieved_at: string
  elements: Record<string, AvlDictionaryEntry>
}

const DICT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'dictionaries')
const cache = new Map<AvlTable, Map<number, AvlDictionaryEntry>>()

/** model (e.g. "FMC650") → the table that decodes it. Built from the generated catalogue. */
const MODEL_TABLE = new Map<string, AvlTable>(
  (catalogue as { models: { model: string; dictionary: string }[] }).models.map((m) => [m.model.toUpperCase(), m.dictionary]),
)

/** Every table a device could be decoded with — the set of files that must exist on disk. */
export const avlTables = (): AvlTable[] => [...new Set(MODEL_TABLE.values())].sort()

/** Which table decodes this model, or undefined if we do not know the model. */
export const tableForModel = (model: string): AvlTable | undefined => MODEL_TABLE.get(model.trim().toUpperCase())

/**
 * Reinterpret a wire value as two's complement when the wiki table says the parameter is SIGNED.
 *
 * The protocol puts every IO element on the wire as raw bytes; the dictionary is what says how to
 * read them. Nothing did (audit MED), so all 36 signed parameters in the FMB1xx table surfaced as
 * unsigned: a coolant or BLE temperature of −5 °C reads as 251, and an accelerometer axis swinging
 * negative reads as ~65 000. Those go straight into `attrs`, so the customer sees them on the device
 * page, in exports, and in any rule threshold built on them — a "below −10 °C" cold-chain alert can
 * never fire, because the value it compares is never negative.
 *
 * Width comes from the dictionary's own `bytes` column, so a 1-byte and a 2-byte signed parameter
 * are each interpreted at their own width. A width we do not recognise returns the value untouched:
 * guessing is how a correct reading becomes a wrong one.
 * https://wiki.teltonika-gps.com/view/FMB120_Teltonika_Data_Sending_Parameters_ID (Type column)
 */
export function applySign(entry: AvlDictionaryEntry | undefined, value: bigint): bigint {
  if (entry === undefined || entry.type !== 'Signed' || value < 0n) return value
  // `bytes` is validated for presence nowhere (buildDictionary checks only `name`), and this runs on
  // the ordered pipeline — a future dictionary entry without it must not throw a TypeError there.
  if (typeof entry.bytes !== 'string') return value
  const bits = { '1': 8, '2': 16, '4': 32, '8': 64 }[entry.bytes.trim()]
  if (bits === undefined) return value
  return BigInt.asIntN(bits, value)
}

/** Validation is separate from loading so malformed shapes are unit-testable. */
export function buildDictionary(file: DictionaryFile): Map<number, AvlDictionaryEntry> {
  // provenance is mandatory (CLAUDE.md rule 8) — a dictionary without it must not load
  if (!file.source_url.startsWith('https://wiki.teltonika-gps.com/')) {
    throw new FrameError(`dictionary ${file.table ?? file.family}: source_url must point at the Teltonika wiki`)
  }
  if (!file.retrieved_at) {
    throw new FrameError(`dictionary ${file.table ?? file.family}: retrieved_at missing`)
  }
  const map = new Map<number, AvlDictionaryEntry>()
  for (const [key, entry] of Object.entries(file.elements)) {
    const id = Number(key)
    if (!Number.isInteger(id) || id < 0 || id > 0xffff) {
      throw new FrameError(`dictionary ${file.table ?? file.family}: invalid AVL id key '${key}'`)
    }
    if (!entry.name) {
      throw new FrameError(`dictionary ${file.table ?? file.family}: AVL id ${id} has no name`)
    }
    map.set(id, entry)
  }
  return map
}

/**
 * Load a table's dictionary, reading it from disk on first use.
 *
 * Lazily, not as 34 static imports: the generated set is ~3.5 MB of JSON and a worker typically
 * serves a handful of models, so eagerly parsing every table would cost memory for tables nobody
 * on this deployment owns. Cached after the first read, so the ordered pipeline pays it once.
 *
 * A table we do not SHIP is an empty dictionary, not a throw and not a fallback to another table.
 * Both alternatives are worse: throwing takes a shard down over a naming mistake, and substituting a
 * neighbouring table is exactly the defect this rewrite exists to remove — a wrong parameter name is
 * worse than none, because a customer can act on it. With an empty dictionary every element still
 * reaches `attrs` as `io_<id>`; §3.7's never-dropped rule holds and nothing is mislabelled.
 *
 * A table we DO ship that fails to load is the opposite case and must be LOUD. Only ENOENT means
 * "not shipped"; a truncated file, a permission error or an I/O fault means something is wrong with
 * this deployment, and swallowing it would strip every parameter's name AND its sign fleet-wide —
 * `applySign` on an absent entry is a pass-through, so every temperature and accelerometer axis
 * would silently read as a large positive, looking exactly like broken devices. This repo deploys
 * by rsync, so a half-written file is a real shape.
 *
 * Nor is a failure cached: an empty map cached on a transient fault poisons that table for the
 * lifetime of the process, with no retry and nothing to notice.
 */
export function loadDictionary(table: AvlTable): Map<number, AvlDictionaryEntry> {
  const cached = cache.get(table)
  if (cached) return cached
  let raw: string
  try {
    raw = readFileSync(join(DICT_DIR, `${table}.json`), 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
    console.warn(`codec: no dictionary shipped for table '${table}' — elements will surface unnamed as io_<id>`)
    const empty = new Map<number, AvlDictionaryEntry>()
    cache.set(table, empty) // a table that does not exist will not start existing; caching is right here
    return empty
  }
  const map = buildDictionary(JSON.parse(raw) as DictionaryFile)
  cache.set(table, map)
  return map
}
