import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import catalogue from '../dictionaries/catalogue.json' with { type: 'json' }
import { FrameError } from './errors.js'

/**
 * AVL ID dictionaries, generated from the wiki per-model tables
 * (PROJECT_PLAN §3.7 dictionary rule). Runtime code never hardcodes AVL IDs
 * outside these files; unknown IDs pass through as `io_<id>` downstream.
 */
/**
 * A dictionary is keyed by the TABLE it came from, not by a product family.
 *
 * Family was the wrong unit and it cost us correctness: 105 Teltonika models render only ~34
 * distinct AVL tables — FMB120 and FMC130 are byte-identical today, while FMB640 shares only 264
 * ids with FMB120 and 211 of those MEAN SOMETHING DIFFERENT. Meanwhile nothing selected a family at
 * all (the parameter had a default and the one caller passed undefined), so every device on the
 * platform decoded against the FMB1xx table: a TAT tamper-detection event surfaced to the customer
 * as "Agricultural State Flags P4". Tables are generated by tools/avl-dict; see catalogue.json.
 */
export type AvlTable = string

export interface AvlDictionaryEntry {
  name: string
  bytes: string
  type: string
  /** The wiki's own value range. Declared because it is EVIDENCE, not metadata: `applySign` uses
   *  `max` to refuse a two's-complement reading the range says is impossible, and it was already in
   *  the generated JSON while being invisible to anyone reading this type. */
  min?: string
  max?: string
  multiplier?: string
  units?: string
  /** which models can actually produce this element, and which hardware it needs */
  hwSupport?: string
  group?: string
  description?: string
}

export interface DictionaryFile {
  /** the generated files carry `table`; the legacy hand-written ones carried `family` */
  table?: string
  family?: string
  source_url: string
  retrieved_at: string
  elements: Record<string, AvlDictionaryEntry>
}

const DICT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'dictionaries')
const cache = new Map<AvlTable, Map<number, AvlDictionaryEntry>>()

/** model (e.g. "FMC650") → the table that decodes it. Built from the generated catalogue. */
const MODEL_TABLE = new Map<string, AvlTable>(
  (catalogue as { models: { model: string; dictionary: string }[] }).models.map((m) => [m.model.toUpperCase(), m.dictionary]),
)

/** Every table a device could be decoded with — the set of files that must exist on disk. */
export const avlTables = (): AvlTable[] => [...new Set(MODEL_TABLE.values())].sort()

/** Which table decodes this model, or undefined if we do not know the model. */
export const tableForModel = (model: string): AvlTable | undefined => MODEL_TABLE.get(model.trim().toUpperCase())

/**
 * Reinterpret a wire value as two's complement when the wiki table says the parameter is SIGNED.
 *
 * The protocol puts every IO element on the wire as raw bytes; the dictionary is what says how to
 * read them. Nothing did (audit MED), so all 36 signed parameters in the FMB1xx table surfaced as
 * unsigned: a coolant or BLE temperature of −5 °C reads as 251, and an accelerometer axis swinging
 * negative reads as ~65 000. Those go straight into `attrs`, so the customer sees them on the device
 * page, in exports, and in any rule threshold built on them — a "below −10 °C" cold-chain alert can
 * never fire, because the value it compares is never negative.
 *
 * Width comes from the dictionary's own `bytes` column, so a 1-byte and a 2-byte signed parameter
 * are each interpreted at their own width. A width we do not recognise returns the value untouched:
 * guessing is how a correct reading becomes a wrong one.
 * https://wiki.teltonika-gps.com/view/FMB120_Teltonika_Data_Sending_Parameters_ID (Type column)
 */
export function applySign(entry: AvlDictionaryEntry | undefined, value: bigint): bigint {
  if (entry === undefined || entry.type !== 'Signed' || value < 0n) return value
  // `bytes` is validated for presence nowhere (buildDictionary checks only `name`), and this runs on
  // the ordered pipeline — a future dictionary entry without it must not throw a TypeError there.
  if (typeof entry.bytes !== 'string') return value
  const bits = { '1': 8, '2': 16, '4': 32, '8': 64 }[entry.bytes.trim()]
  if (bits === undefined) return value
  // A value WIDER than the dictionary claims is not ours to reinterpret. `BigInt.asIntN` truncates
  // rather than declining, so a 2-byte reading against a 1-byte entry silently becomes a different
  // number — 5000 arriving on an entry the table calls 1 byte came out as −120 and was written
  // durably to positions.attrs with no signal. That happens whenever the table we decode with is
  // not the table the device speaks, which is every device until profile → table is wired: fmb120
  // correctly describes 45 of the 105 catalogued models, and eight ids are Signed there at a
  // NARROWER width than another shipped table gives them. Passing the raw value through leaves it
  // visibly odd; truncating makes it plausible and wrong.
  if (value >= 1n << BigInt(bits)) return value
  // TWO refusals follow, and both took a hostile round each to get right. The Type column alone is
  // not sufficient evidence to reinterpret bytes, so the entry's own RANGE has to agree.
  const max = Number(entry.max)
  const min = Number(entry.min)

  // (1) A field whose documented minimum is NOT NEGATIVE has no sign to extend. This is the
  // strongest and simplest of the two, and it was missing: fm36 types eleven EIGHT-BYTE fields
  // `Signed` with `min: "0"` and an unreadable max ("max", "-1E+19") — 78 iButton ID, 75/76/77
  // the Dallas sensor IDs, 147–150 the LVCAN driver IDs, 101 ModuleID and the 124/132 flag words.
  // Those are identifiers and bitmasks, not quantities. `asIntN` turned iButton ROM
  // 0x8B0000021C4A2801 into -8430738493373011967, so roughly half of all ROM codes (the ones with
  // the high bit set) were corrupted — durably, in positions.attrs, breaking driver assignment,
  // exports and any rule keyed on the value. Worse: the FMB120 fallback got it RIGHT, so naming
  // the device's true model made its data worse, which is the opposite of this module's purpose.
  //
  // Requiring a readable, negative Min also means an entry whose range we cannot parse is left
  // alone rather than reinterpreted on the strength of one word in the Type column.
  if (!(Number.isFinite(min) && min < 0)) return value

  // (2) …and a range the dictionary says is impossible for a signed field of this width means the
  // Type column is not describing two's complement either. Teltonika types id 127 Engine Coolant
  // Temperature as `Signed`, 1 byte, range −40…210 — and 210 does not fit int8, because the wire
  // byte is 0…250 with the description "Offset by -40". Reinterpreting it turns a 130 °C engine
  // into −86 °C, so an over-temperature rule can never fire.
  //
  // BUT "max is too big" ALONE IS NOT THAT SHAPE, and testing only max was a bug of its own: it
  // silenced sign extension on 64 entries — every ELD, reefer and Frigo temperature on the FMx6xx
  // tables, e.g. fmc650 id 13396 "Frigo Comp 1 Supply", 2 bytes, −32768…32768. That `32768` is a
  // wiki off-by-one on a field whose own Min is EXACTLY the int16 floor; the field is unambiguously
  // two's complement, and passing it through turned −5.0 °C into 65486.
  //
  // An offset encoding has a signature, and it is the whole range, not one end: the span fits the
  // UNSIGNED width (the wire really is 0…2^bits−1) and the minimum sits ABOVE the signed floor
  // (there is an offset to subtract, not a sign bit). After (1) this clause is load-bearing for
  // exactly ids 127 and 10893 (−40…210); the rest of what it used to catch has a Min of 0 and is
  // now refused earlier, which is the more honest reason.
  const offsetEncoded = Number.isFinite(max) && max - min <= 2 ** bits - 1 && min > -(2 ** (bits - 1))
  if (offsetEncoded && max > 2 ** (bits - 1) - 1) return value
  return BigInt.asIntN(bits, value)
}

/** Validation is separate from loading so malformed shapes are unit-testable. */
/**
 * The wiki's Multiplier cell as a NUMBER, or null when it is not one. The single place that
 * conversion happens (parse.ts has warned for months that it must be exactly one place).
 *
 * The cell is written in two decimal conventions, sometimes inside one file — `0.1` ×468 next to
 * `0,1` ×215 — and 393 of 1335 cells are not a number at all: `0.01*` ×56, `acc and braking: 0.01`
 * ×17. A bare `Number()` returns NaN for 29% of them, and a NaN that reaches a formatter silently
 * drops the scaling on a customer-visible number: 490 stays "490" where it means 49.0 °C.
 *
 * Comma is accepted because it is the same number written the other way. Everything else is
 * REFUSED rather than salvaged — `0.01*` carries a footnote this code cannot read, and guessing
 * that the asterisk is decoration is how a tank reads 10× wrong. A refused cell means the value is
 * shown exactly as the device sent it, which is what happens today.
 * https://wiki.teltonika-gps.com/view/FMC150_Teltonika_Data_Sending_Parameters_ID
 */
export function parseMultiplier(raw: string | undefined): number | null {
  if (raw === undefined) return null
  const t = raw.trim().replace(',', '.')
  if (!/^\d+(\.\d+)?$/.test(t)) return null
  const n = Number(t)
  return Number.isFinite(n) && n > 0 ? n : null
}

export function buildDictionary(file: DictionaryFile): Map<number, AvlDictionaryEntry> {
  // provenance is mandatory (CLAUDE.md rule 8) — a dictionary without it must not load
  if (!file.source_url.startsWith('https://wiki.teltonika-gps.com/')) {
    throw new FrameError(`dictionary ${file.table ?? file.family}: source_url must point at the Teltonika wiki`)
  }
  if (!file.retrieved_at) {
    throw new FrameError(`dictionary ${file.table ?? file.family}: retrieved_at missing`)
  }
  const map = new Map<number, AvlDictionaryEntry>()
  for (const [key, entry] of Object.entries(file.elements)) {
    const id = Number(key)
    if (!Number.isInteger(id) || id < 0 || id > 0xffff) {
      throw new FrameError(`dictionary ${file.table ?? file.family}: invalid AVL id key '${key}'`)
    }
    if (!entry.name) {
      throw new FrameError(`dictionary ${file.table ?? file.family}: AVL id ${id} has no name`)
    }
    // Frozen: `loadDictionary` hands out the cached map and its entries BY REFERENCE to all 16
    // shards for the lifetime of the process. One caller mutating an entry would change what every
    // later record decodes as, fleet-wide, with nothing to debug from.
    map.set(id, Object.freeze(entry))
  }
  return map
}

/**
 * Load a table's dictionary, reading it from disk on first use.
 *
 * Lazily, not as 34 static imports: the generated set is ~3.5 MB of JSON and a worker typically
 * serves a handful of models, so eagerly parsing every table would cost memory for tables nobody
 * on this deployment owns. Cached after the first read, so the ordered pipeline pays it once.
 *
 * A table we do not SHIP is an empty dictionary, not a throw and not a fallback to another table.
 * Both alternatives are worse: throwing takes a shard down over a naming mistake, and substituting a
 * neighbouring table is exactly the defect this rewrite exists to remove — a wrong parameter name is
 * worse than none, because a customer can act on it. With an empty dictionary every element still
 * reaches `attrs` as `io_<id>`; §3.7's never-dropped rule holds and nothing is mislabelled.
 *
 * A table we DO ship that fails to load is the opposite case and must be LOUD. Only ENOENT means
 * "not shipped"; a truncated file, a permission error or an I/O fault means something is wrong with
 * this deployment, and swallowing it would strip every parameter's name AND its sign fleet-wide —
 * `applySign` on an absent entry is a pass-through, so every temperature and accelerometer axis
 * would silently read as a large positive, looking exactly like broken devices. This repo deploys
 * by rsync, so a half-written file is a real shape.
 *
 * Nor is a failure cached: an empty map cached on a transient fault poisons that table for the
 * lifetime of the process, with no retry and nothing to notice.
 */
export function loadDictionary(table: AvlTable): Map<number, AvlDictionaryEntry> {
  const cached = cache.get(table)
  if (cached) return cached
  let raw: string
  try {
    raw = readFileSync(join(DICT_DIR, `${table}.json`), 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
    console.warn(`codec: no dictionary shipped for table '${table}' — elements will surface unnamed as io_<id>`)
    const empty = new Map<number, AvlDictionaryEntry>()
    cache.set(table, empty) // a table that does not exist will not start existing; caching is right here
    return empty
  }
  const map = buildDictionary(JSON.parse(raw) as DictionaryFile)
  cache.set(table, map)
  return map
}
