/** Teltonika element names in German, keyed by PATTERN. See `avlNames.lt.ts` for the rules. */
export const AVL_NAMES_DE: Readonly<Record<string, string>> = {
  'Geofence zone {}': 'Geozone {}',
  'Auto Geofence': 'Automatische Geozone',
  'Manual CAN {}': 'Manuelles CAN {}',
  'Custom scenario {}': 'Eigenes Szenario {}',
  'Custom Scenario {}': 'Eigenes Szenario {}',

  'Battery Voltage': 'Batteriespannung',
  'Battery Voltage {}': 'Batteriespannung {}',
  'Battery Current': 'Batteriestrom',
  'Battery Level': 'Batteriestand',
  'Battery level': 'Batteriestand',
  'External Voltage': 'Externe Spannung',
  'Low Battery {}': 'Batterie schwach {}',
  Unplug: 'Stromversorgung getrennt',
  'Alternator Status {}': 'Lichtmaschinenstatus {}',

  Ignition: 'Zündung',
  Movement: 'Bewegung',
  'Instant Movement': 'Momentane Bewegung',
  'Movement Count {}': 'Bewegungszähler {}',
  Speed: 'Geschwindigkeit',
  'Vehicle Speed': 'Fahrzeuggeschwindigkeit',
  'Over Speeding': 'Geschwindigkeitsüberschreitung',
  Idling: 'Leerlauf',
  Towing: 'Abschleppen',
  'Crash detection': 'Unfallerkennung',
  'Crash trace data': 'Unfallaufzeichnungsdaten',
  'Total Odometer': 'Gesamtkilometerstand',
  'Trip Odometer': 'Tageskilometerstand',
  'Total Mileage': 'Gesamtkilometerstand',
  'Total Mileage (counted)': 'Gesamtkilometerstand (gezählt)',
  Trip: 'Fahrt',
  'Axis X': 'X-Achse',
  'Axis Y': 'Y-Achse',
  'Axis Z': 'Z-Achse',
  'Pitch {}': 'Neigung {}',
  'Roll {}': 'Querneigung {}',

  'GNSS Status': 'GNSS-Status',
  'GNSS HDOP': 'GNSS HDOP',
  'GNSS PDOP': 'GNSS PDOP',
  'ISO{} Coordinates': 'ISO{}-Koordinaten',

  'GSM Signal': 'GSM-Signal',
  'GSM Cell ID': 'GSM-Zellen-ID',
  'GSM Cell ID {}': 'GSM-Zellen-ID {}',
  'GSM Area Code': 'GSM-Ortskennzahl',
  'GSM Cell LAC {}': 'GSM-Zelle LAC {}',
  'GSM Cell MNC {}': 'GSM-Zelle MNC {}',
  'GSM operator code': 'GSM-Betreibercode',
  'Active GSM Operator': 'Aktiver GSM-Betreiber',
  'GSM Signal RX {}': 'GSM-Signal RX {}',
  'LTE Signal RX {}': 'LTE-Signal RX {}',
  'LTE Cell LAC {}': 'LTE-Zelle LAC {}',
  'LTE Cell ID {}': 'LTE-Zellen-ID {}',
  'LTE Cell MNC {}': 'LTE-Zelle MNC {}',
  'Network Type': 'Netztyp',
  'Connectivity quality': 'Verbindungsqualität',
  Jamming: 'Störsender erkannt',
  'ICCID{}': 'ICCID{}',
  'CCID Part{}': 'CCID-Teil {}',
  'Neighbouring Cell {} LAC': 'Nachbarzelle {} LAC',
  'Neighbouring Cell {} ID': 'Nachbarzelle {} ID',
  'Neighbouring Cell {} RSSI': 'Nachbarzelle {} RSSI',
  'Neighbouring Cell {} MNC': 'Nachbarzelle {} MNC',
  'Neighbouring Cell {} MCC': 'Nachbarzelle {} MCC',

  'Sleep Mode': 'Schlafmodus',
  'Data Mode': 'Datenmodus',
  'SD Status': 'SD-Karten-Status',
  'BT Status': 'Bluetooth-Status',
  'PCB Temperature': 'Platinentemperatur',
  'PCB temperature': 'Platinentemperatur',
  'Module ID {}B': 'Modul-ID {}B',
  Alarm: 'Alarm',
  'Alarm {}': 'Alarm {}',
  'Status {}': 'Status {}',
  Immobilizer: 'Wegfahrsperre',
  iButton: 'iButton-Schlüssel',
  RFID: 'RFID',
  'User ID': 'Benutzer-ID',

  'Digital Input {}': 'Digitaleingang {}',
  'Digital Output {}': 'Digitalausgang {}',
  'Digital Output {} Overcurrent': 'Überstrom Digitalausgang {}',
  'Analog Input {}': 'Analogeingang {}',
  'Input {}': 'Eingang {}',
  'Frequency DIN{}': 'Frequenz DIN{}',
  'Pulse Counter Din{}': 'Impulszähler DIN{}',
  'Pulse counter DIN{}': 'Impulszähler DIN{}',
  'Impulse counter value {}': 'Impulszählerwert {}',
  'Impulse counter frequency {}': 'Impulszählerfrequenz {}',
  'Impulse counter RPM {}': 'Impulszähler-Drehzahl {}',
  'External Digital Sensor {}': 'Externer Digitalsensor {}',

  'Engine RPM': 'Motordrehzahl',
  'Engine Load': 'Motorlast',
  'Engine Oil Temperature': 'Motoröltemperatur',
  'Engine Coolant Temperature': 'Kühlmitteltemperatur',
  'Coolant Temperature': 'Kühlmitteltemperatur',
  'Ambient Air Temperature': 'Außentemperatur',
  'Fuel Level': 'Kraftstoffstand',
  'Fuel Rate': 'Kraftstoffverbrauch',
  'Fuel Consumed (counted)': 'Verbrauchter Kraftstoff (gezählt)',
  'Throttle position': 'Drosselklappenstellung',
  'Engine Total Hours (counted)': 'Motorbetriebsstunden gesamt (gezählt)',
  'Ignition On Counter': 'Zündungszähler',
  VIN: 'Fahrgestellnummer',
  'Vehicle Identification Number Part{}': 'Fahrgestellnummer, Teil {}',
  'Fault Codes': 'Fehlercodes',

  'Green Driving Value': 'Wert für sparsames Fahren',
  'Green driving type': 'Ereignistyp sparsames Fahren',
  'Green driving event duration': 'Dauer des Ereignisses sparsames Fahren',
  'Eco Score': 'Eco-Bewertung',
  EcoMaximum: 'Eco, Maximum',
  EcoAverage: 'Eco, Durchschnitt',
  EcoDuration: 'Eco, Dauer',

  'Door Status': 'Türstatus',
  'Door {} Lock Status': 'Schlossstatus Tür {}',

  'Tire {} pressure': 'Reifendruck {}',
  'Tire {} Temperature': 'Reifentemperatur {}',
  'Tire {} Warning': 'Reifenwarnung {}',
  'EBS Tyre {} Pressure': 'EBS Reifendruck {}',
  'EBS Tyre {} Temperature': 'EBS Reifentemperatur {}',
  'EBS Tyre {} Status': 'EBS Reifenstatus {}',
  'EBS Tyre {} Position': 'EBS Reifenposition {}',
  'EBS Tyre {} Additional Data {}': 'EBS Reifen {} Zusatzdaten {}',
  'Axle weight {}': 'Achslast {}',
  'Axle {} Load': 'Last Achse {}',

  'Temperature {}': 'Temperatur {}',
  'Humidity {}': 'Luftfeuchtigkeit {}',
  'Magnet {}': 'Magnet {}',
  'RSSI {}': 'RSSI {}',
  'MAC address {}': 'MAC-Adresse {}',
  'Name {}': 'Name {}',
  'Dallas Temperature {}': 'Dallas-Temperatur {}',
  'Dallas Temperature ID {}': 'Dallas-Sensor-ID {}',
  'Temperature Probe {}': 'Temperaturfühler {}',
  'External Temperature {}': 'Externe Temperatur {}',
  'External Sensor Temperature {}': 'Temperatur externer Sensor {}',
  '{}Wire Humidity {}': '{}-Wire-Luftfeuchtigkeit {}',
  'Sensor {} Unit': 'Einheit Sensor {}',

  'BLE {} Custom #{}': 'BLE {} benutzerdefiniert #{}',
  'BLE Battery {}': 'BLE-Batterie {}',
  'BLE Temperature {}': 'BLE-Temperatur {}',
  'BLE Humidity {}': 'BLE-Luftfeuchtigkeit {}',
  'BLE Sensor Custom {}': 'BLE-Sensor benutzerdefiniert {}',
  'BLE Button {} state #{}': 'BLE-Taster {} Zustand #{}',
  'BLE RFID #{}': 'BLE-RFID #{}',
  'BLE Fuel Level #{}': 'BLE-Kraftstoffstand #{}',
  'BLE Fuel Frequency #{}': 'BLE-Kraftstofffrequenz #{}',
  'BLE Luminosity #{}': 'BLE-Helligkeit #{}',
  'BLE{} EYE sensor lost alarm': 'BLE{} Alarm: EYE-Sensor verloren',
  'EYE Temperature {}': 'EYE-Temperatur {}',
  'EYE Humidity {}': 'EYE-Luftfeuchtigkeit {}',
  'EYE Magnet {}': 'EYE-Magnet {}',
  'EYE Movement {}': 'EYE-Bewegung {}',
  'EYE Pitch {}': 'EYE-Neigung {}',
  'EYE Roll {}': 'EYE-Querneigung {}',
  'EYE Low Battery {}': 'EYE-Batterie schwach {}',
  'EYE Battery Voltage {}': 'EYE-Batteriespannung {}',
  'EYE Movement count {}': 'EYE-Bewegungszähler {}',
  'EYE Magnet count {}': 'EYE-Magnetzähler {}',

  'LLS {} Fuel Level': 'LLS {} Kraftstoffstand',
  'LLS {} Temperature': 'LLS {} Temperatur',
  'Escort LLS Fuel level #{}': 'Escort LLS Kraftstoffstand #{}',
  'Escort LLS Temperature #{}': 'Escort LLS Temperatur #{}',
  'Escort LLS Battery Voltage #{}': 'Escort LLS Batteriespannung #{}',

  'Driver {} Continuous Driving Time': 'Ununterbrochene Lenkzeit Fahrer {}',
  'Driver {} Cumulative Driving Time': 'Kumulierte Lenkzeit Fahrer {}',
  'Driver {} Cumulative Break Time': 'Kumulierte Pausenzeit Fahrer {}',
  'Driver {} Selected Activity Duration': 'Dauer der gewählten Tätigkeit, Fahrer {}',
  'Driver {} Working State': 'Arbeitszustand Fahrer {}',
  'Driver {} Card Presence': 'Karte vorhanden, Fahrer {}',
  'Driver {} Time Related States': 'Zeitbezogene Zustände Fahrer {}',
  'Card {} Issuing Member State': 'Ausstellender Mitgliedstaat, Karte {}',

  'Speed Range {} Distance': 'Strecke im Geschwindigkeitsbereich {}',
  'Speed Range {} Fuel used': 'Kraftstoff im Geschwindigkeitsbereich {}',
  'Speed Range {} Time': 'Zeit im Geschwindigkeitsbereich {}',
  'RPM Range {} Distance': 'Strecke im Drehzahlbereich {}',
  'RPM Range {} Fuel used': 'Kraftstoff im Drehzahlbereich {}',
  'RPM Range {} Time': 'Zeit im Drehzahlbereich {}',
  'Torque Range {} Distance': 'Strecke im Drehmomentbereich {}',
  'Torque Range {} Fuel used': 'Kraftstoff im Drehmomentbereich {}',
  'Torque Range {} Time': 'Zeit im Drehmomentbereich {}',
  'Braking Range {} Distance': 'Strecke im Bremsbereich {}',
  'Braking Range {} Fuel used': 'Kraftstoff im Bremsbereich {}',
  'Braking Range {} Time': 'Zeit im Bremsbereich {}',

  'Maintenance {} Hours': 'Stunden bis Wartung {}',
  'Tell Tale {}': 'Kontrollleuchte {}',

  // Teltonika spells the same concept several ways across tables — see avlNames.lt.ts.
  'Engine Speed': 'Motordrehzahl',
  'Fuel Consumed Counted': 'Verbrauchter Kraftstoff (gezählt)',
  'GSM signal': 'GSM-Signal',
  'Throttle Position': 'Drosselklappenstellung',
  'Total Mileage Counted': 'Gesamtkilometerstand (gezählt)',
  'Control State Flags': 'Steuerungs-Statusflags',
  'Security State Flags': 'Sicherheits-Statusflags',
  'Accel Calibration Quality': 'Qualität der Beschleunigungskalibrierung',
  'Current Active Log File': 'Aktuelle Protokolldatei',
  'Max Log File Count': 'Maximale Anzahl Protokolldateien',
  'Side Vector Delta': 'Änderung des Seitenvektors',
}
