/** Teltonika element names in Polish, keyed by PATTERN. See `avlNames.lt.ts` for the rules. */
export const AVL_NAMES_PL: Readonly<Record<string, string>> = {
  'Geofence zone {}': 'Geostrefa {}',
  'Auto Geofence': 'Geostrefa automatyczna',
  'Manual CAN {}': 'Ręczny CAN {}',
  'Custom scenario {}': 'Scenariusz własny {}',
  'Custom Scenario {}': 'Scenariusz własny {}',

  'Battery Voltage': 'Napięcie akumulatora',
  'Battery Voltage {}': 'Napięcie akumulatora {}',
  'Battery Current': 'Prąd akumulatora',
  'Battery Level': 'Poziom akumulatora',
  'Battery level': 'Poziom akumulatora',
  'External Voltage': 'Napięcie zewnętrzne',
  'Low Battery {}': 'Niski poziom akumulatora {}',
  Unplug: 'Odłączone zasilanie',
  'Alternator Status {}': 'Stan alternatora {}',

  Ignition: 'Zapłon',
  Movement: 'Ruch',
  'Instant Movement': 'Ruch chwilowy',
  'Movement Count {}': 'Liczba ruchów {}',
  Speed: 'Prędkość',
  'Vehicle Speed': 'Prędkość pojazdu',
  'Over Speeding': 'Przekroczenie prędkości',
  Idling: 'Praca na biegu jałowym',
  Towing: 'Holowanie',
  'Crash detection': 'Wykrycie kolizji',
  'Crash trace data': 'Dane zapisu kolizji',
  'Total Odometer': 'Przebieg całkowity',
  'Trip Odometer': 'Przebieg trasy',
  'Total Mileage': 'Przebieg całkowity',
  'Total Mileage (counted)': 'Przebieg całkowity (liczony)',
  Trip: 'Trasa',
  'Axis X': 'Oś X',
  'Axis Y': 'Oś Y',
  'Axis Z': 'Oś Z',
  'Pitch {}': 'Pochylenie {}',
  'Roll {}': 'Przechył {}',

  'GNSS Status': 'Stan GNSS',
  'GNSS HDOP': 'GNSS HDOP',
  'GNSS PDOP': 'GNSS PDOP',
  'ISO{} Coordinates': 'Współrzędne ISO{}',

  'GSM Signal': 'Sygnał GSM',
  'GSM Cell ID': 'ID komórki GSM',
  'GSM Cell ID {}': 'ID komórki GSM {}',
  'GSM Area Code': 'Kod obszaru GSM',
  'GSM Cell LAC {}': 'LAC komórki GSM {}',
  'GSM Cell MNC {}': 'MNC komórki GSM {}',
  'GSM operator code': 'Kod operatora GSM',
  'Active GSM Operator': 'Aktywny operator GSM',
  'GSM Signal RX {}': 'Sygnał GSM RX {}',
  'LTE Signal RX {}': 'Sygnał LTE RX {}',
  'LTE Cell LAC {}': 'LAC komórki LTE {}',
  'LTE Cell ID {}': 'ID komórki LTE {}',
  'LTE Cell MNC {}': 'MNC komórki LTE {}',
  'Network Type': 'Typ sieci',
  'Connectivity quality': 'Jakość połączenia',
  Jamming: 'Zagłuszanie sygnału',
  'ICCID{}': 'ICCID{}',
  'CCID Part{}': 'Część CCID {}',
  'Neighbouring Cell {} LAC': 'LAC komórki sąsiedniej {}',
  'Neighbouring Cell {} ID': 'ID komórki sąsiedniej {}',
  'Neighbouring Cell {} RSSI': 'RSSI komórki sąsiedniej {}',
  'Neighbouring Cell {} MNC': 'MNC komórki sąsiedniej {}',
  'Neighbouring Cell {} MCC': 'MCC komórki sąsiedniej {}',

  'Sleep Mode': 'Tryb uśpienia',
  'Data Mode': 'Tryb danych',
  'SD Status': 'Stan karty SD',
  'BT Status': 'Stan Bluetooth',
  'PCB Temperature': 'Temperatura płytki',
  'PCB temperature': 'Temperatura płytki',
  'Module ID {}B': 'ID modułu {}B',
  Alarm: 'Alarm',
  'Alarm {}': 'Alarm {}',
  'Status {}': 'Stan {}',
  Immobilizer: 'Immobilizer',
  iButton: 'Klucz iButton',
  RFID: 'RFID',
  'User ID': 'ID użytkownika',

  'Digital Input {}': 'Wejście cyfrowe {}',
  'Digital Output {}': 'Wyjście cyfrowe {}',
  'Digital Output {} Overcurrent': 'Przeciążenie wyjścia cyfrowego {}',
  'Analog Input {}': 'Wejście analogowe {}',
  'Input {}': 'Wejście {}',
  'Frequency DIN{}': 'Częstotliwość DIN{}',
  'Pulse Counter Din{}': 'Licznik impulsów DIN{}',
  'Pulse counter DIN{}': 'Licznik impulsów DIN{}',
  'Impulse counter value {}': 'Wartość licznika impulsów {}',
  'Impulse counter frequency {}': 'Częstotliwość licznika impulsów {}',
  'Impulse counter RPM {}': 'Obroty licznika impulsów {}',
  'External Digital Sensor {}': 'Zewnętrzny czujnik cyfrowy {}',

  'Engine RPM': 'Obroty silnika',
  'Engine Load': 'Obciążenie silnika',
  'Engine Oil Temperature': 'Temperatura oleju silnikowego',
  'Engine Coolant Temperature': 'Temperatura płynu chłodzącego',
  'Coolant Temperature': 'Temperatura płynu chłodzącego',
  'Ambient Air Temperature': 'Temperatura otoczenia',
  'Fuel Level': 'Poziom paliwa',
  'Fuel Rate': 'Zużycie paliwa',
  'Fuel Consumed (counted)': 'Zużyte paliwo (liczone)',
  'Throttle position': 'Położenie przepustnicy',
  'Engine Total Hours (counted)': 'Łączny czas pracy silnika (liczony)',
  'Ignition On Counter': 'Licznik włączeń zapłonu',
  VIN: 'Numer VIN',
  'Vehicle Identification Number Part{}': 'Część numeru VIN {}',
  'Fault Codes': 'Kody usterek',

  'Green Driving Value': 'Wartość ekojazdy',
  'Green driving type': 'Typ zdarzenia ekojazdy',
  'Green driving event duration': 'Czas trwania zdarzenia ekojazdy',
  'Eco Score': 'Ocena ekojazdy',
  EcoMaximum: 'Ekojazda, maksimum',
  EcoAverage: 'Ekojazda, średnia',
  EcoDuration: 'Ekojazda, czas trwania',

  'Door Status': 'Stan drzwi',
  'Door {} Lock Status': 'Stan zamka drzwi {}',

  'Tire {} pressure': 'Ciśnienie opony {}',
  'Tire {} Temperature': 'Temperatura opony {}',
  'Tire {} Warning': 'Ostrzeżenie opony {}',
  'EBS Tyre {} Pressure': 'EBS ciśnienie opony {}',
  'EBS Tyre {} Temperature': 'EBS temperatura opony {}',
  'EBS Tyre {} Status': 'EBS stan opony {}',
  'EBS Tyre {} Position': 'EBS pozycja opony {}',
  'EBS Tyre {} Additional Data {}': 'EBS dane dodatkowe opony {} ({})',
  'Axle weight {}': 'Masa na osi {}',
  'Axle {} Load': 'Obciążenie osi {}',

  'Temperature {}': 'Temperatura {}',
  'Humidity {}': 'Wilgotność {}',
  'Magnet {}': 'Magnes {}',
  'RSSI {}': 'RSSI {}',
  'MAC address {}': 'Adres MAC {}',
  'Name {}': 'Nazwa {}',
  'Dallas Temperature {}': 'Temperatura Dallas {}',
  'Dallas Temperature ID {}': 'ID czujnika Dallas {}',
  'Temperature Probe {}': 'Sonda temperatury {}',
  'External Temperature {}': 'Temperatura zewnętrzna {}',
  'External Sensor Temperature {}': 'Temperatura czujnika zewnętrznego {}',
  '{}Wire Humidity {}': 'Wilgotność {}-Wire {}',
  'Sensor {} Unit': 'Jednostka czujnika {}',

  'BLE {} Custom #{}': 'BLE {} własny #{}',
  'BLE Battery {}': 'BLE akumulator {}',
  'BLE Temperature {}': 'BLE temperatura {}',
  'BLE Humidity {}': 'BLE wilgotność {}',
  'BLE Sensor Custom {}': 'BLE czujnik własny {}',
  'BLE Button {} state #{}': 'Stan przycisku BLE {} (#{})',
  'BLE RFID #{}': 'BLE RFID #{}',
  'BLE Fuel Level #{}': 'BLE poziom paliwa #{}',
  'BLE Fuel Frequency #{}': 'BLE częstotliwość paliwa #{}',
  'BLE Luminosity #{}': 'BLE natężenie światła #{}',
  'BLE{} EYE sensor lost alarm': 'BLE{} alarm utraty czujnika EYE',
  'EYE Temperature {}': 'EYE temperatura {}',
  'EYE Humidity {}': 'EYE wilgotność {}',
  'EYE Magnet {}': 'EYE magnes {}',
  'EYE Movement {}': 'EYE ruch {}',
  'EYE Pitch {}': 'EYE pochylenie {}',
  'EYE Roll {}': 'EYE przechył {}',
  'EYE Low Battery {}': 'EYE niski poziom akumulatora {}',
  'EYE Battery Voltage {}': 'EYE napięcie akumulatora {}',
  'EYE Movement count {}': 'EYE liczba ruchów {}',
  'EYE Magnet count {}': 'EYE liczba zadziałań magnesu {}',

  'LLS {} Fuel Level': 'LLS {} poziom paliwa',
  'LLS {} Temperature': 'LLS {} temperatura',
  'Escort LLS Fuel level #{}': 'Escort LLS poziom paliwa #{}',
  'Escort LLS Temperature #{}': 'Escort LLS temperatura #{}',
  'Escort LLS Battery Voltage #{}': 'Escort LLS napięcie akumulatora #{}',

  'Driver {} Continuous Driving Time': 'Czas ciągłej jazdy kierowcy {}',
  'Driver {} Cumulative Driving Time': 'Łączny czas jazdy kierowcy {}',
  'Driver {} Cumulative Break Time': 'Łączny czas przerw kierowcy {}',
  'Driver {} Selected Activity Duration': 'Czas wybranej aktywności kierowcy {}',
  'Driver {} Working State': 'Stan pracy kierowcy {}',
  'Driver {} Card Presence': 'Obecność karty kierowcy {}',
  'Driver {} Time Related States': 'Stany czasowe kierowcy {}',
  'Card {} Issuing Member State': 'Państwo wydania karty {}',

  'Speed Range {} Distance': 'Dystans w zakresie prędkości {}',
  'Speed Range {} Fuel used': 'Paliwo w zakresie prędkości {}',
  'Speed Range {} Time': 'Czas w zakresie prędkości {}',
  'RPM Range {} Distance': 'Dystans w zakresie obrotów {}',
  'RPM Range {} Fuel used': 'Paliwo w zakresie obrotów {}',
  'RPM Range {} Time': 'Czas w zakresie obrotów {}',
  'Torque Range {} Distance': 'Dystans w zakresie momentu {}',
  'Torque Range {} Fuel used': 'Paliwo w zakresie momentu {}',
  'Torque Range {} Time': 'Czas w zakresie momentu {}',
  'Braking Range {} Distance': 'Dystans w zakresie hamowania {}',
  'Braking Range {} Fuel used': 'Paliwo w zakresie hamowania {}',
  'Braking Range {} Time': 'Czas w zakresie hamowania {}',

  'Maintenance {} Hours': 'Godziny do przeglądu {}',
  'Tell Tale {}': 'Kontrolka deski rozdzielczej {}',

  // Teltonika spells the same concept several ways across tables — see avlNames.lt.ts.
  'Engine Speed': 'Obroty silnika',
  'Fuel Consumed Counted': 'Zużyte paliwo (liczone)',
  'GSM signal': 'Sygnał GSM',
  'Throttle Position': 'Położenie przepustnicy',
  'Total Mileage Counted': 'Przebieg całkowity (liczony)',
  'Control State Flags': 'Flagi stanu sterowania',
  'Security State Flags': 'Flagi stanu zabezpieczeń',
  'Accel Calibration Quality': 'Jakość kalibracji akcelerometru',
  'Current Active Log File': 'Bieżący plik dziennika',
  'Max Log File Count': 'Maksymalna liczba plików dziennika',
  'Side Vector Delta': 'Zmiana wektora bocznego',
}
